### ISSUE TITLE
BiLSTM convert into openvino model,  when batchsize > 1,  can't  load model to device

### ISSUE THREAD

**Issue by DuckJ** [openvinotoolkit/openvino#1911] opened 2020-08-24 10:49 UTC
I used the pytorch code [crnn](https://github.com/meijieru/crnn.pytorch/blob/master/models/crnn.py) and the cnn backbone change as mobilenet v3 large 1.0,  to train a ocr recognition model, the input size is set (1,1,,32,100), and convert into onnx model successfully, although there is a warning about lstm batchsize. I think it is caused by the following source code
`class BidirectionalLSTM(nn.Module):

    def __init__(self, nIn, nHidden, nOut):
        super(BidirectionalLSTM, self).__init__()

        self.rnn = nn.LSTM(nIn, nHidden, bidirectional=True)
        self.embedding = nn.Linear(nHidden * 2, nOut)

    def forward(self, input):
        recurrent, _ = self.rnn(input)
        T, b, h = recurrent.size()
        t_rec = recurrent.view(T * b, h)

        output = self.embedding(t_rec)  # [T * b, nOut]
        output = output.view(T, b, -1)

        return output`
I also  convert the onnx model  into openvino xml and bin successfully, when the batchsize set 1, the inference is normal.
But when I try to realize the batchszie=2 ， can't  load model to device, error is 
`terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
what(): Incorrect shape of state ports for layer 891/Split/reverse/LSTMCell_sequence`
I guess it should be caused by LSTM batch first. Anyone can help me? Thanks.

**Comment by DuckJ** [comment] 2020-08-24 10:51
Model Optimizer version is 2020.1.0-61-gd349c3ba4a

**Comment by jgespino** [comment] 2020-08-25 14:53
Hi @DuckJ,

Thanks for reaching out! It looks like you are using an older release of the OpenVINO toolkit. Could you try the latest release (2020.4) and see if the issue is still present?

Regards,
Jesus

**Comment by DuckJ** [comment] 2020-08-26 01:14
@jgespino Thanks for your reply, my  target device is linux Red Hat 4.8.5, I used gcc 4.8.5 to build my project.

**Comment by DuckJ** [comment] 2020-08-26 06:40
@jgespino I tried the latest release (2020.4) version, the error is 
`terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException' what(): Incorrect shape of state ports for layer 891/Split/forward/LSTMCell_sequence`
the error in 2020.1 is 
`Incorrect shape of state ports for layer 891/Split/reverse/LSTMCell_sequence``

**Comment by jgespino** [comment] 2020-09-02 18:15
@DuckJ Let me check with my peers and get back to you. 

Regards,
Jesus

**Comment by dmitryte** [comment] 2020-09-03 15:17
@DuckJ hi! Can you send out your onnx and IR models, please?

**Comment by DuckJ** [comment] 2020-09-14 02:02
@dmitryte I am sorry, the model saved in company  server, I don't have permission to export.
Reference https://github.com/openvinotoolkit/openvino/issues/436,the model in [crnn](https://github.com/meijieru/crnn.pytorch)  seems that there are similar problems. the pytorch model can be converted into onnx via
`torch.onnx.export`
model load code can refer to [this](https://github.com/meijieru/crnn.pytorch/blob/master/demo.py)
then via
`python mo.py --framework onnx --input_modell ***.onnx --input_shape [1,1,32,100], --mean_values [127.5] --scale_values [127.5] --model_name ****  --output_dir *****`

**Comment by dmitryte** [comment] 2020-10-20 14:42
Hi @DuckJ !

I converted the model to onnx with the command you provided and then used MO with the shape 2 1 32 100. Inference works fine in 2020.4.

**Comment by DuckJ** [comment] 2020-10-21 02:36
Hi, @dmitryte . When used  MO with the shape 2 1 32 100,  the inference can work with batchszie 2, but if you change the batchsize into 3 or others,  is everything ok?

**Comment by DuckJ** [comment] 2020-10-21 02:38
@dmitryte https://github.com/openvinotoolkit/openvino/issues/436

**Comment by dmitryte** [comment] 2020-10-23 08:32
@DuckJ I experience same issues with runtime reshape.

As for the recommendations in the last comment here #436, you can generate several IRs and choose them manually inside the script according to your inputs. That would be the best workaround for this case right now.

**Comment by DuckJ** [comment] 2020-10-23 12:23
@dmitryte Thanks, got it

**Comment by dmitryte** [comment] 2020-10-23 12:52
@DuckJ, I'm closing this ticket for now. If I find out how to support the reshape without any hacks, I'll reopen and provide the update.

**Closed by dmitryte** 2020-10-23 12:52 UTC
Labels: TCE, category: IE common
