### ISSUE TITLE
[Bug] Model loading of 2022.2 is slower than 2021.4

### ISSUE THREAD

**Issue by LeonHaoWI** [openvinotoolkit/openvino#17033] opened 2023-04-19 02:24 UTC
##### System information (version)

- OpenVINO : 2022.2 & 2021.4
- Operating System / Platform  : Windows 64 Bit
- 2022.2 from: [w_openvino_toolkit_windows_2022.2.0.7713.af16ea1d79a_x86_64.zip](https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.2/windows/w_openvino_toolkit_windows_2022.2.0.7713.af16ea1d79a_x86_64.zip)
- 2021.4 from: [w_openvino_toolkit_data_dev_p_2021.4.582.zip](https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.4/w_openvino_toolkit_data_dev_p_2021.4.582.zip)
- Problem classification :  model loading performance

##### Detailed description

the model loading of 2022.2 is slower than 2021.4

##### Steps to reproduce

test with benchmark_app on CPU 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
here is result from 2022.2:

```bash
benchmark_app -m LiverDetec.xml -hint latency -d CPU -niter "1" -cache_dir "test"
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO: OpenVINO Runtime version ......... 2022.2.0
[ INFO ] Build ........... 2022.2.0-7713-af16ea1d79a-releases/2022/2
[ INFO ]
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] openvino_intel_cpu_plugin version ......... 2022.2.0
[ INFO ] Build ........... 2022.2.0-7713-af16ea1d79a-releases/2022/2
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Device(CPU) performance hint is set to LATENCY
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 118.51 ms
[ INFO ] Original network I/O parameters:
Network inputs:
    input.1 (node: input.1) : f32 / [...]
Network outputs:
    2901 (node: 2901) : f32 / [...]
[Step 5/11] Resizing network to match image sizes and given batch
[ WARNING ] input.1: layout is not set explicitly, so it is defaulted to NCHW. It is STRONGLY recommended to set layout manually to avoid further issues.
[Step 6/11] Configuring input of the model
[ INFO ] Network batch size: 1
Network inputs:
    input.1 (node: input.1) : u8 / [N,C,H,W]
Network outputs:
    2901 (node: 2901) : f32 / [...]
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 658.94 ms
[Step 8/11] Setting optimal runtime parameters
[ INFO ] Device: CPU
[ INFO ]   { NETWORK_NAME , TEST_all1_nobox_scalerotation_normalizedregulization_1800contract2_5points_batchsize1 }
[ INFO ]   { OPTIMAL_NUMBER_OF_INFER_REQUESTS , 1 }
[ INFO ]   { NUM_STREAMS , 1 }
[ INFO ]   { AFFINITY , NONE }
[ INFO ]   { INFERENCE_NUM_THREADS , 0 }
[ INFO ]   { PERF_COUNT , NO }
[ INFO ]   { INFERENCE_PRECISION_HINT , f32 }
[ INFO ]   { PERFORMANCE_HINT , LATENCY }
[ INFO ]   { PERFORMANCE_HINT_NUM_REQUESTS , 0 }
[Step 9/11] Creating infer requests and preparing input blobs with data
[ WARNING ] No input files were given: all inputs will be filled with random values!
[ INFO ] Test Config 0
[ INFO ] input.1  ([N,C,H,W], u8, {1, 3, 512, 512}, static):    random (image is expected)
[Step 10/11] Measuring performance (Start inference asynchronously, 1 inference requests, limits: 1 iterations)
[ INFO ] BENCHMARK IS IN INFERENCE ONLY MODE.
[ INFO ] Input blobs will be filled once before performance measurements.
[ INFO ] First inference took 94.78 ms
```

and here is result from 2021.4:

```bash
benchmark_app -m LiverDetec.xml -hint latency -d CPU -niter "1" -cache_dir "test"
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
ERROR: unknown command line flag 'hint'

benchmark_app -m LiverDetec.xml -d CPU -niter "1" -cache_dir "test" -nstreams "1" -nireq "1"
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
        IE version ......... 2021.4.0
        Build ........... 2021.4.0-3839-cd81789d294-releases/2021/4
[ INFO ] Device info:
        CPU
        MKLDNNPlugin version ......... 2021.4.0
        Build ........... 2021.4.0-3839-cd81789d294-releases/2021/4

[Step 3/11] Setting device configuration
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 116.61 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
Network inputs:
    input.1 : U8 / NCHW
Network outputs:
    2901 : FP32 / NCHW
[Step 7/11] Loading the model to the device
[ INFO ] Load network took 418.71 ms
[Step 8/11] Setting optimal runtime parameters
[Step 9/11] Creating infer requests and filling input blobs with images
[ INFO ] Network input 'input.1' precision U8, dimensions (NCHW): 1 3 512 512
[ WARNING ] No input files were given: all inputs will be filled with random values!
[ INFO ] Infer Request 0 filling
[ INFO ] Fill input 'input.1' with random values (image is expected)
[Step 10/11] Measuring performance (Start inference asynchronously, 1 inference requests using 1 streams for CPU, limits: 1 iterations)
[ INFO ] First inference took 98.27 ms
```

for the reason that 2021.4 does not support high level performance hint, I set nstreams to 1 and nireq to 1, but If I understand correctly, they have no influence to model loading time.

as you can see, in 2022.2, loading the model to the device takes 658.94ms, and in 2021.4 it's 418.71ms.
It's strange because I used cache_dir, and loading should be just read compiled model. and I have checked the cache dir, in the case of 2022.2, there is a .blob file (the loading takes 734.71ms before the .blob created), while in the case of 2021.4, the cache dir is empty.

So, how could I speed up the loading?

**Comment by LeonHaoWI** [comment] 2023-04-20 08:18
add some new test result for average loading time:
                                                                                                       2021.4            2022.2            2022.3
 Core(TM) i7-11850H @ 2.50GHz                                                  421ms            673ms            534ms
Xeon(R) Silver 4214 CPU @2.2GHz 2.19GHz(two processer)         832ms           1374ms          1043ms

**Comment by mbencer** [comment] 2023-05-04 11:45
@LeonHaoWI Could you provide the model (LiverDetec.xml) which you use for tests (even with fake weights if possible)?
Since described problem relates `LoadNetwork` to CPU plugin @nshchego could you please take a look?

**Comment by LeonHaoWI** [comment] 2023-05-09 07:41
I am using Deep High-Resolution Representation Learning for Human Pose Estimation in testing, you could find a pre-trained model here: model zoo([GoogleDrive](https://drive.google.com/drive/folders/1hOTihvbyIxsm5ygDpbUuJ7O_tzv4oXjC?usp=sharing) or [OneDrive](https://1drv.ms/f/s!AhIXJn_J-blW231MH2krnmLq5kkQ))

**Comment by wenjiew** [comment] 2023-05-12 06:37
@wangleis Can you help take a look whether Affinity and Thread setting will impact the load time. 
@liubo-intel  to help out on cache impact on the FIL, thanks!

**Comment by liubo-intel** [comment] 2023-05-14 13:59
Hi, @LeonHaoWI : from the model link that you mentioned([GoogleDrive](https://drive.google.com/drive/folders/1hOTihvbyIxsm5ygDpbUuJ7O_tzv4oXjC?usp=sharing) or [OneDrive](https://1drv.ms/f/s!AhIXJn_J-blW231MH2krnmLq5kkQ)), we only found the origial pytorch model without its openvino IR(LiverDetec.xml). So we try to use 'higher-hrnet-w32-human-pose-estimation' model to reproduce this issue, it's a human-pose-estimation model based on HigherHRnet (just as the model that you used)from our [open_model_zoo](https://github.com/openvinotoolkit/open_model_zoo/tree/117007cd4aa3d4ad911d0604beae5f6d60d3fe14/models/public/higher-hrnet-w32-human-pose-estimation). The model loading performance data on our local machine is as follows:

2021.4 : 5008.88ms
2023.0(latest master branch)without model cache: 5739.39ms
023.0(latest master branch)with model cache: 4996.55 ms

from 2021.4 version to latest version we indeed reproduce model loading timer higher issue, this because new optimization transoform and kernels are introduced after 2021.4, with these new features, most models gain higher inference performance(e.g. this 'higher-hrnet-w32-human-pose-estimation' model from 22fps to 32fps on our local machine).

And as above data shows we found that with model cache usage, the latest master branch model loading time basically the same as 2021.4 version for 'higher-hrnet-w32-human-pose-estimation' model. so could you please have a try model cache method with latest openvino master branch(or next version to be released) for your model?

About openvino latency mode threading strategy, @wangleis  do you have more comments?

**Comment by wangleis** [comment] 2023-05-14 14:27
File load times are independent of affinity or threading. The difference in model compilation mentioned by @liubo-intel is the root cause.

**Comment by LeonHaoWI** [comment] 2023-05-17 01:55
Hi, @liubo-intel : the test that have been done before with 2022.2 and 2022.3 do use a model cache.
I just test our model with latest openvino (2023.0.0.dev20230427), and the issue remain the same (534.2 ms on Core(TM) i7-11850H @ 2.50GHz).
w.r.t IR model we use may have difference with your test. I tried to download and convert the model from [open_model_zoo](https://github.com/openvinotoolkit/open_model_zoo/tree/117007cd4aa3d4ad911d0604beae5f6d60d3fe14/models/public/higher-hrnet-w32-human-pose-estimation), but have some issue here:

```bash
omz_converter --name higher-hrnet-w32-human-pose-estimation
========== Converting higher-hrnet-w32-human-pose-estimation to ONNX
Conversion to ONNX command: C:\Users\310250211\.conda\envs\openvino-dev\python.exe -- C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\model_zoo\internal_scripts\pytorch_to_onnx.py --model-path=C:\Users\310250211\.conda\envs\openvino-dev\Lib\site-packages\openvino\model_zoo\models\public\higher-hrnet-w32-human-pose-estimation --model-path=C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation --model-name=get_net --import-module=model "--model-param=file_config=r\"C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation/experiments/higher_hrnet.yaml\"" "--model-param=weights=r\"C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation/ckpt/pose_higher_hrnet_w32_512.pth\"" --input-shape=1,3,512,512 --input-names=image --output-names=embeddings,heatmaps --output-file=C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation/higher-hrnet-w32-human-pose-estimation.onnx

============== Diagnostic Run torch.onnx.export version 2.0.1+cpu ==============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX check passed successfully.

========== Converting higher-hrnet-w32-human-pose-estimation to IR (FP16)
Conversion command: C:\Users\310250211\.conda\envs\openvino-dev\python.exe -- C:\Users\310250211\.conda\envs\openvino-dev\Scripts\mo.exe --framework=onnx --output_dir=C:\Users\310250~1\AppData\Local\Temp\tmpwbp6kaxp --model_name=higher-hrnet-w32-human-pose-estimation --input=image --reverse_input_channels --mean_values=image[123.675,116.28,103.53] --scale_values=image[58.395,57.12,57.375] --output=embeddings,heatmaps --input_model=C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation/higher-hrnet-w32-human-pose-estimation.onnx --layout=image(NCHW) "--input_shape=[1, 3, 512, 512]" --compress_to_fp16=True

[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check 'T::broadcast_merge_into(output_shape, input_shapes[1], autob)' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\shape_inference\include\utils.hpp:44:
While validating node 'opset1::Add /Add (/Slice_1[0]:f32[?,17,256,256], /impl/final_layers.1/Conv[0]:f32[?,17,2048..,2048..]) -> (f32[1,17,256,256])' with friendly_name '/Add':
Argument shapes are inconsistent.

[ ERROR ]  Traceback (most recent call last):
  File "C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\tools\mo\convert_impl.py", line 920, in _convert
    ov_model, legacy_path = driver(argv, {"conversion_parameters": non_default_params})
  File "C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\tools\mo\convert_impl.py", line 598, in driver
    res_ngraph_function = moc_emit_ir(ngraph_function, argv)
  File "C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\tools\mo\moc_frontend\serialize.py", line 23, in moc_emit_ir
    apply_moc_transformations(ngraph_function)
  File "C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\tools\mo\back\offline_transformations.py", line 39, in apply_moc_transformations
    apply_moc_transformations(func, cf=False, smart_reshape=True)
RuntimeError: Check 'T::broadcast_merge_into(output_shape, input_shapes[1], autob)' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\shape_inference\include\utils.hpp:44:
While validating node 'opset1::Add /Add (/Slice_1[0]:f32[?,17,256,256], /impl/final_layers.1/Conv[0]:f32[?,17,2048..,2048..]) -> (f32[1,17,256,256])' with friendly_name '/Add':
Argument shapes are inconsistent.


[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
FAILED:
higher-hrnet-w32-human-pose-estimation
```
yet I tested other IR models from open_model_zoo, but found that they cannot run with openvino202104, I will upload the model I used in previous test rencently.

**Comment by liubo-intel** [comment] 2023-05-17 02:21
> Hi, @liubo-intel : the test that have been done before with 2022.2 and 2022.3 do use a model cache. I just test our model with latest openvino (2023.0.0.dev20230427), and the issue remain the same (534.2 ms on Core(TM) i7-11850H @ 2.50GHz). w.r.t IR model we use may have difference with your test. I tried to download and convert the model from [open_model_zoo](https://github.com/openvinotoolkit/open_model_zoo/tree/117007cd4aa3d4ad911d0604beae5f6d60d3fe14/models/public/higher-hrnet-w32-human-pose-estimation), but have some issue here:
> 
> ```shell
> omz_converter --name higher-hrnet-w32-human-pose-estimation
> ========== Converting higher-hrnet-w32-human-pose-estimation to ONNX
> Conversion to ONNX command: C:\Users\310250211\.conda\envs\openvino-dev\python.exe -- C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\model_zoo\internal_scripts\pytorch_to_onnx.py --model-path=C:\Users\310250211\.conda\envs\openvino-dev\Lib\site-packages\openvino\model_zoo\models\public\higher-hrnet-w32-human-pose-estimation --model-path=C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation --model-name=get_net --import-module=model "--model-param=file_config=r\"C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation/experiments/higher_hrnet.yaml\"" "--model-param=weights=r\"C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation/ckpt/pose_higher_hrnet_w32_512.pth\"" --input-shape=1,3,512,512 --input-names=image --output-names=embeddings,heatmaps --output-file=C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation/higher-hrnet-w32-human-pose-estimation.onnx
> 
> ============== Diagnostic Run torch.onnx.export version 2.0.1+cpu ==============
> verbose: False, log level: Level.ERROR
> ======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
> 
> ONNX check passed successfully.
> 
> ========== Converting higher-hrnet-w32-human-pose-estimation to IR (FP16)
> Conversion command: C:\Users\310250211\.conda\envs\openvino-dev\python.exe -- C:\Users\310250211\.conda\envs\openvino-dev\Scripts\mo.exe --framework=onnx --output_dir=C:\Users\310250~1\AppData\Local\Temp\tmpwbp6kaxp --model_name=higher-hrnet-w32-human-pose-estimation --input=image --reverse_input_channels --mean_values=image[123.675,116.28,103.53] --scale_values=image[58.395,57.12,57.375] --output=embeddings,heatmaps --input_model=C:\Users\310250211\Desktop\model\public\higher-hrnet-w32-human-pose-estimation/higher-hrnet-w32-human-pose-estimation.onnx --layout=image(NCHW) "--input_shape=[1, 3, 512, 512]" --compress_to_fp16=True
> 
> [ ERROR ]  -------------------------------------------------
> [ ERROR ]  ----------------- INTERNAL ERROR ----------------
> [ ERROR ]  Unexpected exception happened.
> [ ERROR ]  Please contact Model Optimizer developers and forward the following information:
> [ ERROR ]  Check 'T::broadcast_merge_into(output_shape, input_shapes[1], autob)' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\shape_inference\include\utils.hpp:44:
> While validating node 'opset1::Add /Add (/Slice_1[0]:f32[?,17,256,256], /impl/final_layers.1/Conv[0]:f32[?,17,2048..,2048..]) -> (f32[1,17,256,256])' with friendly_name '/Add':
> Argument shapes are inconsistent.
> 
> [ ERROR ]  Traceback (most recent call last):
>   File "C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\tools\mo\convert_impl.py", line 920, in _convert
>     ov_model, legacy_path = driver(argv, {"conversion_parameters": non_default_params})
>   File "C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\tools\mo\convert_impl.py", line 598, in driver
>     res_ngraph_function = moc_emit_ir(ngraph_function, argv)
>   File "C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\tools\mo\moc_frontend\serialize.py", line 23, in moc_emit_ir
>     apply_moc_transformations(ngraph_function)
>   File "C:\Users\310250211\.conda\envs\openvino-dev\lib\site-packages\openvino\tools\mo\back\offline_transformations.py", line 39, in apply_moc_transformations
>     apply_moc_transformations(func, cf=False, smart_reshape=True)
> RuntimeError: Check 'T::broadcast_merge_into(output_shape, input_shapes[1], autob)' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\shape_inference\include\utils.hpp:44:
> While validating node 'opset1::Add /Add (/Slice_1[0]:f32[?,17,256,256], /impl/final_layers.1/Conv[0]:f32[?,17,2048..,2048..]) -> (f32[1,17,256,256])' with friendly_name '/Add':
> Argument shapes are inconsistent.
> 
> 
> [ ERROR ]  ---------------- END OF BUG REPORT --------------
> [ ERROR ]  -------------------------------------------------
> FAILED:
> higher-hrnet-w32-human-pose-estimation
> ```
> 
> yet I tested other IR models from open_model_zoo, but found that they cannot run with openvino202104, I will upload the model I used in previous test rencently.

ok, please upload the openvino IR(xml format model)(21.4 and 2023.0.0 if possible) that you used to your previous  [GoogleDrive](https://drive.google.com/drive/folders/1hOTihvbyIxsm5ygDpbUuJ7O_tzv4oXjC?usp=sharing) link, we will have  a look at it on our side.

**Comment by LeonHaoWI** [comment] 2023-05-17 08:53
hi @liubo-intel , I have some issue with google drive, and upload the model to [github](https://github.com/LeonHaoWI/modelShareForOpenVINOIsuue), the onnx model is converted to IR with openvino202104:
```bash
mo --input_model test.onnx
```

**Comment by liubo-intel** [comment] 2023-05-24 03:16
Hi, @LeonHaoWI : we have tried that with the following [changes](https://github.com/liubo-intel/openvino/commit/ea28d90c6cb31ab6dd1db4af22ddfcbfd5321e6d) , HigherHRnet based human-pose-estimation models(e.g. 'higher-hrnet-w32-human-pose-estimation' and the model you used) could gain significant improvement for model load time. and this changes is supposed have no effect on the model's inference performance && accuracy result. you may have a try this on your side. but **please notice** that this changes is only a workaround for this kind of special use case, for common use case, further model load time optimization may needs long term's plan for framework update.

And, please warm it up(run 1 iteration first) before officially start your model inference iterations(no matter use the above workaround or not), this warm up will cache some data which also can save times for loading the model again.

**Comment by LeonHaoWI** [comment] 2023-05-24 13:25
Thanks a lot! @liubo-intel 
As you mentioned "this changes is only a workaround for this kind of special use case", dose that means the changes could have disadvantage for other models? Do you have any further advice？
Btw, when could the long term's plan happen?

**Comment by liubo-intel** [comment] 2023-05-25 01:26
> Thanks a lot! @liubo-intel As you mentioned "this changes is only a workaround for this kind of special use case", dose that means the changes could have disadvantage for other models? Do you have any further advice？ Btw, when could the long term's plan happen?

yes, this workaround not works for all models. 
Thanks for your information, we have noticed this kind of optimization request for common model cases. but I'm afraid the time line depends on the priorities of all the requests on the  plan lists, I think currently we haven't the specific time line for this one as far as I know.

**Comment by avitial** [comment] 2023-07-10 16:51
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Closed by avitial** 2023-07-10 16:51 UTC
Labels: category: CPU, support_request
