### ISSUE TITLE
[Bug] Shape inference error with simple TensorFlow array indexing

### ISSUE THREAD

**Issue by kvablack** [openvinotoolkit/openvino#2549] opened 2020-10-06 01:35 UTC
##### System information (version)
- OpenVINO => 2020.4
- Operating System / Platform => Ubuntu 18.04
- Problem classification: Model Conversion
- Framework: TensorFlow 2.2.0

##### Detailed description
Simple array indexing in TensorFlow converts to a StridedSlice op, which subsequently fails shape inference if the index is unknown, even though the output shape should be obvious.

##### Steps to reproduce
Minimal example:
```.py
import tensorflow as tf

class Module(tf.Module):
    @tf.function(input_signature=[tf.TensorSpec([], dtype=tf.int32)])
    def __call__(self, x):
        c = tf.constant([0, 1, 2])
        return c[x]

module = Module()
tf.saved_model.save(module, "saved_model")
```

Then, trying to convert it with:

`python mo_tf.py --saved_model_dir saved_model --log_level=DEBUG`

produces:

```
[ 2020-10-05 20:31:54,544 ] [ DEBUG ] [ infer:130 ]  Partial infer for PartitionedCall/strided_slice
[ 2020-10-05 20:31:54,544 ] [ DEBUG ] [ infer:131 ]  Op: StridedSlice
[ 2020-10-05 20:31:54,544 ] [ DEBUG ] [ infer:132 ]  Inputs:
[ 2020-10-05 20:31:54,544 ] [ DEBUG ] [ infer:32 ]  input[0]: shape = [3], value = [0 1 2]
[ 2020-10-05 20:31:54,545 ] [ DEBUG ] [ infer:32 ]  input[1]: shape = [1], value = <UNKNOWN>
[ 2020-10-05 20:31:54,545 ] [ DEBUG ] [ infer:32 ]  input[2]: shape = [1], value = <UNKNOWN>
[ 2020-10-05 20:31:54,545 ] [ DEBUG ] [ infer:32 ]  input[3]: shape = [1], value = [1]
[ ERROR ]  Cannot infer shapes or values for node "PartitionedCall/strided_slice".
[ ERROR ]  Strided slice layer supports only constant begin and end inputs
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function StridedSlice.infer at 0x7f1f94c9d290>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
```

I've tried `tf.gather` as well as `tf.slice` as workarounds, and neither of those worked either.

**Comment by jgespino** [comment] 2020-10-07 12:57
Hi @kevin3-black 

We just released OpenVINO toolkit 2021.1 with official support for models trained in the TensorFlow 2.x framework. Could you please give the new release a try and see if your issue is solved?
https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html

If the issue is still present, please share your model to reproduce on our end.

Regards,
Jesus

**Comment by jgespino** [comment] 2020-10-16 15:49
Closing, please re-open if additional assistance is needed.

**Comment by kevin3-black** [comment] 2020-11-02 04:47
@jgespino sorry for the delay, got busy with some other things. Tried again with 2021.1 as well as the latest commit on master and had the exact same issue.

**Comment by jgespino** [comment] 2020-11-02 13:40
Hi @kvablack 

Please try to add `--input_shape` to your model optimizer command to specify the input shape. Could you share your model?

Regards,
Jesus

**Comment by kvablack** [comment] 2020-11-02 19:53
@jgespino I tried `--input_shape "[1]"`, same error. I provided some minimal reproduction code in the initial post, but I've attached the SavedModel here as well if that helps. Thanks.

[saved_model.zip](https://github.com/openvinotoolkit/openvino/files/5477656/saved_model.zip)

**Comment by mtolubaeva** [comment] 2020-12-30 15:39
@kvablack TF 2.2 is not supported by OpenVINO yet. Is it possible for you to use older versions?

**Comment by kvablack** [comment] 2020-12-30 23:05
> @kvablack TF 2.2 is not supported by OpenVINO yet. Is it possible for you to use older versions?

Hi @mtolubaeva, I just tried TF 2.0 and the exact same issue ocurred. I've attached the SavedModel.
[saved_model.zip](https://github.com/openvinotoolkit/openvino/files/5755965/saved_model.zip)

**Comment by mtolubaeva** [comment] 2021-01-13 17:56
Hi @kvablack it appears that currently we do not support non-constant `begin` and `end` inputs for `StridedSlice` operation. The dev team put it as a feature request but it will take time to implement it, and it's not planned for the upcoming release.

**Comment by jgespino** [comment] 2021-01-13 19:51
Ref. 44200

**Comment by sahira-rizvi** [comment] 2022-03-22 17:42
Closing, feel free to re-open or start a new issues if additional assistance is needed.

Sincerely,
Sahira

**Closed by sahira-rizvi** 2022-03-22 17:42 UTC
Labels: category: MO, feature, support_request
