### ISSUE TITLE
apt instll openvino error

### ISSUE THREAD

**Issue by JinXiaozhao** [openvinotoolkit/openvino#16076] opened 2023-03-03 09:36 UTC
Problem recurrence:

docker run -it --rm ubuntu:bionic bash
wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
apt-get install gnupg
echo "deb https://apt.repos.intel.com/openvino/2022 bionic main" | sudo tee /etc/apt/sources.list.d/intel-openvino-2022.list
apt update

Error message:
Get:1 https://apt.repos.intel.com/openvino/2022 bionic InRelease [11.4 kB]
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease                  
Get:4 https://apt.repos.intel.com/openvino/2022 bionic/main all Packages [2166 B]
Err:4 https://apt.repos.intel.com/openvino/2022 bionic/main all Packages      
  File has unexpected size (1338 != 2166). Mirror sync in progress? [IP: 192.168.250.189 80]
  Hashes of expected file:
   - Filesize:2166 [weak]
   - SHA512:5febcfbba12f75d261c5e88083f977aef6b4fe623297d505348b89f900759ee9838bd8e012015aba5200b170c2811404b113d3dbe2f6822f9b275cb16d8920cb
   - SHA256:b4b7a4a6d314db290b6d2bb6ec17fbfd8adc6adf74bda477a629cc73a1c3f0a3
   - SHA1:eeff275d4eccac29659bc0142d51298789012052 [weak]
   - MD5Sum:75a7d0adde4d1fa0474e9b1131c37f6b [weak]
  Release file created at: Wed, 14 Dec 2022 04:34:38 +0000
Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                             
Hit:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                            
Get:7 https://apt.repos.intel.com/openvino/2022 bionic/main amd64 Packages [9927 B]    
Err:7 https://apt.repos.intel.com/openvino/2022 bionic/main amd64 Packages
  
Fetched 11.4 kB in 3s (4445 B/s)
Reading package lists... Done
E: Failed to fetch https://apt.repos.intel.com/openvino/2022/dists/bionic/main/binary-all/Packages.gz  File has unexpected size (1338 != 2166). Mirror sync in progress? [IP: 192.168.250.189 80]
   Hashes of expected file:
    - Filesize:2166 [weak]
    - SHA512:5febcfbba12f75d261c5e88083f977aef6b4fe623297d505348b89f900759ee9838bd8e012015aba5200b170c2811404b113d3dbe2f6822f9b275cb16d8920cb
    - SHA256:b4b7a4a6d314db290b6d2bb6ec17fbfd8adc6adf74bda477a629cc73a1c3f0a3
    - SHA1:eeff275d4eccac29659bc0142d51298789012052 [weak]
    - MD5Sum:75a7d0adde4d1fa0474e9b1131c37f6b [weak]
   Release file created at: Wed, 14 Dec 2022 04:34:38 +0000
E: Failed to fetch https://apt.repos.intel.com/openvino/2022/dists/bionic/main/binary-amd64/Packages.gz  
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ilya-lavrenov** [comment] 2023-03-03 10:55
The issue is fixed now.
Please, check

**Closed** 2023-03-03 10:56 UTC
Labels: platform: linux, priority: high, category: packaging
