### ISSUE TITLE
yolov3 inference error cannot convert float NaN to integer

### ISSUE THREAD

**Issue by Diaislam** [openvinotoolkit/openvino#454] opened 2020-04-10 17:02 UTC
Hello  i have followed all the steps to make an inference and successfully run it on the model in this link : https://pjreddie.com/media/files/yolov3.weights
but when i tried it on a model i trained with darknet i get this error :

```
[ INFO ] Creating Inference Engine...
[ INFO ] Loading network files:
	newyolo.xml
	newyolo.bin
[ INFO ] Preparing inputs
[ INFO ] Loading model to the plugin
[ INFO ] Starting inference...
To close the application, press 'CTRL+C' here or switch to the output window and press ESC key
To switch between sync/async modes, press TAB key in the output window
yolo_original.py:280: DeprecationWarning: shape property of IENetLayer is deprecated. Please use shape property of DataPtr instead objects returned by in_data or out_data property to access shape of input or output data on corresponding ports
  out_blob = out_blob.reshape(net.layers[net.layers[layer_name].parents[0]].shape)
[ INFO ] Layer detector/yolo-v3/Conv_14/BiasAdd/YoloRegion parameters: 
[ INFO ]          classes : 10
[ INFO ]          num     : 3
[ INFO ]          coords  : 4
[ INFO ]          anchors : [55.0, 56.0, 42.0, 87.0, 68.0, 81.0]
Traceback (most recent call last):
  File "yolo_original.py", line 363, in <module>
    sys.exit(main() or 0)
  File "yolo_original.py", line 286, in main
    args.prob_threshold)
  File "yolo_original.py", line 153, in parse_yolo_region
    h_scale=orig_im_h, w_scale=orig_im_w))
  File "yolo_original.py", line 99, in scale_bbox
    xmin = int((x - w / 2) * w_scale)
ValueError: cannot convert float NaN to integer
```

knowing that i have provided the right shape and changed  yolo_v3.json to match my model

here is the content of my yolo_v3.json: 

```
[
  {
    "id": "TFYOLOV3",
    "match_kind": "general",
    "custom_attributes": {
      "classes": 10,
      "anchors": [18,22,31,33,33,50,55, 56,42,87,68,81,111,98,73,158,156,202],
      "coords": 4,
      "num": 9,
      "masks":[[6, 7, 8], [3, 4, 5], [0, 1, 2]],
      "entry_points": ["detector/yolo-v3/Reshape", "detector/yolo-v3/Reshape_4", "detector/yolo-v3/Reshape_8"]
    }
  }
]
```
i have tried multiple things to debug this like not providing the jsonfile ....etc

**Comment by maxl16** [comment] 2020-04-13 09:53
Hello @Diaislam 
Where did you get this "yolo_original.py" file? From the error shown it seems like the problem it with the python code itself, and not with the model. An application expects to get "integer" data type, but receives "float NaN" one.
The best way to fix it is to track a code segment where you get NaN value and then convert it to non-NaN or modify the original operation in order to get non-NaN in the first place. The traceback shows some clues on what operations expect to receive integer value, but received NaN:
>>xmin = int((x - w / 2) * w_scale)  
>>h_scale=orig_im_h, w_scale=orig_im_w))

Here's a similar case with code example - https://stackoverflow.com/questions/42463084/python-cant-convert-float-nan-to-integer

Also, you could try "object detection yoloV3  python demo" from OpenVINO toolkit package instead of your yolo_original.py - https://docs.openvinotoolkit.org/latest/_demos_python_demos_object_detection_demo_yolov3_async_README.html

Hope this helps.
Best regards, Max.

**Comment by Diaislam** [comment] 2020-04-13 10:11
> Hello @Diaislam
> Where did you get this "yolo_original.py" file? From the error shown it seems like the problem is with the python code itself, and not with the model. An application expects to get "integer" data type, but receives "float NaN" one.
> The best way to fix it is to track a code segment where you get NaN value and then convert it to non-NaN or modify the original operation in order to get non-NaN in the first place. The traceback shows some clues on what operations expect to receive integer value, but received NaN:
> 
> > > xmin = int((x - w / 2) * w_scale)
> > > h_scale=orig_im_h, w_scale=orig_im_w))
> 
> Here's a similar case with code example - https://stackoverflow.com/questions/42463084/python-cant-convert-float-nan-to-integer
> 
> Also, you could try "object detection yoloV3 python demo" from OpenVINO toolkit package instead of your yolo_original.py - https://docs.openvinotoolkit.org/latest/_demos_python_demos_object_detection_demo_yolov3_async_README.html
> 
> Hope this helps.
> Best regards, Max.

Hello @maxl16 thank you for your reply,
yolo_original.py is the same object detection demo by openvino i just renamed it, as i said the demo runs for the models in the internet , but mine is customly trained and i have changed the yolo_v3.json according to my config , the transformation to IR succeeded without any error , by the inference gives me the results i mentionned

**Comment by maxl16** [comment] 2020-04-13 11:39
@Diaislam 
Okay, in that case the issue is indeed with the model trained. We recommend you to go thru this step by step guide from the scratch in order to make sure that everything is performed in a recommended way including your model conversion from darknet format:
https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html
Also, please ensure that you are using the model optimizer and the inference engine from the latest 2020.1 build of OpenVINO toolkit.

**Comment by Diaislam** [comment] 2020-04-13 11:55
@maxl16 i'm using the latest version of openvino and i followed the guide step by step , the problem is with the output everything is performed right i'm sure.

**Comment by maxl16** [comment] 2020-04-15 10:39
@Diaislam 
This might be a common problem, not related to the model optimizer or the inference engine, as per https://github.com/experiencor/keras-yolo3/issues/117
Are you able to do a test inference with the darknet command?
./darknet detector demo <your-data-file>.data yolov3.cfg  yolov3_<weights-value>.weights

**Comment by AnastasiaKazantaeva** [comment] 2020-07-18 19:05
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,

**Closed by AnastasiaKazantaeva** 2020-07-18 19:05 UTC
