### ISSUE TITLE
[Bug] Can't compile Conv1d layer when dilated, doesn't happen in 2d or if dilation_rate=1 in VPU [category: VPU]

### ISSUE THREAD

**Issue by Horikuab** [openvinotoolkit/openvino#3724] opened 2020-12-24 11:30 UTC
##### System information (version)

- OpenVINO=> 2021.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification => Model Compilation
- Framework: TensorFlow
- Model name: Dilated Convolutional network or TCN

##### Detailed description
I found that when building a tensorflow network with just 2 layers, one Conv1d with dilation_rate>1 and one Dense layer the model can't compile to the Intel Neural Compute Stick 2 but runs without issues in CPU. I tried compiling with dilation_rate set to 1 and then it runs no problem and also tried a model with 2d convolution and dilation_rate >1 and also worked.
I found in the documentation that openvino suports keras-tcn architecture but i also tried building a network using TCN layers and the same error popped up.  I may be missing some parameters but find it very odd.

##### Steps to reproduce
1st Build Tensorflow Model:
  Example:
  //Python
```.py
  model = tf.keras.Sequential()
  model.add(tf.keras.layers.Input(batch_shape=(None, 256, 2)))
  model.add(tf.keras.layers.Conv1d(12, 2, dilation_rate=2, padding='causal')
  model.add(Dense(1))
  model.compile(loss=r2, optimizer=AdaBound(learning_rate=0), metrics=['mse','mae'])
  //2nd Freeze model:
  tf.saved_model.save(model,'/content/drive/MyDrive/')
```
3rd Obtain IR Representation
  In windows, run command:
  python3 mo_tf.py --saved_model_dir {DIR} -b 1 -data FP16

4th Once Obtained, try to run Inference:
```.py
import sys
import datetime
import pylab
from argparse import ArgumentParser, SUPPRESS
from os import path
from openvino.inference_engine import IECore, IENetwork
import numpy as np
import pickle
import pandas as pd
import subprocess
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
import os

#INIT VARIABLES
print(subprocess.run(["C:\\Program Files (x86)\\Intel\openvino_2021\\bin\\setupvars.bat"],capture_output=True))

 ie = IECore()
print("Reading IR...")
net = ie.read_network("TCN/modeldil2/saved_model.xml", "TCN/modeldil2/saved_model.bin")
print("Read Successful")

exec_net = ie.load_network(network=net, device_name="MYRIAD")
print(exec_net.input_info)
i = 0
```

Error:
Traceback (most recent call last):   File "C:/Users/{NAME}/Desktop/Intel NCS2/runmodel.py", line 145, in <module>     sys.exit(main() or 0)   File "C:/Users/{NAME}/Desktop/Intel NCS2/runmodel.py", line 130, in main     exec_net = ie.load_network(network=net, device_name="MYRIAD")   File "ie_api.pyx", line 306, in openvino.inference_engine.ie_api.IECore.load_network   File "ie_api.pyx", line 315, in openvino.inference_engine.ie_api.IECore.load_network RuntimeError: Failed to compile layer "StatefulPartitionedCall/sequential_31/tcn1/residual_block_0/conv1D_0/Pad": AssertionFailed: layer->pads_begin.size() == 4

IR model Used
[saved_model.zip](https://github.com/openvinotoolkit/openvino/files/5739412/saved_model.zip)

**Comment by Horikuab** [comment] 2020-12-28 10:38
Any update please?

**Comment by maxlytkin** [comment] 2020-12-29 13:43
@Horikuab 
Thanks for reporting this. I was able to reproduce this error message on MYRAID using the model provided. Let me check with my peers and get back to you.
Can you please also attach the original TF model?

**Comment by Horikuab** [comment] 2020-12-29 16:07
[model.zip](https://github.com/openvinotoolkit/openvino/files/5751319/model.zip)

**Comment by sonebu** [comment] 2021-01-04 19:50
I suspect [this](https://github.com/openvinotoolkit/openvino/blob/00d37aaa62f18bcfca19a85eea850c850a128d17/inference-engine/src/vpu/graph_transformer/src/stages/pad.cpp#L96) is the source (if the Myriad plugin in the 2021.2 release is indeed built from the open source toolkit), I just ran into it due to a padding layer too.

Seems like the Pad layer is only supported for 4-dimensional tensors on Myriad right now. Is there a specific/good reason for this? (Perhaps the graph transformer is trying to utilize some sort of "hardware padding" like in [here](https://github.com/openvinotoolkit/openvino/blob/d18073260bc742d7bf14d262d6919a1b660e2b61/inference-engine/src/vpu/graph_transformer/include/vpu/middleend/hw/utility.hpp#L41)?) There are of course use cases where a smaller dim array may be padded.

**Comment by Horikuab** [comment] 2021-01-11 10:15
Hey, has any progress been made? 
If some mistake has been made from my part either in coding the model or in the transformation from tensorflow i would really appreciate some feedback.

**Comment by mtolubaeva** [comment] 2021-01-13 17:43
Yes, @sonebu is right, currently Pad layer supports only 4D input/output tensors. We can ask the dev team to support different dimension tensors, but it will need to go through the formal process and will take time.

**Comment by Horikuab** [comment] 2021-01-18 12:12
Thanks for reporting about this, i understand that's just a part of the development process. 
I asked before if there were any settings from the model optimizer which weren't set properly because theoretically one of the supported models from the openvino website (keras-tcn) use in their implementation this type of conv1d dilated layer. If there are any steps to follow in order to run their model maybe a generalization of that could be used in this case.

**Comment by maxlytkin** [comment] 2021-02-16 10:31
@Horikuab 
Unfortunately, we don't have any workaround for this, but here's a feature request to make this problem fixed https://github.com/openvinotoolkit/openvino/pull/4351

**Comment by maxlytkin** [comment] 2021-02-16 10:31
Ref. 46417

**Comment by sonebu** [comment] 2021-02-16 12:00
@maxlytkin @mtolubaeva is it possible to modify this open source version of the Myriad plugin (e.g., for this problem), build it (without any additional proprietary tools), and then use it like the normal published version of the plugin (the one in the latest releases of the "Intel's distribution of OpenVINO")? Or is this open source version of the toolkit not the complete package and you need additional proprietary tools to build the Myriad plugin?

**Comment by maxlytkin** [comment] 2021-02-17 09:36
@sonebu 
It should be possible. For reference, please check the following articles:
1. [How to Build the Open-Source OpenVINO™ toolkit for Linux* from Source with the Python* API Wrapper](https://www.intel.com/content/www/us/en/support/articles/000057448/software/development-software.html) 
2. [Intel® Neural Compute Stick 2 and Open Source OpenVINO™ Toolkit](https://software.intel.com/content/www/xl/es/develop/articles/intel-neural-compute-stick-2-and-open-source-openvino-toolkit.html)

The aforementioned PR is available for OpenVINO open source version only. So yes, please feel free to test it. MYRIAD plugin is included into the open source package.
The fix should be also implemented into one of future Intel's distribution of OpenVINO releases.

**Comment by maxlytkin** [comment] 2021-02-25 10:14
@Horikuab 
the PR https://github.com/openvinotoolkit/openvino/pull/4351 has been merged. Please, verify from your side

**Comment by maxlytkin** [comment] 2021-03-04 09:53
Closing, feel free to re-open or start a new issue if additional assistance is needed.

**Closed by maxlytkin** 2021-03-04 09:53 UTC
Labels: TCE, bug, feature, support_request
