### ISSUE TITLE
error while converting Keras H5

### ISSUE THREAD

**Issue by dev2y** [openvinotoolkit/openvino#13734] opened 2022-10-31 04:40 UTC
Hi, want to try OV for our AI work and trying convert our H5 custom models to OV.

Was looking at OV [documentation ](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html)but getting error. Can you please help?

```
import tensorflow as tf
from custom_layer import CustomLayer
model = tf.keras.models.load_model('model.h5', custom_objects={'CustomLayer': CustomLayer})
tf.saved_model.save(model,'model')
```

Error:
```
>>> from custom_layer import CustomLayer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'custom_layer'

```

I've tried this on TF2.3 and TF2.10

**Comment by rkazants** [comment] 2022-10-31 06:25
Hi @dev2y,

First of all, let us figure out if you have custom layers in your model. Assume that there is no custom layers, you can re-save your model to the SavedModel format as like:

```
import tensorflow as tf
model = tf.keras.models.load_model('model.h5')
tf.saved_model.save(model,'model')
```

If you have loading error complaining on some non-Keras layer `YourLayer` from your_layer_module.py, that means you need to pre-load these layers from Python modules with its implementation:

```
from your_layer_module import YourLayer
model = tf.keras.models.load_model('model.h5', custom_objects={'YourLayer': YourLayer})
```

Please send me errors if you still face the issue.

Best regards,
Roman

**Comment by dev2y** [comment] 2022-10-31 15:48
@rkazants
Hi Roman, thank you. 

When I try loading model h5, I get the following error.

```
import tensorflow as tf
model = tf.keras.models.load_model('model.h5')

```
Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tfenv/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "tfenv/lib/python3.8/site-packages/keras/utils/generic_utils.py", line 1269, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'freeze')
```

**Comment by rkazants** [comment] 2022-11-01 04:08
Hi @dev2y,

Will it be possible to share the model with me? You can share the model with fake weights.
It is difficult to say the reason of the loading problem. Can you check what TF version do you use and try to upgrade it? Also, please try to load the model by native Keras API and save it into SM format by TF:

```
import tensorflow as tf
from keras.models import load_model
model = load_model('model.h5')
tf.saved_model.save(model,'saved_model')
```

Best regards,
Roman

**Comment by dev2y** [comment] 2022-11-01 07:48
Hi Roman, I tried loading model with keras but still the same 'freeze' error.

here is my [model ](https://drive.google.com/file/d/1VXPEmKjwfkb6wy9LRmqJizogiXBqLPX_/view?usp=sharing
)with dummy weights. Thank you

**Comment by rkazants** [comment] 2022-11-01 09:26
Hi @dev2y,

I visualized your model and noticed the custom layers: Anchors, 
regression_submodel, classification_submodel, RegressBoxes, etc.
![image](https://user-images.githubusercontent.com/35459624/199201991-73b387c7-67b5-4b2a-aa9a-39117ac76f74.png)

I think you need to pre-load these custom layers. And the displayed issue about `freeze` was confusing and just mixed up us.
How did you get this model? Is it from Keras Zoo?

Best regards,
Roman

**Comment by rkazants** [comment] 2022-11-02 10:16
Hi @dev2y,

Any news? Do you have a chance to contact developers of this model to get the instructions to infer this model via the original framework (Keras or TensorFlow)?

Best regards,
Roman

**Comment by avitial** [comment] 2022-11-21 21:19
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.

**Closed by avitial** 2022-11-21 21:19 UTC
Labels: category: MO, support_request
