### ISSUE TITLE
[Bug]Cannot initialize InferenceEngine::Core

### ISSUE THREAD

**Issue by laizewei** [openvinotoolkit/openvino#5581] opened 2021-05-11 01:57 UTC
- OpenVINO => 2021.3.394
- Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz   3.10 GHz
- Operating System / Platform => Windows10 64 Bit 
- Compiler => Visual Studio 2019
- Problem classification: Cannot initialize InferenceEngine::Core
- Framework: Onnx (if applicable)
------------------------------------------------
#include <iostream>
#include <inference_engine.hpp>
int main()
{
	InferenceEngine::Core core;//<-----error
	std::cout << "aa" << std::endl;
}
-------------------------------------------------------------
Unhandled Exception at 0x00007FFCA55DD759 (in test_openvinin.exe) : Microsoft C++ Exception: InferenceEngine: : the details: : InferenceEngineException, located in the memory location 0 x00000096c5b1f510.

**Comment by laizewei** [comment] 2021-05-11 04:16
ie_.LoadNetwork(network_, “CPU”);//error

**Comment by ilya-lavrenov** [comment] 2021-05-12 12:42
Hi @laizewei 

> Unhandled Exception at 0x00007FFCA55DD759 (in test_openvinin.exe) : Microsoft C++ Exception: InferenceEngine: : the details: : InferenceEngineException, located in the memory location 0 x00000096c5b1f510.

It's hard to predict what is going wrong. Could you please provide more details? sample code? can you compile in debug mode and provide back traces?

Thanks,
Ilya.

**Comment by laizewei** [comment] 2021-05-12 13:06
The ONNX model is a dynamic input with the size [1,1,32,-1], which may be the reason for the inference error.I changed the input to [1,1,32,180] to convert to OpenVino Model(xml,bin), but I still got an inference error.I am using the OnNXRuntime inference model now. OnNXRuntime1.7.0 supports OpenVino, but I tried to link to the OpenVino library and got an error.

**Comment by fperezgamonal** [comment] 2021-05-20 09:37
Hi there,

I'm also facing a similar issue when trying to run in 'debug' configuration an application where I'm trying to integrate OpenVINO to inference on machines without dedicated GPUs. I can run all the C++ samples in debug configuration without problems, stopping at every line.

Release configuration crashes in a third party logger code but is probably related to changes done to integrate OpenVINO (since it did not happen before).

Anyway, in hopes of getting more information, I added a catch statement for **InferenceEngineException**(s). As follows:
```
#pragma once
#pragma warning(push)
#pragma warning(disable:4251)
#pragma warning(disable:4275)
#   include <inference_engine.hpp>
#   include <ie_iextension.h>
#   include <details/ie_exception.hpp>
#ifdef OPENVINO2019
#   include <ext_list.hpp>              // Required for CPU extension usage
#endif
#pragma warning(pop)

// [...]
int main(int argc, char* argv[]){
try
{
    // [...]
    InferenceEngine::Core ie;  // <==== the exception is thrown here
    InferenceEngine::CNNNetwork cnn_network;
    InferenceEngine::ExecutableNetwork executable_network;
    InferenceEngine::InputsDataMap inputs_info;
    InferenceEngine::DataPtr outputs_info;
    // [...]
}
catch (InferenceEngine::details::InferenceEngineException e)
{
    std::cerr << "InferenceEngineException: " << e.what() << " (status code: " << e.getStatus() << ")") << std::endl;
}
//[...] other catch(s) here
}
```
The catched exception prints the following cryptic message:
![image](https://user-images.githubusercontent.com/19503950/118956118-9d7a4600-b95f-11eb-9121-a289ca905636.png)

As you said, on the visual studio output I get the non-descriptive message you attached:
```
Exception thrown at 0x00007FFF5FB59689 in OpenVINO_demo.exe: Microsoft C++ exception: InferenceEngine::details::InferenceEngineException at memory location 0x00000051C16FE910.
```
After taking a look at several other issues, I thought it may be related to ["[ ERROR ] Error loading XML file: ..\..\plugins.xml:1:0: File was not found #395"](https://github.com/openvinotoolkit/openvino/issues/395) and that for some reason I didn't get the proper XML filename.

However, when I tried to apply @simeoncapy 's solution (by simply copying plugins.xml from `C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\inference_engine\bin\intel64\Debug` to where my exe is located, I still got the same error.

I will keep investigating and get back to you if I found anything useful. Any help would be much appreciated since I'm quite lost at the moment. The only hint I have is the reference to **ie_core.cpp:191** but I can obviously not access that file nor line... Meanwhile I'll revert to trying to found any major configuration difference between the C++ samples and my application that can explain the error.

I attach my environment details in case they may be useful to gather more intel (no pun intended) on the problem.
- In my path I've added:
```
C:\Program Files (x86)\Intel\openvino_2021.2.185\inference_engine\bin\intel64\Release
C:\Program Files (x86)\Intel\openvino_2021.2.185\inference_engine\bin\intel64\Debug
C:\Program Files (x86)\Intel\openvino_2021.2.185\opencv\bin
C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\inference_engine\external\tbb\bin
C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\ngraph\lib
C:\Program Files (x86)\Intel\openvino_2021.2.185\inference_engine\bin\intel64\Release
C:\Program Files (x86)\Intel\openvino_2021.2.185\inference_engine\bin\intel64\Debug
```
- OS: Windows 10 (version 1809)
- OpenVINO:  2021.2.0-1877-176bdf51370-releases/2021/2
- IDE/Compiler: Visual Studio 2017 / MSVC

Let me know if any more information would be helpful.

Cheers,

Ferran.

**Comment by laizewei** [comment] 2021-05-20 13:52
It is recommended to use OnNXRuntime inference because OpenVino cannot load some OnNX models.

**Comment by fperezgamonal** [comment] 2021-05-20 14:05
Hello, in my case, I'm working with a model exported from Tensorflow 1.X. I'll update my previous post to be clearer!

**Comment by ilya-lavrenov** [comment] 2021-05-20 15:44
From the logs I see that `plugins.xml` is missed and Core reports about it. It should be located near the inference_engine.dll / libinference_engine.so

**Comment by fperezgamonal** [comment] 2021-05-21 08:25
Hello @ilya-lavrenov ,

It is indeed located in the same folder as `inference_engined.dll` (debug version). Nevertheless, I still get the same exception having the path `C:\Program Files (x86)\Intel\openvino_2021.2.185\deployment_tools\inference_engine\bin\intel64\Debug` and its release counterpart in my `$PATH`.

I even tried to directly copy all the contents from the folder above (i.e.: all DLLs and `plugins.xml`) to the application folder but it still fails with the same exception.
Maybe something was not properly installed? I'm only suggesting that because of the junk printed instead of `plugins.xml` in the thrown exception.

If I make any progress, I'll let you know. Thanks!!

**Comment by fperezgamonal** [comment] 2021-05-26 09:29
Hello again,

Just to let you know, the problem I encountered was inside a project with a broken Debug configuration. Maybe something related to the project configuration is causing the XML not to be found. 
Once we fix the configuration, I'll try to run OpenVINO and debug and I'll let you know if that fixes it.

Nevertheless, feel free to close this issue if you need to.
Cheers!

**Comment by Iffa-Meah** [comment] 2021-05-28 03:39
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Closed by Iffa-Meah** 2021-05-28 03:39 UTC
Labels: ONNX, category: MO, support_request

**Comment by Hezhexi2002** [comment] 2022-01-09 11:15
@ilya-lavrenov Hi,I meet this problem on Ubuntu20.04 too,My openvino version is 2021.4.752 and here is the screenshot:
![Screenshot from 2022-01-09 18-54-19](https://user-images.githubusercontent.com/53631206/148679734-7d457516-7a4d-4157-9861-f9526933c3b3.png)
As you can see I have put the nanodet.xml into my workplace folder but it can't open it all the time,I meet this when I use vs to run it too,so is there any solution for my situation now,I would  appreciate it if you can give me some advices！

**Comment by Hezhexi2002** [comment] 2022-03-07 14:28
![image](https://user-images.githubusercontent.com/53631206/157052298-58479d29-9396-41aa-b3ca-dd377bf8afaa.png)
@fperezgamonal Hi! I got the same error when I ran it on VS2017 in Debug x64 and I will get this error when I switched to Release x64 mode:
![image](https://user-images.githubusercontent.com/53631206/157052698-0a36cfea-27e5-4747-952c-0dad55c5a00b.png)
Can you give some instructions about how to get rid of this error？I have struggled with it for a long time,I would appreciate it if you can give me some instructions！:-)

**Comment by ilya-lavrenov** [comment] 2022-03-09 10:35
OpenVINO is build on Windows OS with MSVC 2019. 
I am not sure whether is can be a problem that you use 2017 VS.

**Comment by Hezhexi2002** [comment] 2022-03-10 12:53
> OpenVINO is build on Windows OS with MSVC 2019. I am not sure whether is can be a problem that you use 2017 VS.

![image](https://user-images.githubusercontent.com/53631206/157665681-95419a4a-15cd-4878-b757-85b579a70c09.png)
Hi,I try to rebuild it on VS2019 and it still get this error

**Comment by ilya-lavrenov** [comment] 2022-03-10 13:16
Could you please try to build with debug version and see back-trace? It's hard to imagine what happens..

**Comment by Hezhexi2002** [comment] 2022-03-10 13:29
I'm currently using debug mode to run it and I have used F10 to see the back-trace,the error seems to be caused by the xml_path of my model

**Comment by Hezhexi2002** [comment] 2022-03-10 13:32
[Plan A.zip](https://github.com/openvinotoolkit/openvino/files/8223773/Plan.A.zip)
here is my pdb file

**Comment by Hezhexi2002** [comment] 2022-03-11 00:58
@ilya-lavrenov 
![image](https://user-images.githubusercontent.com/53631206/157779902-cf7b84e8-7ac7-4b22-8015-6b09cc625229.png
![image](https://user-images.githubusercontent.com/53631206/157780299-21766071-e981-4831-aecd-a26357fd1a6b.png)
Hi,sorry to bother you again but I try to just verify wether it can initialize the inferenceEngine::core properly.As you can see in the two screenshots above,the first one is which I didin't comment the line of`auto cnnNetwork = ie.ReadNetwork("H:/GitHub/LabelRoboMaster/resource/model-opt.xml");` and it throw this error once again,However,the code can initialize the InferenceEngine::core correctly as soon as I removed the line and it print the string "aa" which was shown in the second picture.So I wonder if it caused by the path of my xml file which contains blank space but it didn't change anything after I replace the path with one didn't contain blankspace.I really can't think of another reason of this problem!:-(

**Comment by Asthestarsfalll** [comment] 2022-04-07 02:37
@Hezhexi2002
hi, do you solve this? I encounter the same problem.

**Comment by Hezhexi2002** [comment] 2022-04-07 02:38
> @Hezhexi2002 hi, do you solve this? I encounter the same problem.

Not yet:-(
