### ISSUE TITLE
when loading INT8 model, 'Floating point exception (core dumped)‘ happended

### ISSUE THREAD

**Issue by NotMorven** [openvinotoolkit/openvino#1387] opened 2020-07-20 07:42 UTC
OpenVINO 2020.3, full precision IR model can be inferred correctly using IECore, but errors happended after Post-Training Optimization when 'ie.load_network()'

Has anyone had a similar problem？

**Comment by brmarkus** [comment] 2020-07-20 07:48
Can you provide more information about the model, please? Where have you got it from, how have you done the post-training-optimizations?
Can you reproduce the behavior with one of the OpenVINO/OpenModelZoo samples, e.g. "benchmark_app"?
Have you done the optimization on one machine and run the inference on another machine (e.g. different machines with different instruction sets)?
How does the core-dump look like, can you maybe provide the output, please?

**Comment by NotMorven** [comment] 2020-07-20 13:40
> Can you provide more information about the model, please? Where have you got it from, how have you done the post-training-optimizations?
> Can you reproduce the behavior with one of the OpenVINO/OpenModelZoo samples, e.g. "benchmark_app"?
> Have you done the optimization on one machine and run the inference on another machine (e.g. different machines with different instruction sets)?
> How does the core-dump look like, can you maybe provide the output, please?

Hi brmakus,
The model is InceptionV3 pretrained on ImageNet. I did the post-training optimizations in simple mode with "DefaultQuantization" algorithm. The using command is "pot -c xxx_smple_mode.json". 
I have done the post-training optimization and int8-model inference on my Win10 PC (Core i5-8265U) successfully. The Error happens on Linux Server(Xeon Platinum 8269CY), when I do the same procedure. I installed openvino in the docker environment of the server. The official samples can be correctly reproduce, and the Inferrence Engine can infer the full precision model successfully, but there is an error when loading the int8 model (ie.load_network) with only ouput information "Floating point exception (core dumped)". I have downloaded and tested the int8 model on my Win10 PC, it can be inferred successfully. So I think the int8 model is valid. 
I don't know what went wrong. Looking forward to your reply. Thanks!!!!!

**Comment by maxlytkin** [comment] 2020-07-23 15:58
Hi @NotMorven 
Please test your INT8 model with OpenVINO Benchmark app on Linux OS. Do you get the same core dumped error message?
Benchmark C++ Tool https://docs.openvinotoolkit.org/latest/openvino_inference_engine_samples_benchmark_app_README.html
Benchmark Python Tool https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_benchmark_tool_README.html

Thanks.
Best regards, Max.

**Comment by NotMorven** [comment] 2020-07-27 08:46
> Hi @NotMorven
> Please test your INT8 model with OpenVINO Benchmark app on Linux OS. Do you get the same core dumped error message?
> Benchmark C++ Tool https://docs.openvinotoolkit.org/latest/openvino_inference_engine_samples_benchmark_app_README.html
> Benchmark Python Tool https://docs.openvinotoolkit.org/latest/openvino_inference_engine_tools_benchmark_tool_README.html
> 
> Thanks.
> Best regards, Max.

Hi @maxlytkin 
I have tested my int8-model using Benchmark C++ Tool, still get the 'Floating point exception(core dumped)', and the full output is below:
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     /root/downloads/mt_baker.jpg
[ WARNING ] -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance,but it still may be non-optimal for some cases, for more information look at README.

[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
        API version ............ 2.1
        Build .................. 2020.3.0-3467-15f2c61a-releases/2020/3
        Description ....... API
[ INFO ] Device info:
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 2020.3.0-3467-15f2c61a-releases/2020/3

[Step 3/11] Setting device configuration
[Step 4/11] Reading the Intermediate Representation network
[ INFO ] Loading network files
[ INFO ] Read network took 316.85 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
Floating point exception (core dumped)

Thanks!!!
Morven

**Comment by maxlytkin** [comment] 2020-07-27 15:55
@NotMorven 
I've tested pre-trained Inception V3 models from here https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html 
inception_v3_2016_08_28.tar.gz and inception_v3_quant.tgz
They both work fine on my Linux machine. Can you please share your quantized model so we could also test this from our end?

Best regards, Max.

**Comment by NotMorven** [comment] 2020-07-29 07:53
> @NotMorven
> I've tested pre-trained Inception V3 models from here https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html
> inception_v3_2016_08_28.tar.gz and inception_v3_quant.tgz
> They both work fine on my Linux machine. Can you please share your quantized model so we could also test this from our end?
> 
> Best regards, Max.

@maxlytkin 
I'm sorry I cann't share my quantized model with you due to our secrecy provisions. But I have new progress here to update with you: I migrated the same OpenVINO environment docker image to a Linux machine with an **older CPU model** ( Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz ) and **all the problems were solved**. The problemmatic CPU model is Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz.
So I'm wondering if OpenVINO's lack of support for this model of CPU caused such a problem.

Best regards, Morven.

**Comment by maxlytkin** [comment] 2020-07-31 12:44
Hi @NotMorven 
As per the documentation, OpenVINO toolkit supports all generations of Xeon Scalable processors (Skylake, Cascade Lake, Cooper Lake). However, as I see, Xeon Platinum 8269CY is not a publicly available CPU model, so this supposed to be specific ODM's SKU with, for example, modified instructions. This might be the reason. 
Thanks for sharing this with the community.

**Comment by NotMorven** [comment] 2020-08-03 03:33
Hi @maxlytkin 
I got it. Thank you. 
By the way, I'm also wondering if there is a way to manually set the CPU utilization of the infer request. I did not see the relevant content in the Python API. 

Best regards, Morven

**Comment by maxlytkin** [comment] 2020-08-04 12:21
Hi @NotMorven 
As I'm aware, there's no direct method to limit or configure CPU utilization, however, you can play with different CPU plugin values, especially KEY_CPU_THREADS_NUM and KEY_CPU_THROUGHPUT_STREAMS parameters described on [CPU plugin page](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_supported_plugins_CPU.html#supported_configuration_parameters)
Thank you.

**Comment by NotMorven** [comment] 2020-08-05 07:25
Hi @maxlytkin 
I tried the method you suggested. The configuration is as follows:
```
config={'CPU_THREADS_NUM': '0', 'CPU_THROUGHPUT_STREAMS': '1'}. 
```
**As per the documentation, all the logical cores are supposed to be used. But it's weird, after testing, the CPU utilization is only 49% on the 8-core machine and 40% on the 32-core machine.** 

The cpu information are list below:
**(1) 8-core machine**
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz
Stepping:              7
CPU MHz:               2500.002
BogoMIPS:              5000.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap avx512cd xsaveopt xsavec xgetbv1 arat

**(2)32-core machine**
Architecture:          x86_64
CPU op-mode(s)：    32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core：2
Core(s) per socket：  16
Socket(s):             1
NUMA node(s)：         1
Vendor ID：           GenuineIntel
CPU family：          6
Model：              85
Model name:            Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
Stepping：              4
CPU MHz：             2500.024
BogoMIPS:              5000.04
Hypervisor vendor：  KVM
Virtualization type：     full
L1d cache：          32K
L1i cache：          32K
L2 cache：           1024K
L3 cache：           33792K
NUMA node0 CPU(s):     0-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ibrs ibpb stibp kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap avx512cd xsaveopt xsavec xgetbv1

Best regards, Morven

**Comment by maxlytkin** [comment] 2020-08-06 10:30
Hi @NotMorven 
It might be sufficient for your application and model to utilize this amount of CPU resources to parallelize the execution as much as possible.
Also, please have a chance to try the recommendations in "Throughput Mode for CPU" section from [CPU Checklist](https://docs.openvinotoolkit.org/latest/openvino_docs_optimization_guide_dldt_optimization_guide.html#cpu-checklist) and also Best Latency on the Multi-Socket CPUs / Throughput Mode for CPU / Benchmark App in [Performance Topics](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Intro_to_Performance.html#best_latency_on_the_multi_socket_cpus).

**Comment by NotMorven** [comment] 2020-08-10 09:28
Hi @maxlytkin 
Thanks for your help, I have benefited a lot from you and OpenVINO Toolkit. 
See you next issue: )!

Morven

**Comment by maxlytkin** [comment] 2020-08-10 11:00
@NotMorven 
Glad to help. Thank you for using OpenVINO toolkit.

**Comment by jike-algorithm-zhangxiao** [comment] 2021-01-14 09:33
> Hi @NotMorven
> As per the documentation, OpenVINO toolkit supports all generations of Xeon Scalable processors (Skylake, Cascade Lake, Cooper Lake). However, as I see, Xeon Platinum 8269CY is not a publicly available CPU model, so this supposed to be specific ODM's SKU with, for example, modified instructions. This might be the reason.
> Thanks for sharing this with the community.

Have any solutions for that?
In Alibaba Cloud, most of cpus are Xeon Platinum 8269CY or Xeon Platinum 8269. 
I appreciate you can give some solutions.

**Comment by hussam789** [comment] 2021-01-25 15:18
I'm having the same issue as most of Alibaba Cloud uses Xeon Platinum 8269CY.
@maxlytkin  Please reopen the issue or give us give some solution if you already have.

**Comment by maxlytkin** [comment] 2021-01-26 10:14
@hussam789 @jike-algorithm-zhangxiao 
No solution for the time being. Let me check this further on how we could support it.
Connected case - https://github.com/openvinotoolkit/openvino/issues/4005

**Comment by guoyejun** [comment] 2021-01-31 01:59
i also see 'Floating point exception (core dumped)' on CPU8269CY with mobilenet-v2 int8 model with l_openvino_toolkit_p_2021.2.185.tgz, all my steps follow https://docs.openvinotoolkit.org/latest/pot_configs_examples_README.html. Here is the output to run the native program benchmark_app.
```
~/inference_engine_cpp_samples_build/intel64/Release# ./benchmark_app -m /root/example/results/mobilenet-v2-pytorch_DefaultQuantization/2021-01-30_22-06-20/optimized/mobilenet-v2-pytorch.xml
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
        API version ............ 2.1
        Build .................. 2021.2.0-1877-176bdf51370-releases/2021/2
        Description ....... API
[ INFO ] Device info:
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 2021.2.0-1877-176bdf51370-releases/2021/2

[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance,but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 81.73 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
Floating point exception (core dumped)
```

also attached the model files and core file for your convenience.
[optimized.zip](https://github.com/openvinotoolkit/openvino/files/5899073/optimized.zip)
[core.zip](https://github.com/openvinotoolkit/openvino/files/5899074/core.zip)

**Comment by guoyejun** [comment] 2021-01-31 02:07
to narrow down the issue, i'd like to cut the int8 model. For example, if there's 100 layers in the model, just keep the first layer in the model file and discard all the other 99 layers, or, connect layer20 to layer30 and discard the 10 layers in between (if applicable). 

is there an example or any function/document for such model cut?  thanks.

btw, is there a tool to visualize the int8 openvino model file? (just like tensorboard for tensorflow model).

**Comment by guoyejun** [comment] 2021-01-31 12:27
I found the root cause, cpu detection does not work for CPU8269CY, it makes default value 0 used for cpu cores, and so caused 0/0 error. see detail below.

```
in function Xbyak::util::Cpu::setNumCores

172│                         x2APIC_supported_ = true;
173│                         for (unsigned int i = 0; i < maxTopologyLevels; i++) {
174│                                 getCpuidEx(0xB, i, data);
175│                                 IntelCpuTopologyLevel level = (IntelCpuTopologyLevel)extractBit(data[2], 8, 15);
176├>                                if (level == SmtLevel || level == CoreLevel) {
177│                                         numCores_[level - 1] = extractBit(data[1], 0, 15);
178│                                 }
179│                         }
180│                 } else {
181│                         /*
182│                                 Failed to deremine num of cores without x2APIC support.
183│                                 TODO: USE initial APIC ID to determine ncores.
/root/openvino_work/openvino/inference-engine/thirdparty/mkl-dnn/src/cpu/xbyak/xbyak_util.h

(gdb) p level
$6 = (unknown: 0)

so numCores_[i] is not assigned a value here.
```

```
below is where the 0/0 error happens

249│         unsigned int getNumCores(IntelCpuTopologyLevel level) {
250│                 if (!x2APIC_supported_) throw Error(ERR_X2APIC_IS_NOT_SUPPORTED);
251│                 switch (level) {
252│                 case SmtLevel: return numCores_[level - 1];
253├>                case CoreLevel: return numCores_[level - 1] / numCores_[SmtLevel - 1];
254│                 default: throw Error(ERR_X2APIC_IS_NOT_SUPPORTED);
255│                 }
256│         }
257│
258│         unsigned int getDataCacheLevels() const { return dataCacheLevels_; }
259│         unsigned int getCoresSharingDataCache(unsigned int i) const
260│         {
/root/openvino_work/openvino/inference-engine/thirdparty/mkl-dnn/src/cpu/xbyak/xbyak_util.h
```

```
we can work round it by hard code

~/openvino_work/openvino/inference-engine/thirdparty/mkl-dnn# git diff
diff --git a/src/cpu/xbyak/xbyak_util.h b/src/cpu/xbyak/xbyak_util.h
index 68a1e24ff..dc0266076 100644
--- a/src/cpu/xbyak/xbyak_util.h
+++ b/src/cpu/xbyak/xbyak_util.h
@@ -175,6 +175,9 @@ class Cpu {
                                IntelCpuTopologyLevel level = (IntelCpuTopologyLevel)extractBit(data[2], 8, 15);
                                if (level == SmtLevel || level == CoreLevel) {
                                        numCores_[level - 1] = extractBit(data[1], 0, 15);
+                               } else {
+                                       numCores_[1] = 8;
+                                       numCores_[0] = 1;
                                }
                        }
                } else {
```

hope to get a new release with fix soon, thanks.

**Comment by dmitry-gorokhov** [comment] 2021-02-01 09:56
@guoyejun Big thanks for digging into this! 
[Xbyak](https://github.com/herumi/xbyak) is used by [oneDNN](https://github.com/openvinotoolkit/oneDNN) which is OpenVINO third-party. As far as I can see the issue you observed was fixed already on Xbyak side: https://github.com/herumi/xbyak/commit/5722393d41218fcf32a69127c725f0fb1e030ba5. Since OV just [migrated](https://github.com/openvinotoolkit/openvino/pull/3725) on newer version of oneDNN this fix is already available on master branch (and should be released as part of OV 2021.3). So my I ask you to try latest master and check if the fix works for you?
Thanks!

**Comment by guoyejun** [comment] 2021-02-02 15:04
just tried master branch at 79fa676e351a1e48bea290159229db94df775e7b, there's still issue.

```
~/inference_engine_cpp_samples_build/intel64/Release# ./benchmark_app -m /root/example/results/mobilenet-v2-pytorch_DefaultQuantization/2021-01-30_10-06-20/optimized/mobilenet-v2-pytorch.xml
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading Inference Engine
[ INFO ] InferenceEngine:
        API version ............ 2.1
        Build .................. custom_master_79fa676e351a1e48bea290159229db94df775e7b
        Description ....... API
[ INFO ] Device info:
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... custom_master_79fa676e351a1e48bea290159229db94df775e7b

[Step 3/11] Setting device configuration
[ WARNING ] -nstreams default value is determined automatically for CPU device. Although the automatic selection usually provides a reasonable performance,but it still may be non-optimal for some cases, for more information look at README.
[Step 4/11] Reading network files
[ INFO ] Loading network files
[ INFO ] Read network took 465.58 ms
[Step 5/11] Resizing network to match image sizes and given batch
[ INFO ] Network batch size: 1
[Step 6/11] Configuring input of the model
[Step 7/11] Loading the model to the device
benchmark_app: /root/openvino_work/openvino/inference-engine/thirdparty/mkl-dnn/src/cpu/x64/jit_avx512_core_x8s8s32x_conv_kernel.cpp:805: void dnnl::impl::cpu::x64::_jit_avx512_core_x8s8s32x_fwd_kernel<Vmm>::generate() [with Vmm = Xbyak::Zmm]: Assertion `idx == ker_dw_reg_base_idx' failed.
benchmark_app: /root/openvino_work/openvino/inference-engine/thirdparty/mkl-dnn/src/cpu/x64/jit_avx512_core_x8s8s32x_conv_kernel.cpp:805: void dnnl::impl::cpu::x64::_jit_avx512_core_x8s8s32x_fwd_kernel<Vmm>::generate() [with Vmm = Xbyak::Zmm]: Assertion `idx == ker_dw_reg_base_idx' failed.
Aborted

```

**Comment by dmitry-gorokhov** [comment] 2021-02-02 15:22
@guoyejun This is debug assert which is not valid. We will remove it asap. For now you can try to just comment this assert or build w/o DEBUG enabled.

**Comment by guoyejun** [comment] 2021-02-03 11:10
tried with release build, it works, thanks.

**Comment by maxlytkin** [comment] 2021-02-10 09:40
@guoyejun 
Thanks for letting us know. I'm closing this ticket.

**Closed by maxlytkin** 2021-02-10 09:40 UTC
Labels: bug
