### ISSUE TITLE
2020.1 build failure

### ISSUE THREAD

**Issue by mjhammel** [openvinotoolkit/openvino#447] opened 2020-04-06 16:22 UTC
I'm attempting to build 2020.1 for an embedded system using a custom Linux distro.  This was implemented a year ago on 2018r4, where it built okay, and I'm trying to bring it up to date.  I grabbed the 2020.1 release, then grabbed the respective ade and ngraph commits and manually install them in their respective locations in the 2020.1 tree.  This is because our build doesn't currently support use of git to clone remote repos.

I'm currently getting C++ compilation errors the the MKLDNN plugin.  I'm not a C++ dev so it's not clear ot me what's going on here though it kinda looks like a public function has a different prototype than is being used.  

[mlkdnn.txt](https://github.com/opencv/dldt/files/4439567/mlkdnn.txt)

Here is my cmake config

        cmake -DTHREADS_PTHREAD_ARG=0 \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_SYSTEM_PROCESSOR=x86_64 \
              -DLINUX_OS_NAME="CentOS 7" \
              -DCMAKE_TOOLCHAIN_FILE=$(LOCAL_TOOLS)/bin/$($1_ARCH).cmake \
              -DENABLE_MKL_DNN=ON \
              -DENABLE_CLDNN=OFF \
              -DENABLE_NGRAPH=ON \
              -DENABLE_TESTS=OFF \
              -DENABLE_SAMPLES=OFF \
              -DENABLE_GNA=OFF \
              -DENABLE_PROFILING_ITT=OFF \
              -DENABLE_SAMPLES_CORE=ON \
              -DENABLE_SEGMENTATION_TESTS=OFF \
              -DENABLE_OBJECT_DETECTION_TESTS=OFF \
              -DBUILD_TESTS=OFF \
              -DNGRAPH_UNIT_TEST_ENABLE=OFF \
              -DNGRAPH_TEST_UTIL_ENABLE=OFF \
              CFLAGS="-O" \
              ..

Note that I'm NOT on CentOS 7.  I just chose that because the build host is Fedora, though it's actually running in a Ubuntu docker instance.  I could try ubuntu instead, I guess.  I don't think that's the problem here, though.

Any help would be appreciated.  Thanks.

**Comment by mjhammel** [comment] 2020-04-06 20:56
I've found that switching from _-fvisibility=hidden -fvisibility-inline-hidden_ to _-fvisibility=default_ in the follwoing fixed the build problem.  

- unpacked/dldt-2020.1/cmake/os_flags.cmake
- unpacked/dldt-2020.1/CMakeLists.txt
- unpacked/dldt-2020.1/inference-engine/thirdparty/mkl-dnn/cmake/platform.cmake

However, I'm not sure this is desirable as the GCC documentation says this will generate larger artifacts.  I'll have to research it more.  If anyone can offer some insight on the side effects from this change I'd appreciate it.  Thanks again.

**Comment by alalek** [comment] 2020-04-06 22:34
> to -fvisibility=default

It is a bad idea to expose all symbols as exported.

---

Problem is that "warnings as errors" mode is enabled **by default** through `-Werror` or `/WX` compiler options.
So it is better to remove all `-Werror` stuff instead. See here: #149

duplicate of #225

**Comment by mjhammel** [comment] 2020-04-07 23:56
Disabling -Werror also worked.  The build now completes as expected.
Thanks for the tip.

**Comment by ilya-lavrenov** [comment] 2020-04-18 12:57
In 2020.2 it was fixed and warnings as errors are moved under `TREAT_WARNING_AS_ERROR` cmake option.

**Comment by mjhammel** [comment] 2020-04-22 15:12
I haven't verified for 2020.2 but since I have it working now I'm closing the issue.

**Closed** 2020-04-22 15:12 UTC

**Comment by alalek** [comment] 2021-11-02 12:17
@ilya-lavrenov

> In 2020.2 it was fixed and warnings as errors are moved under TREAT_WARNING_AS_ERROR cmake option.

It is broken again in 2021.4.1 at least (by #5270): https://github.com/openvinotoolkit/openvino/blame/2021.4.1/ngraph/CMakeLists.txt#L200

/cc @ilyachur

**Comment by ilya-lavrenov** [comment] 2021-11-02 12:45
@alalek fixed in master https://github.com/openvinotoolkit/openvino/blob/master/ngraph/CMakeLists.txt (this file does not contain options anymore). Do we need to port this to 2021.4.x?
