### ISSUE TITLE
[Feature Request]: pot quantization anomaly in super-resolution network models

### ISSUE THREAD

**Issue by itjianggit** [openvinotoolkit/openvino#21869] opened 2023-12-26 09:15 UTC
### Request Description

Reference link: https://blog.csdn.net/gc5r8w07u/article/details/116131440

There are currently no examples of post training quantization for super-resolution networks (NNCF). Refer to the above website link, and encountering the problem of quantization super-resolution networks consuming a large amount of memory and causing out of bounds using pot tools. 

Attempt to reproduce the issue based on the link address above. Due to the older openvino version used for quantization in the super-resolution network model, to verify the download pip install openvino-dev==2021.4.2.

Using the provided scripts and commands, provide a dataset with the same steps as the webpage.

![accuracy-check](https://github.com/openvinotoolkit/openvino/assets/69840007/d8dd6b3b-9f40-4489-9029-1b34ed893790)

![pot](https://github.com/openvinotoolkit/openvino/assets/69840007/70ef13fc-02cb-4cc9-9d20-96942831fa22)
[pot_waifu2x.zip](https://github.com/openvinotoolkit/openvino/files/13770237/pot_waifu2x.zip)

code address
https://gitee.com/tisandman/pot_waifu2x_ov2021

### Feature Use Case

Question: Can there be a way to reduce memory usage for pot quantization in super-resolution networks, as it can increase the universality of quantization in the dataset, or is there any other quantization method for super-resolution models that have limited resources related to OpenVino super-resolution inference. Or can you provide a reference for quantifying relevant super-resolution network models regarding NNCF.

### Issue submission checklist

- [X] The feature request or improvement must be related to OpenVINO

**Comment by itjianggit** [comment] 2023-12-26 09:18
Using other network models may result in crossing boundaries.
[pot_bsrn.zip](https://github.com/openvinotoolkit/openvino/files/13770305/pot_bsrn.zip)

**Comment by rkazants** [comment] 2023-12-26 12:06
@AlexKoff88, @MaximProshin, please take a look.

**Comment by AlexKoff88** [comment] 2023-12-26 12:19
@itjianggit, please try to set
"stat_requests_number" and "eval_requests_number" to 1 in the config, as it is shown [here](https://github.com/AlexKoff88/openvino/blob/ac9a80e6c9adcabc1ba631ca952021f99ce77315/tools/pot/configs/default_quantization_spec.json#L22)

**Comment by itjianggit** [comment] 2023-12-26 12:31
@AlexKoff88 
Okay, I tried it, the memory has been reduced to some extent and now the memory required for 20 images is about 50GB. There is one more issue, as the number of dataset images increases, the memory will also increase. Did the pot tool not release operations during the quantization process?

Thank you for your reply.

**Comment by AlexKoff88** [comment] 2023-12-26 13:09
It collects statistics to estimate activation quantization parameters. But there can be some issues in 3rd party code that deals with dataset. You can try NNCF API on you own. It is relatively simple and we have multiple examples for CV models [here](https://github.com/openvinotoolkit/openvino_notebooks), including quantization of the recent Efficient SAM. There you can implement a fine-grained control over RAM.

**Comment by itjianggit** [comment] 2023-12-28 06:49
Thank you for your suggestion. I have seen that the YOLOV8 model has quantization after training. Regarding the difficulty of super-resolution networks in dataset processing, it may be necessary to pay attention to the use of the NNCF API.

**Comment by itjianggit** [comment] 2024-01-03 02:50
@AlexKoff88 Sorry to bother you again, but I have another question to ask. Can OpenVino's xml and bin file support multiple resolutions, such as three different resolution images, and support separate input processing without the need to re read the model for preprocessing.

**Comment by AlexKoff88** [comment] 2024-01-03 07:00
> @AlexKoff88 Sorry to bother you again, but I have another question to ask. Can OpenVino's xml and bin file support multiple resolutions, such as three different resolution images, and support separate input processing without the need to re read the model for preprocessing.

@itjianggit, yes, it can. It is a matter of how you organize the code in the framework to handle that and export the model to OpenVINO IR, then. If you just need 3 different resolutions, you can reshape the model using OpenVINO API or use dynamic shapes when exporting the model. If you really need to have different image preprocessing methods you can introduce a control flow inside the model that will select the proper one based on the shapes of the input data.

**Comment by itjianggit** [comment] 2024-01-03 07:57
@AlexKoff88 Thank you very much for your reply. I will use the preprocessing API to adjust the model size..

**Comment by itjianggit** [comment] 2024-01-04 04:15
@AlexKoff88 Sorry, I found that after preprocessing images with different heights and widths, the model needs to be reloaded onto the device each time, which takes a long time, even longer than inference time.Is there a way to solve the problem of duplicate loading, which has a significant impact on performance？
![image](https://github.com/openvinotoolkit/openvino/assets/69840007/e4eb7677-1e93-407d-b9b8-034b509891b4)

**Comment by AlexKoff88** [comment] 2024-01-04 05:38
You can do the following to avoid this `model.reshape([1, 3, -1, -1])`. After that the model will be able to work with any valid shape and will cache the optimal execution kernels for the shapes that it has already seen.

**Comment by AlexKoff88** [comment] 2024-01-04 05:38
Please take a look here as well for more details: https://docs.openvino.ai/2023.2/openvino_docs_OV_UG_DynamicShapes.html

**Comment by itjianggit** [comment] 2024-01-04 06:05
This can reduce the number of times and consumption of loading the model, but it will increase the consumption of inference performance. If the model is only loaded and compiled once, the consumption will be even greater.
![image](https://github.com/openvinotoolkit/openvino/assets/69840007/1bf34f04-2501-4186-be73-3d0740845af0)

**Comment by itjianggit** [comment] 2024-01-11 09:08
@AlexKoff88 Hello, the ARM platform has a model conversion tool that allows bin files to support multiple resolutions, with a maximum of 64 resolutions per bin file. This eliminates the need for repeated model reading operations. Does the x86 MO model conversion tool also have a similar extension? At the same time, I found that preprocessing and setting dynamic dimensions on a model, and then modifying the resolution, cannot operate on the same model. Is there any way to solve this?

![image](https://github.com/openvinotoolkit/openvino/assets/69840007/718ad31e-82de-4262-85f7-fde721e996f4)

![pic](https://github.com/openvinotoolkit/openvino/assets/69840007/49000e13-c5ee-42ba-b8fd-6bb692d50d40)

**Comment by itjianggit** [comment] 2024-01-11 09:09
@AlexKoff88 Hello, the ARM platform has a model conversion tool that allows bin files to support multiple resolutions, with a maximum of 64 resolutions per bin file. This eliminates the need for repeated model reading operations. Does the x86 MO model conversion tool also have a similar extension? At the same time, I found that preprocessing and setting dynamic dimensions on a model, and then modifying the resolution, cannot operate on the same model. Is there any way to solve this?

![pic](https://github.com/openvinotoolkit/openvino/assets/69840007/6fa32d9e-85bd-4fae-95b7-d8804f6c3575)

![image](https://github.com/openvinotoolkit/openvino/assets/69840007/0bb26b20-9252-43b9-a851-ce1bf58231fe)

**Comment by ilya-lavrenov** [comment] 2024-01-11 10:07
> Does the x86 MO model conversion tool also have a similar extension?

MO (deprecated, please use OVC) is architecture independent tool, which operates in a unified manner on all OSes and platforms. 

> At the same time, I found that preprocessing and setting dynamic dimensions on a model, and then modifying the resolution, cannot operate on the same model. Is there any way to solve this?

Could you please provide more complete code snippets which does this thing?

**Comment by itjianggit** [comment] 2024-01-12 02:05
@ilya-lavrenov Thank you for your reply. I will provide the pictures and code as a package.

[demo.zip](https://github.com/openvinotoolkit/openvino/files/13910693/demo.zip)

**Comment by AlexKoff88** [comment] 2024-01-16 05:42
@itjianggit, can you please provide a link to the model we should use to reproduce the issue?

**Comment by AlexKoff88** [comment] 2024-01-16 05:45
> @itjianggit, can you please provide a link to the model we should use to reproduce the issue?

I was able to find it in the issue description. 

Can you confirm the the issue is visible with the latest version of OpenVINO, i.e. 2023.2?

**Comment by itjianggit** [comment] 2024-01-16 06:02
@AlexKoff88 

Yes. I have included the relevant problem description and code in the compressed file.

I will also provide you with the model.

[model.zip](https://github.com/openvinotoolkit/openvino/files/13945954/model.zip)

**Comment by AlexKoff88** [comment] 2024-01-16 06:10
@vladimir-paramuzov, @p-durandin, can anyone from the GPU team take a look at this issue?

**Comment by itjianggit** [comment] 2024-01-16 06:13
> @vladimir-paramuzov, @p-durandin, can anyone from the GPU team take a look at this issue?

Do I need to resubmit a question?

**Comment by AlexKoff88** [comment] 2024-01-19 09:10
@isanghao, maybe someone from your team can help here as well?

**Comment by AlexKoff88** [comment] 2024-01-19 09:14
@itjianggit, can you please file a different issue with a clear description of the dynamic shapes issue on GPU and we will find the right person to help you?

**Comment by itjianggit** [comment] 2024-01-19 09:22
@AlexKoff88 Here is the link address for the new issue.

https://github.com/openvinotoolkit/openvino/issues/22250

**Comment by AlexKoff88** [comment] 2024-01-19 09:29
Thanks, I think we can close this one, then.

**Comment by itjianggit** [comment] 2024-01-19 09:33
Yes, thank you for your help!

**Closed** 2024-02-13 02:26 UTC
Labels: enhancement, feature
