### ISSUE TITLE
[Bug] memory leak on LoadNetwork

### ISSUE THREAD

**Issue by kunkun007** [openvinotoolkit/openvino#9926] opened 2022-01-26 09:49 UTC
##### System information (version)

- OpenVINO => 2021.4.2
- Operating System / Platform =>centos7.8
- Compiler => vs code 
- Framework: openvino 
- Model name: person-detection-0202

##### Detailed description
I installed openvino by l_openvino_toolkit_p_2021.4.752.tgz, try to load model person-detection-0202 provided by openvino,
load model success, but valgrind report like this:

==98627== 24,720 (19,960 direct, 4,760 indirect) bytes in 5 blocks are definitely lost in loss record 57 of 57
==98627==    at 0x4C2A4C3: operator new(unsigned long) (vg_replace_malloc.c:344)
==98627==    by 0xA05AF03: ???
==98627==    by 0x95B31DC: ???
==98627==    by 0x91E099E: ???
==98627==    by 0x904793C: ???
==98627==    by 0x9047D17: ???
==98627==    by 0x9020EF8: ???
==98627==    by 0x6466AC1: tbb::interface7::internal::task_arena_base::internal_execute(tbb::interface7::internal::delegate_base&) const (in /home/code/test_person_detection/lib/libtbb.so.2)
==98627==    by 0x4F60253: InferenceEngine::CPUStreamsExecutor::Execute(std::function<void ()>) (in /home/code/test_person_detection/lib/libinference_engine.so)
==98627==    by 0x90219BD: ???
==98627==    by 0x9021BE1: ???
==98627==    by 0x4F66A3D: std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) (in /home/code/test_person_detection/lib/libinference_engine.so)
==98627== 
==98627== LEAK SUMMARY:
==98627==    definitely lost: 33,680 bytes in 18 blocks
==98627==    indirectly lost: 47,536 bytes in 176 blocks
==98627==      possibly lost: 21,280 bytes in 35 blocks
==98627==    still reachable: 26,732 bytes in 24 blocks
==98627==                       of which reachable via heuristic:
==98627==                         newarray           : 24,600 bytes in 3 blocks
==98627==         suppressed: 0 bytes in 0 blocks
==98627== 
==98627== Use --track-origins=yes to see where uninitialised values come from
==98627== For lists of detected and suppressed errors, rerun with: -s
==98627== ERROR SUMMARY: 203 errors from 27 contexts (suppressed: 0 from 0)

##### Steps to reproduce
Load model:
InferenceEngine::Core engine;
InferenceEngine::CNNNetwork network = engine.ReadNetwork(modelName);
InferenceEngine::ExecutableNetwork executable_network = engine.LoadNetwork(network, "CPU", {});
Use valgrind to run the program:
valgrind --log-file=valgrind.log --tool=memcheck --leak-check=full --show-leak-kinds=all ./your_app

I cannot figure this out, any suggestions?

**Comment by jgespino** [comment] 2022-01-26 22:09
Hi @kunkun007 

Thank you for reporting, I was able to reproduce using OpenVINO 2021.4.2 release on Ubuntu 18.04. I will open an Internal ticket with the development team to investigate. 

```
valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all ./memory_leak CPU person-detection-0202.xml
==1756== LEAK SUMMARY:
==1756==    definitely lost: 29,992 bytes in 18 blocks
==1756==    indirectly lost: 41,624 bytes in 64 blocks
==1756==      possibly lost: 912 bytes in 3 blocks
==1756==    still reachable: 2,122 bytes in 8 blocks
==1756==         suppressed: 0 bytes in 0 blocks
```

Regards,
Jesus

**Comment by jgespino** [comment] 2022-02-01 23:51
Hi @kunkun007 

Quick update: there are a couple of PRs for this GitHub Issue.
https://github.com/openvinotoolkit/openvino/pull/9578
https://github.com/openvinotoolkit/openvino/pull/10052

There are also many leaks in dlopen, it seems to be a known bug in valgrind and these should be ignored.

Regards,
Jesus

**Comment by kunkun007** [comment] 2022-02-08 02:00
Thank you for your reply, should I test openvino on master brach or the next latest release or  something?

**Comment by jgespino** [comment] 2022-02-14 19:42
Hi @kunkun007 

The two PRs mentioned before have merged, there are a couple more that just merged.
https://github.com/openvinotoolkit/openvino/pull/10199
https://github.com/openvinotoolkit/openvino/pull/10202

I am waiting for confirmation from the dev team to test on the latest master branch. I will let you know.

Regards,
Jesus

**Comment by jgespino** [comment] 2022-02-17 00:48
Hi @kunkun007 

I tested on the latest branch (https://github.com/openvinotoolkit/openvino/commit/1fc61299c85331d6c561ab54535b4765145fac00)  which contains all the PRs mentioned above and the memory leak has been fixed. Please try it from your side and let me know if you have any issues.

```
$ valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all ./memory_leak CPU person-detection-0202.xml
LEAK SUMMARY:
==16891==    definitely lost: 0 bytes in 0 blocks
==16891==    indirectly lost: 0 bytes in 0 blocks
==16891==      possibly lost: 144 bytes in 1 blocks
==16891==    still reachable: 30,596 bytes in 191 blocks
==16891==                       of which reachable via heuristic:
==16891==                         stdstring          : 79 bytes in 1 blocks
==16891==         suppressed: 0 bytes in 0 blocks
```

Regards,
Jesus

**Comment by jgespino** [comment] 2022-03-01 18:25
Closing, please re-open if additional assistance is needed.

**Closed by jgespino** 2022-03-01 18:25 UTC
Labels: bug, category: IE common, support_request, PSE
