### ISSUE TITLE
error：NonZero layer with name 'NonZero_0' has incorrect number of output edges: 2

### ISSUE THREAD

**Issue by gyr-kdgc** [openvinotoolkit/openvino#11970] opened 2022-06-27 04:07 UTC
I convert paddle's yolov3 model to IR model using command like below：
paddle2onnx --model_dir "./model/inference_model/yolov3_darknet_voc/" \
            --model_filename "__model__" \
            --params_filename "__params__" \
            --save_file paddle_model.onnx \
            --opset_version 11

python -m paddle2onnx.optimize --input_model paddle_model.onnx \
                               --output_model new_paddle_model.onnx \
                               --input_shape_dict "{'x':[1,3,608,608]}"

mo --input_model new_paddle_model.onnx --input_shape [1,3,608,608],[1,2] --input image,im_size --output_dir paddle_model 

But I encountered the following error when inferring:
ie = Core()
model = ie.read_model(model="./paddle_model/new_paddle_model.xml", weights="./paddle_model/new_paddle_model.bin")
compiled_model = ie.compile_model(model=model, device_name="CPU")

ERROR AS FOLLOW：
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_2116/2230287381.py in <module>
     10 ie = Core()
     11 model = ie.read_model(model="./paddle_model/new_paddle_model.xml", weights="./paddle_model/new_paddle_model.bin")
---> 12 compiled_model = ie.compile_model(model=model, device_name="CPU")
     13 
     14 input_layer = next(iter(compiled_model.inputs))

/home/usr/local/miniconda3/lib/python3.7/site-packages/openvino/runtime/ie_api.py in compile_model(self, model, device_name, config)
    264 
    265         return CompiledModel(
--> 266             super().compile_model(model, device_name, {} if config is None else config)
    267         )
    268 

RuntimeError: NonZero layer with name 'NonZero_0' has incorrect number of output edges: 2

How can I solve this problem?

**Comment by mateusztabaka** [comment] 2022-06-27 08:46
Can you try on latest master? Possibly fixed by https://github.com/openvinotoolkit/openvino/commit/4be0c595059e0eab6166b174f3c9514cbb945d83

**Comment by gyr-kdgc** [comment] 2022-06-28 11:52
> Can you try on latest master? Possibly fixed by [4be0c59](https://github.com/openvinotoolkit/openvino/commit/4be0c595059e0eab6166b174f3c9514cbb945d83)

This method really works，I can convert my paddle model and make inferences now，thank u very much！

**Comment by gyr-kdgc** [comment] 2022-06-30 06:16
**Another problem，**According to the last method, I installed openvino2022.2 on the basis of the original openvino2022.1 environment. Both tensorflow1.x and paddle models can be converted, but after I re-install the latest openvino2022.2 on a brand new image,  the following error occurs when I convert tensorflow1.x model ：
**command：**
!python /home/packages/openvino/tools/mo/openvino/tools/mo/mo.py --framework tf --input_model /home/alg/model/frozen_model.pb  -b 1 --output_dir frozen_model
**logs：**
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/alg/model/frozen_model.pb
	- Path for generated IR: 	/home/alg/frozen_model
	- IR output name: 	frozen_model
	- Log level: 	ERROR
	- Batch: 	1
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Source layout: 	Not specified
	- Target layout: 	Not specified
	- Layout: 	Not specified
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- User transformations: 	Not specified
	- Reverse input channels: 	False
	- Enable IR generation for fixed input shape: 	False
	- Use the transformations config file: 	None
Advanced parameters:
	- Force the usage of legacy Frontend of Model Optimizer for model conversion into IR: 	False
	- Force the usage of new Frontend of Model Optimizer for model conversion into IR: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Use the config file: 	None
fatal: not a git repository (or any of the parent directories): .git
OpenVINO runtime found in: 	/home/packages/openvino/scripts/setupvars/python/python3.7/openvino
OpenVINO runtime version: 	custom_master_72505b1d82f8782cacfa4740e17fb86629f80733
Model Optimizer version: 	unknown version
[ WARNING ] Model Optimizer and OpenVINO runtime versions do not match.
[ WARNING ] Consider building the OpenVINO Python API from sources or reinstall OpenVINO (TM) toolkit using "pip install openvino" (may be incompatible with the current Model Optimizer version)
fatal: not a git repository (or any of the parent directories): .git
[ WARNING ]  	
Support of the Model Optimizer tool in TensorFlow 1.x environment is deprecated.It is highly recommended to use TensorFlow 2.x.

[ FRAMEWORK ERROR ]  Cannot load input model: TensorFlow cannot read the model file: "/home/alg/model/frozen_model.pb" is incorrect TensorFlow model file. 
The file should contain one of the following TensorFlow graphs:
1. frozen graph in text or binary format
2. inference graph for freezing with checkpoint (--input_checkpoint) in text or binary format
3. meta graph

Make sure that --input_model_is_text is provided for a model in text format. By default, a model is interpreted in binary format. Framework error details: Error parsing message with type 'tensorflow.GraphDef'. 
 For more information please refer to Model Optimizer FAQ, question #43. (https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=43#question-43)

**I found that the version of openvino runtime in two environments are different:**
**openvino can not be used:**
OpenVINO runtime version: 	custom_master_72505b1d82f8782cacfa4740e17fb86629f80733
**openvino can be used:**
OpenVINO runtime version: 	custom_master_a4e6cda7e87a74352a4fc96dde2e547e42b8cae1
I want to know what is the difference between this two version of openvino runtime?

**Comment by gyr-kdgc** [comment] 2022-07-01 05:39
> Can you try on latest master? Possibly fixed by [4be0c59](https://github.com/openvinotoolkit/openvino/commit/4be0c595059e0eab6166b174f3c9514cbb945d83)
How can I solve the problem above?Thank u

**Comment by mateusztabaka** [comment] 2022-07-01 06:04
There is not much of a difference between those two versions. I'm guessing the issue is with your model. Can you share it?

**Comment by gyr-kdgc** [comment] 2022-07-02 06:52
> There is not much of a difference between those two versions. I'm guessing the issue is with your model. Can you share it?

I don't know how to share my model with you，it is too large. It is just a .pb model file of tensorflow_1.15.  In the environment where this model can be converted, the 2021.4 version of openvino has also been installed.So I am confused about this.
Here is the code to save the .pb model:

def freeze_graph(model_folder):
    input_checkpoint = model_folder
    output_graph = MODEL_NAME  #  MODEL_NAME  is "xxx.pb"

    output_node_names = "predictions"
    saver = tf.train.Saver()

    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()

    with tf.Session() as sess:
        sess.run(tf.initialize_all_variables())
        saver.restore(sess, input_checkpoint)
        output_graph_def = graph_util.convert_variables_to_constants(
            sess,
            input_graph_def,
            output_node_names.split(",")
        )
        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))

        for op in graph.get_operations():
            #print(op.name, op.values())
            print("name:",op.name)
        print ("success!")

**Comment by mateusztabaka** [comment] 2022-07-05 09:12
> Here is the code to save the .pb model:

Can you also share full model definition in tensorflow? So I can save the model using your method.

**Comment by slyalin** [comment] 2022-07-15 09:00
> > Can you try on latest master? Possibly fixed by [4be0c59](https://github.com/openvinotoolkit/openvino/commit/4be0c595059e0eab6166b174f3c9514cbb945d83)
> 
> This method really works，I can convert my paddle model and make inferences now，thank u very much！

The originally reported issue has been completely solved at that point, right?

Have you achieved successful conversion by using paddle to ONNX conversion step first and only the feeding the resulting ONNX model to OpenVINO as you described in your original message? Or have you made it by feeding the original paddle model directly to OpenVINO? Just FYI, we are supporting direct paddle import without need to go through ONNX first. Not sure that it works for your model, the level of support is different. But you could try and look if it works in the same way you would save one step in your model preparation pipeline.

**Comment by rkazants** [comment] 2022-07-15 10:49
Hello @gyr-kdgc! 

We didn't change the logic of reading .pb format in the latest release. However, we changed `requirements.txt` file so your original TF1 environment is not re-written to TF2 anymore (unlike in the previous OpenVINO release). My hypothesis is that you have a deal with TF2 model in .pb format and your environment is TF1 that is why the conversion is broken. Please try to run `pip install -r requirements_tf2.txt` to set-up TF2 environment and re-run model conversion.

**Comment by jgespino** [comment] 2022-07-25 20:56
Closing, please re-open if additional assistance is needed.

**Closed by jgespino** 2022-07-25 20:56 UTC
Labels: category: MO, support_request
