### ISSUE TITLE
[Bug] compile_model() Runtime crash in opencl

### ISSUE THREAD

**Issue by zabomate** [openvinotoolkit/openvino#14468] opened 2022-12-07 11:43 UTC
##### System information (version)
- OpenVINO => openvino_2022.1.0.643
- Operating System / Platform => Ubuntu 20.04 64 Bit
- Compiler => pre compiled apt package Ubuntu 20.04
- Problem classification: Runtime Crash
- Framework: TensorFlow (if applicable)

##### Detailed description
We would like to switch to the new OpenVINO™ API 2.0 from our old implementation. We have an issue with the compile_model() for GPU target. It seems like a timing issue since its not breaking every time when we would like to load the model but every 40% of the time it crashes.

##### Steps to reproduce

```
ov::Core core;
std::shared_ptr<ov::Model> model;
std::string target = "GPU";
... (read model) ...
ov::set_batch(model, ov::Dimension(1, 16));
compiledModel = core.compile_model(model, target); <-- Crash
```
Based on the attached image it seems like an libopencl-clang.so.11.

Operating system: Linux
                  5.15.0 -52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64
CPU: amd64
     family 6 model 151 stepping 2
     20 CPUs

Crash reason:  SIGSEGV / SEGV_MAPERR
Crash address: 0x48
Process uptime: 35 seconds

```
Thread 176 (crashed)
 0  libopencl-clang.so.11!llvm::BasicBlock::dropAllReferences() + 0x0
     rax = 0x00007fd07c5f9720    rdx = 0x00007fd07d6bf440
     rcx = 0x00007fd3a39f2bf6    rbx = 0x0000000000000030
     rsi = 0x0000000000000081    rdi = 0x0000000000000018
     rbp = 0x00007fd07c5f9560    rsp = 0x00007fd05fffc788
      r8 = 0x00007fd07c8479d8     r9 = 0x0000000000001fff
     r10 = 0x0000000000000000    r11 = 0x0000000000000246
     r12 = 0x00007fd07c5f95a8    r13 = 0x00007fd07c9be890
     r14 = 0x00007fd07c5f9560    r15 = 0x00007fd05fffc830
     rip = 0x00007fd2dded6770
    Found by: given as instruction pointer in context
 1  libopencl-clang.so.11!llvm::Function::dropAllReferences() + 0x2d
     rbx = 0x0000000000000030    rbp = 0x00007fd07c5f9560
     rsp = 0x00007fd05fffc790    r12 = 0x00007fd07c5f95a8
     r13 = 0x00007fd07c9be890    r14 = 0x00007fd07c5f9560
     r15 = 0x00007fd05fffc830    rip = 0x00007fd2ddf4667e
    Found by: call frame info
 2  libopencl-clang.so.11!llvm::Function::~Function() + 0xf
     rbx = 0x00007fd07c5f9560    rbp = 0x00007fd07c745150
     rsp = 0x00007fd05fffc7b0    r12 = 0x00007fd07c8479b0
     r13 = 0x00007fd07c9be890    r14 = 0x00007fd07c5f9560
     r15 = 0x00007fd05fffc830    rip = 0x00007fd2ddf4ded0
    Found by: call frame info
 3  libopencl-clang.so.11!llvm::Function::eraseFromParent() + 0x46
     rbx = 0x00007fd07c5f9560    rbp = 0x00007fd07c745150
     rsp = 0x00007fd05fffc7e0    r12 = 0x00007fd07c8479b0
     r13 = 0x00007fd07c9be890    r14 = 0x00007fd07d9f3e50
     r15 = 0x00007fd05fffc830    rip = 0x00007fd2ddf4dfd7
    Found by: call frame info
 4  libopencl-clang.so.11!SPIRV::OCLToSPIRVBase::runOCLToSPIRV(llvm::Module&) + 0x206
     rbx = 0x00007fd07c8479d8    rbp = 0x00007fd07c745150
     rsp = 0x00007fd05fffc800    r12 = 0x00007fd07c8479b0
     r13 = 0x00007fd07c9be890    r14 = 0x00007fd07d9f3e50
     r15 = 0x00007fd05fffc830    rip = 0x00007fd2dbf14547
    Found by: call frame info
 5  libopencl-clang.so.11!llvm::legacy::PassManagerImpl::run(llvm::Module&) + 0x406
     rbx = 0x00007fd05fffc8d0    rbp = 0x00007fd05fffc950
     rsp = 0x00007fd05fffc8a0    r12 = 0x00007fd07cb06f00
     r13 = 0x00007fd07c8937f0    r14 = 0x00007fd07c847a08
     r15 = 0x00007fd07c893810    rip = 0x00007fd2ddf99737
    Found by: call frame info
 6  libopencl-clang.so.11!llvm::writeSpirv(llvm::Module*, SPIRV::TranslatorOpts const&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) + 0xd1
     rbx = 0x00007fd07d698d30    rbp = 0x0000000000000001
     rsp = 0x00007fd05fffc960    r12 = 0x00007fd05fffc970
     r13 = 0x00007fd07cb06f00    r14 = 0x00007fd05fffcbe0
     r15 = 0x00007fd05fffcbc0    rip = 0x00007fd2dbe5b682
    Found by: call frame info
 7  libopencl-clang.so.11!Compile + 0x24b2
     rbx = 0x00007fd05fffccd8    rbp = 0x00007fd05fffcf90
     rsp = 0x00007fd05fffc9d0    r12 = 0x00007fd07cb06f00
     r13 = 0x00007fd05fffcb60    r14 = 0x00007fd05fffcbb0
     r15 = 0x00007fd07cddc7e0    rip = 0x00007fd2dbdf76c3
    Found by: call frame info
 8  libigdfcl.so.1 + 0x46fad
     rbx = 0x00007fd05fffd380    rbp = 0x00007fd05fffd290
     rsp = 0x00007fd05fffcfa0    r12 = 0x00007fd05fffd070
     r13 = 0x00007fd05fffd0b0    r14 = 0x00007fd05fffd010
     r15 = 0x00007fd05fffd0d0    rip = 0x00007fd394405fae
    Found by: call frame info
 9  libigdfcl.so.1 + 0x48805
     rbp = 0x00007fd05fffd5f0    rsp = 0x00007fd05fffd2a0
     rip = 0x00007fd394407806
    Found by: previous frame's frame pointer
10  libigdfcl.so.1 + 0x56dcf
     rbp = 0x00007fd05fffd760    rsp = 0x00007fd05fffd600
     rip = 0x00007fd394415dd0
    Found by: previous frame's frame pointer
11  libigdrcl.so + 0x5cd8c0
     rbp = 0x00007fd05fffd8c0    rsp = 0x00007fd05fffd770
     rip = 0x00007fd2e3ae88c1
    Found by: previous frame's frame pointer
12  libigdrcl.so + 0x10ca67
     rbp = 0x00007fd05fffda30    rsp = 0x00007fd05fffd8d0
     rip = 0x00007fd2e3627a68
    Found by: previous frame's frame pointer
```
<img width="671" alt="image (6)" src="https://user-images.githubusercontent.com/37272041/206148179-78014d2c-ea7b-4354-a2a6-6611f9138c1d.png">

**Comment by vladimir-paramuzov** [comment] 2022-12-08 12:38
@zabomate First of all, I'd suggest trying another OCL runtime versions as crash happens somewhere in the driver libs.
If OCL runtime version switch doesn't help, please provide some info on your device (clinfo output) and OCL runtime version(s) that you've tried in addition to things mentioned by @Iffa-Meah

**Comment by zabomate** [comment] 2022-12-09 13:43
@Iffa-Meah 
1. Unfortunately it is not possible since its not a public model.
2. Yes only the 5 line of code
3. Actually when the application crashed it crashed fully so I cannot use it any further the expected result is to not crash in the compile_model(). When its not crashed during the compile it works as expected.

@vladimir-paramuzov 
I have tried the newest version [22.43.24558](https://github.com/intel/compute-runtime/releases/tag/22.43.24558) and I have tried the [21.48.21782](https://github.com/intel/compute-runtime/releases/tag/21.48.21782) version which was recommended somewhere on the openvino website. I had an older version(19.41.14441) with older processor and I didn't experienced this issue. Unfortunately this version is a pretty old version and it isn't support the CPU versions what I would like to use i7-12700K, i7-12700H or other 12th generation CPUs.
Here are the outputs of the clinfo:

```
Number of platforms                               1
  Platform Name                                   Intel(R) OpenCL HD Graphics
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 3.0 
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_intel_command_queue_families cl_intel_subgroups cl_intel_required_subgroup_size cl_intel_subgroups_short cl_khr_spir cl_intel_accelerator cl_intel_driver_diagnostics cl_khr_priority_hints cl_khr_throttle_hints cl_khr_create_command_queue cl_intel_subgroups_char cl_intel_subgroups_long cl_khr_il_program cl_intel_mem_force_host_memory cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_subgroup_non_uniform_arithmetic cl_khr_subgroup_shuffle cl_khr_subgroup_shuffle_relative cl_khr_subgroup_clustered_reduce cl_intel_device_attribute_query cl_khr_suggested_local_work_size cl_intel_spirv_media_block_io cl_intel_spirv_subgroups cl_khr_spirv_no_integer_wrap_decoration cl_intel_unified_shared_memory_preview cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_intel_planar_yuv cl_intel_packed_yuv cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_3d_image_writes cl_intel_media_block_io cl_intel_va_api_media_sharing cl_intel_sharing_format_query cl_khr_pci_bus_info cl_intel_subgroup_local_block_io 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             INTEL

  Platform Name                                   Intel(R) OpenCL HD Graphics
Number of devices                                 1
  Device Name                                     Intel(R) Graphics [0x46a6]
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 3.0 NEO 
  Driver Version                                  21.48.21782
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               96
  Max clock frequency                             1400MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             512x512x512
  Max work group size                             512
  Preferred work group size multiple              64
  Max sub-groups per work group                   64
  Sub-group sizes (Intel)                         8, 16, 32
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 1 / 1       
    half                                                 8 / 8        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (n/a)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    64, Little-Endian
  Global memory size                              26699628544 (24.87GiB)
  Error Correction support                        No
  Max memory allocation                           4294959104 (4GiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   No
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics                 
    SVM                                           64 bytes
    Global                                        64 bytes
    Local                                         64 bytes
  Max size for global variable                    65536 (64KiB)
  Preferred total size of global vars             4294959104 (4GiB)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        0
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            268434944 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   4 bytes
    Pitch alignment for 2D image buffers          4 pixels
    Max 2D image size                             16384x16384 pixels
    Max planar YUV image size                     16384x16352 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                128
    Max number of read/write image args           128
  Max number of pipe args                         0
  Max active pipe reservations                    0
  Max pipe packet size                            0
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Max number of constant args                     8
  Max constant buffer size                        4294959104 (4GiB)
  Max size of kernel argument                     2048 (2KiB)
  Queue properties (on host)                      
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Queue properties (on device)                    
    Out-of-order execution                        No
    Profiling                                     No
    Preferred size                                0
    Max size                                      0
  Max queues on device                            0
  Max events on device                            0
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      52ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Sub-group independent forward progress        No
    IL version                                    SPIR-V_1.2 
    SPIR versions                                 1.2 
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_intel_command_queue_families cl_intel_subgroups cl_intel_required_subgroup_size cl_intel_subgroups_short cl_khr_spir cl_intel_accelerator cl_intel_driver_diagnostics cl_khr_priority_hints cl_khr_throttle_hints cl_khr_create_command_queue cl_intel_subgroups_char cl_intel_subgroups_long cl_khr_il_program cl_intel_mem_force_host_memory cl_khr_subgroup_extended_types cl_khr_subgroup_non_uniform_vote cl_khr_subgroup_ballot cl_khr_subgroup_non_uniform_arithmetic cl_khr_subgroup_shuffle cl_khr_subgroup_shuffle_relative cl_khr_subgroup_clustered_reduce cl_intel_device_attribute_query cl_khr_suggested_local_work_size cl_intel_spirv_media_block_io cl_intel_spirv_subgroups cl_khr_spirv_no_integer_wrap_decoration cl_intel_unified_shared_memory_preview cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_intel_planar_yuv cl_intel_packed_yuv cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_3d_image_writes cl_intel_media_block_io cl_intel_va_api_media_sharing cl_intel_sharing_format_query cl_khr_pci_bus_info cl_intel_subgroup_local_block_io 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [INTEL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Intel(R) OpenCL HD Graphics
    Device Name                                   Intel(R) Graphics [0x46a6]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Intel(R) OpenCL HD Graphics
    Device Name                                   Intel(R) Graphics [0x46a6]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Intel(R) OpenCL HD Graphics
    Device Name                                   Intel(R) Graphics [0x46a6]
	NOTE:	your OpenCL library only supports OpenCL 2.2,
		but some installed platforms support OpenCL 3.0.
		Programs using 3.0 features may crash
		or behave unexpectedly
```

**Comment by Iffa-Meah** [comment] 2022-12-12 06:32
@zabomate have you tried to infer your model with the [OpenVINO Benchmark App](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html) ?

This would ensure whether your model is fully supported by OpenVINO or not.

**Comment by vladimir-paramuzov** [comment] 2022-12-12 06:36
@zabomate can't reproduce the crash for now. 

Let me ask few more questions:
- Does the crash reproduce with other models in your env? 
- Do you observe crash on your model if you don't set dynamic batch?
- Do you observe crash on your model if you set lower value for batch upper bound? like `ov::set_batch(model, ov::Dimension(1, 8));`

**Comment by Iffa-Meah** [comment] 2022-12-16 03:49
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by zabomate** [comment] 2023-03-10 15:54
@vladimir-paramuzov @Iffa-Meah 
[VinoCrashTest.zip](https://github.com/openvinotoolkit/openvino/files/10943652/VinoCrashTest.zip)

I have attached a test program with source code and a Vino model which can reproduce the crash.

**Comment by Iffa-Meah** [comment] 2023-03-17 01:24
@zabomate I validated your dynamic shaped model and it seems to be supported.

<img width="583" alt="14468_benchmark" src="https://user-images.githubusercontent.com/79643476/225787722-f116532c-b973-4666-b312-ea31896a9e3b.png">

Could you help to: 
1. Share the steps that you did to build, compile and run the custom code that you shared?
2. Any chance that you tried the model with one of the [official OpenVINO Inference Engine samples](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Samples_Overview.html)?

**Comment by Iffa-Meah** [comment] 2023-03-30 08:44
@zabomate your custom code **cannot** be built, compiled, and run as a "simple cmake project" as you mentioned since some libraries are not complete and those libraries seem to be dependent on each other (Qt libraries).


<img width="702" alt="14468" src="https://user-images.githubusercontent.com/79643476/228780627-e7832c8a-2305-44b3-9024-8d4b45937add.PNG">

**Comment by zabomate** [comment] 2023-03-30 08:50
@Iffa-Meah I attached a new zip file called VinoCrashTestCMake.zip in my previous comment. That one is a cmake project.

**Comment by Iffa-Meah** [comment] 2023-03-30 10:13
@zabomate Got it. Could you elaborate how you setup your openvino/openvino.hpp in your custom code?
Did you copy & paste certain files into it or it's actually your entire OpenVINO runtime folder (which officially downloaded), or else

<img width="387" alt="14468cmake" src="https://user-images.githubusercontent.com/79643476/228804637-ce4b2abe-b6b0-48ec-a56c-2c3aed1ccf15.PNG">

**Comment by Iffa-Meah** [comment] 2023-04-05 05:12
@zabomate thanks for the clarification.

From my end, it seems your custom code is unable to read your model.
<img width="730" alt="14468_model" src="https://user-images.githubusercontent.com/79643476/229986618-0cfa4c40-2240-4d9b-893e-60fb5ab526fb.PNG">

**Comment by Iffa-Meah** [comment] 2023-04-13 23:10
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Closed by Iffa-Meah** 2023-04-13 23:10 UTC
Labels: category: GPU, support_request
