### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jpapon** [openvinotoolkit/openvino#96] opened 2019-03-04 16:41 UTC
There is a memory leak in clDNN 9.1 that does not show up until after many thousands of inferences.
It's definitely there though, and was fixed in version 12.0 (https://github.com/intel/clDNN)
We were able to work around this by pulling in and building the new version of clDNN.

I think it's of highest priority that this new version of clDNN be pulled into the next release of Openvino and into the current master branch as well. The memory leak completely breaks any system if you leave it running inference for a day or two, and is very sneaky - it doesn't start leaking memory until *after* a great many inferences (how many exactly is hard to say).

This issue is also documented here: https://software.intel.com/en-us/forums/computer-vision/topic/802273

**Comment by shubha-ramani** [comment] 2019-03-04 21:01
jpapon the original poster of this issue said that lDNN version to Drop 12.1 fixes the problem. Am I mistaken ?

**Comment by ts-accessio** [comment] 2019-03-05 10:15
With clDNN Drop 12.1 we did not observe the problem but we did not check in which Drop the problem was actually fixed.

**Comment by jpapon** [comment] 2019-03-05 20:17
Yes, it looks like it was fixed in 12.0. 
13 definitely does not have the problem.

I only posted the issue because the version currently included in the inference engine is 9.1, which definitely does leak memory.

**Comment by jpapon** [comment] 2019-04-06 00:22
Just want to add that this issue was not fixed in the binary release of 2019R1 - inference still leaks memory after many thousands of inferences. It appears to be a little slower than in 2018R5, but was not eliminated completed.
Hopefully it will be fixed in the source release.

For reference, the following did fix the memory leak in our Docker build:

```
RUN git clone https://github.com/opencv/dldt.git && \
    cd dldt/inference-engine/thirdparty && \
    git clone https://github.com/opencv/ade.git && \
    cd .. && \
    rm -rf build && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make -j"$(nproc)" && \
    cd ../bin/intel64/Release/ && \
    rm -rf /opt/intel/computer_vision_sdk/inference_engine/lib/ubuntu_18.04/intel64/ && \
    rm -rf /opt/intel/computer_vision_sdk_2018.5.445/deployment_tools/inference_engine/lib/ubuntu_18.04/intel64/ && \
    cp -r lib/ /opt/intel/computer_vision_sdk_2018.5.445/deployment_tools/inference_engine/lib/ubuntu_18.04/intel64 && \
    cp -r lib/ /opt/intel/computer_vision_sdk/inference_engine/lib/ubuntu_18.04/intel64
```

**Comment by shubha-ramani** [comment] 2019-04-06 19:32
Dear @jpapon Can you kindly open a new issue on the new Memory Leak you are witnessing - as well as reproduction steps ?

Thanks for using OpenVino !

Shubha

**Comment by vladimir-paramuzov** [comment] 2020-12-17 11:25
We don't observe memory leaks on GPU for the latest OV releases, so I close this issue. 

@jpapon if you still have any issues with mem leaks, feel free to reopen.

**Closed by vladimir-paramuzov** 2020-12-17 11:25 UTC
Labels: category: GPU
