### ISSUE TITLE
Unexpected exception when running the model optimizer on Yolov3 with GPU

### ISSUE THREAD

**Issue by alontrais** [openvinotoolkit/openvino#237] opened 2019-09-05 12:21 UTC
Hi,

I use the object_detection_demo_yolov3_async.py script
in "/opt/intel/openvino_2019.2.275/deployment_tools/inference_engine/samples/python_samples/object_detection_demo_yolov3_async" folder.

I succeeded to run the script on CPU:
"python3 object_detection_demo_yolov3_async.py --labels coco.names -i splits -m frozen_darknet_yolov3_model.xml -d CPU --cpu_extension libcpu_extension_sse4.so"

but when I try to run the script on GPU:
"python3 object_detection_demo_yolov3_async.py --labels coco.names -i splits -m frozen_darknet_yolov3_model.xml -d GPU"

I get "Segmentation fault (core dumped)" error

**Comment by shubha-ramani** [comment] 2019-09-06 19:15
Dear @alontrais,
Wow. That's pretty bad. Sorry to hear that the yolov3_async.py bombed on the GPU. Looks like you're on the latest and greatest OpenVino also so thank you.

Let me try and reproduce it myself and I will report back here.

Thanks for your patience,

Shubha

**Comment by shubha-ramani** [comment] 2019-09-09 17:34
Dear @alontrais 
I tried reproducing your this issue on  both 2019R2.01 and R3 (which you don't have yet).  So far I could not. Can you post the screen output during the execution ? I'm curious to know precisely when the core dump happens.

Thanks,

Shubha

**Comment by lazarevevgeny** [comment] 2020-05-25 12:12
@alontrais is this issue actual?

**Comment by alontrais** [comment] 2020-06-04 07:15
@lazarevevgeny thanks it is not actual.

**Comment by lazarevevgeny** [comment] 2020-06-04 11:07
Closing.

**Closed by lazarevevgeny** 2020-06-04 11:07 UTC
Labels: category: samples
