### ISSUE TITLE
[Bug] custom layter output initialize

### ISSUE THREAD

**Issue by wang7393** [openvinotoolkit/openvino#12273] opened 2022-07-25 03:40 UTC
##### System information (version)
- OpenVINO=> :2022.1
- Operating System / Platform => :win10
- Problem classification => :custom layter output initialize

##### Detailed description

I have  implemented a custom layer.
With cpu inference  under Release mode(the output was initialized 0), it can get correct results. But under Debug mode, can not get correct results, and found that the output was not initialized(all -43160208) resulting in incorrect inference.
With gpu inference, the output with the first inference is initialized to 0 in both Debug and Release mode.  But in the subsequent inference process, the output was not cleared. I implemented an operation like this: "out[i] += 1", As the number of inference increases, the output will increase infinitely.
How to solve it? Is there any interface for custom layer that can  initialize or reset the output?

**Comment by Iffa-Meah** [comment] 2022-07-26 02:19
@wang7393 could you share your model files for us to check from our side? and may I know which framework this model and its topology?

**Comment by wang7393** [comment] 2022-07-26 03:05
@Iffa-Meah 
The model is a custom layer model. After check, there is no problem under gpu inference.
But under cpu inference, the above problems still exist: under debug mode, the custom layer's output has not been initialized, but under release mode, the custom layer's output has been initialized.
So you should check that the initialization of the input and output of the custom layer is configured correctly.
Thanks.

**Comment by wang7393** [comment] 2022-07-26 03:07
@Iffa-Meah 
The model is a custom layer model. After check, there is no problem under gpu inference.
But under cpu inference, the above problems still exist: under debug mode, the custom layer's output has not been initialized, but under release mode, the custom layer's output has been initialized.
So you should check that the initialization of the input and output of the custom layer is configured correctly.  Because I don't see anything in the documentation or in the examples where the custom layer needs to manually allocate memory and initialize input and output
Thanks.

**Comment by Iffa-Meah** [comment] 2022-07-27 02:39
@wang7393 there's possibility that you are using an unsupported framework layer which you may cross-check with yours [here](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_Supported_Frameworks_Layers.html).

**Comment by wang7393** [comment] 2022-07-27 04:56
@Iffa-Meah 
I told you that my problem is with the custom layer (which onnxdoes not support), which was implemented using the tutorial.  https://docs.openvino.ai/latest/openvino_docs_Extensibility_UG_Intro.html
The output of the custom layer has not been properly initialized and the output of the custom layer has not been allocated or initialized properly.

**Comment by wang7393** [comment] 2022-07-27 08:04
@Iffa-Meah 
added：
the same model(contain custom layer) with gpu inference. The output memory of the custom layer has not been reset. Because my custom layer has a cumulative operation, the output of the custom layer increases infinitely as the number of inferences increases.
So I recommend for the custom layer: implement memory allocation or resetting at the bottom, or provide a dedicated interface for memory allocation or resetting.

**Comment by Iffa-Meah** [comment] 2022-07-28 02:12
@wang7393 since you couldn't share your model files for us to validate from our side, we'll assess and get back to you with the possible & appropriate solution/s asap.

Thank you for your patience.

**Comment by jgespino** [comment] 2022-08-02 18:59
@wang7393 Could you please share the following for us to reprodue and investigate the issue?

- Steps to reproduce
- Model
- Model Optimizer Command used
- Code
- Test input
- Expected results

Feel free to share it via email (visable on my profile) if you need to keep the information private.

**Comment by wang7393** [comment] 2022-08-11 03:08
@jgespino  sorry, This involves custom networking and code.
But you can do the following simulation:   
Using OpencL to achieve a cumulative operation. Moreover, the inference result of each time is viewed. If the output memory is not cleared before each inference, it will be continuously increased.

**Comment by jgespino** [comment] 2022-08-25 18:55
@wang7393 I've reached out to the development team for additional input on this issue.

Ref. 90158 & 90159

**Comment by vladimir-paramuzov** [comment] 2022-09-15 07:39
@wang7393 intermediate buffer of arbitrary operation is not memory state of the model and users shouldn't expect it to be reset or initialized anyhow (doing so would ruin the performance). 
So could you please clarify what op you're trying to do via custom layer? `out[i] += 1`  looks like some artificial thing. 
If you really need to add 1 to the input tensor, why do you need custom op for that? Add operation with constant will do the trick. 
If model state is needed, please refer to https://docs.openvino.ai/latest/openvino_docs_OV_UG_network_state_intro.html for details on how to deal with the state.

**Comment by wang7393** [comment] 2022-09-17 02:33
@vladimir-paramuzov 
My custom layer is a complex operation, one of which is to add the output of the previous layer, and then output the accumulated result. If the output memory of the custom layer is not cleared, then with the increase of the number of inference, the input result will continue to increase, resulting in the output error.

It is true that zeroing the output space after each inference will affect performance, so I will have to manually zeroing it according to my needs.

**Comment by avitial** [comment] 2022-12-29 17:43
Closing this, I hope previous responses from vladimir-paramuzov were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Closed by avitial** 2022-12-29 17:43 UTC
Labels: bug, support_request, PSE
