### ISSUE TITLE
How to add OpenCL kernel create custom opset on GPU

### ISSUE THREAD

**Issue by 18582088138** [openvinotoolkit/openvino#21004] opened 2023-11-10 05:56 UTC
I reference the source code the "[gpu_test_function_custom_op](https://github.com/openvinotoolkit/openvino/tree/d6852598cead3e68ca29a9df24328bd2a0cd39dd/src/plugins/intel_gpu/tests/functional/custom_op)" to build a custom_op , and I want to use python API "opset_utils._get_node_factory.create()" to register this custom operate, but it doesn't work

Could you provide a sample code for registering a custom opset on GPU?

**Comment by ilya-lavrenov** [comment] 2023-11-10 08:33
Hi @18582088138 
Here is a doc https://docs.openvino.ai/2023.1/openvino_docs_Extensibility_UG_GPU.html

**Comment by 18582088138** [comment] 2023-11-13 07:23
Sure, thank for your useful guide, I had already referenced it to run pipe successes 
but in my opencl kernel there are some inline function, and I do not find any reference for opencl inline function plugin.

I tried to build the model with my custom kernel, the model can be compiled and also can create infer_request, but when I set_tensor into infer_request, I got error "**clEnqueueNDRangeKernel, error code: -52**"
but if I delete the inline function , this can work, 
So I think, maybe I am using inline function in worry way, could you provide any references or snippets about How to use inline function in OpenCL custom kernel to plugin it in OpenVINO model

Thanks

**Comment by vladimir-paramuzov** [comment] 2023-11-24 06:34
@18582088138 Error -52 means CL_INVALID_KERNEL_ARGS:
From https://man.opencl.org/clEnqueueNDRangeKernel.html :
```
CL_INVALID_KERNEL_ARGS if the kernel argument values have not been specified or if a kernel argument declared to be a pointer to a type does not point to a named address space.
```
So please double-check that count of kernel arguments matches count of arguments described in xml config (`Buffers` section). Most likely the issue is not anyhow related to inline function as in such case you would just face OCL compiler error, not runtime one. If you share xml config and custom kernel code (kernel interface at least), we could try to provide a hint on what could be wrong.

**Comment by avitial** [comment] 2023-12-22 17:38
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.

**Closed by avitial** 2023-12-22 17:38 UTC
Labels: question, category: GPU, support_request
