### ISSUE TITLE
issue about openvino load onnx model

### ISSUE THREAD

**Issue by konioy** [openvinotoolkit/openvino#4746] opened 2021-03-12 02:08 UTC
I use openvino to load the onnx model directly. Two models with nuances are loaded, as shown in the following image. which
The role of the first Transpose is to turn NCHWinto NHWC, and the second is NHWC to NCHW. the result of inferencing obtained by the two onnx models are consistent. Is that reasonable? Is this a bug?
![image](https://user-images.githubusercontent.com/24238694/110881145-d4f2c380-831a-11eb-8411-0ce0e36dd03e.png)

**Comment by ilya-lavrenov** [comment] 2021-03-14 09:25
I suppose if we move the second transpose before softmax, we will have NCHW->NHWC->NCHW which actually does nothing and it's equal to the second model. So, the results are the same.

**Comment by konioy** [comment] 2021-03-15 02:49
why move the second transpose before softmax? 
The input data format of softmax on the left is NHWC, and on the right is NCHW, and the axis parameters of softmax are the same, but why are the results the same?

**Comment by jgespino** [comment] 2021-06-03 02:26
@ilya-lavrenov Do you have any additional input?

**Comment by jgespino** [comment] 2021-07-09 21:20
Hi @konioy 

I'm not sure if the issue is still relevant, if it is could you check if it's still applicable in the latest release (2021.4) and provide the model?

Regards,
Jesus

**Comment by ilyachur** [comment] 2021-07-12 03:41
cc @tomdol

**Comment by jgespino** [comment] 2021-07-26 22:48
Closing, please re-open if additional assistance is needed.

**Closed** 2021-07-26 22:47 UTC
Labels: PSE, bug, support_request
