### ISSUE TITLE
[Bug] build on CentOS7.9

### ISSUE THREAD

**Issue by Fred-cell** [openvinotoolkit/openvino#13881] opened 2022-11-06 01:58 UTC
##### System information (version)

cmake -DCMAKE_BUILD_TYPE=Release -DONEDNN_ENABLE_MAX_CPU_ISA=ON -DENABLE_CLDNN=OFF -DENABLE_INTEL_GPU=OFF -DENABLE_INTEL_GNA=OFF -DENABLE_INTEL_MYRIAD_COMMON=OFF -DENABLE_INTEL_MYRIAD=OFF -DVERBOSE_BUILD=OFF -DENABLE_PYTHON=ON -DENABLE_WHEEL=ON -DCMAKE_INSTALL_PREFIX=../install -DTREAT_WARNING_AS_ERROR=OFF -DENABLE_OPENCV=OFF -DPYTHON_EXECUTABLE=`which python3.7` -DPYTHON_LIBRARY=/home/conda_envs/ov-22.3/lib/libpython3.7m.so -DPYTHON_INCLUDE_DIR=/home/conda_envs/ov-22.3/include/python3.7m ..
The operation is hung as follow:
![image](https://user-images.githubusercontent.com/99886928/200150424-2535275a-37f5-44c2-90e5-6cedf52a5cc3.png)
Log of CMake is as below:

[CMakeOutput.log](https://github.com/openvinotoolkit/openvino/files/9945018/CMakeOutput.log)

**Comment by zulkifli-halim** [comment] 2022-11-08 01:47
Hi @Fred-cell, do you get a chance to check the guide on how to [Building OpenVINO on CentOS 7](https://github.com/openvinotoolkit/openvino/wiki/Building-OpenVINO-on-CentOS-7-Guide)? This guide will provide you with detailed guidelines for building OpenVINO on CentOS 7.9.

**Comment by sammysun0711** [comment] 2022-11-08 04:03
I found the CMake hang issue caused by: https://github.com/openvinotoolkit/openvino/blob/e1f014ac15ed5b59343c336598bd77fd81eef765/cmake/developer_package/IEDevScriptsConfig.cmake#L98
which will call：https://github.com/openvinotoolkit/openvino/blob/e1f014ac15ed5b59343c336598bd77fd81eef765/cmake/developer_package/shellcheck/shellcheck.cmake#L10
This issue can be reproduced by running 
`/usr/bin/shellcheck --version`

ShellCheck is used for shell static analysis, which is not mandatory for building OpenVINO on CentOS, user may remove ShellCheck package in system as workaround: 
`sudo yum remove ShellCheck`

**Comment by sammysun0711** [comment] 2022-11-08 04:08
Please note, Shellcheck issue may not reproduce in all CentOS 7 system, I verified two systems, CLX6248 failed while i7-10700 works, it may related kernel version installed. 
Here is system information for two machine:

CLX6248: 
- OS: CentOS Linux release 7.9.2009 (Core)
- Kernel: 3.10.0-1127.13.1.el7.x86_64
- Glibc: 2.17
- ShellCheck: ShellCheck-0.3.8-1.el7.x86_64
[strace_shellcheck_CLX6248.log](https://github.com/openvinotoolkit/openvino/files/9957509/strace_shellcheck_CLX6248.log)

I7-10700
- OS: CentOS Linux release 7.9.2009 (Core)
- Kernel: 3.10.0-1160.el7.x86_64
- Glibc: 2.17
- ShellCheck: ShellCheck-0.3.8-1.el7.x86_64
[strace_shellcheck_i7-10700.log](https://github.com/openvinotoolkit/openvino/files/9957510/strace_shellcheck_i7-10700.log)

**Comment by zulkifli-halim** [comment] 2022-11-17 13:37
Closing issue. Feel free to reopen if further assistance is needed.

**Closed by zulkifli-halim** 2022-11-17 13:37 UTC
Labels: category: build, support_request
