### ISSUE TITLE
'statistics_processor. hpp' can not find

### ISSUE THREAD

**Issue by blackantywj** [openvinotoolkit/openvino#324] opened 2019-11-19 10:23 UTC
When I compile to 98 percent,
`DLDT/inferenceengine/build/ie_bridges/python/SRC/openvino/tools/statistics_collector/statistics_collector_api.cxx`  
this file always appended an error:
`fatal error: statistics_processor. hpp:No such file or directory`
 So I want to know how the header file contained in line 612 of statistics_collector_api.cxx was generated.
How do I import it so that it compiles successfully?
Thank you very much.

**Comment by asuhov** [comment] 2019-11-19 18:16
Hello, 
The statistics_processor.hpp file is located here: https://github.com/opencv/dldt/tree/2019/inference-engine/tools/calibration_tool/statistics_collector
Could you check if it exists in your repo?

**Comment by blackantywj** [comment] 2019-11-20 01:10
> 您好，
> statistics_processor.hpp文件位于以下位置：[https](https://github.com/opencv/dldt/tree/2019/inference-engine/tools/calibration_tool/statistics_collector) : [//github.com/opencv/dldt/tree/2019/inference-engine/tools/calibration_tool/statistics_collector](https://github.com/opencv/dldt/tree/2019/inference-engine/tools/calibration_tool/statistics_collector)
> 您能否检查存储库中是否存在该文件？
Sorry, I just got started. Where is the repo you said? In addition, I found that I moved the missing header file to the wrong folder
`DLDT/inferenceengine/build/ie_bridges/python/SRC/openvino/tools/statistics_collector`
he reported the following error:
`[ 98%] Linking CXX shared module ../../../../../../../bin/aarch64/Release/lib/py                                                  thon_api/python1.4/openvino/tools/statistics_collector/statistics_collector_api.                                                  so
/usr/bin/ld: cannot find -lstatistics_collector_s
collect2: error: ld returned 1 exit status
ie_bridges/python/src/openvino/tools/statistics_collector/CMakeFiles/statistics_                                                  collector_api.dir/build.make:101: recipe for target '../bin/aarch64/Release/lib/                                                  python_api/python1.4/openvino/tools/statistics_collector/statistics_collector_ap                                                  i.so' failed
make[2]: *** [../bin/aarch64/Release/lib/python_api/python1.4/openvino/tools/sta                                                  tistics_collector/statistics_collector_api.so] Error 1
CMakeFiles/Makefile2:2258: recipe for target 'ie_bridges/python/src/openvino/too                                                  ls/statistics_collector/CMakeFiles/statistics_collector_api.dir/all' failed
make[1]: *** [ie_bridges/python/src/openvino/tools/statistics_collector/CMakeFil                                                  es/statistics_collector_api.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
`
Looking forward to your reply, thank you.

**Comment by blackantywj** [comment] 2019-11-20 01:30
> Hello,
> The statistics_processor.hpp file is located here: https://github.com/opencv/dldt/tree/2019/inference-engine/tools/calibration_tool/statistics_collector
> Could you check if it exists in your repo?


` cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_SSE42=OFF -DTHREADING=SEQ  -DENABLE_GNA=OFF -DENABLE_VPU=ON -DENABLE_MYRIAD=ON -DENABLE_MKL_DNN=OFF -DENABLE_CLDNN=OFF -DENABLE_SAMPLES=OFF -DENABLE_OPENCV=OFF -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 ..
`

**Comment by ts-accessio** [comment] 2019-12-04 08:52
It seems to be a problem when building without OpenCV. My fix (which I guess only works if you have OpenCV installed):
In "inference_engine/tools/CMakeLists.txt":
```
-if (ENABLE_OPENCV)
+#if (ENABLE_OPENCV)
     add_subdirectory(calibration_tool/statistics_collector)
-endif()
+#endif()
```

**Comment by blackantywj** [comment] 2019-12-04 08:56
> It seems to be a problem when building without OpenCV. My fix (which I guess only works if you have OpenCV installed):
> In "inference_engine/tools/CMakeLists.txt":
> 
> ```
> -if (ENABLE_OPENCV)
> +#if (ENABLE_OPENCV)
>      add_subdirectory(calibration_tool/statistics_collector)
> -endif()
> +#endif()
> ```
Thanks for your reply. I have solved this problem, because the above documents are not compatible with my system.

**Comment by JacobLau84** [comment] 2020-01-03 11:51
![image](https://user-images.githubusercontent.com/34982075/71721987-3dfec180-2e62-11ea-8e90-cda12daa0818.png)
How did you solve it ?

**Comment by blackantywj** [comment] 2020-01-03 12:44
> ![image](https://user-images.githubusercontent.com/34982075/71721987-3dfec180-2e62-11ea-8e90-cda12daa0818.png)
> How did you solve it ?
You don't need the statictics_processpr library, just comment it out in the configuration file.
By the way, on what device do you deploy the DLDT library.
Regrads

**Comment by blackantywj** [comment] 2020-01-03 12:54
> ![image](https://user-images.githubusercontent.com/34982075/71721987-3dfec180-2e62-11ea-8e90-cda12daa0818.png)
> How did you solve it ?

I commented out the statistics_processor compilation in the compiled configuration file because of its python version (1.4?)Too old...

**Comment by JacobLau84** [comment] 2020-01-03 13:52
> 
> 
> > ![image](https://user-images.githubusercontent.com/34982075/71721987-3dfec180-2e62-11ea-8e90-cda12daa0818.png)
> > How did you solve it ?
> 
> I commented out the statistics_processor compilation in the compiled configuration file because of its python version (1.4?)Too old...
> By the way, do you want to compile the DLDT library on pi4？

Yes, I want to use NCS2 stick with Raspberry Pi 4.
I found some discussion here https://software.intel.com/es-es/node/813265, and I trying it.
btw, 我可以用中文和您溝通嗎，我英文沒有很溜xdd

**Comment by blackantywj** [comment] 2020-01-03 14:14
> > > ![image](https://user-images.githubusercontent.com/34982075/71721987-3dfec180-2e62-11ea-8e90-cda12daa0818.png)
> > > How did you solve it ?
> > 
> > 
> > I commented out the statistics_processor compilation in the compiled configuration file because of its python version (1.4?)Too old...
> > By the way, do you want to compile the DLDT library on pi4？
> 
> Yes, I want to use NCS2 stick with Raspberry Pi 4.
> I found some discussion here https://software.intel.com/es-es/node/813265, and I trying it.
> btw, 我可以用中文和您溝通嗎，我英文沒有很溜xdd

您好
当然可以，我在jetson nano上编译成功并且现在运行正常 我主要参考的就是此链接中给出的
`https://www.pyimagesearch.com/2019/04/08/openvino-opencv-and-movidius-ncs-on-the-raspberry-pi/
`
请问您是按流程叙述的过程操作的吗？
谢谢

**Comment by JacobLau84** [comment] 2020-01-03 14:22
> > > > ![image](https://user-images.githubusercontent.com/34982075/71721987-3dfec180-2e62-11ea-8e90-cda12daa0818.png)
> > > > How did you solve it ?
> > > 
> > > 
> > > I commented out the statistics_processor compilation in the compiled configuration file because of its python version (1.4?)Too old...
> > > By the way, do you want to compile the DLDT library on pi4？
> > 
> > 
> > Yes, I want to use NCS2 stick with Raspberry Pi 4.
> > I found some discussion here https://software.intel.com/es-es/node/813265, and I trying it.
> > btw, 我可以用中文和您溝通嗎，我英文沒有很溜xdd
> 
> 您好
> 当然可以，我在jetson nano上编译成功并且现在运行正常 我主要参考的就是此链接中给出的
> `https://www.pyimagesearch.com/2019/04/08/openvino-opencv-and-movidius-ncs-on-the-raspberry-pi/ `
> 请问您是按流程叙述的过程操作的吗？
> 谢谢

想請教一下，在jetson nano上跑這個加速棒的話，在跑神經網路的時候是gpu和加速棒可以同時加速嗎？

**Comment by blackantywj** [comment] 2020-01-03 14:23
> > > > > ![image](https://user-images.githubusercontent.com/34982075/71721987-3dfec180-2e62-11ea-8e90-cda12daa0818.png)
> > > > > How did you solve it ?
> > > > 
> > > > 
> > > > I commented out the statistics_processor compilation in the compiled configuration file because of its python version (1.4?)Too old...
> > > > By the way, do you want to compile the DLDT library on pi4？
> > > 
> > > 
> > > Yes, I want to use NCS2 stick with Raspberry Pi 4.
> > > I found some discussion here https://software.intel.com/es-es/node/813265, and I trying it.
> > > btw, 我可以用中文和您溝通嗎，我英文沒有很溜xdd
> > 
> > 
> > 您好
> > 当然可以，我在jetson nano上编译成功并且现在运行正常 我主要参考的就是此链接中给出的
> > `https://www.pyimagesearch.com/2019/04/08/openvino-opencv-and-movidius-ncs-on-the-raspberry-pi/ `
> > 请问您是按流程叙述的过程操作的吗？
> > 谢谢
> 
> 想請教一下，在jetson nano上跑這個加速棒的話，在跑神經網路的時候是gpu和加速棒可以同時加速嗎？

nanp功率应该是不够的

**Comment by JacobLau84** [comment] 2020-01-03 14:27
> > > > > > ![image](https://user-images.githubusercontent.com/34982075/71721987-3dfec180-2e62-11ea-8e90-cda12daa0818.png)
> > > > > > How did you solve it ?
> > > > > 
> > > > > 
> > > > > I commented out the statistics_processor compilation in the compiled configuration file because of its python version (1.4?)Too old...
> > > > > By the way, do you want to compile the DLDT library on pi4？
> > > > 
> > > > 
> > > > Yes, I want to use NCS2 stick with Raspberry Pi 4.
> > > > I found some discussion here https://software.intel.com/es-es/node/813265, and I trying it.
> > > > btw, 我可以用中文和您溝通嗎，我英文沒有很溜xdd
> > > 
> > > 
> > > 您好
> > > 当然可以，我在jetson nano上编译成功并且现在运行正常 我主要参考的就是此链接中给出的
> > > `https://www.pyimagesearch.com/2019/04/08/openvino-opencv-and-movidius-ncs-on-the-raspberry-pi/ `
> > > 请问您是按流程叙述的过程操作的吗？
> > > 谢谢
> > 
> > 
> > 想請教一下，在jetson nano上跑這個加速棒的話，在跑神經網路的時候是gpu和加速棒可以同時加速嗎？
> 
> nano功率应该是不够的
> 另外，请问您有社交账号吗，也许我们可以在那个中交流，因为马上我也想将NCS迁移到pi4中

有可以直接寫這裡嗎😂
我微信id:
JacoB0322

**Comment by blackantywj** [comment] 2020-01-03 14:29
> > > > > > > ![image](https://user-images.githubusercontent.com/34982075/71721987-3dfec180-2e62-11ea-8e90-cda12daa0818.png)
> > > > > > > How did you solve it ?
> > > > > > 
> > > > > > 
> > > > > > I commented out the statistics_processor compilation in the compiled configuration file because of its python version (1.4?)Too old...
> > > > > > By the way, do you want to compile the DLDT library on pi4？
> > > > > 
> > > > > 
> > > > > Yes, I want to use NCS2 stick with Raspberry Pi 4.
> > > > > I found some discussion here https://software.intel.com/es-es/node/813265, and I trying it.
> > > > > btw, 我可以用中文和您溝通嗎，我英文沒有很溜xdd
> > > > 
> > > > 
> > > > 您好
> > > > 当然可以，我在jetson nano上编译成功并且现在运行正常 我主要参考的就是此链接中给出的
> > > > `https://www.pyimagesearch.com/2019/04/08/openvino-opencv-and-movidius-ncs-on-the-raspberry-pi/ `
> > > > 请问您是按流程叙述的过程操作的吗？
> > > > 谢谢
> > > 
> > > 
> > > 想請教一下，在jetson nano上跑這個加速棒的話，在跑神經網路的時候是gpu和加速棒可以同時加速嗎？
> > 
> > 
> > nano功率应该是不够的
> > 另外，请问您有社交账号吗，也许我们可以在那个中交流，因为马上我也想将NCS迁移到pi4中
> 
> 有可以直接寫這裡嗎😂
> 我微信id:
> JacoB0322

好的 请求已发送

**Comment by yutkin** [comment] 2020-01-29 13:34
The same problem. Dockerfile to reproduce:

```Dockerfile
FROM python:3.7

RUN apt-get update && apt-get install -y --no-install-recommends \
	wget \
	git \
	build-essential \
    cmake \
    curl \
    wget \
    libssl-dev \
    ca-certificates \
    git \
    libboost-regex-dev \
    gcc-multilib \
    g++-multilib \
    libgtk2.0-dev \
    pkg-config \
    unzip \
    automake \
    libtool \
    autoconf \
    libcairo2-dev \
    libpango1.0-dev \
    libglib2.0-dev \
    libgtk2.0-dev \
    libswscale-dev \
    libavcodec-dev \
    libavformat-dev \
    libgstreamer1.0-0 \
    gstreamer1.0-plugins-base \
    libusb-1.0-0-dev \
    libopenblas-dev \
    libpng-dev 

WORKDIR /opt

RUN git clone https://github.com/opencv/dldt && \
	cd dldt/inference-engine && \
	git submodule init && \
	git submodule update --recursive

RUN pip install -r dldt/inference-engine/ie_bridges/python/requirements.txt

RUN cd dldt/inference-engine && \
	mkdir build && cd build && \
	cmake \
		-DCMAKE_BUILD_TYPE=Release \
		-DENABLE_CLDNN=OFF \
		-DENABLE_MKL_DNN=OFF \
		-DENABLE_PYTHON=ON \
		-DPYTHON_EXECUTABLE=`which python3.7` \
		-DPYTHON_LIBRARY=/usr/local/lib/libpython3.7m.so \
		-DPYTHON_INCLUDE_DIR=/usr/local/include/python3.7m .. && \
	make --jobs=$(nproc --all)

```

**Comment by yutkin** [comment] 2020-01-29 14:43
Resolved by building OpenCV.

**Comment by ilya-lavrenov** [comment] 2020-05-29 05:03
Closing as resolved

**Closed by ilya-lavrenov** 2020-05-29 05:03 UTC
