### ISSUE TITLE
Failed to run object_detection_sample_ssd python code with HDDL

### ISSUE THREAD

**Issue by evenpengqnap** [openvinotoolkit/openvino#1166] opened 2020-06-30 15:12 UTC
With OpenVINO 2020.3 LTS release, I cannot run "object_detection_sample_ssd" python sample code with Intel pre-trained model "person-detection-retail-0013" using HDDL.
It shows "RuntimeError: Unexpected CNNNetwork format: it was converted to deprecated format prior plugin's call"

But, the benchmark_app python sample can benchmark model "person-detection-retail-0013" using HDDL.

**Comment by jgespino** [comment] 2020-07-01 17:31
Hi @evenpengqnap 

Thanks for reaching out, I did a quick test on my Ubuntu 18.04 system with OpenVINO 2020.3 and I was able to run the python demo without any issues. Could you please share additional information about your setup (OS, HDDL model, CPU model) and where you downloaded the model from?

Downloaded the model with the **models.lst** file included in the demo directory
`python3 /opt/intel/openvino/deployment_tools/tools/model_downloader/downloader.py --list models.lst`

Ran the demo:
`python3 object_detection_demo_ssd_async.py -i people-detection.mp4 -d HDDL -m intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml`

Please let me know if I am missing any steps to reproduce the issue.

Regards,
Jesus

**Comment by evenpengqnap** [comment] 2020-07-02 04:19
Hi @jgespino 

Instead of `object_detection_demo_ssd_async.py`, I was trying to run `object_detection_sample_ssd.py`. The model is downloaded by model_downloader.

Here is the command and results:
`
python3 ./object_detection_sample_ssd.py -m /opt/intel/openvino/deployment_tools/tools/model_downloader/intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml -i sample.jpg -d HDDL
[ INFO ] Loading Inference Engine
[ INFO ] Loading network files:
	/opt/intel/openvino/deployment_tools/tools/model_downloader/intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml
	/opt/intel/openvino/deployment_tools/tools/model_downloader/intel/person-detection-retail-0013/FP16/person-detection-retail-0013.bin
[ INFO ] Device info:
        HDDL
        MKLDNNPlugin version ......... 2.1
        Build ........... 2020.3.0-3467-15f2c61a-releases/2020/3
inputs number: 1
input shape: [1, 3, 320, 544]
input key: data
[ INFO ] File was added:
[ INFO ]         sample.jpg
[ WARNING ] Image sample.jpg is resized from (320, 544) to (320, 544)
[ INFO ] Preparing input blobs
[ INFO ] Batch size is 1
[ INFO ] Preparing output blobs
[ INFO ] Loading model to the device
Traceback (most recent call last):
  File "./object_detection_sample_ssd.py", line 213, in <module>
    sys.exit(main() or 0)
  File "./object_detection_sample_ssd.py", line 166, in main
    exec_net = ie.load_network(network=net, device_name=args.device)
  File "ie_api.pyx", line 178, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 187, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Unexpected CNNNetwork format: it was converted to deprecated format prior plugin's call
`

HDDL module: Mustang-MPCIE-MX2 (https://www.ieiworld.com/tw/product/model.php?II=658)
hddldaemon logs:
`
[10:23:28.5830][1547]I[main.cpp:243] ## HDDL_INSTALL_DIR: /opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/external/hddl
[10:23:28.5831][1547]I[main.cpp:245] Config file '/opt/intel/openvino_2020.3.194/deployment_tools/inference_engine/external/hddl/config/hddl_service.config' has been loaded
[10:23:28.5841][1547]I[FileHelper.cpp:272] Set file:/var/tmp/hddl_service_alive.mutex owner: user-'no_change', group-'users', mode-'0660'
[10:23:28.5842][1547]I[FileHelper.cpp:272] Set file:/var/tmp/hddl_service_ready.mutex owner: user-'no_change', group-'users', mode-'0660'
[10:23:28.5843][1547]I[FileHelper.cpp:272] Set file:/var/tmp/hddl_start_exit.mutex owner: user-'no_change', group-'users', mode-'0660'
[10:23:28.5845][1547]I[AutobootStarter.cpp:156] Info: No running autoboot process. Start autoboot daemon...
[10:23:50.3751][1547]I[AutobootStarter.cpp:85] Info: Autoboot is running.
[10:23:50.3811][1547]W[ConfigParser.cpp:269] Warning: Cannot find key, path=scheduler_config.max_graph_per_device subclass=0, use default value: 1.
[10:23:50.3812][1547]W[ConfigParser.cpp:292] Warning: Cannot find key, path=scheduler_config.use_sgad_by_default subclass=0, use default value: false.
[10:23:50.3812][1547]I[DeviceSchedulerFactory.cpp:56] Info: ## DeviceSchedulerFacotry ## Created Squeeze Device-Scheduler2.
[10:23:50.3813][1547]I[DeviceManager.cpp:551] ## SqueezeScheduler created ##
[10:23:50.3814][1547]I[DeviceManager.cpp:649] times 0: try to create worker on device(4.2)
[10:23:52.3871][1547]I[DeviceManager.cpp:670] [SUCCESS] times 0: create worker on device(4.2)
[10:23:52.3872][1547]I[DeviceManager.cpp:719] worker(Wt4.2) created on device(4.2), type(0)
[10:23:52.3873][1547]I[DeviceManager.cpp:649] times 0: try to create worker on device(4.1)
[10:23:54.3936][1547]I[DeviceManager.cpp:670] [SUCCESS] times 0: create worker on device(4.1)
[10:23:54.3937][1547]I[DeviceManager.cpp:719] worker(Wt4.1) created on device(4.1), type(0)
[10:23:54.3937][1547]I[DeviceManager.cpp:145] DEVICE FOUND : 2
[10:23:54.3938][1547]I[DeviceManager.cpp:146] DEVICE OPENED : 2
[10:23:54.3940][1547]I[DeviceManagerCreator.cpp:81] New device manager(DeviceManager0) created with subclass(0), deviceCount(2)
[10:23:54.3949][1547]I[TaskSchedulerFactory.cpp:45] Info: ## TaskSchedulerFactory ## Created Polling Task-Scheduler.
[10:23:54.3960][1547]I[FileHelper.cpp:272] Set file:/var/tmp/hddl_snapshot.sock owner: user-'no_change', group-'users', mode-'0660'
[10:23:54.3968][1547]I[FileHelper.cpp:272] Set file:/var/tmp/hddl_service.sock owner: user-'no_change', group-'users', mode-'0660'
[10:23:54.3971][1547]I[MessageDispatcher.cpp:87] Message Dispatcher initialization finished
[10:23:54.3972][1547]I[main.cpp:103] SERVICE IS READY ...
`

OS information:
`
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
`

CPU information:
`
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               92
Model name:          Intel(R) Atom(TM) Processor E3940 @ 1.60GHz
Stepping:            9
CPU MHz:             797.216
CPU max MHz:         1800.0000
CPU min MHz:         800.0000
BogoMIPS:            3187.20
Virtualization:      VT-x
L1d cache:           24K
L1i cache:           32K
L2 cache:            1024K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts md_clear arch_capabilities
`

**Comment by jgespino** [comment] 2020-07-02 23:21
Hi @evenpengqnap 

Thanks for pointing that out, I was able to replicate the issue you are seeing. The error is caused by the IRv10 model, this is a known issue that is being investigated. 

As a workaround, can you try using the IRv7 model found at the following link?
https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/person-detection-retail-0013/FP16/

Regards,
Jesus

**Comment by evenpengqnap** [comment] 2020-07-03 06:13
Hi @jgespino 

It works with the IRv7 model.
Will this issue be fixed in 2020.3?

**Comment by brmarkus** [comment] 2020-07-03 06:28
You might want to try this: https://github.com/opencv/opencv/pull/17134

**Comment by jgespino** [comment] 2020-07-17 18:12
Issue has been fixed in 2020.4 release. Feel free to re-open if you continue to see the error.

**Closed by jgespino** 2020-07-17 18:12 UTC
Labels: bug, category: samples

**Comment by mbenguig** [comment] 2022-09-06 11:51
Hi, for the NCS1 compatibility, is it possible de bring this fix to the 2020.3 (2020.3.1) ?
Regards

**Comment by jgespino** [comment] 2022-09-06 16:27
@mbenguig OpenVINO 2020.3 LTS is the previous LTS Release. Could you please try the latest 2021.4.2 LTS Release? It should already be included there. Please start a new issue if you have any further questions.
