### ISSUE TITLE
RuntimeError: Cannot create internal buffer.

### ISSUE THREAD

**Issue by zilion22** [openvinotoolkit/openvino#422] opened 2020-03-17 17:40 UTC
Hi,

I am trying to do inference on a model based on a tweaked InceptionV3 keras/tf model.
I managed to freeze and mo_tf.py but during inference I got the following error:

` File "src/infer_by_openvino.py", line 156, in setup_openvino
    net.batch_size = 1
  File "ie_api.pyx", line 547, in openvino.inference_engine.ie_api.IEPlugin.load
  File "ie_api.pyx", line 557, in openvino.inference_engine.ie_api.IEPlugin.load
RuntimeError: Cannot create internal buffer. Buffer can be overrun.
`

Do you have any idea what it can be?
Can I debug someho what exactly caused this?
Thanks,

**Comment by maxl16** [comment] 2020-03-19 00:32
Hello @zilion22 
I am able to successfully freeze the Inception v3 model from here https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html#Convert_From_TF and convert it to Intermediate Representation and then do inference on it.

1) Can you please try to run your model with the benchmark tool from latest OpenVINO 2020.1 build? Do you see any errors?
openvino/deployment_tools/tools/benchmark_tool/benchmark_app.py
2) If you see no errors, please specify what application you use for inference?

Best regards, Max.

**Comment by maxl16** [comment] 2020-03-21 23:24
Hello @zilion22 
Is there any directory missed from the path openvino/deployment_tools/tools/benchmark_tool/benchmark_app.py or you just don't see benchmark_app.py file in the last directory?

And please also confirm if you follow the same process as described below?
1) Latest OpenVINO toolkit build being downloaded from https://software.intel.com/en-us/openvino-toolkit/choose-download
2) OpenVINO toolkit being installed and configured (Ubuntu 18.04) per https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_linux.html
3) We took the example of Inception V3 non-frozen model (including --mean_values and --scale values for model optimizer command) from https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html#Convert_From_TF
4) Converted per this example https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Slim_Library_Models.html 

If after these steps you are still not able to make this work, is this possible for you to share your model (keras/tf or IR format) with us that we could test it in our environment? Either your modification of Inception V3 model is for some reason not supported by DLDT/OpenVINO toolkit or you might be doing something else wrong.

Best regards, Max.

**Comment by ilyachur** [comment] 2020-05-29 08:12
@zilion22 Looks like converted network contains incorrect weights for convolution layer.

Weights dimensions are `{32,3,3,3}`, but input is `{1,1,1024,1024}`, in this case weights should have dimensions: `{32,1,3,3}`

@lazarevevgeny Could you give an advice if the problem in the MO?

**Comment by lazarevevgeny** [comment] 2020-05-29 08:15
Without the model or a simple reproducer we cannot provide any feedback.

**Comment by AnastasiaKazantaeva** [comment] 2020-07-18 18:36
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,

**Closed by AnastasiaKazantaeva** 2020-07-18 18:36 UTC
Labels: bug, category: MO, needs reproducer, question
