### ISSUE TITLE
Unexpected behavior of OpenVINO(TBB) during load testing

### ISSUE THREAD

**Issue by sttell** [openvinotoolkit/openvino#17837] opened 2023-06-01 09:27 UTC
## Description of problem

Hello! After embedding in the OpenVINO product and using it as a library of neural network inference, I ran into a problem. Load testing showed unexpected results on absolutely all models used. The tests were carried out under the same conditions on a server with Intel Xeon (see below).

The number of threads was controlled using inference_num_threads = N. C++ API.

I would like to know why OpenVINO shows such strange results in multithreaded and multiprocessor mode of operation. We expected performance improvements, including at 10, 20 ceilings and a large number of processes, but TBB seems to ignore the number of threads less than the number of hardware cores.

## Test Reuslts

Threads num set: [1, 2, 3, 4, 5, 10, 20, 40, 80]
Process num set: [1, 2, 3, 4, 5, 10, 20, 40, 80]
Load time: 30 second per one test unit run

Operations per second on 95th percentile. 
![liveness full1_50th_ops_heatmap](https://github.com/openvinotoolkit/openvino/assets/63280507/73e4a4b5-b434-4329-af5d-9518997189d6)

Model runtime (ms) 95 th percentile:
![liveness crop1_95th_runtime_heatmap](https://github.com/openvinotoolkit/openvino/assets/63280507/c05dbeed-3e8a-4aa0-9a74-e71aaafc344b)

---

Hardware parameters:
2x Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
RAM: 512 GB
OS: Ubuntu18.04 (Docker container on RHEL8).
OpenVINO version: 2022.3.0
Threading: TBB
API: C++ API
Plugin: CPU Only

---

OpenVINO build parameters:
```
cmake -DCMAKE_BUILD_TYPE=Release  \
         -DENABLE_INTEL_GPU=OFF  \
         -DENABLE_INTEL_CPU=ON  \
         -DENABLE_INTEL_GNA=OFF  \
         -DENABLE_OV_PDPD_FRONTEND=OFF  \
         -DENABLE_OV_TF_FRONTEND=OFF  \
         -DENABLE_SAMPLES=OFF \
         -DENABLE_PYTHON=OFF \
         -DENABLE_WHEEL=OFF \
         -DENABLE_IR_V7_READER=OFF \
         -DTHREADING=TBB
```

**Comment by sttell** [comment] 2023-06-01 10:54
Model arch: Efficient-Net-B0/B1 based model.

**Comment by wangleis** [comment] 2023-06-02 03:50
@sttell Could you share more detail about your test command? 

- If using benchmark_app, please share the parameters of benchmark_app.
- If using C++ API in your application, please share properties set by set_properties() and compile_model()

Please also share the log of "lscpu" and "lscpu -e" in your docker container.

**Comment by sttell** [comment] 2023-06-02 10:35
Good day, dear @wangleis

We use C++ API in our app. Model usage code example:
```
      / / Create compiled model
      core.set_property("CPU", ov::inference_num_threads(internal_threads_count));
      core.set_property("CPU", ov::num_streams(internal_threads_count));
      core.set_property("CPU", ov::enable_profiling(false));

      std::stringstream onnx_model_ss(std::string(data.begin(), data.end()));
      std::shared_ptr<ngraph::Function> ng_func = ngraph::onnx_import::import_onnx_model(onnx_model_ss);
      std::shared_ptr<ov::Model> model = std::make_shared<InferenceEngine::CNNNetwork>(ng_func)->getFunction();

      ov::preprocess::PrePostProcessor ppp(model);
      model = ppp.build();

      compiled_model_ = std::make_unique<ov::CompiledModel>(
              std::move(core.compile_model(
                      model,
                      "CPU",
                      ov::hint::performance_mode(ov::hint::PerformanceMode::LATENCY)
                      )
              )
      );
```
```
        // Model inference
        ov::InferRequest infer_request = compiled_model_->create_infer_request();

        for ( size_t input_idx = 0; input_idx < inputs.size(); input_idx++ ) {

            auto& input = inputs[input_idx];
            ov::Shape shape(input.size.p, input.size.p + input.size.dims());
            ov::Tensor input_tensor = ov::Tensor{ ov::element::f32, shape, input.data };

            infer_request.set_input_tensor(input_idx, input_tensor);
        }

        return executeRequest(infer_request);
```


CPU info from ```lscpu -e```:
```
Architecture:              x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:                 Little Endian
CPU(s):                       80
On-line CPU(s) list:   0-79
Thread(s) per core:   2
Core(s) per socke:     20
Sockets:                      2
NUMA node(s):          2
Vendor ID:                   GenuineIntel
CPU family:                 6
Model:                         79
Model name:              Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
Stepping:                    1
CPU MHz:                   3600.000
CPU max MHz:           3600,0000
CPU min MHz:            1200,0000
BogoMIPS:                  4389.83
Virtualization:             VT-x
L1d cache:                  32K
L1i cache:                   32K
L2 cache:                   256K
L3 cache:                   51200K
NUMA node0 CPU(s):   0-19,40-59
NUMA node1 CPU(s):   20-39,60-79
Flags:                         fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
```


I also want to note an explicit picture when monitoring performance in ```htop```. CPU is loaded by no more than 1 core with threads count < 40.

**Comment by wangleis** [comment] 2023-06-02 13:47
@sttell The problem is when multiple streams are created to do inference in parallel, there is only one inference request.

Please refer OpenVINO C++ sample https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/benchmark/throughput_benchmark/main.cpp.

Please note 

- If ov::inference_num_threads is greater than number of logical processors, ov::inference_num_threads will be limited to number of logical processors
- If ov::num_streams is greater than limited ov::inference_num_threads, ov::num_streams will be limited to  ov::inference_num_threads

**Comment by sttell** [comment] 2023-06-02 16:34
With ov::num_streams value is 1
![liveness crop1_95th_ops_heatmap](https://github.com/openvinotoolkit/openvino/assets/63280507/5b9408ad-2ac6-460a-9813-eb02a6a36d9a)

**Comment by wangleis** [comment] 2023-06-03 13:01
@sttell If your scenario only processes one image at a time, we recommend set ov::num_stream to 1.

From my understanding, threads count in table is internal_threads_count in code. Could you clarify how to change process numbers in table?

**Comment by sttell** [comment] 2023-06-05 08:20
We are running processes in python. 1st process - load measure. Another processes - test processes.
```
import multiprocessing as mp

processes = list()
load_process = mp.Process(target=get_system_resources_load, args=(use_gpu, ram_used, cpu_percent, gpu_percent, gpu_vram_used, lock, event))
processes.append(load_process)

for _ in range(measure_processes[-1]):
    processes.append(mp.Process(target=test_func, args=(...)))

for process_number, process in enumerate(processes):
    file_name = f'processes_number_{str(process_number).zfill(6)}.csv'
    process.start()
    if process_number == 0:
        # cpu ram load process
        sleep(5)
        save_all_results_to_file(result_path, file_name, cpu_percent, gpu_percent, ram_used, gpu_vram_used, [0], [0])
        cpu_percent[:] = []
        ram_used[:] = []
        operations_runtime[:] = []
        continue

    if process_number in measure_processes:
        logger.info(f'{process_number} processes running in parallel. '
                    f'Next processes start in >>> {test_running_time} seconds')
                    
        # while current process sleep the test runs on the required number of processes
        time.sleep(test_running_time)

        # save results
        lock.acquire()
        save_all_results_to_file(result_path, file_name, cpu_percent, gpu_percent, ram_used, gpu_vram_used,
                                 operations_runtime, function_ram_usage)
        cpu_percent[:] = []
        gpu_percent[:] = []

        ram_used[:] = []
        operations_runtime[:] = []
        function_ram_usage[:] = []
        lock.release()

event.set()  # stop all processes
for p in processes:
    p.join()
```

**Comment by sttell** [comment] 2023-06-05 13:05
@wangleis 
What do you mean? If I'll use the ```subprocess``` library will it satisfy your request?

**Comment by wangleis** [comment] 2023-06-06 09:24
@sttell OpenVINO Runtime is library and run inference with multiple threads which is available in one process.  

So if your application work with multiple processes, please ensure allocate enough CPU cores to process running OpenVINO Runtime. 

I'm not a python expert and not sure which python library will suffice for your application.

**Comment by wangleis** [comment] 2023-06-12 07:11
@sttell Could you use Linux `numactl` command instead of the python library to limit application's CPU processors and verify OpenVINO performance using all application's CPU processors?

**Comment by avitial** [comment] 2023-06-26 21:21
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask any questions related to this topic.

**Closed by avitial** 2023-06-26 21:21 UTC
Labels: category: CPU, support_request
