### ISSUE TITLE
Visitor API is not supported in v0::NullNode NullNode_187 () -> (dynamic...)

### ISSUE THREAD

**Issue by Raise-me-up** [openvinotoolkit/openvino#13605] opened 2022-10-24 04:00 UTC
OpenVINO runtime version:       2022.2.0-7713-af16ea1d79a-releases/2022/2
Model Optimizer version:        2022.2.0-7713-af16ea1d79a-releases/2022/2
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  Check 'node->visit_attributes(visitor)' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\src\pass\serialize.cpp:926:
Visitor API is not supported in v0::NullNode NullNode_187 () -> (dynamic...)

[ ERROR ]  Traceback (most recent call last):
  File "D:\workspace\openvino\openvino_env\Lib\site-packages\openvino\tools\mo\main.py", line 533, in main
    ret_code = driver(argv)
  File "D:\workspace\openvino\openvino_env\Lib\site-packages\openvino\tools\mo\main.py", line 493, in driver
    ret_res = moc_emit_ir(ngraph_function, argv)
  File "D:\workspace\openvino\openvino_env\lib\site-packages\openvino\tools\mo\moc_frontend\serialize.py", line 45, in moc_emit_ir
    serialize(ngraph_function, (orig_model_name + ".xml").encode('utf-8'), (orig_model_name + ".bin").encode('utf-8'))
RuntimeError: Check 'node->visit_attributes(visitor)' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\core\src\pass\serialize.cpp:926:
Visitor API is not supported in v0::NullNode NullNode_187 () -> (dynamic...)

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

What is the problem? Anyone help please?

**Comment by brmarkus** [comment] 2022-10-24 05:07
Can you provide more information about your environment (HW and SW), please?
You might want to share your model files (or a simplified version) to allow reproduction and deeper analysis of the problem.

**Comment by Raise-me-up** [comment] 2022-10-24 06:15
> Can you provide more information about your environment (HW and SW), please? You might want to share your model files (or a simplified version) to allow reproduction and deeper analysis of the problem.

HW:  11th Gen Intel(R) Core(TM) i7-1165G7
SW:   Windows 10 Home 21H2 
         OpenVINO 2022.2.0

The model is in the attachment. Please check and help, thanks!

[PDCCRN.zip](https://github.com/openvinotoolkit/openvino/files/9849176/PDCCRN.zip)

**Comment by Raise-me-up** [comment] 2022-10-24 06:26
> Can you provide more information about your environment (HW and SW), please? You might want to share your model files (or a simplified version) to allow reproduction and deeper analysis of the problem.

The command line I use is as follows:
mo --input_model PDCCRN.onnx --input "input_0[-1 2 256 -1],input_1[192]"  --output_dir ./

**Comment by andrei-kochin** [comment] 2022-10-24 10:54
Hello @Raise-me-up ,

Thanks for reaching OpenVINO!
I recall that similar issue was fixed in code #12797 not sure if it is related but looks like on master the issue is not present:

```
Model Optimizer version:        2022.3.0-8242-e8c8ad19f43
[ SUCCESS ] Total execution time: 1.54 seconds.
Find more information about API v2.0 and IR v11 at https://docs.openvino.ai
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: C:\Users\akochin\Downloads\PDCCRN.xml
[ SUCCESS ] BIN file: C:\Users\akochin\Downloads\PDCCRN.bin
```

Could you please try latest master?

Best regars,
Andrei

**Comment by andrei-kochin** [comment] 2022-10-25 19:37
@Raise-me-up sure!
Please kindly provide some protobuf error snippets you face with during you build so we can guide you?

CC @ilya-lavrenov

**Comment by Raise-me-up** [comment] 2022-10-26 01:31
> @Raise-me-up sure! Please kindly provide some protobuf error snippets you face with during you build so we can guide you?
> 
> CC @ilya-lavrenov

The error messages are as follows:

“D:\workspace\openvino\openvino-master\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
       “D:\workspace\openvino\openvino-master\build\src\bindings\python\wheel\ie_wheel.vcxproj”(默认目标) (4) ->
       “D:\workspace\openvino\openvino-master\build\ov_frontends.vcxproj”(默认目标) (11) ->
       “D:\workspace\openvino\openvino-master\build\src\frontends\paddle\src\openvino_paddle_frontend.vcxproj”(默认目标) (36) ->
       “D:\workspace\openvino\openvino-master\build\src\frontends\common\shutdown_protobuf\ov_protobuf_shutdown.vcxproj”(默认目 标) (1
       03) ->
       (ClCompile 目标) ->
         D:/workspace/openvino/openvino-master/thirdparty/protobuf/protobuf/src\google/protobuf/stubs/common.h(46,10): fatal erro
       r C1083: 无法打开包括文件: “absl/strings/string_view.h”: No such file or directory [D:\workspace\openvino\openvino-master\build\sr
       c\frontends\common\shutdown_protobuf\ov_protobuf_shutdown.vcxproj]


       “D:\workspace\openvino\openvino-master\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
       “D:\workspace\openvino\openvino-master\build\src\bindings\python\wheel\ie_wheel.vcxproj”(默认目标) (4) ->
       “D:\workspace\openvino\openvino-master\build\ov_frontends.vcxproj”(默认目标) (11) ->
       “D:\workspace\openvino\openvino-master\build\src\frontends\onnx\frontend\openvino_onnx_frontend.vcxproj”(默认目标) (41) ->
       “D:\workspace\openvino\openvino-master\build\thirdparty\protobuf\protobuf\cmake\libprotobuf-lite.vcxproj”(默认目标) (89) ->
         D:/workspace/openvino/openvino-master/thirdparty/protobuf/protobuf/src\google/protobuf/arena_align.h(91,69): error C4146
       : 一元负运算符应用于无符号类型，结果仍为无符号类型 [D:\workspace\openvino\openvino-master\build\thirdparty\protobuf\protobuf\cmake\libprotobuf-lit
       e.vcxproj]
         D:/workspace/openvino/openvino-master/thirdparty/protobuf/protobuf/src\google/protobuf/arena_align.h(125,68): error C414
       6: 一元负运算符应用于无符号类型，结果仍为无符号类型 [D:\workspace\openvino\openvino-master\build\thirdparty\protobuf\protobuf\cmake\libprotobuf-li
       te.vcxproj]


       “D:\workspace\openvino\openvino-master\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
       “D:\workspace\openvino\openvino-master\build\src\bindings\python\wheel\ie_wheel.vcxproj”(默认目标) (4) ->
       “D:\workspace\openvino\openvino-master\build\ov_frontends.vcxproj”(默认目标) (11) ->
       “D:\workspace\openvino\openvino-master\build\src\frontends\onnx\frontend\openvino_onnx_frontend.vcxproj”(默认目标) (41) ->
       “D:\workspace\openvino\openvino-master\build\thirdparty\onnx\onnx\onnx.vcxproj”(默认目标) (90) ->
       “D:\workspace\openvino\openvino-master\build\thirdparty\onnx\onnx\onnx_proto.vcxproj”(默认目标) (91) ->
       “D:\workspace\openvino\openvino-master\build\thirdparty\onnx\onnx\gen_onnx_data_proto.vcxproj”(默认目标) (92) ->
       “D:\workspace\openvino\openvino-master\build\thirdparty\onnx\onnx\gen_onnx_proto.vcxproj”(默认目标) (94) ->
       “D:\workspace\openvino\openvino-master\build\thirdparty\protobuf\protobuf\cmake\protoc.vcxproj”(默认目标) (95) ->
       “D:\workspace\openvino\openvino-master\build\thirdparty\protobuf\protobuf\cmake\libprotobuf.vcxproj”(默认目标) (98) ->
         D:\workspace\openvino\openvino-master\thirdparty\protobuf\protobuf\src\google/protobuf/arena_align.h(91,69): error C4146
       : 一元负运算符应用于无符号类型，结果仍为无符号类型 [D:\workspace\openvino\openvino-master\build\thirdparty\protobuf\protobuf\cmake\libprotobuf.vcx
       proj]
         D:\workspace\openvino\openvino-master\thirdparty\protobuf\protobuf\src\google/protobuf/arena_align.h(125,68): error C414
       6: 一元负运算符应用于无符号类型，结果仍为无符号类型 [D:\workspace\openvino\openvino-master\build\thirdparty\protobuf\protobuf\cmake\libprotobuf.vc
       xproj]

    1134 个警告
    5 个错误

**Comment by ilyachur** [comment] 2022-10-26 05:18
@Raise-me-up Could you provide the machine configuration and VS version what you use?

Also OpenVINO can use system protobuf. It means that you can install protobuf on your system and OpenVINO will use it

**Comment by Raise-me-up** [comment] 2022-10-26 06:10
> @Raise-me-up Could you provide the machine configuration and VS version what you use?
> 
> Also OpenVINO can use system protobuf. It means that you can install protobuf on your system and OpenVINO will use it

Machine:  

HW: 11th Gen Intel(R) Core(TM) i7-1165G7
SW: Windows 10 Home 21H2

VS:  VS 2019 Community

Cmake: 3.24.2 

Can the protobuf part inside the openvino source codes  be empty?

**Comment by ilyachur** [comment] 2022-10-26 07:02
> Can the protobuf part inside the openvino source codes be empty?

No it cannot, you need to update submodulies before the build in order to avoid empty submodules.

But OpenVINO also won't use this protobuf version if you build it with system protobuf.

**Comment by Raise-me-up** [comment] 2022-10-26 07:24
> > Can the protobuf part inside the openvino source codes be empty?
> 
> No it cannot, you need to update submodulies before the build in order to avoid empty submodules.
> 
> But OpenVINO also won't use this protobuf version if you build it with system protobuf.

So, how can I use the system protobuf to build with the presence of the 3rd party protobuf?

Is there any wiki?

**Comment by ilyachur** [comment] 2022-10-26 08:18
Yes we have a CMAKE option: `ENABLE_SYSTEM_PROTOBUF`
It presented on this wiki page: https://github.com/openvinotoolkit/openvino/wiki/CMakeOptionsForCustomCompilation

**Comment by Raise-me-up** [comment] 2022-10-26 09:53
> Yes we have a CMAKE option: `ENABLE_SYSTEM_PROTOBUF` It presented on this wiki page: https://github.com/openvinotoolkit/openvino/wiki/CMakeOptionsForCustomCompilation

Sadly, we have tried the method you mentioned above, which produces 64 error messages. 

Part of error messages is as follows:

D:\workspace\openvino\openvino-master\bin\intel64\Release\openvino_paddle_frontend.dll : fatal error LNK1120: 2 个无法解 析的外部
       命令 [D:\workspace\openvino\openvino-master\build\src\frontends\paddle\src\openvino_paddle_frontend.vcxproj]


       “D:\workspace\openvino\openvino-master\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
       “D:\workspace\openvino\openvino-master\build\src\bindings\python\wheel\ie_wheel.vcxproj”(默认目标) (8) ->
       “D:\workspace\openvino\openvino-master\build\ov_frontends.vcxproj”(默认目标) (13) ->
       “D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensorflow_frontend.vcxproj”(默认目标) (38)
        ->
         variable.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_str
       ing<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_stri
       ng" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std
       @@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensor
       flow_frontend.vcxproj]
         step_stats.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_s
       tring<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_st
       ring" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@s
       td@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tens
       orflow_frontend.vcxproj]
         summary.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_stri
       ng<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_strin
       g" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@
       @V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensorf
       low_frontend.vcxproj]
         tensor.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_strin
       g<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string
       " (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@
       V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensorfl
       ow_frontend.vcxproj]
         tensor_shape.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic
       _string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_
       string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D
       @std@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_te
       nsorflow_frontend.vcxproj]
         op_def.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_strin
       g<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string
       " (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@
       V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensorfl
       ow_frontend.vcxproj]
         reader_base.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_
       string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_s
       tring" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@
       std@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_ten
       sorflow_frontend.vcxproj]
         remote_fused_graph_execute_info.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstruct
       ed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::f
       ixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_strin
       g@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorf
       low\src\openvino_tensorflow_frontend.vcxproj]
         resource_handle.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::ba
       sic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_emp
       ty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_trait
       s@D@std@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino
       _tensorflow_frontend.vcxproj]
         kernel_def.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_s
       tring<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_st
       ring" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@s
       td@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tens
       orflow_frontend.vcxproj]
         log_memory.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_s
       tring<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_st
       ring" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@s
       td@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tens
       orflow_frontend.vcxproj]
         model.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string
       <char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string"
        (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V
       ?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensorflo
       w_frontend.vcxproj]
         node_def.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_str
       ing<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_stri
       ng" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std
       @@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensor
       flow_frontend.vcxproj]
         cost_graph.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_s
       tring<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_st
       ring" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@s
       td@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tens
       orflow_frontend.vcxproj]
         device_attributes.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::
       basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_e
       mpty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_tra
       its@D@std@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvi
       no_tensorflow_frontend.vcxproj]
         function.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_str
       ing<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_stri
       ng" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std
       @@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensor
       flow_frontend.vcxproj]
         graph_transfer_info.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std
       ::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address
       _empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_t
       raits@D@std@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\open
       vino_tensorflow_frontend.vcxproj]
         decoder_proto.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_s
       tring<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_st
       ring" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@s
       td@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tens
       orflow_frontend.vcxproj]
         allocation_description.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class
       std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_addr
       ess_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$cha
       r_traits@D@std@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\o
       penvino_tensorflow_frontend.vcxproj]
         api_def.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_stri
       ng<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_strin
       g" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@
       @V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensorf
       low_frontend.vcxproj]
         attr_value.pb.obj : error LNK2001: 无法解析的外部符号 "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_s
       tring<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_st
       ring" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@s
       td@@V?$allocator@D@2@@std@@@123@A) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tens
       orflow_frontend.vcxproj]
         step_stats.pb.obj : error LNK2001: 无法解析的外部符号 "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGlo
       balEmptyTable@internal@protobuf@google@@3QBQEAXB) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\sr
       c\openvino_tensorflow_frontend.vcxproj]
         decoder_proto.obj : error LNK2001: 无法解析的外部符号 "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGlo
       balEmptyTable@internal@protobuf@google@@3QBQEAXB) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\sr
       c\openvino_tensorflow_frontend.vcxproj]
         attr_value.pb.obj : error LNK2001: 无法解析的外部符号 "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGlo
       balEmptyTable@internal@protobuf@google@@3QBQEAXB) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\sr
       c\openvino_tensorflow_frontend.vcxproj]
         function.pb.obj : error LNK2001: 无法解析的外部符号 "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGloba
       lEmptyTable@internal@protobuf@google@@3QBQEAXB) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\
       openvino_tensorflow_frontend.vcxproj]
         node_def.pb.obj : error LNK2001: 无法解析的外部符号 "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGloba
       lEmptyTable@internal@protobuf@google@@3QBQEAXB) [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\
       openvino_tensorflow_frontend.vcxproj]
         attr_value.pb.obj : error LNK2019: 无法解析的外部符号 "private: static char const * const * const google::protobuf::FieldDescript
       or::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQEBDB)，函数 "public: class std::basic_string<char,s
       truct std::char_traits<char>,class std::allocator<char> > const & __cdecl google::protobuf::MapKey::GetStringValue(void)co
       nst " (?GetStringValue@MapKey@protobuf@google@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) 中 引
       用了该符号 [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensorflow_frontend.vcxproj]
         function.pb.obj : error LNK2001: 无法解析的外部符号 "private: static char const * const * const google::protobuf::FieldDescriptor
       ::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQEBDB) [D:\workspace\openvino\openvino-master\build
       \src\frontends\tensorflow\src\openvino_tensorflow_frontend.vcxproj]
         node_def.pb.obj : error LNK2001: 无法解析的外部符号 "private: static char const * const * const google::protobuf::FieldDescriptor
       ::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQEBDB) [D:\workspace\openvino\openvino-master\build
       \src\frontends\tensorflow\src\openvino_tensorflow_frontend.vcxproj]
         step_stats.pb.obj : error LNK2001: 无法解析的外部符号 "private: static char const * const * const google::protobuf::FieldDescript
       or::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQEBDB) [D:\workspace\openvino\openvino-master\bui
       ld\src\frontends\tensorflow\src\openvino_tensorflow_frontend.vcxproj]
         D:\workspace\openvino\openvino-master\bin\intel64\Release\openvino_tensorflow_fe.dll : fatal error LNK1120: 3 个无法解析 的外部命令
        [D:\workspace\openvino\openvino-master\build\src\frontends\tensorflow\src\openvino_tensorflow_frontend.vcxproj]

    1139 个警告
    64 个错误

**Comment by ilyachur** [comment] 2022-10-26 17:29
@Raise-me-up you got the error that protobuf symbols weren't found in libraries. You need to add system protobuf to the PATH in order to use it with OpenVINO

**Comment by Raise-me-up** [comment] 2022-10-27 03:41
> @Raise-me-up you got the error that protobuf symbols weren't found in libraries. You need to add system protobuf to the PATH in order to use it with OpenVINO

Sadly, it doesn't work, and it is the same error. Thanks for your reply! I have decided to give up the building of the whole source codes. However, I find the MO part is built successfully, and it can be installed for use reluctantly.

**Comment by ilyachur** [comment] 2022-10-27 04:02
So I see that you get errors for the TF now. 
If ONNX frontend and python API were built I think yes it should be enough to run MO and  convert your model.

**Comment by Raise-me-up** [comment] 2022-10-27 06:07
> So I see that you get errors for the TF now. If ONNX frontend and python API were built I think yes it should be enough to run MO and convert your model.

OK. Thanks for your precious guide!

**Comment by Raise-me-up** [comment] 2022-11-04 01:35
> @Raise-me-up have you managed to convert the model at last?
> 
> Do you need more guidance or help?

I think the partial build of the source codes can meet my demand at present. So, thank you for your kind help.

**Closed** 2022-11-04 01:35 UTC
Labels: category: MO, support_request
