### ISSUE TITLE
[urgent] Segmentation fault core dumped error while inference on Intel Arria 10 GX with PAC card using python

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [openvinotoolkit/openvino#4115] opened 2021-02-01 13:35 UTC
Hi 
I have Intel Arria 10GX with PAC card. I have setup all the pre- requisites and able to see my device on aocl diagnose. 

When I am trying to inference using cpp code I am able to do  that but with python while loading network to device load_network() I meet this error.

I tried  with openvino 2020.3.287 and 341 but no luck.
I am attaching the screenshot please help me with this. 
![IMG_20210201_185050](https://user-images.githubusercontent.com/46083296/106465791-76872980-64c0-11eb-94f5-0e88c417aff5.jpg)

**Comment by SAIVENKATARAJU** [comment] 2021-02-02 07:45
Hi 
I tried to debug segmentation fault using gdb. And I got the error form mkl library it seems. Can you please check, I have provided screenshot.
![Uploading intel_gdb_error.png…]()

**Comment by maxlytkin** [comment] 2021-02-02 15:10
@SAIVENKATARAJU 
Are you able to run this Python sample within the same environment on CPU device only?

**Comment by SAIVENKATARAJU** [comment] 2021-02-02 15:11
Hi @maxlytkin 
Yes I am able to inference using cpu only on same environment

**Comment by maxlytkin** [comment] 2021-02-02 15:33
@SAIVENKATARAJU 
Can you please re-attach your screenshot from gdb? Seems like it failed to upload.

**Comment by SAIVENKATARAJU** [comment] 2021-02-02 15:34
![intel_gdb_error](https://user-images.githubusercontent.com/46083296/106622991-2aa8b300-659a-11eb-87dd-82b68574b038.png)
Please find the screenshot

**Comment by maxlytkin** [comment] 2021-02-03 10:30
@SAIVENKATARAJU 
I'm not able to reproduce this from my end, however, I'm testing this on Arria 10 FPGA SG2, not on Arria 10 GX PAC.
Please have a chance to try it on OpenVINO 2020.4 version and with the same squeezenet1.1.xml model, which is utilized in this [verification example](https://docs.openvinotoolkit.org/2020.4/openvino_docs_install_guides_PAC_Configure.html#use_the_intel_distribution_of_openvino_toolkit) 

> root@user-S2600WFT:/opt/intel/openvino_2020.3.341/inference_engine/samples/python/classification_sample# source /home/user/init_openvino.sh 
> INTELFPGAOCLSDKROOT is set to /opt/altera/aocl-pro-rte/aclrte-linux64. Using that.
> aoc was not found, but aocl was found. Assuming only RTE is installed.
> AOCL_BOARD_PACKAGE_ROOT is set to /opt/intel/openvino/bitstreams/a10_vision_design_sg2_bitstreams/BSP/a10_1150_sg2. Using that.
> Adding /opt/altera/aocl-pro-rte/aclrte-linux64/bin to PATH
> Adding /opt/altera/aocl-pro-rte/aclrte-linux64/linux64/lib to LD_LIBRARY_PATH
> Adding /opt/altera/aocl-pro-rte/aclrte-linux64/host/linux64/lib to LD_LIBRARY_PATH
> Adding /opt/intel/openvino/bitstreams/a10_vision_design_sg2_bitstreams/BSP/a10_1150_sg2/linux64/lib to LD_LIBRARY_PATH
> [setupvars.sh] OpenVINO environment initialized
> root@user-S2600WFT:/opt/intel/openvino_2020.3.341/inference_engine/samples/python/classification_sample# python3 classification_sample.py -i /opt/intel/openvino_2020.3.341/deployment_tools/demo/car.png -m ~/openvino_models/ir/public/squeezenet1.1/FP16/squeezenet1.1.xml -d HETERO:FPGA,CPU
> [ INFO ] Creating Inference Engine
> [ INFO ] Loading network files:
> 	/root/openvino_models/ir/public/squeezenet1.1/FP16/squeezenet1.1.xml
> 	/root/openvino_models/ir/public/squeezenet1.1/FP16/squeezenet1.1.bin
> [ INFO ] Preparing input blobs
> [ WARNING ] Image /opt/intel/openvino_2020.3.341/deployment_tools/demo/car.png is resized from (259, 787) to (227, 227)
> [ INFO ] Batch size is 1
> [ INFO ] Loading model to the plugin
> [ INFO ] Starting inference in synchronous mode
> [ INFO ] Processing output blob
> [ INFO ] Top 10 results: 
> Image /opt/intel/openvino_2020.3.341/deployment_tools/demo/car.png
> classid probability
>   817    0.6841186
>   479     0.1841280
>   511    0.0911500
>   436    0.0203383
>   751    0.0072518
>   656    0.0045381
>   717    0.0025857
>   581    0.0018624
>   468    0.0014280
>   661    0.0007643
> [ INFO ] This sample is an API example, for any performance measurements please use the dedicated benchmark_app tool
> root@user-S2600WFT:/opt/intel/openvino_2020.3.341/inference_engine/samples/python/classification_sample#

**Comment by SAIVENKATARAJU** [comment] 2021-02-03 11:07
I tries with openvino 2020.4 but no luck surprisingly it's works on CPP example.

**Comment by maxlytkin** [comment] 2021-02-04 13:01
@SAIVENKATARAJU 
Please check the following topic and try to apply a workaround from the comment https://github.com/ContinuumIO/anaconda-issues/issues/9606#issuecomment-397463319

**Comment by maxlytkin** [comment] 2021-02-17 21:39
Closing, please re-open if further assistance is needed.

**Closed by maxlytkin** 2021-02-17 21:39 UTC
