### ISSUE TITLE
RuntimeError: Failed to find plugins.xml file

### ISSUE THREAD

**Issue by Json0926** [openvinotoolkit/openvino#15694] opened 2023-02-14 02:32 UTC
I can normally run the classification_sample_async.py in the demo , but after I package it into exe through pyinstaller, the runtimeerror problem will occur：

from openvino.runtime import Core
ie = Core()

[ INFO ] Creating OpenVINO Runtime Core
Traceback (most recent call last):
  File "classification_sample_async.py", line 131, in <module>
  File "classification_sample_async.py", line 63, in main
RuntimeError: Failed to find plugins.xml file
[16308] Failed to execute script 'classification_sample_async' due to unhandled exception!

**Comment by ilya-lavrenov** [comment] 2023-02-14 08:18
Hi @Json0926 
Does the pyinstaller package plugins.xml file? 
Could you please provide steps to reproduce the issue?

**Comment by Json0926** [comment] 2023-02-14 11:58
I use openvino and onnx to do inference, the code is as follows:
![WechatIMG799](https://user-images.githubusercontent.com/19401269/218707577-f993f661-8636-4e23-a8a3-32e6c81c73f8.jpeg)

It can be used normally in the py file, but after being packaged into exe through pyinstaller, an error will be reported：
<img width="628" alt="image" src="https://user-images.githubusercontent.com/19401269/218722479-84df79f1-9429-469e-a26c-8a09c8b22742.png">

package command：pyinstaller -F/D server.py --clean
After packaging, there are only these in the openvino folder
![8001676374584_ pic](https://user-images.githubusercontent.com/19401269/218726503-738a349f-2e7c-41aa-a173-fe5f784b3d42.jpg)
![8011676374584_ pic](https://user-images.githubusercontent.com/19401269/218726702-f62cc1ba-2093-4e30-accb-6c9fc98c7d02.jpg)
I don't know how to package plugins.xml

openvino：2022.3.0
the server.exe runs normally and interrupts at ie=Core().
The error is: RuntimeError: Failed to find plugins.xml file

**Comment by vurusovs** [comment] 2023-02-15 06:58
@Json0926 hello!
First of all, thank you for using OpenVINO!

Because `pyinstaller` can't determine `plugins.xml` as dependency, it won't be added by default. You need to configure `pyinstaller` to add it to correct place. For example:
```
pyinstaller --add-data "/path/to/plugins.xml:/path/where/it/should/be" -F/D server.py --clean
```
Or you may update`datas` field in `server.spec` file
You may find more details in https://pyinstaller.org/en/stable/usage.html and https://pyinstaller.org/en/stable/spec-files.html#using-spec-files

Please, note that `plugins.xml` should be placed in same folder where `openvino.dll` is placed

**Comment by Json0926** [comment] 2023-02-15 08:09
Do I need to pack all these files into the same folder where openvino.dll is located?
![502221676448061_ pic](https://user-images.githubusercontent.com/19401269/218967732-1f4a9a55-8822-491e-a682-f5ea09cff46f.jpg)

**Comment by vurusovs** [comment] 2023-02-21 11:14
@Json0926 I'm closing issue as resolved. Feel free to reopen if you have any issues

**Closed by vurusovs** 2023-02-21 11:14 UTC
Labels: question, category: inference, support_request

**Comment by mqlllorca** [comment] 2023-06-22 15:16
Hi @Json0926 could you share what path did you use to place the xml inside the exe? I'm new to pyinstaller and don't really understand where it needs to be.
