### ISSUE TITLE
Stage node onnx::Cast_3092 (Greater) types check error: input #0 has type S32, but one of [FP16] is expected; IR Conversion Error

### ISSUE THREAD

**Issue by Simardeep27** [openvinotoolkit/openvino#16105] opened 2023-03-05 21:15 UTC
I am trying to convert a custom onnx [model ](https://drive.google.com/drive/folders/1YpecpADpNnhR6TzQwHjXCAdmcVzuheO4?usp=sharing)to OpenVino IR. The conversion is successful, however the model gives the following error while running on MYRIAD device:

super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: onnx::Cast_3092 of type Greater: [ GENERAL_ERROR ]
C:\j\workspace\private-ci\ie\build-windows-vs2019@3\b\repos\openvino\src\plugins\intel_myriad\graph_transformer\src\stages\eltwise.cpp:164 Stage node onnx::Cast_3092 (Greater) types check error: input #0 has type S32, but one of [FP16] is expected

I inspected the code through which this error is being generated, it is a basic comparison of two tensors whose output is of Bool type (which is the expected data type), so why does MYRIAD device expects FP16 data type for the same? Is there any method to solve this?

**Comment by Wan-Intel** [comment] 2023-03-16 04:11
VPU Plugin supports FP16 model format.
Please refer to [Supported Model Formats](https://docs.openvino.ai/2022.3/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html#supported-model-formats) in [Supported Devices](https://docs.openvino.ai/2022.3/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html#supported-devices).

**Comment by Wan-Intel** [comment] 2023-03-24 01:17
Hi Simardeep27,
Just wanted to follow up and see if the issue has been resolved.

**Comment by Simardeep27** [comment] 2023-03-24 04:59
Hi @Wan-Intel, I was able to convert the model by modifying the xml file and adding Convert layers where necessary. That issue was resolved, but when I am trying to load the model on MYRIAD, the process freezes, the model fails to load for 6-7 hours.  What can the reason be for this issue? Could it be due to the complexity of the model?

**Comment by Wan-Intel** [comment] 2023-03-27 07:41
Hi Simardeep27,
When loading the model on the CPU with [Benchmark C++ Tool](https://docs.openvino.ai/2022.3/openvino_inference_engine_samples_benchmark_app_README.html), the process freezes too.

We'll further investigate this and update as soon as possible.

**Comment by Simardeep27** [comment] 2023-03-27 08:05
Hi @Wan-Intel, Thanks that would be really helpful. Also, I was able to remove this bad allocation error by reducing the input size. The model loads on CPU but freezes for MYRIAD

**Comment by avitial** [comment] 2023-04-27 21:37
@Simardeep27 looks like you found the workaround to include a convert operations in model. Does the model (modified with convert operations) load on CPU/GPU? And does the model with smaller input size also load on GPU? 

The freeze/hang of Myriad might be caused by long execution of model compilation (large amount of data), and the fact that this network may not be supported by the Myriad plugin.

**Comment by avitial** [comment] 2023-05-03 20:36
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Closed by avitial** 2023-05-03 20:36 UTC
Labels: category: VPU, support_request, PSE
