### ISSUE TITLE
convert_annotation.py not found in macos openvino installer

### ISSUE THREAD

**Issue by jnbli** [openvinotoolkit/openvino#3114] opened 2020-11-12 23:47 UTC
##### System information (version)
- OpenVINO => 2021.1.11
- Operating System / Platform => macOS 10.15.7

##### Detailed description
convert_annotation.py does not exist within /opt/intel folder

##### Steps to reproduce
1. Follow the tutorial: https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_macos.html
and install OpenVino using the installer
2. Search for "convert_annotation.py"

**Comment by eaidova** [comment] 2020-11-13 08:01
@jnbli, sirry for inconvinience, but it is not a bug, convert_annotation.py was deprecated and removed many releases ago. It was replaced by command convert_annotation (like accuracy_check), which available after accuracy checker installation.
see https://docs.openvinotoolkit.org/latest/omz_tools_accuracy_checker_accuracy_checker_annotation_converters_README.html for details

**Comment by jgespino** [comment] 2020-11-20 15:59
Closing, please re-open if additional assistance is needed.

**Closed by jgespino** 2020-11-20 15:59 UTC
Labels: category: tools, support_request
