### ISSUE TITLE
[Bug] cpu_throughput_streams from 1 to 2 or other positive number（>1）openvino can't load the model

### ISSUE THREAD

**Issue by duhuajiang** [openvinotoolkit/openvino#9293] opened 2021-12-18 09:32 UTC
OpenVINO = 2021.4
Operating System / Platform = linux

when I set the cpu_throughput_streams=1, openvino can load the model and run, and get the right result, but when I change the cpu_throughput_streams from 1 to  2 or other positive number（>1）,openvino can't load the model, so can't get result.
the error is: mkldnn_memory.h:120  can not get the memory.

so I debug into the function LoadNetwork, I find the node（Canstant -> i32{0}）,can not generate with the mkldnn_input_node. so i read the code of  MKLDNNInputNode::MKLDNNInputNode(), find the lambda exp:

```
auto cloneBlob = [&, this] () {
        MKLDNNMemory memory{ getEngine() };
        memory.Create(memDesc, constOp->get_data_ptr());

        MKLDNNMemoryPtr ptr = MKLDNNMemoryPtr(new MKLDNNMemory(getEngine()));
        ptr->Create(memDesc);
        ptr->SetData(memory);

        return ptr;
    };  
```
the ptr->SetData(memory) throw the exception.

because function SetData(memory), need get handle to data, but function  Create with i32{0},did not build the data, so setData error.

solution: I change the lambda to:

```
auto cloneBlob = [&, this] () {
        MKLDNNMemoryPtr ptr = MKLDNNMemoryPtr(new MKLDNNMemory(getEngine()));
        ptr->Create(memDesc, constOp->get_data_ptr());
        return ptr;
    };  
```
so  the vino can load model and run, get the right results.

**Comment by Iffa-Meah** [comment] 2021-12-22 01:59
According to the [CPU Plugin documentation](https://docs.openvino.ai/latest/openvino_docs_IE_DG_supported_plugins_CPU.html#supported-configuration-parameters), it is emphasized that **all parameters must be set with the InferenceEngine::Core::LoadNetwork() method.**

I tested this functionality with Benchmark C++ Tool using AlexNet model,with different "CPU_THROUGHPUT_STREAMS" values using the parameter -nstreams.

The source code of the Benchmark C++ Tool depicts the assignment of CPU_THROUGHPUT_STREAMS using nstreams which is then **fed to the LoadNetwork() method**.

![srcCode](https://user-images.githubusercontent.com/79643476/147022118-b050dc54-4e7e-431b-8682-917de4738032.png)

No issues were found since this parameter is used according to the requirement.
![streams1](https://user-images.githubusercontent.com/79643476/147022178-bd5888fe-8ab1-4f5d-9e94-a934e371f59b.png)
![streams5](https://user-images.githubusercontent.com/79643476/147022186-b4e12c18-9aaf-4889-90bd-335afff3f346.png)

**Comment by duhuajiang** [comment] 2021-12-22 04:02
@Iffa-Meah Thanks Reply！
This is my code, same like the code in doc, simply like:
`InferenceEngine::CNNNetwork network = ie.ReadNetwork(opv_model_path);
 InferenceEngine::ExecutableNetwork executable_network = ie.LoadNetwork(network, _device_name, plugin_conf);`

in your test case, the network did not have the node **Canstant -> i32{0}**, so did not have exception, you can test the **MKLDNNInputNode::MKLDNNInputNode** use node  **Canstant -> i32{0}**, you can get same error, because the lambda expr did not consider this case. by the way, I can't upload the model， the model is belong the company

**Comment by duhuajiang** [comment] 2021-12-22 08:55
@Iffa-Meah here, show more info!
when node is Constant Constant_xxxx () -> (i32{0}),
in function: MKLDNNInputNode::MKLDNNInputNode() -> cloneBlobIfRequired()
```
void MKLDNNInputNode::cloneBlobIfRequired() {
MKLDNNDims dims(constOp->get_shape().empty() ? ngraph::Shape(1, 1) : constOp->get_shape());
const auto prec = convertPrecision(constOp->get_element_type());
const size_t size = dims.size();
MKLDNNMemoryDesc memDesc(dims, MKLDNNExtensionUtils::IEPrecisionToDataType(prec));
auto cloneBlob = [&, this] () {
    MKLDNNMemory memory{ getEngine() };
    memory.Create(memDesc, constOp->get_data_ptr());
    MKLDNNMemoryPtr ptr = MKLDNNMemoryPtr(new MKLDNNMemory(getEngine()));
    std::cout << "MKLDNNInputNode constOp: " << constOp << std::endl;
    ptr->Create(memDesc);
    ptr->SetData(memory);
    return ptr;
};
if (weightCache) {
    MKLDNNMemoryPtr ptr = *weightCache->findOrCreate(blobKey(), cloneBlob);
    memoryPtr = std::const_pointer_cast<const MKLDNNMemory>(ptr);
}
}
```
**because the CPU_THROUGHPUT_STREAMS>1, so the weightCache != nullptr, then use lambda exptr -> cloneBlob.**
then next call chains as follow：
```
in function ptr->Create(memDesc); (path: inference-engine/src/mkldnn_plugin/mkldnn_memory.cpp)
->new memory(desc, eng): (path: inference-engine/thirdparty/mkl-dnn/include/dnnl.hpp)
->status_t dnnl_memory_create: (path: inference-engine/thirdparty/mkl-dnn/src/common/memory.cpp)
->dnnl_memory::dnnl_memory(): (path: inference-engine/thirdparty/mkl-dnn/src/common/memory.cpp)
->cpu_engine_t::create_memory_storage(): (path: inference-engine/thirdparty/mkl-dnn/src/cpu/cpu_engine.cpp)
-> memory_storage_t::init():  (path: inference-engine/thirdparty/mkl-dnn/src/common/memory_storage.cpp)
```
the code of init function is:
```
status_t memory_storage_t::init(unsigned flags, size_t size, void *handle) {
    assert(flags & (memory_flags_t::alloc | memory_flags_t::use_runtime_ptr));
    if (flags & memory_flags_t::alloc) {
        assert(!handle);
        **if (size == 0) return status::success;**
        return init_allocate(size);
    }
    assert(flags & memory_flags_t::use_runtime_ptr);
    return **set_data_handle(handle);**
}
```
when size==0, **directly return, not set the data_handle,** so when in lambda cloneBlob, the ptr-SetData(), **the SetData need get the data_handle. but it is nullptr, so get a exception**

```
auto cloneBlob = [&, this] () {
        MKLDNNMemory memory{ getEngine() };
        memory.Create(memDesc, constOp->get_data_ptr());

        MKLDNNMemoryPtr ptr = MKLDNNMemoryPtr(new MKLDNNMemory(getEngine()));
        **ptr->Create(memDesc);   // -> not set data handle
        ptr->SetData(memory);**  // -> need data_handle, but is nullptr

        return ptr;
    };  

```
in fact, the  cloneBlob just copy the temp MKLDNNMemory to a pointer of MKLDNNMemory ,  why not vino allocate the mem when new the pointer ?

**Comment by avitial** [comment] 2021-12-27 20:11
@duhuajiang thanks for providing additional information, I see that you can't share the model as it belongs to your company. Would it be possible to share a dummy model or simplified model that is enough to reproduce the issue you are reporting?

**Comment by avitial** [comment] 2022-01-26 20:42
Closing this, feel free to reopen and provide additional information or ask any questions related to this topic.

**Closed by avitial** 2022-01-26 20:42 UTC
Labels: support_request, PSE
