### ISSUE TITLE
Why there are so many reorders in a binary network IR trained from nncf

### ISSUE THREAD

**Issue by gj-raza** [openvinotoolkit/openvino#5817] opened 2021-05-25 17:11 UTC
##### System information (version)

- OpenVINO = 2021.1.110
- Operating System / Platform => ubuntu 18.04
- Problem classification: Model Conversion
- Framework: NNCF (Pytorch 1.8.1)
- Model name: Squeezenet (Classification)
- CPU: Intel core i7 9700k

##### Detailed description
I trained a squeezenet classification model using given training pipeline script in nncf examples with XNOR  binarization as compression method, keeping first conv layer as fp32 and rest of the net in binary, converted to onnx and then to IR via model optimizer and ran benchmarks with the OV's benchmark tool and found that in addition to fake quantize, there are reorders happening before every binary conv layer execution which are costly and essentially taking away the speed up that could be achieved through binarization as a result, the FPS are even lower that a full FP32 model (benchmark report attached). 

As you can see below before every binary conv, a reorder is happening from nchw8c to nhwc, although as per docs of binary conv [here](https://docs.openvinotoolkit.org/latest/openvino_docs_ops_convolution_BinaryConvolution_1.html), the binary conv layer can accept NCHW format. 

Concern is, why the model optimizer/Inferece Engine is adding reorders before every bin conv and is there a way to avoid these?
Detailed benchmark counters for full FP32 model and binary model are attached for reference.

![binary_net_benchmark](https://user-images.githubusercontent.com/59055565/119538178-47b0fe00-bda4-11eb-83bc-1967ca6afa0c.png)

[benchmark_detailed_counters_report_squeezenet1_1_imagenet_binary_xnor.csv](https://github.com/openvinotoolkit/openvino/files/6541105/benchmark_detailed_counters_report_squeezenet1_1_imagenet_binary_xnor.csv)
[benchmark_detailed_counters_report_squeezenet_1_1_fp32.csv](https://github.com/openvinotoolkit/openvino/files/6541108/benchmark_detailed_counters_report_squeezenet_1_1_fp32.csv)

[benchmark_report_squeezenet1_1_imagenet_binary_xnor.csv](https://github.com/openvinotoolkit/openvino/files/6541132/benchmark_report_squeezenet1_1_imagenet_binary_xnor.csv)
[benchmark_report_squeezenet_1_1_fp32.csv](https://github.com/openvinotoolkit/openvino/files/6541137/benchmark_report_squeezenet_1_1_fp32.csv)

**Comment by ilyachur** [comment] 2021-05-26 04:09
@dmitry-gorokhov Could you have a look?

**Comment by gj-raza** [comment] 2021-05-28 12:41
@dmitry-gorokhov here are model onnx files for your reference, 


https://drive.google.com/drive/folders/1EzkohZOjGg-Cul0IoLok9QJu1NO0GMQ2?usp=sharing

**Comment by zulkifli-halim** [comment] 2021-06-11 12:09
Hello @gj-raza. Thank you for your patience. The developer is investigating the case and might take some time.

**Comment by jgespino** [comment] 2021-12-20 23:09
Hi @gj-raza 

I apologize for the delay in our response. The development team has confirmed that Binary models support is currently experimental in OpenVINO. Additional optimizations still need to be implemented in order to speed up such binary models. 

I will convert this issue into a feature request. 

Regards,
Jesus

**Comment by hbalasu1** [comment] 2023-04-05 08:09
Hi @gj-raza, thank you for your feedback on this case, 
I am closing this case as it won't fix . This is because binary networks are currently a low priority for OpenVINO.

**Closed by hbalasu1** 2023-04-05 08:09 UTC
Labels: category: MO, feature
