### ISSUE TITLE
Setup a correct model conversion from(pytorch to onnx to IR)  but with needed pre-processing

### ISSUE THREAD

**Issue by AyaNasser96** [openvinotoolkit/openvino#11942] opened 2022-06-21 13:15 UTC
Hello, 
My classification model (resnet) is trained with pytorch and the pre-process of the test-set was as follow:

![image](https://user-images.githubusercontent.com/98317981/174807694-8363d4dd-b64a-465b-bffd-cc960ade2d70.png)

![image](https://user-images.githubusercontent.com/98317981/174799825-9666a2f3-96ca-426f-8699-7b44ff9766c1.png)

Then I converted that model to onnx successfully.
![image](https://user-images.githubusercontent.com/98317981/174800095-623423ca-723e-43df-9881-092a487e917b.png)

I've convert the onnx model  to IR with the following parameters to make it meets the pre-process 

`python3 mo_onnx.py --input_model vclass.onnx --input_shape [1,3,224,224]  --mean_values [123.675,116.28,103.53] --scale_values [58.395,57.12,57.37]  --reverse_input_channels --output_dir /openvino `

- **Note**: the mean values  are composed of (pretrained_means * 255) 
scale values composed of (std * 255) 

**there's a slightly difference between the inference result using original (onnx or pytorch) models and the inference results with IR model**

**So how could I meet that pytorch pre-processing while converting to IR model ??**

**Comment by zulkifli-halim** [comment] 2022-06-22 09:56
Hi @AyaNasser96. This inference difference issue might be due to the converter (PyTorch-ONNX exporter). 

Which OpenVINO version did you use to convert the model? Also, please share with us the PyTorch model, ONNX model, and the demo/script you used to run inference.

**Comment by AyaNasser96** [comment] 2022-06-22 17:48
@zulkifli-halim 
I would appreciated if could you send me your mail to send you the model, because it's slightly a confidential model ^^
Thanks in advanced

**Comment by AyaNasser96** [comment] 2022-06-22 18:13
Also for the public, 
I've tried the original (inception-v3) model, and convert it to onnx, 
and I got a the same classes with most of imgs but with difference with confidence number.

So here's the code that consists (pytroch-inference, convert-to-onnx, inference-with-onnx)
and the converted model (onnx) 
and the sample img I use.

https://drive.google.com/drive/folders/1u7U0p3F-EvIcpzweOqvHLkoCKfmyg0SY?usp=sharing

**Comment by zulkifli-halim** [comment] 2022-06-23 01:55
@AyaNasser96, here is my email:
zulkiflix.bin.abdul.halim@intel.com

**Comment by AyaNasser96** [comment] 2022-06-23 08:08
for IR model I am using the classification demo for openvino 2021.4.2
https://github.com/openvinotoolkit/open_model_zoo/tree/2021.4.2/demos/classification_demo/cpp

But it seems the problem doesn't belong to openvino, the problem is at onnx model 
(the conversion from pytorch to onnx produces a not accurate model)

**Comment by AyaNasser96** [comment] 2022-06-23 11:35
@zulkifli-halim I've sent you email with the model and infer script, and the openvino infer is using classification demo as I've mentioned, 

The conversion command from onnx to IR is

`python3 mo_onnx.py --input_model vclass.onnx --input_shape [1,3,224,224] --mean_values [123.675,116.28,103.53] --scale_values [58.395,57.12,57.37] --reverse_input_channels --output_dir /openvino`

**Comment by zulkifli-halim** [comment] 2022-06-24 01:38
@AyaNasser96, I sent a request to access your files, please grant me access.

**Comment by AyaNasser96** [comment] 2022-06-26 08:37
@zulkifli-halim The access is given 2 days ago ^^

**Comment by zulkifli-halim** [comment] 2022-06-27 01:41
@AyaNasser96. Thank you for sharing the model with us. We are looking into this and get back to you soon.

**Comment by zulkifli-halim** [comment] 2022-06-27 12:10
I tested your [Inception model](https://drive.google.com/drive/folders/1u7U0p3F-EvIcpzweOqvHLkoCKfmyg0SY?usp=sharing) using _infer_inception.py_ (for ONNX) and [Classification Python Demo](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/classification_demo/python) (for IR format). Both give a similar inference output.

ONNX format:
```
minivan 0.9267292618751526
minibus 0.011256512254476547
beach wagon 0.008942116051912308
pickup 0.008054458536207676
grille 0.007050654850900173
##############
[ONNX] predicted class:  minivan
[ONNX] Confidence is:  0.81422734
```


IR format:
![image](https://user-images.githubusercontent.com/79680111/175892421-2ca77618-2bf6-4e6e-83b2-28280aca8afc.png)

For _resnet-erasing_ model, I wasn't able to run the _vclass_model_infer.py_ script as I received this error:
```
C:\Python\Python37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Python\Python37\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
C:\Python\Python37\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)
Traceback (most recent call last):
  File "vclass_model_infer.py", line 6, in <module>
    from model import ResNet
ImportError: cannot import name 'ResNet' from 'model' (unknown location)
```
This error occurred due to the ResNet file cannot be found in the model folder.

I also tested your _resnet_erasing_ model using [Classification Python Demo](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/classification_demo/python) and here are the results:

ONNX:
![image](https://user-images.githubusercontent.com/79680111/175934797-d8cb3906-c878-4b03-b86d-2a6fa770c533.png)


IR format:
![image](https://user-images.githubusercontent.com/79680111/175934730-0a90a596-cee1-41d5-bddc-488a60b1bda1.png)

It seems that the model is not well trained. Can you share with us your inference results for the _resnet_erasing_ model for (both .onnx and .xml)?

**Comment by AyaNasser96** [comment] 2022-06-27 12:28
And about the pytorch & ONNX results
**Pytorch**: 

> Car Type: cross-over
> conf is: 0.85531

IR Model:

> Type is:  cross_overType
> Conf is:  0.794115

**Comment by AyaNasser96** [comment] 2022-07-05 12:09
@jgespino @zulkifli-halim
Hello, any updates ?

**Comment by jgespino** [comment] 2022-07-08 18:07
Hi @AyaNasser96 Appologies for the delay. I've been taking a look at your model and python scripts shared with @zulkifli-halim 

Using the latest OpenVINO 2022.1 release, I am getting really close results to the pytorch model results. See below, I rounded to two decimal point to make it easier to compare.

![image](https://user-images.githubusercontent.com/18014973/178045064-2c1e83c5-c798-41ca-933d-4ef041e0ae12.png)

Are these results close to what you would expect? Is upgrading to OpenVINO 2022.1 an option for you?

Tested the resnet-erasing.onnx model with our classification_demo.py using the following command:
`python classification_demo.py -i sample.jpg -m resnet-erasing.onnx --mean_values 0.485 0.456 0.406 --scale_values 58.395 57.12 57.37 -topk 8 --labels labels.txt`

Converted the onnx model to IR:
`mo --input_model resnet-erasing.onnx --input_shape [1,3,224,224] --mean_values [0.485,0.456,0.406] --scale_values [58.395,57.12,57.375]`

Tested the IR file with our classifcation_demo.py using the following command:
`python classification_demo.py -i sample.jpg -m resnet-erasing.xml -topk 8`

**Comment by jgespino** [comment] 2022-07-15 17:21
Closing, please re-open if additional assitance is needed.

**Closed by jgespino** 2022-07-15 17:21 UTC
Labels: support_request, PSE

**Comment by AyaNasser96** [comment] 2022-07-17 09:47
Thank you so much @jgespino , 
Why you are using those mean values ? should not we use the mean values * 255 ?  
Do you have any interpretation why original-onnx results are different from pytorch results ?

**Comment by BowenBao** [comment] 2022-10-29 00:54
@AyaNasser96 Hi I tested the inception model script that you shared. It turned out that the source of mismatch is from different preprocessing. After applying the same preprocessing code, ORT outputs the same confidence score as pytorch.
```
minivan 0.9267292022705078
minibus 0.011256570927798748
beach wagon 0.008942145854234695
pickup 0.008054500445723534
grille 0.007050680927932262
##############
[ONNX] predicted class:  minivan
[ONNX] Confidence is:  0.9267296
```

```python
def infer_inception_onnx(img_path, onnx_model):
    ort_session = onnxruntime.InferenceSession(onnx_model)
    # pretrained_means = [0.485, 0.456, 0.406]
    # pretrained_stds = [0.229, 0.224, 0.225]

    # def to_numpy(tensor):
    #     return (
    #         tensor.detach().cpu().numpy()
    #         if tensor.requires_grad
    #         else tensor.cpu().numpy()
    #     )

    # img = Image.open(img_path)
    # resize = transforms.Resize([299, 299])
    # img = resize(img)

    # to_tensor = transforms.ToTensor()
    # img = to_tensor(img)

    # normalize = transforms.Normalize(mean=pretrained_means, std=pretrained_stds)
    # img = normalize(img)
    # img.unsqueeze_(0)

    # Replace processing for ONNX model input with same code copied from
    # above function for pytorch.
    from PIL import Image
    from torchvision import transforms

    input_image = Image.open(img_path)
    preprocess = transforms.Compose(
        [
            transforms.Resize(299),
            transforms.CenterCrop(299),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ]
    )
    input_tensor = preprocess(input_image)
    input_batch = input_tensor.unsqueeze(
        0
    )  # create a mini-batch as expected by the model

    # move the input and model to GPU for speed if available
    # if torch.cuda.is_available():
    device = "cpu"
    input_batch = input_batch.to(device)

    ort_inputs = {ort_session.get_inputs()[0].name: input_batch.cpu().numpy()}
    ort_outs = ort_session.run(None, ort_inputs)
    out_y = ort_outs[0]
    e_x = np.exp(out_y - np.max(out_y))
    softmax_list = e_x / e_x.sum()
    highest_index = out_y.argmax(axis=1)[0]
    detected_class = str(classes[highest_index])
    print("[ONNX] predicted class: ", detected_class)
    print("[ONNX] Confidence is: ", softmax_list[0][highest_index])
    return detected_class
```

**Comment by Bea07** [comment] 2023-02-02 08:39
@AyaNasser96 is the solution provided by @BowenBao confirmed?
I have the same problem with a u-net, but I used the same preprocessing with pytorch and onnx.
