### ISSUE TITLE
[Bug] ExecutableNetwork::operator! implementation is wrong

### ISSUE THREAD

**Issue by chao-camect** [openvinotoolkit/openvino#15654] opened 2023-02-11 00:03 UTC
```
bool ExecutableNetwork::operator!() const noexcept {
    return !_impl || !actual;
}
```
It should be
```
bool ExecutableNetwork::operator!() const noexcept {
    return !_impl && !actual;
}
```

**Comment by ilya-lavrenov** [comment] 2023-02-11 06:58
@chao-camect I suppose you use obsolete OpenVINO version. Which one?
Currently, this oeprator is implemented as:
```c++
bool ExecutableNetwork::operator!() const noexcept {
    return !_impl;
}
```

**Comment by hbalasu1** [comment] 2023-03-15 13:52
Hi @chao-camect, any update on this case? Do you submit any PR ? so that we can capture it here.

**Comment by akladiev** [comment] 2023-05-11 16:33
This issue will be closed in 2 weeks in case of no activity.

**Comment by ilya-lavrenov** [comment] 2023-09-16 19:18
Looks like the issue is not urgent anymore. Closing.

**Closed by ilya-lavrenov** 2023-09-16 19:18 UTC
Labels: bug
