### ISSUE TITLE
Python crashes when loading net from ModelOptimizer

### ISSUE THREAD

**Issue by Laubeee** [openvinotoolkit/openvino#1307] opened 2020-07-13 15:47 UTC
I tried to optimize the openpose COCO .caffemodel with `mo.py`, passing model and proto
When I try to load it with `readNet`, python crashes. A message is printed, but from googling it it seems unrelated: `[E:] [BSL] found 0 ioexpander device`

the original file can be read perfectly fine.

OpenCV: 4.3.0-openvino-2020.3.0
Python: 3.7.2 (default, Feb 21 2019, 17:35:59) [MSC v.1915 64 bit (AMD64)]
CPU: i7-7600U
Win10 1909

update: this doesn't seem to be a model-specific error since I just downloaded human-pose-estimation-0001 with openVINO provided model downloader and got the same error.

update2: for the human-pose-estimation-0001 it seems to be a different issue. I tried to make an overview:

```python
net = cv2.dnn.readNet("../models/pose_coco.caffemodel", "../models/pose_coco.prototxt")  # works
net = cv2.dnn.readNet("../models/pose_coco.bin", "../models/pose_coco.xml")              # fails
base = "../models/intel/human-pose-estimation-0001/FP16-INT8/human-pose-estimation-0001."
net = cv2.dnn.readNetFromModelOptimizer(base + "bin", base + "xml")                      # fails
net = cv2.dnn.readNet(base + "bin", base + "xml")                                        # works
```

**Comment by jgespino** [comment] 2020-07-13 17:42
Hi @Laubeee 

I also see the `[E:] [BSL] found 0 ioexpander device` message when running a quick test. However, my python script does not crash and runs without any issues. Could you try running the example mentioned in this discussion? https://github.com/opencv/open_model_zoo/issues/20#issuecomment-444398342

Also, the OpenVINO Toolkit documentation shows Python 3.6.5 64-bit as a requirement. Could you try downgrading to that version? 

Regards,
Jesus

**Comment by dkurt** [comment] 2020-07-14 05:51
> net = cv2.dnn.readNetFromModelOptimizer(base + "bin", base + "xml")                      # fails
net = cv2.dnn.readNet(base + "bin", base + "xml")                                        # works

Please read documentation:

[readNetFromModelOptimizer](https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga4f3b552113d2bff48a54e168791c448e):

```
Net cv::dnn::readNetFromModelOptimizer ( const String & xml,  const String & bin )`
```

and 
[readNet](https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga3b34fe7a29494a6a4295c169a7d32422):
```
An order of model and config arguments does not matter.
```

**Comment by Laubeee** [comment] 2020-07-14 09:56
@dkurt I see. The naming `Net cv::dnn::readNet( const String & model, const String & config = "", const String & framework = "")` suggests the order `model, config` though. Didn't see its reversed for most other functions. Wouldn't it make sense to kinda unify this? Since config is sometimes optional the `model, config` order seems also more intuitive, but to unify without breaking code it is probably be easier to reverse the parameter names of readNet.. anyway that is a whole different topic.

@jgespino in what way is the example different from the last line in my post?
using python: `3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:55) [MSC v.1900 64 bit (AMD64)]` now, issue persists

**Comment by dkurt** [comment] 2020-07-14 10:08
@Laubeee, Once again, for `readNet` the order of arguments `model` and `config` does not matter. For framework specific methods `readNetFrom*` does. You may use `readNet("model.xml", "model.bin")` or `readNet("model.bin", "model.xml")`.

**Comment by Laubeee** [comment] 2020-07-14 10:19
I'm not opposing that.
You see, when I look up the order and see that line: `Net cv::dnn::readNet( const String & model, const String & config = "", ...` I stop looking and pass the model first and config second. When I switch to function `readNetFromModelOptimizer` I expect the order to be the same, unless there is a (real) reason. But maybe much more important, I would expect an actual error to be printed and not a silent python crash.

**Comment by dkurt** [comment] 2020-07-14 11:58
There is error message in this case:
```
import cv2 as cv

net = cv.dnn.readNetFromModelOptimizer('face-detection-retail-0005.bin', 'face-detection-retail-0005.xml')
```

```
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Error loading XML file: face-detection-retail-0005.bin:1:34: Could not determine tag type
Aborted (core dumped)
```

**Comment by Laubeee** [comment] 2020-07-14 13:07
Not at my end, no:
```
(py36) C:\Projects\at_CaRe\WellfasterKeypointDetection\python\models\intel\human-pose-estimation-0001\FP16-INT8>python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.dnn.readNetFromModelOptimizer("human-pose-estimation-0001.bin", "human-pose-estimation-0001.xml")
[E:] [BSL] found 0 ioexpander device

(py36) C:\Projects\at_CaRe\WellfasterKeypointDetection\python\models\intel\human-pose-estimation-0001\FP16-INT8>
```

and if there were, jupyter probably wouldn't display it anyway if it terminates the kernel. Is that wanted behaviour?

but we're kinda getting off topic here. I am still at loss why the converted model fails to load:
`net = cv2.dnn.readNet("../models/pose_coco.bin", "../models/pose_coco.xml")`

**Comment by jgespino** [comment] 2020-07-14 20:06
Hi @Laubeee 

Since I am not able to reproduce the issue with our models. Could you share your Caffe model and model optimizer command used?

Regards,
Jesus

**Comment by Laubeee** [comment] 2020-07-14 20:19
Sure, use this script to download the .caffemodel: https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/models
I tried the `/pose/coco`

As stated I passed both files to `mo.py` with the respective flags, and didnt use anything else, so it should've been
`python mo.py --input_model <.caffemodel> --input_proto <.prototxt>`

**Comment by jgespino** [comment] 2020-07-17 20:20
Hi @Laubeee 

I was able to replicate using the /pose/coco model from the repository you linked. Reading the model using the OpenVINO Inference Engine I was able to get additional information. I believe the issue is that the data shape is not being defined correctly by the model optimizer. I will reach out to some peers to see if this can be solved and if this model is supported. 

```
from openvino.inference_engine import IENetwork, IECore
ie = IECore()
net = ie.read_network(model = 'pose_iter_440000.xml', weights ='pose_iter_440000.bin')
```

```
Traceback (most recent call last):
  File "IE_Read_Model.py", line 4, in <module>
    net = ie.read_network(model = 'pose_iter_440000.xml', weights ='pose_iter_440000.bin')
  File "ie_api.pyx", line 261, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 293, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Check 'window_dilated_dim <= data_padded_dilated_dim' failed at C:\j\workspace\private-ci\ie\build-windows-icc2018\b\repos\openvino\ngraph\src\ngraph\validation_util.cpp:212:
While validating node 'v1::MaxPool MaxPool_11(Relu_10[0]:f32{1,64,1,1}) -> (dynamic?)':
Window after dilation has dimension (dim: 2) larger than the data shape after padding (dim: 1) at axis 0.
```

Regards,
Jesus

**Comment by ilyachur** [comment] 2020-08-31 07:59
Hi,

The problem is that MO generates incorrect IR.
Because prototxt contains the next code:
```
input: "image" 
input_dim: 1 
input_dim: 3 
input_dim: 1 # This value will be defined at runtime 
input_dim: 1 # This value will be defined at runtime
```
H and W dimensions is too small, it cause the issue.

You can use the next command line to generate the right IR:
```
python3 mo.py --input_model model.caffemodel --input_proto deploy.prototxt --input_shape [1,3,600,600]
```
The shape specialization allows to resolve this ticket.

**Comment by manuiiitv** [comment] 2020-09-03 11:55
Intel openvino version used in deployment setup openvino_2020.1.023.
Openvino engines for detection models created on Machine M1.
@Laubeee @ilyachur @jgespino @dkurt @dmitryte 
Deployment Setup 1 :: machine M2
Deployment Setup 2 :: machine M3

CPUs of machine M1, M2 and machine M3 are different.

Everything is same on Deployment setup machines like all the version of the dependencies required and openvino.

Engines generated on machine M1 gives different detections on Machine M2 and Machine M3 with binary generated from same code file written in cpp.

Any help in finding what could be the possible reasons for this?

Thanks in advance for your reply.

**Comment by potatozrollin** [comment] 2020-09-04 08:39
> Hi,
> 
> The problem is that MO generates incorrect IR.
> Because prototxt contains the next code:
> 
> ```
> input: "image" 
> input_dim: 1 
> input_dim: 3 
> input_dim: 1 # This value will be defined at runtime 
> input_dim: 1 # This value will be defined at runtime
> ```
> 
> H and W dimensions is too small, it cause the issue.
> 
> You can use the next command line to generate the right IR:
> 
> ```
> python3 mo.py --input_model model.caffemodel --input_proto deploy.prototxt --input_shape [1,3,600,600]
> ```
> 
> The shape specialization allows to resolve this ticket.

Can I ask if by any chance the this IR model took very long to infer (e.g. 300s) when you ran it on Intel NCS2 stick? Thank you!

**Comment by Laubeee** [comment] 2020-09-04 11:23
> You can use the next command line to generate the right IR:
> 
> ```
> python3 mo.py --input_model model.caffemodel --input_proto deploy.prototxt --input_shape [1,3,600,600]
> ```

That model will then only be able to process 600x600 images? or will it be able to adapt to different sizes?

@manuiiitv how different are they? are the values somewhat alike or completely different? Could it be a precision thing, e.g. one machine supports lower precision and therefore faster execution, while the other doesn't?

@potatozrollin 600x600 is quite big for this model, so for a (weak?) CPU I could imagine this kind of runtime to be possible. My i7-7600U needs 10-20 seconds for a single frame on much lower resolution (I think that was for ~380x380px, but I'd have to double check to be sure).

**Comment by potatozrollin** [comment] 2020-09-05 08:16
> > You can use the next command line to generate the right IR:
> > ```
> > python3 mo.py --input_model model.caffemodel --input_proto deploy.prototxt --input_shape [1,3,600,600]
> > ```
> 
> That model will then only be able to process 600x600 images? or will it be able to adapt to different sizes?
> 
> @manuiiitv how different are they? are the values somewhat alike or completely different? Could it be a precision thing, e.g. one machine supports lower precision and therefore faster execution, while the other doesn't?
> 
> @potatozrollin 600x600 is quite big for this model, so for a (weak?) CPU I could imagine this kind of runtime to be possible. My i7-7600U needs 10-20 seconds for a single frame on much lower resolution (I think that was for ~380x380px, but I'd have to double check to be sure).

Hmm I tried using the 600 x 600 and the results seem to be really different from the original caffemodel. Did you run into this as well when you tried? @manuiiitv @Laubeee

**Comment by jgespino** [comment] 2020-09-16 13:38
@Laubeee Changes were merged to master branch to catch such errors. I was not able to access your model once more to verify. I believe your issue is now resolved by @ilyachur suggestion to specify the shape. Let me know if we can proceed to close this issue. 

@potatozrollin @manuiiitv Your issue seems to be different, please start a new issue if you need additional assistance.

**Comment by Laubeee** [comment] 2020-09-16 14:33
I have not tested it myself as I proceeded the project using the human pose estimation from the model zoo, but as @potatozrollin reported the workaround still has some issues...

Of course it would be cool if the model could be converted even without any further shape specification, but if this is out of scope you can close the issue here. Thanks!

**Comment by suygungelen** [comment] 2020-09-17 10:02
@Laubeee regarding your question _"That model will then only be able to process 600x600 images? or will it be able to adapt to different sizes?":_ you can also try different sizes, 600x600 was an example. You can also try reshaping the input size on-fly if the generated model's input shape does not fit the image size during inference. You can check https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_ShapeInference.html for more details about dynamic input size.

**Closed** 2020-09-22 12:43 UTC
Labels: TCE, category: MO

**Comment by computervisionpro** [comment] 2021-02-21 10:04
Hi All,
I am too getting this error.
`[E:] [BSL] found 0 ioexpander device`

I am not able read OpenVINO pretrained model [vehicle-detection-adas-0002](https://docs.openvinotoolkit.org/latest/omz_models_intel_vehicle_detection_adas_0002_description_vehicle_detection_adas_0002.html) 

OpenVINO version: 2021.2.185
OS: Windows
Python: 3.7.9


I am not using any MYRIAD. Also, the model precision is FP32. Any help is appreciated.

<img width="607" alt="openvino error" src="https://user-images.githubusercontent.com/40919247/108621511-06354d80-7459-11eb-9d46-d1412b8ebd91.png">

**Comment by dkurt** [comment] 2021-02-23 15:36
@computervisionpro, that's not an error.tryto run model. Use OpenCV forum to ask usage questions please: https://forum.opencv.org/
