### ISSUE TITLE
VPU optimization and MYRIAD inference results 

### ISSUE THREAD

**Issue by alrzmshy** [openvinotoolkit/openvino#2109] opened 2020-09-07 12:50 UTC
Hi,

I have two question on inference using MYRIAD. It is explained [here](https://www.intel.com/content/www/us/en/support/articles/000056285/boards-and-kits/neural-compute-sticks.html) that  `VPU_HW_STAGES_OPTIMIZATION` should be set off for getting the right results.  

What is the purpose of having `VPU_HW_STAGES_OPTIMIZATION` if setting it to 'YES' leads to poor performance? 

Also, I have seen these lines in the code:

`Disable HW pooling`   
`std::map<std::string, std::string> networkConfig;`
`networkConfig["VPU_HW_STAGES_OPTIMIZATION"] = "NO";`

What does HW pooling do?

**Comment by maxlytkin** [comment] 2020-09-08 13:07
@alrzmshy 
This is being considered as a bug and we might expect this to be fixed soon later.
The option VPU_HW_STAGES_OPTIMIZATION exists for debug purposes. When you turn it off, all the hardware acceleration gets disabled for the model. It might affect various characteristics like accuracy, memory requirements, and performance. 
As for the HW pooling, where did you get these lines from?

**Comment by alrzmshy** [comment] 2020-09-08 13:13
Thank you for your response.

When I tried to look for a documentation on VPU_HW_STAGES_OPTIMIZATION, I found those lines [here](https://github.com/openvinotoolkit/openvino/blob/7566e8202fa6c00f27de27889e7bf99d7ddf2636/inference-engine/tests_deprecated/functional/vpu/common/layers/myriad_layers_rfcn_test.cpp#L691).

**Comment by maxlytkin** [comment] 2020-09-09 12:06
@alrzmshy 
Looking at the code it should simply disable VPU hardware acceleration as a network configuration.

**Comment by alrzmshy** [comment] 2020-09-10 12:01
OK. Thank you. The name is a bit confusing though. Especially when we are in the context of deep learning pooling layers and the usual notation for height and width (HW).

**Comment by mhkabir** [comment] 2020-09-14 17:33
Seemingly a duplicate of https://github.com/openvinotoolkit/openvino/issues/1822

**Comment by maxlytkin** [comment] 2020-10-15 12:36
@mhkabir 
The result is inaccurate when HW optimization is enabled because there might be a half precision overflow on MatMul layer. We were informed that we can't make any workaround or fixes because of data sensitivity and possible impacts on other models.
We would recommend to regenerate IR using MO with --scale parameter (scale 4, 8, 16, etc.). In this case, data values and weights will be analyzed by the myriad plugin correctly and there will be no overflow.
And then you would be able to accurately infer your model with enabled VPU_HW_STAGES_OPTIMIZATION.

**Comment by jgespino** [comment] 2020-10-27 13:47
Hi @alrzmshy @mhkabir 

Where you able to test your model by converting to IR using the model optimizer with `--scale` parameter? Please let me know the results. 

Regards,
Jesus

**Comment by jgespino** [comment] 2020-11-03 17:12
Closing, please re-open if additional assistance is needed.

**Closed by jgespino** 2020-11-03 17:12 UTC
Labels: bug, category: VPU, question
