### ISSUE TITLE
Failed to add custom op

### ISSUE THREAD

**Issue by Jsy0220** [openvinotoolkit/openvino#12754] opened 2022-08-25 11:18 UTC
I have followed the steps here [https://docs.openvino.ai/2022.1/openvino_docs_Extensibility_UG_Intro.html](https://docs.openvino.ai/2022.1/openvino_docs_Extensibility_UG_Intro.html) to add a new op and try to use tool mo with --extension to load onnx, but it have following error: 
      OpenVINO does not support the following ONNX xxx:xxxx

I have succeed to add a op in version 2020.3. It seems that it is more simple than the old version because it only needs to add one class which inherits class ov::op::Op,  but it doesn't work. So is there anything wrong ？

**Comment by ilya-lavrenov** [comment] 2022-08-25 12:16
@Jsy0220 could you please please provide the reproducer? 
I suppose you need not only to create derived class from ov::Op, but also add conversion rule from ONNX operator to this custom OpenVINO operator. See https://docs.openvino.ai/2022.1/openvino_docs_Extensibility_UG_Frontend_Extensions.html

CC @slyalin

**Comment by Jsy0220** [comment] 2022-08-26 01:21
@ilya-lavrenov 
Like this ?
![WeChatWorkScreenshot_58d0f2b4-12b0-4a82-b6ea-da50c18d6f6f](https://user-images.githubusercontent.com/6188672/186795204-c1f4b42c-daec-4f48-b62f-25f58aca99c8.png)

I have also tried shared library in c++ and mo --extension to load onnx, but they all doesn't work.

**Comment by ilyachur** [comment] 2022-08-26 18:23
Hi @Jsy0220 Could you provide the error message that you get?

Moreover would you like to support "correlation" operation, am I right?

**Comment by Jsy0220** [comment] 2022-08-27 02:07
Hi @ilyachur  
Yeah, I want to support the custom operation named "correlation", but I think it also can be the other name, e.g. "Identity". I just want to try the custom extension mechanism, so it doesn't matter what it is named.

And when loading the onnx model using c++ API, I got this error:
![WeChatWorkScreenshot_7fdde438-807b-44ce-be5f-cb15b5b28dbe](https://user-images.githubusercontent.com/6188672/187009695-0802dc54-1b63-4ead-a606-d231990d4d98.png)

And when using `mo` to load onnx model without --extension, I also got the error above. But when the extension added, it changed to:
![WeChatWorkScreenshot_9ed0b007-0626-4348-8568-68049a56af22](https://user-images.githubusercontent.com/6188672/187009920-7a162956-2547-4303-9067-2239b865096c.png)

**Comment by ilyachur** [comment] 2022-08-27 04:30
Could you try to change the name of operation from:
```
OPENVINO_OP("correlation");
```
to
```
OPENVINO_OP("thea.correlation");
```
Will it help you to load model in C++ code?

**Comment by Jsy0220** [comment] 2022-08-27 06:25
hi @ilyachur 
No, I have tried it, still got the same error.

**Comment by ilyachur** [comment] 2022-08-29 10:00
@tomdol @mlukasze Could you please take a look?

**Comment by tomdol** [comment] 2022-08-29 11:41
Will do, please give me some time though to finish the current assignments.

**Comment by tomdol** [comment] 2022-08-30 14:02
@Jsy0220 could you please share your code and the model? I had a look but I don't know where exactly you have your implementation. It will be much easier to have a look at some existing solution and spot the problem there.

**Comment by Jsy0220** [comment] 2022-09-02 00:59
@tomdol 
I am sorry to bother you again, but is there anything wrong in the code or model ? I want to know why this not work.

**Comment by Jsy0220** [comment] 2022-09-07 09:09
Hi, I have read onnx frontend codes about  adding custom ops and found that when using `ov::frontend::OpExtension` to register operation mapping, it  registers operator with empty domain as following:
![WeChatWorkScreenshot_d965b7ac-e74a-418f-ae1a-44ed7aa3f941](https://user-images.githubusercontent.com/6188672/188838989-e39a2439-e6c1-4de5-b1be-bd6cb63b316f.png)

but when loading onnx model, it extracts domain of the node to search in the opset as following:
![WeChatWorkScreenshot_3c407e72-0130-4eab-abcb-d56971d5519b](https://user-images.githubusercontent.com/6188672/188839000-ea9a4381-9199-4ccd-9867-a17ff78d3783.png)

So it can not be found.
I remember that the domain of the custom op can be set in previous version. So where can I set the domain for the custom op in version 2022.1.0 ?

**Comment by itikhono** [comment] 2022-09-09 19:50
Hi @Jsy0220. Sorry for the long delay in response. It looks like we always expect "" domain for operations registered via OpExtensions, I believe it's a bug. 
Is it possible to change domain in your onnx model? in the attached example from thea to ""
After that this should work for you:
```
class Correlation : public ov::op::Op
{
public:
    OPENVINO_OP("Correlation"); // openvino operation name here, class name is ok

    Correlation() = default;
    Correlation(const ov::Output<ov::Node>& arg0, const ov::Output<ov::Node>& arg1);

    void                      validate_and_infer_types() override;
    std::shared_ptr<ov::Node> clone_with_new_inputs(const ov::OutputVector& new_args) const override;
    bool                      visit_attributes(ov::AttributeVisitor& visitor) override;

    bool evaluate(ov::TensorVector& outputs, const ov::TensorVector& inputs) const override;
    bool has_evaluate() const override;
};
```
```
        ov::Core core;

        core.add_extension(ov::OpExtension<Correlation>());
        core.add_extension(ov::frontend::OpExtension<Correlation>("correlation")); // we pass framework operation name here as an argument
```

and from infer_request.set_input_tensors({ input_tensor0, input_tensor1 });
to 
```
        infer_request.set_input_tensor(0, input_tensor0);
        infer_request.set_input_tensor(1, input_tensor1);
```

**Comment by tomdol** [comment] 2022-09-12 09:21
The scope of required changes is changing so I've added a jira ticket to track this activity. Ticket number for reference 91705.
I was able to confirm that the initial approach doesn't work for ONNX FE but it requires a more in-depth analysis. The domain issue with the conversion extension seems to be a minor fix that can be implemented quickly.

**Comment by Jsy0220** [comment] 2022-09-29 07:30
Hi, I have tried version 2022.2 and it can add custom extensions successfully in c++ with following codes: 
![WeChatWorkScreenshot_2184051e-af6a-42ca-8844-f1dbe156d15e](https://user-images.githubusercontent.com/6188672/192961036-27be1b63-e482-4b1a-b275-b917c97801be.png)
and export the extension library libvino_ext.so with following codes:
![WeChatWorkScreenshot_93271b07-0d82-470e-aa50-a66482e6b3c0](https://user-images.githubusercontent.com/6188672/192961833-4da27b81-3525-4f9f-9055-34a68cd521e2.png)

But it still failed when using `mo --extension libvino_ext.so` to load onnx. The error is same as the above: _free(): invalid pointer_. And I tried to recompile the source code to add some log to find the problems. I found that the error happend when destructing variable _extensions_ in following codes
![WeChatWorkScreenshot_9eaaa3d2-5e54-4876-9a8d-5b93201b5aca](https://user-images.githubusercontent.com/6188672/192966077-87d655f1-8114-46bf-b3c7-1994717ba93d.png)

I noticed that this vector allocates memory in libvino_ext.so but deallocate memory in libopenvino.so, So I have tried using 
`reserve` to pre-allocates memory in libopenvino.so in case of memory allocating in libvino_ext.so as following:
![WeChatWorkScreenshot_1cd7d4ee-5e2f-4ec0-a534-fda2f16bc935](https://user-images.githubusercontent.com/6188672/192966596-9959dc4e-92de-479a-ac7a-61624c6b1d90.png)
and it seemed work.

So what's the problems ? Is there some compile parameters should be set when compiling extension library to solve this problem?

**Comment by itikhono** [comment] 2022-09-29 08:33
Hi @Jsy0220, could you share the code?

**Comment by ilyachur** [comment] 2022-09-29 08:48
Hi @Jsy0220 what compiler do you use?

**Comment by Jsy0220** [comment] 2022-09-29 11:53
@ilyachur  Ubuntu 20.04 (64-bit) with default GCC* 9.3.0
@itikhono  here is the code:
[extension.zip](https://github.com/openvinotoolkit/openvino/files/9674325/extension.zip)

**Comment by ilyachur** [comment] 2022-09-30 11:02
@Jsy0220 Thank you, do you use official OpenVINO binaries? Or do you build own version of OpenVINO?

**Comment by Jsy0220** [comment] 2022-10-08 01:20
@ilyachur Hi, sorry for the long delay in response. I built and installed OpenVINO in docker according to [https://github.com/openvinotoolkit/docker_ci/tree/master/dockerfiles/ubuntu20/build_custom] with OPENVINO_BRANCH="2022.2.0"
I tried `extensions.clear()` and `extensions.shrink_to_fit()` to release the memory, the error happened once it called.

**Comment by ilyachur** [comment] 2022-10-11 04:03
Ok, thank you for information. Need to investigate what is happening...
Am I right that you use the same compiler for building extensions and OpenVINO?

**Comment by mbencer** [comment] 2022-10-17 16:23
Hi @Jsy0220, I've tried to reproduce your problem and the current status is:

1. Scenario: Provided external library via MO `--extension` argument (extension.zip) 
I am not able to reproduce the problem "free invalid pointer" on the version 2022.2 (hash af16ea1) and on the current master (built from source, using both gcc and clang).

2. Scenario: Registration core op via `ov::OpExtension` and frontend op via `ov::frontend::OpExtension` (vino_extension.zip). 
I'm confirming the problem with domain in such scenario. Work in progress.

**Comment by ilyachur** [comment] 2022-10-20 11:37
@Jsy0220 Could you try this PR: https://github.com/openvinotoolkit/openvino/pull/13573

Does it help you to avoid problems?

**Comment by mbencer** [comment] 2022-12-02 12:11
The problem from Scenario 2 was resolved in: https://github.com/openvinotoolkit/openvino/pull/14375
Now you can use:
```
#include <openvino/frontend/onnx/extension/conversion.hpp>
...
core.add_extension(ov::frontend::onnx::OpExtension<Correlation>("correlation", "thea"));
```
to register extension with custom domain. The equivalent way is still:
```
    core.add_extension(ov::frontend::onnx::ConversionExtension("correlation", "thea", ov::frontend::CreatorFunction(
                                                                [](const ov::frontend::NodeContext& context)
                                                                {
                                                                    const auto correlation = std::make_shared<Correlation>(context.get_input(0), context.get_input(1));
                                                                    return correlation->outputs();
                                                                })));
```
@Jsy0220 Please confirm if it works for you and please let us know if you can still reproduce "free invalid pointer" (Scenario 1) on the curret master and/or on @ilyachur fix proposition (https://github.com/openvinotoolkit/openvino/pull/13573)

Thanks,
Mateusz

**Comment by mbencer** [comment] 2022-12-23 14:54
@Jsy0220 Can we close the issue?

**Comment by ilyachur** [comment] 2023-01-02 06:59
@Jsy0220 Could you verify that OV works for your cases?

**Comment by avitial** [comment] 2023-01-09 20:34
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Closed by avitial** 2023-01-09 20:34 UTC
Labels: bug, category: extensions
