### ISSUE TITLE
[Bug] penvino/inference_engine/__init__.py", line 30, in <module>     from .ie_api import * ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jinfagang** [openvinotoolkit/openvino#9523] opened 2022-01-06 15:23 UTC
penvino/inference_engine/__init__.py", line 30, in <module>
    from .ie_api import *
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

**Comment by alalek** [comment] 2022-01-06 17:08
Please provide more information:
- how did you get OpenVINO? which version?
- `python3 --version`
- `python3 -c "import sys; print(sys.path)"`
- `LD_DEBUG=libs python3 -c "from .ie_api import *"` (attach output as .txt file)
- `ldd <path_to_ie_api.so>`

**Comment by jinfagang** [comment] 2022-01-07 06:07
@alalek I just install openvino from pip install openvino. can not import it.

**Comment by Iffa-Meah** [comment] 2022-01-07 06:49
Hi @jinfagang ,

The libpython3.8.so.1.0 file might not exist in your system, hence causing the error.
Please help to share **all information** requested by @alalek. 
This would help us to narrow down the cause of the issue.

**Comment by dkurt** [comment] 2022-01-07 10:46
Have you installed `libpython3.8-dev`? Which OS is used?

**Comment by jinfagang** [comment] 2022-01-07 11:39
@dkurt @Iffa-Meah hi, I will update my os env and detailed output once get home. am using ubuntu 20.04, I think I have libpython3.8-dev installed.

**Comment by jinfagang** [comment] 2022-01-11 15:18
@dkurt Sorry for late reply. I just double check:

```
locate libpython3.8.so.1.0                                                                          bm/
/snap/gnome-3-38-2004/76/usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
/snap/gnome-3-38-2004/87/usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
/snap/ogre-meshviewer/494/usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
```

Seems my system version is:

```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 

```

So I maybe don't have this .so? How should I install it?

**Comment by Iffa-Meah** [comment] 2022-01-12 02:21
@jinfagang  since you posted this question in OpenVINO GitHub thread, I assume you get this OpenVINO package into your system by building from source.

You need to build the Python API wrapper so that your system recognizes which Python package you are trying to use with OpenVINO. 

Enable the `-DENABLE_PYTHON=ON` in the CMake (Step #5)  refer to this [Build on Linux Systems](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux)

To specify an exact Python version, use the following options (adjust according to yours):
```
-DPYTHON_EXECUTABLE=`which python3.7` \
-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.7m.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.7
```

**Comment by jinfagang** [comment] 2022-01-13 02:52
@Iffa-Meah  thanks a ton. I will try it later on.

BTW, why using `base` env and `pip install openvino` doesn't work here? As you can see, I am using `base` env which is also an venv in conda.

**Comment by Iffa-Meah** [comment] 2022-01-13 07:21
@jinfagang the base environment means that you are using your main system environment. Installation in this base environment usually made the OpenVINO to look for Python packages that are within your main system instead of Anaconda.
(Note that currently, your Python Packages are inside Anaconda). This often causes issue which can be solved by building the Python API wrapper and specifying an exact Python version (this is only applicable if you build from source: [Build on Linux Systems](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux) ).

Therefore, it is recommended to create a virtual environment in Anaconda and install OpenVINO there. This would guarantee the correct Python Package is being used.

**Comment by jinfagang** [comment] 2022-01-13 09:01
@Iffa-Meah  thanks, I though openvino doesn't opensource all code before. does openvino opensourced just like tensorrt? Only opensource OSS but not core lib?

**Comment by Iffa-Meah** [comment] 2022-01-14 02:04
@jinfagang , you'll need to do the setup as in the link I provided above. 
Once the setup is successful, you can clone the Open Model Zoo repository and get the pre-trained models/sample app.
Here is the repo: [Open_Model_Zoo](https://github.com/openvinotoolkit/open_model_zoo).

**Comment by Iffa-Meah** [comment] 2022-01-24 17:25
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Closed by Iffa-Meah** 2022-01-24 17:25 UTC
Labels: category: python api, support_request

**Comment by AlexHex7** [comment] 2022-06-17 08:16
@jinfagang Hi, you should install libpython3.8 in your ubuntu system.

`sudo apt-get install libpython3.8`
