### ISSUE TITLE
Symptom openvino cannot be used properly after being installed and configured in windows

### ISSUE THREAD

**Issue by fanxiaochen456** [openvinotoolkit/openvino#13935] opened 2022-11-10 06:48 UTC
Hello, I have installed the tool suite of OpenVINO2021 and configured the path of the OpenVINO toolkit in the local system environment, but the following error message appears when I call OpenVINO using VS2019:
![图片](https://user-images.githubusercontent.com/101849755/201019833-986d416e-a555-4753-8966-86ff579a15ea.png)
Here are the environment variables I configured:
![图片](https://user-images.githubusercontent.com/101849755/201019973-731d5f28-c2d6-48ee-a28f-6036a01eb0c6.png)
![图片](https://user-images.githubusercontent.com/101849755/201020107-7ee17789-b723-4cd8-a6b4-f3e60e061d8b.png)

**Comment by andrei-kochin** [comment] 2022-11-11 04:26
Hello @fanxiaochen456,

Thanks for reaching OpenVINO. Is it possible for you to share the code snippet to preproduce the issue? unfortunately it hard to get from the attached screenshots which routine throws abort exception.

Thank you!

**Comment by avitial** [comment] 2022-12-29 20:34
Closing this as it can't be reproduced due to incomplete details.

Feel free to reopen and ask additional questions related to this topic if issue persists, and provide requested information.

**Closed by avitial** 2022-12-29 20:34 UTC
Labels: incomplete, support_request
