### ISSUE TITLE
[Bug] Incorrect number of input edges for Add node when load (INT8) IR model converted from ONNX

### ISSUE THREAD

**Issue by nsk-lab** [openvinotoolkit/openvino#2478] opened 2020-10-01 00:15 UTC
##### System information (version)
- OpenVINO => 2020.2
- Operating System / Platform => Ubuntu 18.04.3 LTS
- Problem classification: Model Conversion and Inference
- Framework: Pytorch with NNCF -> ONNX format -> IR format
- Model name: ResNet-backnorn Detector

##### Detailed description
I have pytorch detection model. I could export it to onnx and then convert it to IR model.
I also confirmed the inference result is ok.

This time I use NNCF tool to train the model with INT8 optimization and export as ONNX file.
Then I converted the model to IR using below command (same command as I used before when without NNCF)
` python3 /opt/intel/openvino/deployment_tools/model_optimizer/mo_onnx.py --input_model $onnx_file --input_shape [1,3,$MY_H,$MY_W] --log_level WARNING --mean_values [$MY_M,$MY_M,$MY_M] --scale_values [$MY_S,$MY_S,$MY_S] `
The conversion succeeds.

Then I load the IR model using  `openvino.inference_engine.ie_api.IECore.load_network` but following error occurs
```
  File "ie_api.pyx", line 178, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 187, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Incorrect number of input edges for layer 560/variance/Fused_Add_
```

I checked the IR model by netron visualizer and there is 2 input as I expected (bottom left Add node).
It seems that the top left Add node is ok but bottom left Add node `560/variance/Fused_Add_` has wrong number of input even though the netron visualizer shows 2 input node as I expected.
![image](https://user-images.githubusercontent.com/58692908/94752115-43734300-03c5-11eb-8fc4-08d335656921.png)

The corresponding part of .xml file:
```
                <layer id="385" name="560/variance/Fused_Add_" type="Add" version="opset1">
                        <input>
                                <port id="0">
                                        <dim>1</dim>
                                        <dim>256</dim>
                                        <dim>18</dim>
                                        <dim>32</dim>
                                </port>
                                <port id="1">
                                        <dim>1</dim>
                                        <dim>256</dim>
                                        <dim>1</dim>
                                        <dim>1</dim>
                                </port>
                        </input>
                        <output>
                                <port id="2" precision="FP32">
                                        <dim>1</dim>
                                        <dim>256</dim>
                                        <dim>18</dim>
                                        <dim>32</dim>
                                </port>
                        </output>
                </layer>
```

I created [issue](https://github.com/openvinotoolkit/nncf_pytorch/issues/157#issuecomment-701263314) at NNCF repo and got suggestion to create a issue here.

**Comment by jgespino** [comment] 2020-10-01 14:45
Hi @nsk-lab 

Do you see the same issue with the OpenVINO toolkit 2020.4 release? We also have a step-by-step tutorial on how to integrate NNCF package, did you give that a try?

https://github.com/openvinotoolkit/nncf_pytorch/blob/develop/docs/Usage.md

Regards,
Jesus

**Comment by nsk-lab** [comment] 2020-10-02 01:10
@jgespino Thanks for response.

1)

I referred top page [README](https://github.com/openvinotoolkit/nncf_pytorch/blob/develop/README.md) to modify my training code.
I check Usage.md and confirmed that I obeyed instructions described there.

some details of my code:
- define subclass of nncf.initialization.InitializingDataLoader and implemented get_inputs() which returns real image. get_target() returns dummy
- register_default_init_args(nncf_config, train_loader, criterion=None). criterion is None
- load pre-trained weight before `compression_ctrl, compressed_model = create_compressed_model(model, nncf_config)`
- use int8 optimization only

2)

I tried 2020.4 by [docker image](https://hub.docker.com/layers/openvino/ubuntu18_dev/2020.4/images/sha256-36a2d3840d85af4cb82f2e164a40f3ea77e3b9f9b15ff779df7d9b5ebe5e34d1?context=explore) to convert onnx and run inference.
I succeeded to run the inference but number of detected object is zero...
It may be training problem or model conversion problem. (The loss when I train INT8 is almost same value compared the loss of FP32 normal training.)


BTW I have codebase which is developed for openvino 2020.2 .
Is it ok to run 2020.2-based inference code with 2020.4 API? In other words, 2020.4 has backward compatibility to 2020.2 ?

**Comment by jgespino** [comment] 2020-10-07 17:30
Hi @nsk-lab 

We actually just release OpenVINO toolkit 2021.1 yesterday, could you update your OpenVINO toolkit and give it a try on the latest release? There has been some changes in the API since 2020.2 release, I recommend taking a look at the release notes for backwards incompatibility changes. 
https://software.intel.com/content/www/us/en/develop/articles/openvino-relnotes.html

Does your onnx model with INT8 optimization detect objects prior to converting to IR? Could you share your model and model optimizer command to reproduce on my end? Please provide the values "[1,3,$MY_H,$MY_W] --log_level WARNING --mean_values [$MY_M,$MY_M,$MY_M] --scale_values [$MY_S,$MY_S,$MY_S]" for the variables.

Regards,
Jesus

**Comment by jgespino** [comment] 2020-10-16 15:48
Closing, please re-open if additional assistance is needed.

**Closed by jgespino** 2020-10-16 15:48 UTC
Labels: bug, support_request
