### ISSUE TITLE
MobileNetV3  is not supported?

### ISSUE THREAD

**Issue by Fighting-JJ** [openvinotoolkit/openvino#214] opened 2019-07-31 09:43 UTC
onnx model of  MobileNetV3 can be converted into IR model succesfully, but it failed in Network loading with c++ API.

**Comment by shubha-ramani** [comment] 2019-07-31 17:05
Dear @Fighting-JJ MobileNetV3 is not in C:\Program Files (x86)\IntelSWTools\openvino_2019.2.242\deployment_tools\tools\model_downloader\list_topologies.yml which leads me to believe that MobileNetV3 is not supported.  Nor do I see MobileNetV3 in the [Tensorflow Supported Models]http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.htmll)

I do see MobileNet V2 in the topologies.yml however.

Sorry for the inconvenience,

Shubha

**Comment by Fighting-JJ** [comment] 2019-08-01 09:01
@shubha-ramani 
I tried mobilenetv2 in pytorch, it still failed in the Network loading with c++ API

**Comment by shubha-ramani** [comment] 2019-08-01 17:57
Dear @Fighting-JJ 

Please see [pytorch supported doc](http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_ONNX.html) for supported PyTorch topologies. Unfortunately mobilenetv2 is not one of them.

Thanks !

Shubha

**Comment by elvin-nnov** [comment] 2019-08-03 19:49
Can you provide more details which exactly models do you mean and what are the error messages? the Model Optimizer command line would be also desirable.
Just a guess - could the problem be in some layers been implemented in extensions? Have you tried to plug extension library with CPU kernels before loading of these models?

**Comment by lazarevevgeny** [comment] 2020-05-25 12:19
@Fighting-JJ  is this issue still actual? Can you share the model?

**Comment by AnastasiaKazantaeva** [comment] 2020-07-13 15:58
It seems the issue is not actual, closing it

**Closed by AnastasiaKazantaeva** 2020-07-13 15:58 UTC
