### ISSUE TITLE
[Bug] GPU inference performance drop dramatically with high-frequency

### ISSUE THREAD

**Issue by wang7393** [openvinotoolkit/openvino#13999] opened 2022-11-15 04:04 UTC
##### System information (version)
- OpenVINO=> : 2021.4 or 2022.1 or 2022.2
- Operating System / Platform => : win10 64
- Problem classification => : gpu inference speed 

##### Detailed description
We have meet the problem that the gpu inference speed is slowed down suddenly(We tried multiple models and they all slowed down drasticly, one from 20ms to 200ms). 
However, the cpu inference speed is still normal when this problem occurs.
The problem occurred on multiple machines (with different driver versions, some just booted up, some on standby for a period of time to reuse).

It is worth mentioning that we use opencv-intel-gpu-opengcl acceleration, which also slows down at the time.

Some computers restart the computer or disable and restore the intel-gpu device can be restored to normal. But some computers still slow after restart.
![image](https://user-images.githubusercontent.com/29936604/201823042-21a438f3-2e1a-4426-b5a4-3523c60406ba.png)

Is it a matter of gpu drivers or hardware?

**Comment by brmarkus** [comment] 2022-11-15 05:44
Can you provide more information about your system, please?
What does your HW look like, which SoC, which CPU and GPU exactly are you using? Could you imagine a temperature-problem (in case your system is not actively cooled, but passively only), have you tried to monitor the system's and/or the SoC's temperature (to see if a thermal throttling has happened)?
Could you imagine your system is running out of system-memory (and the OS starts to compress memory, move memory to pagefile), have you tried to monitor system-memory?

**Comment by wang7393** [comment] 2022-11-16 00:59
the system info is as flowwings:
![image](https://user-images.githubusercontent.com/29936604/202055497-95b5118a-d9de-4db6-afb0-160b78aae353.png)

When this problem occurs, I have monitored the system memory, gpu memory, cpu utilization and gpu utilization, and they are all normal. 
The computer should also be at a normal temperature, as I didn't feel much heat.

**Comment by Iffa-Meah** [comment] 2022-11-16 02:36
@wang7393 could you provide these:
1. Relevant model files
2. Which OpenVINO sample app did you use for this test case? (e.g. benchmark_app)
3. Since you are asking in GitHub, I assume you are using OpenVINO build from source ?

**Comment by wang7393** [comment] 2022-11-18 03:29
@Iffa-Meah 
1. When occurs the problem, The inference speed of any model under the gpu dropped dramatically, the performance  of intel-gpu-opencl also dropped dramatically.
2 and 3. We use OpenVino runtime dlls to build custom apps.

**Comment by Iffa-Meah** [comment] 2022-11-18 06:20
@wang7393 from your explanation, I assume the model is confidential from your side (since you mentioned it's a custom app) and you are unable to share it with us for further validation.

There are a couple of elements to be considered when it's related to inferencing performance.
1. Model precision/format: GPU should performs best with FP16 precision since this is its preferred format. You may refer [here](https://docs.openvino.ai/latest/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html#supported-model-formats). 

2. [Model optimization for faster inferencing time](https://docs.openvino.ai/latest/openvino_docs_model_optimization_guide.html#doxid-openvino-docs-model-optimization-guide):  This is an optional offline step of improving final model performance by applying special optimization methods. You may consider using [OpenVINO Post Training Optimization (POT) ](https://docs.openvino.ai/latest/pot_introduction.html#doxid-pot-introduction) to optimize your model inferencing.

**Comment by wang7393** [comment] 2022-11-18 06:55
@Iffa-Meah 
1. The all models we used are both fp16 format.
2. And int8 POT quantization we also have implemented.
But I don't think that's relevant to my question.
Have you encountered similar problems, or do you have the idea of troubleshooting problems?

**Comment by brmarkus** [comment] 2022-11-18 07:03
Can you comment on your code, how you do inferencing? Multi-threaded? Static or dynamic shapes for input/output, using batches?
Can you reproduce the behavior with OpenVINO/Open-Model-Zoo demos, like "benchmark_app -d GPU ... ..."?
Is there anything else performed on the GPU (like your application is a Game doing 3D graphics)?
Is your input to the NN-model video-content, which gets decoded by the GPU (e.g. AVC/h.264 or AV1, in FullHD resolution)?

**Comment by wang7393** [comment] 2022-11-18 07:20
@brmarkus 
my code like this:
`class Dtetetor`
`{`
`public:`
	`Dtetetor();`
	`~Dtetetor();`
	`bool LoadModel()`
	`{`
		`ov::Core core;`
		`m_model = core.read_model("xxxx");`
		`m_compiledModel = core.compile_model(m_model, "GPU");`
		`m_inferRequest = m_compiledModel.create_infer_request();`
	`}`
	`bool  Process(Mat inpuImage)`
	`{`
		`// 1. make input tensor`
		`ov::Shape srcShape = { 1, (size_t)inpuImage.rows,
									(size_t)inpuImage.cols,
									(size_t)inpuImage.channels() };`
		`ov::Tensor inputTensor{ ov::element::u8, srcShape, inpuImage.data };`
		`m_inferRequest.set_tensor("src", inputTensor);`
		`//2. infer`
		`m_inferRequest.infer();`
		`// 3. get output Tensors`
		`vector<ov::Tensor> outPutTensors;`
		`vector<string>& outputNames = {"xx", "xxxx"};`
		`for (size_t i = 0; i < outputNames.size(); i++)`
		`{`
			`ov::Tensor& outputTensor = m_inferRequest.get_tensor(outputNames[i]);`
			`outPutTensors.push_back(outputTensor);`
		`}`
	`}`
`private:`
	`ov::CompiledModel m_compiledModel;`
	`std::shared_ptr<ov::Model> m_model;`
	`ov::InferRequest m_inferRequest;`
`};`
single thread, static input, not using batch inference.

If this problem occurs again, I will test with openvino official sample or benckmark app.

When this problem occurs, I have monitored the system memory, gpu memory, cpu utilization and gpu utilization, and they are all normal. And also there is no other applications are running on GPU.

Video decoding is cpu, not gpu.

**Comment by hbalasu1** [comment] 2022-11-25 03:19
Hi @wang7393, 
Can I know what model you use in your application? 
so that we can further identify the reason behind the drop in performance.

**Comment by brmarkus** [comment] 2022-11-25 06:07
> @brmarkus my code like this:
> 
> 	`bool  Process(Mat inpuImage)`
> 	`{`
> 	        `vector<ov::Tensor> outPutTensors;`
> 		`for (size_t i = 0; i < outputNames.size(); i++)`
> 		`{`
> 		`}`
> 	`}`
> 
> If this problem occurs again, I will test with openvino official sample or benckmark app.
> 
> Video decoding is cpu, not gpu.

Have you had a chance to reproduce with one of the OpenVINO or OpenModelZoo samples?

Could you add log-messages, e.g. containing time-stamps or time-spans to see in which area the sudden increase/decrease comes from?
Could it be from an increasing size of "outputNames.size()"?
What happens with `outPutTensors`, is it really a local variable, or shared with the caller, which pre-/post-processes it, maybe locked with a mutex and causing delays?
Could it be from the caller of `Process()`?
Could it be from CPU-decoding?
Could it be from the video/stream itself - could you try to keep repeating the same frame (maybe the input changes resolution, or framerate, or color-format, or suddenly the video/stream contains increasing number of detected objects?

**Comment by wang7393** [comment] 2022-11-29 01:38
Many of our own models have suffered serious performance degradation, I think it has nothing to do with the model.

I've met this problem recur on my machine a few times recently,
I tested it with benchmark_app and hello_classification sample, and the performance also decreased significantly.

**Comment by wang7393** [comment] 2022-11-29 01:40
> > @brmarkus my code like this:
> > `bool  Process(Mat inpuImage)`
> > `{`
> > `vector<ov::Tensor> outPutTensors;`
> > `for (size_t i = 0; i < outputNames.size(); i++)`
> > `{`
> > `}`
> > `}`
> > If this problem occurs again, I will test with openvino official sample or benckmark app.
> > Video decoding is cpu, not gpu.
> 
> Have you had a chance to reproduce with one of the OpenVINO or OpenModelZoo samples?
> 
> Could you add log-messages, e.g. containing time-stamps or time-spans to see in which area the sudden increase/decrease comes from? Could it be from an increasing size of "outputNames.size()"? What happens with `outPutTensors`, is it really a local variable, or shared with the caller, which pre-/post-processes it, maybe locked with a mutex and causing delays? Could it be from the caller of `Process()`? Could it be from CPU-decoding? Could it be from the video/stream itself - could you try to keep repeating the same frame (maybe the input changes resolution, or framerate, or color-format, or suddenly the video/stream contains increasing number of detected objects?

The serious performance degradation mainly comes from: `m_inferRequest.infer();`
As for the other questions you mentioned, I have verified that they have nothing to do with them.

**Comment by brmarkus** [comment] 2022-11-29 05:52
Would you mind sharing one or some of the problematic models - or simplified versions of them?
Can you provide more details about the models, architecture, use-case, training/re-training, conversion, please? it might be possible to identify what turned a model into a problematic model (like using YoloV5 as a base with good performance, then replacing the backend, or re-training, or modified post-processing from NMS, etc.)
Then the engineering team could have a closer look.

**Comment by wang7393** [comment] 2022-11-29 06:40
@brmarkus 
Test found that the problem should have nothing to do with the model itself. 
When this problem occurred, we tested many models, such as detection model, classification model, segmentation model and so on.

In addition,:
1. we also test the benchmark app, including our own Model and OpenVino Model Zoo's model (googlenet-v1), which showed serious inference performance degradation.
2. We also use the OpenVino  hello_classification sample test the googlenet-v1 model, the same problem.

**Comment by brmarkus** [comment] 2022-11-29 07:08
Can you comment on how OpenVINO and especially the "drivers" were installed?

**Comment by wang7393** [comment] 2022-11-30 00:45
OpenVino:
python version or dev: pip install openvino, pip install openvino-dev[onnx]
c ++ runtime:  We extract the dlls from w_openvino_toolkit_runtime_p_2022.1.0.643.zip, and use find "find_package(OpenVINO REQUIRED)";
Drivers:
It starts with the version that comes with the factory system.
There have been several updates from "Intel® Driver & Support Assistant" [https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html](url)

**Comment by wang7393** [comment] 2022-12-16 02:15
@p-durandin 
Are you talking about the 11th generation cpu? not gpu?
The cpu type of the two machines we are currently watching closely (where this problem often occurs) are: 11th i9-11950H,  11th i5-1180h.
It is worth mentioning that when this problem occurs, we are concerned that the probability of this problem seems to be getting higher and higher. In many cases, this problem may occur once when the machine is turned on.

**Comment by hbalasu1** [comment] 2023-03-03 09:01
Hi @wang7393 

My apology to you for keeping this case for long. 
For your information, we have the latest release, OpenVINO 2022.3, and from the [release note](https://www.intel.com/content/www/us/en/developer/articles/release-notes/openvino-2022-3-lts-relnotes.html), there is some fixes and improvement on GPU devices. 

I also perform experiments using the googlenet-v1 model tested with benchmark_app with the following command.

`benchmark_app -m googlenet-v1\googlenet-v1.xml -d GPU`
Here are the results I obtained; 

`[ INFO ] Count:            18944 iterations
[ INFO ] Duration:         62172.01 ms
[ INFO ] Latency:
[ INFO ]    Median:        1668.72 ms
[ INFO ]    Average:       1661.96 ms
[ INFO ]    Min:           354.68 ms
[ INFO ]    Max:           1775.73 ms
[ INFO ] Throughput:   304.70 FPS



[ INFO ] Count:            19968 iterations
[ INFO ] Duration:         63141.13 ms
[ INFO ] Latency:
[ INFO ]    Median:        1611.51 ms
[ INFO ]    Average:       1601.44 ms
[ INFO ]    Min:           331.58 ms
[ INFO ]    Max:           1741.71 ms
[ INFO ] Throughput:   316.24 FPS


[ INFO ] Count:            19600 iterations
[ INFO ] Duration:         60409.16 ms
[ INFO ] Latency:
[ INFO ]    Median:        309.16 ms
[ INFO ]    Average:       306.83 ms
[ INFO ]    Min:           219.95 ms
[ INFO ]    Max:           357.93 ms
[ INFO ] Throughput:   324.45 FPS

[ INFO ] Count:            18944 iterations
[ INFO ] Duration:         62504.82 ms
[ INFO ] Latency:
[ INFO ]    Median:        1679.27 ms
[ INFO ]    Average:       1670.59 ms
[ INFO ]    Min:           671.48 ms
[ INFO ]    Max:           1793.52 ms
[ INFO ] Throughput:   303.08 FPS

[ INFO ] Count:            17408 iterations
[ INFO ] Duration:         62795.93 ms
[ INFO ] Latency:
[ INFO ]    Median:        1839.66 ms
[ INFO ]    Average:       1823.14 ms
[ INFO ]    Min:           641.57 ms
[ INFO ]    Max:           2043.04 ms
[ INFO ] Throughput:   277.22 FPS `

The results show that the GPU performance is expected with no significant performance reduction. 
Perhaps you could try on your end with the latest OpenVINO 2022.3 and observe the performance of the GPU. 
For your information, there is a time you will see some drop in GPU performance due to various factors like display rendering usage and other utilization of GPU from other applications that might affect the performance of your application too. 

I hope this information help. 
Thank you

**Comment by avitial** [comment] 2023-05-01 20:32
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Closed by avitial** 2023-05-01 20:32 UTC
Labels: category: GPU, support_request, PSE
