### ISSUE TITLE
[Bug] ZeroDivisionError when running code based on Multi Camera Multi Person Python* Demo

### ISSUE THREAD

**Issue by mattans** [openvinotoolkit/openvino#2430] opened 2020-09-27 07:16 UTC
##### System information (version)

- OpenVINO=> 2020.4
- Operating System / Platform => Windows 10
- Compiler => VS 2019
- Problem classification => ZeroDivisionError

##### Detailed description

I have a program based on the Multi Camera Multi Person Python* Demo and I am getting this type of error some times, on some models, for example, the models person-detection-retail-0002\FP32\person-detection-retail-0002.xml person-reidentification-retail-0265\FP32\person-reidentification-retail-0265.xml

```
Processing frame: 5240, fps = 212.3 (avg_fps = 12.8)Traceback (most recent call last):
  File "C:\person_tracker_ov_container\person_tracker_eval.py", line 49, in <module>
    pt_dsa_run(output_path=output_path, capture=capture, detector=object_detector, reid=object_recognizer, networking=False)
  File "C:\person_tracker_ov_container\person_tracker_dsa.py", line 139, in run
    tracker.process(prev_frames, all_detections, all_masks)
  File "C:\person_tracker_ov_container\mc_tracker\mct.py", line 55, in process
    all_detections[i], mask = self._filter_detections(all_detections[i], mask)
  File "C:\person_tracker_ov_container\mc_tracker\mct.py", line 96, in _filter_detections
    ar = h / w
ZeroDivisionError: division by zero
```

##### Steps to reproduce
The problem does not reproduce. When I re-run the detection model & ReID model & test video combination, it runs successfully. However this error occured multiple times over multiple combinations. Is there a non-deterministic part in OpenVINO?

**Comment by jgespino** [comment] 2020-09-28 16:42
Hi @mattans 

Thanks for reaching out, how often do you see the ZeroDevisionError? Are you able to reproduce by using our demo code without any modifications? I was not able to reproduce from my end by running the multi_camera_multi_target_tracking demo using the person-detection-retail-0013 and person-reidentification-retail-0265 on OpenVINO 2020.4.

Could you describe the multiple combinations where you see this error?

Regards,
Jesus

**Comment by mattans** [comment] 2020-09-29 22:03
> Hi @mattans
> 
> Thanks for reaching out, how often do you see the ZeroDevisionError? Are you able to reproduce by using our demo code without any modifications? I was not able to reproduce from my end by running the multi_camera_multi_target_tracking demo using the person-detection-retail-0013 and person-reidentification-retail-0265 on OpenVINO 2020.4.
> 
> Could you describe the multiple combinations where you see this error?
> 
> Regards,
> Jesus

Hi Jesus,
I see it quite a lot, but I cannot reproduce it. Are there are any non-deterministic parts of the algorithm?
I tried fixing the random seed, but it didn't work.
Anyway, I added some debug prints to the code.
Sometimes the algorithm detects bboxes like (0, a, 0 ,b). They have zero width so that's where the failure happens.
I am currently filtering out these detections. But how come the models predict such bboxes in the first place?

**Comment by jgespino** [comment] 2020-10-02 15:32
Hi @mattans 

I don't believe there are any non-deterministic parts. Do you know the confidence value of the predictions with zero width?
Please try to run our demo without any modifications and the following models to see if any zero width predictions are present. 

```
person-detection-retail-0013
person-reidentification-retail-0265 
```

Regards,
Jesus

**Comment by mattans** [comment] 2020-10-11 10:55
Hi @jgespino,
I'm essentially running the demo, just without the visualizations, and in a loop (many models X videos combinations)
I don't think it's related to a specific model, I think it's in the "glue code" - zero area bboxes are allowed, when they shouldn't

**Comment by jgespino** [comment] 2020-10-14 13:32
Hi @mattans 

Please try on the latest 2021.1 release and let me know if the issue is still present. I have been unable to replicate the error, I will try and match your system configuration.

Please share the following:

- CPU model
- Python version
- Cmake version
- Full command used to run demo

Regards,
Jesus

**Comment by jgespino** [comment] 2020-10-29 16:03
Closing, feel free to re-open if additional assistance is needed.

**Closed by jgespino** 2020-10-29 16:03 UTC
Labels: bug, support_request
