### ISSUE TITLE
[Bug] python3 mo.py --version can not print the version result

### ISSUE THREAD

**Issue by wangzhenyu32** [openvinotoolkit/openvino#1907] opened 2020-08-24 08:37 UTC
python3 mo.py --version
Version of Model Optimizer is:

**Comment by jgespino** [comment] 2020-08-24 13:40
Hi @wangzhenyu32 

Thank you for reporting, I was able to reproduce on release 2020.3 and 2020.4. I've opened a bug for the development team to take a look. 

Regards,
Jesus

Ref. 37816

**Comment by Werni2A** [comment] 2020-08-28 20:22
Looks like `openvino/model-optimizer/version.txt` that contains the necessary info was removed in commit `72660e9a4d683dc6a0c50e9fad96e59b7edd1f71`

The original content was:
```
06:46PM December 13, 2018
1.5.12.49d067a0
49d067a07dedf8e95920e9649e890a76451ca648
```

I hope this helps :)

**Comment by jgespino** [comment] 2020-08-31 17:21
@Werni2A That is expected behavior for the open sourced version of the OpenVINO toolkit (GitHub). Are you using the open sourced version? The Intel® Distribution of OpenVINO™ toolkit does appear to have a bug with the `python3 mo.py --version`.

**Comment by Werni2A** [comment] 2020-08-31 17:33
@jgespino Yes, I use a self compiled build. In my case the model optimizer prints `Version of Model Optimizer is: unknown version`, I just thought it would be a similar bug. Is it still possible to add some versioning scheme to the source builds? E.g. the last commit hash or something like that. It would be nice for documentation to know which model optimizer version was used for conversion. If you want to I can open a separate issue for this wish.

**Comment by jgespino** [comment] 2020-09-02 17:49
Hi @Werni2A 

There is another discussion about the versions from open source OpenVINO here: https://github.com/openvinotoolkit/openvino/issues/1435
Please also follow and add your input. 

Regards,
Jesus

**Comment by jgespino** [comment] 2020-09-03 14:13
Fix has been merged into master branch. See https://github.com/openvinotoolkit/openvino/pull/2022

**Closed by jgespino** 2020-09-03 14:13 UTC
Labels: bug, category: MO
