### ISSUE TITLE
[Bug] Asynchronous InferRequest anomaly on Intel Xe hardware

### ISSUE THREAD

**Issue by w3sip** [openvinotoolkit/openvino#18788] opened 2023-07-25 19:53 UTC
##### System information (version)
- OpenVINO Source => Runtime 
- OpenVINO Version => Version 2021.4
- Operating System / Platform => Windows 64 Bit 
- Compiler => Visual Studio 2017 / Cmake
- Problem classification: Bug
- Device use: CPU / GPU

##### Detailed description

I ran into a weird problem with our inference code when ran on a particular hardware.

The code creates a number of InferRequest objects, calls StartAsync on them, and then waits for completion. Logging values of input/output blobs of InferRequest during normal execution -- right before calling StartAsync -- looks like this:

```
23/07/25-14:06:29.965 T <29532> [root] start detection tick=0 input=00000232DCE7FBC0 output=00000232DCF8D3F0
23/07/25-14:06:29.975 T <19588> [root] start detection tick=1 input=00000232DCFFC2C0 output=00000232DD0FB300
23/07/25-14:06:30.021 T <19588> [root] start detection tick=2 input=00000232DD16A1C0 output=00000232DD269A20
23/07/25-14:06:30.035 T <19588> [root] start detection tick=3 input=00000232DD2D88C0 output=00000232DD3D6920
23/07/25-14:06:30.046 T <19588> [root] start detection tick=4 input=00000232DD447000 output=00000232DD544830
23/07/25-14:06:30.058 T <19588> [root] start detection tick=5 input=00000232DD5B3F00 output=00000232DD6B1B30
23/07/25-14:06:30.111 T <19588> [root] start detection tick=6 input=00000232DD720A00 output=00000232DD81EA30
23/07/25-14:06:30.120 T <19588> [root] start detection tick=7 input=00000232DD88D900 output=00000232DD98B930
```

Running on an Intel NUC machine with Intel Xe graphics things look strange:

```
2023-07-25T17:36:39.5740134Z 23/07/25-13:36:39.573 T <17396> [root] start detection tick=0 input=000001B89B8ED040 output=000001B898BB0000
2023-07-25T17:36:39.5820326Z 23/07/25-13:36:39.581 T <10816> [root] start detection tick=1 input=000001B89A5F0040 output=000001B898BB0000
2023-07-25T17:36:39.5896459Z 23/07/25-13:36:39.589 T <10816> [root] start detection tick=2 input=000001B89B01C440 output=000001B898BB0000
2023-07-25T17:36:39.5969593Z 23/07/25-13:36:39.596 T <10816> [root] start detection tick=3 input=000001B89B09B080 output=000001B898BB0000
2023-07-25T17:36:39.6044367Z 23/07/25-13:36:39.604 T <10816> [root] start detection tick=4 input=000001B899F27E40 output=000001B898BB0000
2023-07-25T17:36:39.6119254Z 23/07/25-13:36:39.611 T <10816> [root] start detection tick=5 input=000001B899FA6AC0 output=000001B898BB0000
2023-07-25T17:36:39.6193705Z 23/07/25-13:36:39.619 T <10816> [root] start detection tick=6 input=000001B89A245C40 output=000001B898BB0000
2023-07-25T17:36:39.6267904Z 23/07/25-13:36:39.626 T <10816> [root] start detection tick=7 input=000001B89A2C48C0 output=000001B898BB0000
2023-07-25T17:36:39.6339454Z 23/07/25-13:36:39.633 T <10816> [root] start detection tick=8 input=000001B89A11FDC0 output=000001B898BB0000
2023-07-25T17:36:39.6413575Z 23/07/25-13:36:39.641 T <10816> [root] start detection tick=9 input=000001B89A19EA00 output=000001B898BB0000
```

Note that output blob on all the InferRequest objects has the same value! This obviously leads to incorrect inference results. The only ways to fix this was either to disable async execution (e.g. wait for result of each inference), *or* disabling clDNN plugin in runtime configuration XML file. With just the CPU plugin, the problem disappears.

Nothing changed with the code compared to it working on multiples machines, except attempting to run it on that new hardware.

I'm not sure I can produce an isolated reproduction case right now, but perhaps it is a known issue/limitation.

A screenshot of hardware used ... Windows 10 Pro.

<img width="374" alt="Screen Shot 2023-07-25 at 3 47 28 PM" src="https://github.com/openvinotoolkit/openvino/assets/4392548/c3d29b49-23fd-4cd2-8195-df463fd071c3">

**Comment by wangleis** [comment] 2023-08-17 02:59
@w3sip May I know if issue can be reproduced on master branch? 

Could you share your code about setting OpenVINO properties, loading network model and starting inference?

**Comment by avitial** [comment] 2023-08-28 21:54
Closing this as it can't be reproduced due to insufficient info. Feel free to reopen to provide requested information or to ask any questions related to this topic.

**Closed by avitial** 2023-08-28 21:54 UTC
Labels: bug, category: GPU
