### ISSUE TITLE
openvino cmake error on linux

### ISSUE THREAD

**Issue by Maosquerade** [openvinotoolkit/openvino#844] opened 2020-06-09 15:30 UTC
Hi, I've tried to build openvino with cmake, but I always meet this cmake error:
```
CMake Error at docs/template_extension/CMakeLists.txt:13 (add_library):
  Target "template_extension" links to target "IE::inference_engine_c_api"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
```
and when I make this project, this error will stop me doing that.
Have this issue happened to anyone else ? Or can I change some cmake options to avoid that ?

**Comment by avitial** [comment] 2020-06-09 16:01
Hi @Maosquerade, can you provide more details as to what steps have you taken to build dldt? What CMake options have you used to build the project? Please share environment details that would help reproduce the observed issue (OS, CMake, Python, OpenCV, etc.). 

In addition to the [Build Steps for Linux*](https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#build-on-linux-systems), please take a look at this [guide](https://software.intel.com/content/www/us/en/develop/articles/arm64-sbc-and-ncs2.html) for detailed build steps (ignore the NCS 2 related steps if not applicable). 

Regards,
~Luis

**Comment by Maosquerade** [comment] 2020-06-09 16:12
Thanks！My CMake options:
```
cmake -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_MKL_DNN=ON \
    -DENABLE_CLDNN=OFF \
    -DENABLE_GNA=OFF \
    -DENABLE_SSE42=OFF \
    -DTHREADING=SEQ \
    -DENABLE_SAMPLES=ON \
    ..
```
I tried this CMake option on both centos8.0 and ubuntu16.04, but they have the same CMake Error mentioned above. 
Then I tried to remove the 'docs' building part of CMakeList.txt, and that works for me now. Thanks a lot!

**Comment by lionkunonly** [comment] 2020-06-16 03:55
@ilya-lavrenov I meet the same build error on linux. The commit of OpenVINO I use is `e66e0cd89` which contains the #861. So I think it does not work. 

And removing the `docs` building part still work for me. I want to know what will happen if I remove the `docs` part.

**Comment by ilya-lavrenov** [comment] 2020-06-16 08:12
@ilyachur looks like we don't need to use libraries with prefix `IE::` in docs? Maybe config is not created yet?

**Comment by dkurt** [comment] 2020-07-09 19:15
The problem still exists:
```
CMake Error at inference-engine/CMakeLists.txt:53 (export):
  export given target "gtest" which is not built by this project.
Call Stack (most recent call first):
  inference-engine/CMakeLists.txt:183 (ie_developer_export)


-- Register template_plugin to be built in build-plugins/template_plugin
CMake Error at build/inference-engine/build-plugins/InferenceEngineDeveloperPackageConfig.cmake:24 (add_library):
  add_library cannot create ALIAS target "IE::gtest" because target "gtest"
  does not already exist.
Call Stack (most recent call first):
  docs/template_plugin/CMakeLists.txt:17 (find_package)


CMake Error at build/inference-engine/build-plugins/InferenceEngineDeveloperPackageConfig.cmake:25 (add_library):
  add_library cannot create ALIAS target "IE::gtest_main" because target
  "gtest_main" does not already exist.
Call Stack (most recent call first):
  docs/template_plugin/CMakeLists.txt:17 (find_package)


CMake Error at build/inference-engine/build-plugins/InferenceEngineDeveloperPackageConfig.cmake:29 (add_library):
  add_library cannot create ALIAS target "IE::gmock" because target "gmock"
  does not already exist.
Call Stack (most recent call first):
  docs/template_plugin/CMakeLists.txt:17 (find_package)
```

**Comment by feolcn** [comment] 2020-09-16 08:36
I meet the same build error , Is there any update?

**Comment by ilyachur** [comment] 2020-09-16 10:22
@feolcn What version of the OpenVINO do you use?

**Comment by feolcn** [comment] 2020-09-16 10:54
@ilyachur 2020.4

**Comment by ilyachur** [comment] 2020-09-16 11:05
@feolcn Do you have another version of OpenVINO in your environment?
Can CMake find the old OpenVINO version in [this line](https://github.com/openvinotoolkit/openvino/blob/master/docs/CMakeLists.txt#L14)?

**Comment by feolcn** [comment] 2020-09-16 11:40
@ilyachur  thank you for your quickly replay, after comment the line which include  if and endif   ,it works.
if(NOT InferenceEngine_FOUND)
    set(InferenceEngine_DIR ${CMAKE_BINARY_DIR})
endif()

**Comment by ilyachur** [comment] 2020-09-16 11:43
@feolcn It looks like you have an older version of OpenVINO in your environment and CMake try to use this old version to build the documentation.
Please check that your environment doesn't contain other version of OpenVINO.

**Comment by feolcn** [comment] 2020-09-20 07:06
@ilyachur Thank you,i will follow your comment,and check my evironment

**Comment by avitial** [comment] 2021-01-19 17:09
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.

**Closed** 2021-01-19 17:09 UTC
Labels: category: build
