### ISSUE TITLE
[Bug]libusb is required

### ISSUE THREAD

**Issue by everfate** [openvinotoolkit/openvino#5089] opened 2021-04-02 11:30 UTC
##### System information (version)

- OpenVINO => 2021.3
- Operating System / Platform => ubuntu 20.04 on Rspberrypi4B
- Problem classification: build

##### Detailed description
when i cmake under openvino/build like this

```
cmake -DCMAKE_BUILD_TYPE=Release \
-DENABLE_SSE42=OFF \
-DTHREADING=SEQ  \
-DENABLE_GNA=OFF \
-DENABLE_VPU=ON \
-DENABLE_MYRIAD=ON \
-DENABLE_MKL_DNN=OFF \
-DENABLE_CLDNN=OFF \
-DENABLE_SAMPLES=OFF \
-DENABLE_PYTHON=ON \
-DPYTHON_EXECUTABLE=/usr/bin/python3.8 \
-DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.8.so \
-DPYTHON_INCLUDE_DIR=/usr/include/python3.8 \
.. && make -j3
```

i get following warning and error

```
CMake Warning at inference-engine/cmake/vpu_dependencies.cmake:119 (message):
  VPU_OCL_COMPILER is not found.  Some tests will skipped
Call Stack (most recent call first):
  inference-engine/cmake/dependencies.cmake:39 (include)
  inference-engine/CMakeLists.txt:14 (include)


CMake Warning at inference-engine/cmake/dependencies.cmake:199 (message):
  OpenCV is not found!
Call Stack (most recent call first):
  inference-engine/CMakeLists.txt:14 (include)`

CMake Error at inference-engine/thirdparty/movidius/XLink/XLink.cmake:32 (message):
  libusb is required
Call Stack (most recent call first):
  inference-engine/thirdparty/movidius/XLink/CMakeLists.txt:7 (include)
```

i have compiled cunstom opencv 4.4.0
```
ubuntu@ubuntu:~$ whereis opencv4
opencv4: /usr/include/opencv4 /usr/share/opencv4
```

and i have libusb already
```
/usr/lib/aarch64-linux-gnu/libusb-1.0.so.0
/usr/lib/aarch64-linux-gnu/libusb-1.0.so.0.2.0
/usr/lib/aarch64-linux-gnu/libusbmuxd.so.6
/usr/lib/aarch64-linux-gnu/libusbmuxd.so.6.0.0
/usr/share/doc/libusb-1.0-0
/usr/share/doc/libusbmuxd6
/snap/lxd/19040/lib/aarch64-linux-gnu/libusbredirhost.so.1
/snap/lxd/19040/lib/aarch64-linux-gnu/libusbredirhost.so.1.0.0
/snap/lxd/19040/lib/aarch64-linux-gnu/libusbredirparser.so.1
/snap/lxd/19040/lib/aarch64-linux-gnu/libusbredirparser.so.1.0.0
/snap/lxd/19040/lib/libusb-1.0.so
/snap/lxd/19040/lib/libusb-1.0.so.0
/snap/lxd/19040/lib/libusb-1.0.so.0.3.0
/snap/lxd/19648/lib/aarch64-linux-gnu/libusbredirhost.so.1
/snap/lxd/19648/lib/aarch64-linux-gnu/libusbredirhost.so.1.0.0
/snap/lxd/19648/lib/aarch64-linux-gnu/libusbredirparser.so.1
/snap/lxd/19648/lib/aarch64-linux-gnu/libusbredirparser.so.1.0.0
/snap/lxd/19648/lib/libusb-1.0.so
/snap/lxd/19648/lib/libusb-1.0.so.0
/snap/lxd/19648/lib/libusb-1.0.so.0.3.0
/var/cache/apt/archives/libusbmuxd6_2.0.1-2_arm64.deb
/var/lib/dpkg/info/libusb-1.0-0:arm64.list
/var/lib/dpkg/info/libusb-1.0-0:arm64.md5sums
/var/lib/dpkg/info/libusb-1.0-0:arm64.shlibs
/var/lib/dpkg/info/libusb-1.0-0:arm64.symbols
/var/lib/dpkg/info/libusb-1.0-0:arm64.triggers
/var/lib/dpkg/info/libusbmuxd6:arm64.shlibs
/var/lib/dpkg/info/libusbmuxd6:arm64.list
/var/lib/dpkg/info/libusbmuxd6:arm64.triggers
/var/lib/dpkg/info/libusbmuxd6:arm64.symbols
/var/lib/dpkg/info/libusbmuxd6:arm64.md5sums
/home/ubuntu/Desktop/libusb_find.txt
```

is there something wrong with system PATH?
```
ubuntu@ubuntu:~/openvino/build$ env
SHELL=/bin/bash
PWD=/home/ubuntu/openvino/build
LOGNAME=ubuntu
XDG_SESSION_TYPE=tty
MOTD_SHOWN=pam
HOME=/home/ubuntu
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=192.168.137.1 12844 192.168.137.230 22
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm
LESSOPEN=| /usr/bin/lesspipe %s
USER=ubuntu
DISPLAY=localhost:10.0
SHLVL=1
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1000
SSH_CLIENT=192.168.137.1 12844 22
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/usr/local/sbin:/usr/local/bin:/usr/locale/include:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
SSH_TTY=/dev/pts/0
_=/usr/bin/env
```
what should i do to solve it?

**Comment by zulkifli-halim** [comment] 2021-04-06 02:15
Hi @everfate 
We will reproduce the case and get back to you soon.

**Comment by jgespino** [comment] 2021-04-07 17:57
Hi @everfate 

Thanks for your patience, I believe you are missing the libusb-1.0-0-dev package. Try to install the package and let me know if your issue is resolved. 

`apt install libusb-1.0-0-dev`

Also, ensure you run `./install_build_dependencies.sh` in the project root directory to ensure all dependencies are downloaded. This is mentioned in step 2 in the [building instructions](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux).

Regards,
Jesus

**Comment by jgespino** [comment] 2021-04-14 16:50
Closing, please reopen if additional assistance is needed.

**Closed by jgespino** 2021-04-14 16:50 UTC
Labels: PSE, category: build, support_request

**Comment by drux007** [comment] 2021-11-29 09:53
@everfate, did you manage to solve the issue?

I get the same error:
```
CMake Warning at inference-engine/cmake/vpu_dependencies.cmake:119 (message):
  VPU_OCL_COMPILER is not found.  Some tests will skipped
Call Stack (most recent call first):
  inference-engine/cmake/dependencies.cmake:38 (include)
  inference-engine/CMakeLists.txt:14 (include)
CMake Warning at inference-engine/cmake/dependencies.cmake:293 (message):
  Unable to locate Speech Demo
Call Stack (most recent call first):
  inference-engine/CMakeLists.txt:14 (include)
CMake Error at inference-engine/thirdparty/movidius/XLink/XLink.cmake:36 (message):
  libusb is required
Call Stack (most recent call first):
  inference-engine/thirdparty/movidius/XLink/CMakeLists.txt:7 (include)
  ```
while trying to build `openvino` from soruce inside Docker container [gcc8-armv7hf](https://hub.docker.com/r/conanio/gcc8-armv7hf/).

I use `Ubuntu 18.04` and the latest `2021.4.2` openvino release and I also did install `libusb` with:
```
apt install libusb-1.0-0-dev
```
and all other dependencies in `./install_build_dependencies.sh` in the project root directory.

**Comment by jgespino** [comment] 2021-11-30 19:12
@drux007 Please start a new issue with the details above.

**Comment by drux007** [comment] 2021-12-01 15:47
Thanks @jgespino for your answer, but I immediately hid my comment since I managed to make it work by disabling components I don't need.

**Comment by yuezhuang1387** [comment] 2022-02-21 09:55
> Thanks @jgespino for your answer, but I immediately hid my comment since I managed to make it work by disabling components I don't need.

Hi ,I get the same error, how did you  disable components?

**Comment by Litchilitchy** [comment] 2022-12-26 09:52
> > Thanks @jgespino for your answer, but I immediately hid my comment since I managed to make it work by disabling components I don't need.
> 
> Hi ,I get the same error, how did you disable components?

I got the same error when I was trying to re-build in a built directory. I deleted this directory and re-run then it worked
