### ISSUE TITLE
[CPU] ImportNetwork with dynamic batch

### ISSUE THREAD

**Issue by shining-love** [openvinotoolkit/openvino#18886] opened 2023-07-31 13:30 UTC
- OpenVINO Source => Runtime
- OpenVINO Version => Version 2023.0.1 
- Operating System / Platform => Windows 64 Bit 
- Compiler => Visual Studio 2019
- Problem classification: Model Conversion
- Device use: CPU
- Framework:Pytorch
- Model name: yolov5s.onnx

##### Detailed description
The ImportNetwork function interface read the *. blob file of the dynamic batch and encountered an error when creating an inference request:

Auto iq=executable_ Network. CreateInferRequest()// Error reporting

**Comment by avitial** [comment] 2023-08-28 21:58
@shining-love sorry for the delay, can you provide a minimal sample reproducer for us to take a look? Also are you using Python API or C++ API when the issue occurs?

**Comment by avitial** [comment] 2023-12-22 01:07
Closing this as it can't be reproduced due to insufficient info, I hope previous responses were sufficient to help you proceed or resolve the issue. Feel free to reopen and ask additional questions related to this topic if issue persists.

**Closed by avitial** 2023-12-22 01:07 UTC
Labels: bug, category: CPU, incomplete
