### ISSUE TITLE
Unable to convert TF_slim model to IR format

### ISSUE THREAD

**Issue by varunjain3** [openvinotoolkit/openvino#3826] opened 2021-01-07 17:29 UTC
I want to use my custom fine-tuned InceptionV3 classification model to work with dlstreamer,

I was following this [reference](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/IR-Model-from-Tensorflow/td-p/1181115) and this [reference](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/OpenVINO-2018-R4-After-converted-inception-v3-openvino-result-is/td-p/1165366)

I completed all the steps as per the TF_slim repository. After using the freeze_graph.py file I was able to freeze my model, file size being ~85mbs, exactly similar to this [post](https://github.com/tensorflow/models/issues/2283).

Now I'm not really sure how I can I use mo_tf.py to convert my frozen model to the .XML and .bin format. 
I tried these commands and all of them failed:

```bash
python3 mo_tf.py --input_model final.pb 
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/final.pb
	- Path for generated IR: 	/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/.
	- IR output name: 	final
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Use the config file: 	None
Model Optimizer version: 	2021.2.0-1877-176bdf51370-releases/2021/2
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.output_cut.OutputCut'>): Graph contains 0 node after executing <class 'extensions.front.output_cut.OutputCut'>. It considered as error because resulting IR will be empty which is not usual
```

```bash
python3 mo_tf.py --input_model final.pb -ms '[127.5,127.5,127.5]' --scale 127.5
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/final.pb
	- Path for generated IR: 	/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/.
	- IR output name: 	final
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	[127.5,127.5,127.5]
	- Scale values: 	Not specified
	- Scale factor: 	127.5
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Use the config file: 	None
Model Optimizer version: 	2021.2.0-1877-176bdf51370-releases/2021/2
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.output_cut.OutputCut'>): Graph contains 0 node after executing <class 'extensions.front.output_cut.OutputCut'>. It considered as error because resulting IR will be empty which is not usual
```
```bash
python3 mo_tf.py --input_model final.pb --input input --input_shape=[1,299,299,3]
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/final.pb
	- Path for generated IR: 	/opt/intel/openvino_2021.2.185/deployment_tools/model_optimizer/.
	- IR output name: 	final
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	input
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	[1,299,299,3]
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
TensorFlow specific parameters:
	- Input model in text protobuf format: 	False
	- Path to model dump for TensorBoard: 	None
	- List of shared libraries with TensorFlow custom layers implementation: 	None
	- Update the configuration file with input/output node names: 	None
	- Use configuration file used to generate the model with Object Detection API: 	None
	- Use the config file: 	None
Model Optimizer version: 	2021.2.0-1877-176bdf51370-releases/2021/2
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.front.user_data_repack.UserDataRepack'>): No node with name input
```
## Extra Details:
I used the master branch of tensorflow/models repo commit = ```7786b741e3ee5692819264568341dfc84f6b07b7``` to fine-tune the pre-trained model with TF1.15
Used tf2.1 to convert the frozen model using freeze_graph.py
Using the current development docker image of the dl_streamer for OpenVINO environment
Here are my model files and the frozen model - https://drive.google.com/drive/folders/1lWHnrEos6fy0hE7qr8o832sg1v0cA2zF?usp=sharing

**Comment by avitial** [comment] 2021-01-22 18:22
Closing this as it is a duplicate of https://github.com/openvinotoolkit/openvino/issues/3787.

**Closed by avitial** 2021-01-22 18:22 UTC
