### ISSUE TITLE
Cannot inference with IR model SSD

### ISSUE THREAD

**Issue by lynx97** [openvinotoolkit/openvino#880] opened 2020-06-11 03:52 UTC
I converted successfully inceptionv2 SSD object detection. I followed examples from [this](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_Object_Detection_API_Models.html). But when I tried to inference. It has runtime error that 
```
Traceback (most recent call last):                                                                                             
  File "object_detection_sample_ssd.py", line 213, in <module>                                                             
    sys.exit(main() or 0)                                                                                                 
  File "object_detection_sample_ssd.py", line 59, in main                                                                        
    net = IECore().read_network(model=model_xml, weights=model_bin)                                                       
  File "ie_api.pyx", line 136, in openvino.inference_engine.ie_api.IECore.read_network                                    
  File "ie_api.pyx", line 157, in openvino.inference_engine.ie_api.IECore.read_network                                    
RuntimeError: Cannot create ShapeOf layer PriorBoxClustered_0/0_port id:519
```
That is exactly same as when I load this model in openvino model_server (from docker 18.04 model_server).
```
Content error: Cannot create ShapeOf layer PriorBoxClustered_0/0_port id:519
```
I tried some example model (face_detection, CRNN_tensorflow). It works fine.
Many thanks for any supports

**Comment by avitial** [comment] 2020-06-12 23:09
Hi @lynx97, please provide more details about your environment that could help us reproduce the issue (i.e. versions of OS, OpenVINO, Python, MO command used to convert model, command used to run object_detection_sample_ssd.py, sample input image file, etc.). 

Using 2020.2 release for Linux*, I tested the pre-trained SSD InceptionV2 topology given in the pointed document and both model and sample are working.


~Luis

**Comment by lynx97** [comment] 2020-06-15 07:29
> Hi @lynx97, please provide more details about your environment that could help us reproduce the issue (i.e. versions of OS, OpenVINO, Python, MO command used to convert model, command used to run object_detection_sample_ssd.py, plugin, sample input image file, etc.).
> 
> Using 2020.2 release for Linux*, I tested the pre-trained SSD InceptionV2 topology given in the pointed document and both model and sample are working.
> 
> ~Luis

Thanks for your supports, I had inferenced with IR model SSD successfully. But when I loaded IR model in Openvino model server, It has error `ERROR - Content error: Cannot create ShapeOf layer PriorBoxClustered_0/0_port id:519`. I asked in [#271](https://github.com/openvinotoolkit/model_server/issues/271)

**Comment by avitial** [comment] 2020-06-15 21:57
@lynx97 I am still unable to reproduce the stated issue. Using Model Optimizer on full Linux* 2020.3 package to convert _ssd_inception_v2_coco_2018_01_28_, then copied resulting IR files to the Docker container _openvino/ubuntu18_model_server_ and necessary files (.py sample, car.png) as the Docker image seems to have only a subset of OpenVINO v2020.3 components. 

How are you converting the pre-trained SSD InceptionV2 model to IR? Did you follow a similar approach? If so, make sure both OpenVINO versions in Docker and System match. If not, please provide more details to reproduce.


openvino@5db49a218878:~/cases/880-ssd_inceptionv2$ python3 object_detection_sample_ssd.py -m ~/cases/880-ssd_inceptionv2/ssd_inception_v2_coco_2018_01_28.xml -i car.png -d CPU
[ INFO ] Loading Inference Engine
[ INFO ] Loading network files:
	/home/openvino/cases/880-ssd_inceptionv2/ssd_inception_v2_coco_2018_01_28.xml
	/home/openvino/cases/880-ssd_inceptionv2/ssd_inception_v2_coco_2018_01_28.bin
[ INFO ] Device info:
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 2020.3.0-3467-15f2c61a-releases/2020/3
inputs number: 1
input shape: [1, 3, 300, 300]
input key: image_tensor
[ INFO ] File was added: 
[ INFO ]         car.png
[ WARNING ] Image car.png is resized from (300, 300) to (300, 300)
[ INFO ] Preparing input blobs
[ INFO ] Batch size is 1
[ INFO ] Preparing output blobs
[ INFO ] Loading model to the device
[ INFO ] Creating infer request and starting inference
[ INFO ] Processing output blobs
[0,3] element, prob = 0.896194    (9,1)-(773,252) batch id : 0 WILL BE PRINTED!
[ INFO ] Image out.bmp created!
[ INFO ] Execution successful

[ INFO ] This sample is an API example, for any performance measurements please use the dedicated benchmark_app tool


Regards,
Luis

**Comment by lynx97** [comment] 2020-06-17 08:54
I described how I converted and loading in OVMS in [this link](https://github.com/openvinotoolkit/model_server/issues/271#issuecomment-645243391)

**Comment by avitial** [comment] 2020-06-23 20:42
@lynx97, still unable to reproduce the issue. Converted model as mentioned in provided link above inside Docker image (from Dockerfile) with v2020.3 and IR files work as expected.

Make sure the OpenVINO version in Docker image used to convert to IR matches to v2020.3 as _openvino/ubuntu18_model_server:latest_ seems to run v2020.3. Using your converted models provided ([from other issue link](https://github.com/openvinotoolkit/model_server/issues/271#issuecomment-645243391)) with v2020.2, I can see error ` [ ERROR ] Cannot create ShapeOf layer PriorBoxClustered_0/0_port id:519`. Please double check your OpenVINO versions.


Regards,
Luis

**Comment by avitial** [comment] 2020-07-02 22:43
Closing this as it can't be reproduced, I hope previous responses were sufficient to help you proceed or resolve the issue. Feel free to reopen and ask additional questions related to this topic if issue persists.

**Closed by avitial** 2020-07-02 22:43 UTC
Labels: category: samples
