### ISSUE TITLE
[ ERROR ] Error loading XML file: ..\..\plugins.xml:1:0: File was not found 

### ISSUE THREAD

**Issue by zhaotun** [openvinotoolkit/openvino#395] opened 2020-02-27 08:48 UTC
when I run the "demo_squeezenet_download_convert_run.bat" , error occurred as follows：

[ ERROR ] Error loading XML file: C:\Users\wt\Documents\Intel\OpenVINO\inference_engine_samples_build\intel64\Release\plugins.xml:1:0: File was not found

what is the "plugins.xml:1:0" file ? how to solove the error? thanks.

**Comment by jgespino** [comment] 2020-02-27 23:56
Hi @zhaotun 

Which version of the OpenVINO toolkit are you using? If you recently upgraded to the latest release 2020.1 please make sure to delete or rename the following directory and run the demo again to regenerate.

C:\Users\<User_Name>\Documents\Intel\OpenVINO\inference_engine_demos_build
C:\Users\<User_Name>\Documents\Intel\OpenVINO\inference_engine_samples_build
C:\Users\<User_Name>\Documents\Intel\OpenVINO\openvino_models

Regards,
Jesus

**Comment by zhaotun** [comment] 2020-02-28 01:22
@jgespino  Thank you !

My OpenVINO is 2020.1. It works when I followed your advice.

But when I want to just run the classification_sample_async.exe file in the follow path：
```shell
C:\Users<User_Name>\Documents\Intel\OpenVINO\inference_engine_samples_build\intel64\Release
```
I copy the "car.png" file and model file to the path.
Then I run the following command
```shell
classification_sample_async.exe -i car.png -m FP16\squeezenet1.1.xml -d CPU
```
I get some errors said that "can't find xxx.dll ", then I serch and copy all the lost dlls to the path
![image](https://user-images.githubusercontent.com/13940249/75500859-1a429c80-5a09-11ea-9a1f-71aa9537ed65.png)
After all dlls are ready, run the command again, get the error "plugins.xml:1:0: File was not found"

At this time  I go to the "deployment_tools\demo" path and run the "demo_squeezenet_download_convert_run.bat" , also get the error "plugins.xml:1:0: File was not found".

However, when I go to the "OpenVINO\inference_engine_samples_build\intel64\Release" path ,and delete the dlls just added ,and run the "demo_squeezenet_download_convert_run.bat" , no error occurred.

It seems that I can't run the classification_sample_async.exe file in the path where the exe file is located . why?

**Comment by jgespino** [comment] 2020-02-28 05:44
Hi @zhaotun 

Are you sourcing the environment variables? 
`C:\Program Files (x86)\IntelSWTools\openvino\bin\setupvars.bat`

What version of Visual Studio, CMake, and Python do you have installed? I will try to reproduce.

Regards,
Jesus

**Comment by zhaotun** [comment] 2020-02-28 06:09
My VS is  VS2015 Update 3
![image](https://user-images.githubusercontent.com/13940249/75514954-bbdee380-5a33-11ea-874e-1be6764a363b.png)
And CMake is 3.10.2 , python is 3.5.6
![image](https://user-images.githubusercontent.com/13940249/75515009-e92b9180-5a33-11ea-8e71-5603582d22e9.png)

**Comment by zhaotun** [comment] 2020-02-28 07:52
@jgespino when I go to the follow path , and want to run the  "interactive_face_detection_demo.exe" , the same error "plugins.xml:1:0: File was not found" occurred too.
```shell
C:\Users<User_Name>\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release
```
![image](https://user-images.githubusercontent.com/13940249/75521010-c7390b80-5a41-11ea-9576-05c699091f66.png)


My cmd command is
```shell
interactive_face_detection_demo.exe -i cam -m fd/face-detection-adas-0001.xml -m_ag fd/age-gender-recognition-retail-0013.xml -m_hp fd/head-pose-estimation-adas-0001.xml -m_em fd/emotions-recognition-retail-0003.xml -m_lm fd/facial-landmarks-35-adas-0002.xml -d GPU
```
![image](https://user-images.githubusercontent.com/13940249/75521065-e041bc80-5a41-11ea-9707-de946b86473d.png)

And even I just run "interactive_face_detection_demo.exe -h",  the same error "plugins.xml:1:0: File was not found" occurred too.
 
![image](https://user-images.githubusercontent.com/13940249/75521224-3e6e9f80-5a42-11ea-9562-23b944d42725.png)

**Comment by ArtemSkrebkov** [comment] 2020-02-29 12:14
@zhaotun  
Have you called the script `setupvars.bat` before running the application? If not, please follow
```
cd C:\Program Files (x86)\IntelSWTools\openvino\bin\
setupvars.bat
```
For more information about installing OpenVINO on windows. please refer to https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_windows.html

**Comment by zhaotun** [comment] 2020-03-01 06:39
@ArtemSkrebkov 
I runed the script setupvars.bat

**Comment by alalek** [comment] 2020-03-01 09:31
@zhaotun

> I serch and copy all the lost dlls to the path

This is wrong.
Right way is setupvars.sh approach. Without any manual copying of DLLs which break normal behavior.

**Note**: setupvars.sh has very limited effect for the current terminal only.

---

There is nothing to fix in this repository.

**Comment by DarkPatate68** [comment] 2020-03-04 10:49
I got the same problem with the plugins.xml file not found.
The `setupvars.bat` doesn't seem to work, because I had to manually add the PATH variables myself, in order to find the DLLs.

**Comment by DarkPatate68** [comment] 2020-03-04 10:57
I just found the file in <openVinoFolder>\deployment_tools\inference_engine\bin\intel64\Release and i just copied it next to the EXE and it's working :)

**Comment by jjkislele** [comment] 2020-04-30 09:38
@DarkPatate68 got the right path.

I just want to make some additions. If the environment is Linux, `plugins.xml` locates at `your_openvino_install_root/openvino/inference_engine/lib/intel64`.

BTW, you guys may have the question "why every OpenVINO model needs `plugins.xml`?". Because, when we initialize `InferenceEngine::Core::Core` object, `InferenceEngine::Core::Core` would load default plugin with default plugin path `plugins.xml`.

Precisely, please refer to [InferenceEngine::Core::Core](https://docs.openvinotoolkit.org/latest/classInferenceEngine_1_1Core.html#a13a5038dbd13b44690416fcba45cf68f):

```
InferenceEngine::Core::Core(const std::string & xmlConfigFile = std::string()) explicit

Constructs Inference Engine Core instance using XML configuration file with plugins description.
See RegisterPlugins for more details.

xmlConfigFile
A path to .xml file with plugins to load from. If XML configuration file is not specified, then default Inference Engine plugins are loaded from the default plugin.xml file.
```

Moreover, if we cat the `plugins.xml`:

```
<ie>
    <plugins>
        <plugin name="GNA" location="libGNAPlugin.so">
        </plugin>
        <plugin name="HETERO" location="libHeteroPlugin.so">
        </plugin>
        <plugin name="CPU" location="libMKLDNNPlugin.so">
        </plugin>
        <plugin name="MULTI" location="libMultiDevicePlugin.so">
        </plugin>
        <plugin name="GPU" location="libclDNNPlugin.so">
        </plugin>
        <plugin name="MYRIAD" location="libmyriadPlugin.so">
        </plugin>
        <plugin name="HDDL" location="libHDDLPlugin.so">
        </plugin>
        <plugin name="FPGA" location="libdliaPlugin.so">
        </plugin>
    </plugins>
</ie>
```
So, if we don't need the specific plugin, just remove lines.

Regards,
Thanks

**Comment by ilya-lavrenov** [comment] 2020-05-29 04:36
@DarkPatate68 @jjkislele if some plugins are not needed, we don’t have to fix plugins.xml file and remove some lines. If such plugins are not used, there is no error if they are still mentioned in plugins.xml file

**Comment by ilya-lavrenov** [comment] 2020-05-29 04:37
Suppose the question is answered. Closing

**Closed by ilya-lavrenov** 2020-05-29 04:37 UTC
