### ISSUE TITLE
Big difference in output results between CPU and HDDL

### ISSUE THREAD

**Issue by edwardnguyen1705** [openvinotoolkit/openvino#2637] opened 2020-10-13 01:07 UTC
Dear @jgespino ,
I am able to convert the full [yolov5](https://github.com/edwardnguyen1705/yolov5) v2 models to `OpenVINO`, and here is a converted model: [yolov5xxs_320_custom_up_face](https://github.com/edwardnguyen1705/openvino/tree/master/detection/checkpoints). However, there is a significant mAP drop when loading the model to `HDDL` device compared to `CPU`.  While doing [`plugins['HDDL'].set_config({'VPU_HW_STAGES_OPTIMIZATION': 'NO'})`](https://github.com/edwardnguyen1705/openvino/blob/master/base/base_network.py) can reduce the mAP drop, the speed (FPS) decreases almost half.
I observe that with `plugins['HDDL'].set_config({'VPU_HW_STAGES_OPTIMIZATION': 'YES'})`, the predicted confidence scores of the model drop.
The experiments have been conducted in both `2020R1` and `2020R4`. 
Here is our hardware info: 
[tank_core_i5_info.txt](https://github.com/openvinotoolkit/openvino/files/5364781/tank_core_i5_info.txt)

Could you mind examining the given model? If you need more information, please just let me know.
I really appreciate your time.

_Originally posted by @edwardnguyen1705 in https://github.com/openvinotoolkit/openvino/issues/1551#issuecomment-707057635_

I will try out the OpenVINO 2021.1 release version, but we would like to use the 2020.R1 version that is employed in our deploy environment.

**Comment by jgespino** [comment] 2020-10-13 19:07
Hi @edwardnguyen1705 

Thanks for reposting as a new issue, this model has not been validated with OpenVINO. Are you using the model optimizer to convert the model to IR format? Please try adding the --scale parameter and see if you obtain the expected results. 

Regards,
Jesus

**Comment by edwardnguyen1705** [comment] 2020-10-14 01:51
Dear @jgespino ,
Yes, you're right this model has not been tested by your team. And here is how I got the `IR`:

```
INPUT_SIZE=320
MODEL_NAME=yolov5xxs_${INPUT_SIZE}_custom_up_face

python ~/intel_2020R1/openvino/deployment_tools/model_optimizer/mo_onnx.py \
--input_model /Users/thanhnguyen/Documents/Sourcecodes/yolov5/weights/onnx/${MODEL_NAME}.onnx \
--output_dir /Users/thanhnguyen/Documents/Sourcecodes/yolov5/weights/openvino \
--input_shape="[1,3,${INPUT_SIZE},${INPUT_SIZE}]" \
--data_type FP16 \
--log_level DEBUG
```

I already did the scaling in the preprocessing the input image: https://github.com/edwardnguyen1705/openvino/blob/b82db3ed995c9805f1328be3ab3d4781c2ef9237/detection/detection.py#L33

Or maybe I miss understand the parameter `--scale` function in the conversion process?

**Comment by jgespino** [comment] 2020-10-14 15:36
Hi @edwardnguyen1705 

Try converting the model by passing `--scale 255` and not use it in the preprocessing. Additional information can be found in the MO documentation section [When to Specify Mean and Scale Values](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_Converting_Model_General.html#when_to_specify_mean_and_scale_values).

Also, could you share your model to test on my side?

Regards,
Jesus

**Comment by edwardnguyen1705** [comment] 2020-10-14 16:22
Dear @jgespino ,

Thanks for your time. I will convert the model passing the parameter `--scale 255` like what you suggested.
I would like to share two converted models:
1. At first, I think the problem caused by the `torch.nn.Upsample`, so I customized an `Upsample` class, like this: https://github.com/edwardnguyen1705/yolov5/blob/9a6e4a87f75dc69a178aa50509ae951cf899b6d1/models/common.py#L150  
[custom_Upsample.zip](https://github.com/openvinotoolkit/openvino/files/5379527/custom_Upsample.zip)
2. Use the default `torch.nn.Upsample`
[torch_nnUpsample.zip](https://github.com/openvinotoolkit/openvino/files/5379529/torch_nnUpsample.zip)

If you need more information or have any suggestion, just let me know.

Best regards,
Edward

**Comment by edwardnguyen1705** [comment] 2020-10-16 08:44
Dear @jgespino ,

I did add the parameter `--scale 255` in the conversion command, and do not perform `img / 255.0` in the preprocessing step, but the issue still remains.

Best regards,
Edward

**Comment by jgespino** [comment] 2020-10-16 13:02
@edwardnguyen1705 Let me check with my peers to see if they have additional suggestions, we will get back to you shortly.

**Comment by agungor2** [comment] 2020-10-21 22:40
@edwardnguyen1705, thanks for the details. We are working on model enabling for yolov5 models.  I ran your IR files with benchmark app and saw 752 on HDDL whereas 175 with I7-6700K. 

Can you attach the original ONNX model file for me to reproduce the issue? Please also point me to the location for .pt files and your steps to create ONNX file.

**Comment by edwardnguyen1705** [comment] 2020-10-22 16:09
Dear @agungor2 Thanks so much for your effort. I would like to send you all models: `PyTorch`, `ONNX`, and `OpenVINO`: 
[yolov5xxs_320_face.zip](https://github.com/openvinotoolkit/openvino/files/5424023/yolov5xxs_320_face.zip)

You can take a look a the `README.md` file of this repo, in which I describe every step that I do to convert: [yolov5](https://github.com/edwardnguyen1705/yolov5).

The configuration for the `PyTorch` model is [yolov5xxs.yaml](https://github.com/edwardnguyen1705/yolov5/blob/conversion-all/models/yolov5xxs.yaml)

If you have further questions, please let me know.

Best regards,
Edward

**Comment by violet17** [comment] 2020-10-30 14:33
I think the HDDL plugin is not suitable for yolov5. Since I revised the code in myriad plugin, and rebuilt openvino, then I got the same results as CPU.
That may be the reason that the scale in graph transformer not work for every network and the way MYX calculate.

**Comment by agungor2** [comment] 2021-06-11 16:35
Hello @edwardnguyen1705 , 

There is a new pull request that is merged to the master for yolo-v5 support. Would you like to take a look and give it a try now? 
https://github.com/openvinotoolkit/openvino/pull/5976

**Closed** 2021-06-23 00:56 UTC
Labels: TCE, category: VPU
