### ISSUE TITLE
[Bug]: Using benchmark_app to run model on GPU target casing crash

### ISSUE THREAD

**Issue by dimitryn** [openvinotoolkit/openvino#19429] opened 2023-08-27 15:14 UTC
Ubuntu 2022

OpenVino 2023.0.1

Hi , converted model from onnx running without problem on CPU target, when I change target to GPU 
I am getting error

(openvino_env) administrator@xxxxx:~/Downloads/ZippyPoint$ benchmark_app -m /home/administrator/Downloads/LightGlue/DISK/QVGA/lightglue_disk_extractor_qvga.xml -d GPU  -hint  none -nstreams 1 -inference_only 
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ] 
[ INFO ] Device info:
[ INFO ] GPU
[ INFO ] Build ................................. 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ] 
[ INFO ] 
[Step 3/11] Setting device configuration
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 6.17 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Model inputs:
[ INFO ]     /Pad_output_0 , image (node: image) : f32 / [...] / [1,3,240,320]
[ INFO ] Model outputs:
[ INFO ]     keypoints (node: keypoints) : i64 / [...] / [1,..76800,2]
[ INFO ]     scores (node: scores) : f32 / [...] / [1,..76800]
[ INFO ]     descriptors (node: descriptors) : f32 / [...] / [1,..76800,128]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Model batch size: 1
[Step 6/11] Configuring input of the model
[ INFO ] Model inputs:
[ INFO ]     /Pad_output_0 , image (node: image) : u8 / [N,C,H,W] / [1,3,240,320]
[ INFO ] Model outputs:
[ INFO ]     keypoints (node: keypoints) : i64 / [...] / [1,..76800,2]
[ INFO ]     scores (node: scores) : f32 / [...] / [1,..76800]
[ INFO ]     descriptors (node: descriptors) : f32 / [...] / [1,..76800,128]
[Step 7/11] Loading the model to the device
[ ERROR ] Check 'false' failed at src/inference/src/core.cpp:114:
Check 'false' failed at src/plugins/intel_gpu/src/plugin/program.cpp:386:
GPU program build failed!
std::bad_alloc

Traceback (most recent call last):
  File "/home/administrator/Downloads/openvino_env/lib/python3.10/site-packages/openvino/tools/benchmark/main.py", line 408, in main
    compiled_model = benchmark.core.compile_model(model, benchmark.device, device_config)
  File "/home/administrator/Downloads/openvino_env/lib/python3.10/site-packages/openvino/runtime/ie_api.py", line 398, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Check 'false' failed at src/inference/src/core.cpp:114:
Check 'false' failed at src/plugins/intel_gpu/src/plugin/program.cpp:386:
GPU program build failed!
std::bad_alloc

Please assist.

**Comment by ilyachur** [comment] 2023-08-28 03:38
CC @vladimir-paramuzov @p-durandin

**Comment by vurusovs** [comment] 2023-08-28 07:34
@dimitryn hello!
Could you share the size of .bin file and how much memory is consumed during CPU execution? Because `std::bad_alloc` mostly caused when application is out of memory, you may try decrease memory consumption by applying some suggestions from https://github.com/openvinotoolkit/openvino/blob/master/docs/optimization_guide/memory_optimization_guide.md
Could you also try C++ benchmark_app instead of Python version?

**Comment by dimitryn** [comment] 2023-08-28 08:09
Hello @vurusovs !
Bin size 2.2 MB
with c++ benchmark_app I am getting error
[ ERROR ] Check 'false' failed at src/inference/src/core.cpp:114:
Check 'false' failed at src/plugins/intel_gpu/src/plugin/program.cpp:386:
GPU program build failed!
std::bad_array_new_length

from ubuntu top on CPU run
![image](https://github.com/openvinotoolkit/openvino/assets/36672340/96ebd95c-bf27-449c-88f2-19af07735f5c)

**Comment by p-durandin** [comment] 2023-09-18 07:18
@dimitryn could you please share the model?

**Comment by avitial** [comment] 2023-12-22 16:05
Closing this as it can't be reproduced due to insufficient info. Feel free to reopen and ask additional questions related to this topic. If issue persists kindly share the model as previously requested.

**Closed by avitial** 2023-12-22 16:05 UTC
Labels: bug, category: GPU
