### ISSUE TITLE
Int 8 Quantization for Multilabel Classification

### ISSUE THREAD

**Issue by aanubhav** [openvinotoolkit/openvino#267] opened 2019-10-01 10:16 UTC
Hi, I am trying to convert OpenVINO optimized model (with xml and bin files) for multi-label classification to a int8 quantized model.

i am using the attached converter.py  and convert_annotations.py file for converting the annotations, using the command

python3 convert_annotation.py multilabel  --images_dir CheXpert-v1.0-small/ --image_set_file ./test.csv -ss 32

i able to get the json and pickle files.

while executing the calibration file using command :

python3 /opt/intel/openvino/deployment_tools/tools/calibration_tool/calibrate.py -c densenet-calib.yml

It throws me the following error :

09:38:21 openvino.tools.calibration WARNING: presenter was set to 'return_value'
09:38:21 openvino.tools.calibration INFO: Processor: x86_64
09:38:21 openvino.tools.calibration INFO: Collecting FP32 statistics for /root/repo_pipe_multilabel/OPENVINO_Latest/multi_label_densenet121_frozen_model_latest.xml...
IE version: 1.6.custom_releases/2019/R1.1_28dfbfdd28954c4dfd2f94403dd8dfc1f411038b
Loaded CPU plugin version: 1.6.23780
  0%|                                                                                                                                                                                       | 0/32 [00:00<?]Traceback (most recent call last):
  File "/opt/intel/openvino/deployment_tools/tools/calibration_tool/calibrate.py", line 21, in <module>
    network = calibration.Calibrator(config).run()
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/calibration/calibrator.py", line 51, in run
    collect_performance_counters=True)
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/calibration/base_calibrator.py", line 380, in infer
    collect_performance_counters=collect_performance_counters)
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/calibration/base_calibrator.py", line 469, in _infer
    output_callback=process_dataset_callback.callback)
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/accuracy_checker/accuracy_checker/model_evaluator.py", line 72, in process_dataset
    self.metric_executor.update_metrics_on_batch(annotations, predictions)
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/accuracy_checker/accuracy_checker/metrics/metric_executor.py", line 96, in update_metrics_on_batch
    zipped_transform(self.update_metrics_on_object, annotation, prediction)
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/accuracy_checker/accuracy_checker/utils.py", line 137, in zipped_transform
    iter_res = fn(*values)
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/accuracy_checker/accuracy_checker/metrics/metric_executor.py", line 85, in update_metrics_on_object
    metric.metric_fn.submit(annotation, prediction)
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/accuracy_checker/accuracy_checker/metrics/metric.py", line 146, in submit
    annotation_, prediction_ = self._resolve_representation_containers(annotation, prediction)
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/accuracy_checker/accuracy_checker/metrics/metric.py", line 139, in _resolve_representation_containers
    resolved_prediction = resolve(prediction, self.prediction_types, 'prediction')
  File "/opt/intel/openvino_2019.1.144/python/python3.5/openvino/tools/accuracy_checker/accuracy_checker/metrics/metric.py", line 131, in resolve
    raise ConfigError(message_not_found.format(representation_name, self.name))
openvino.tools.accuracy_checker.accuracy_checker.config.config_validator.ConfigError: suitable prediction for metric multi_accuracy not found

(.py and .yml files are converted to txt files for upload purposes)
[convert_annotation.txt](https://github.com/opencv/dldt/files/3675630/convert_annotation.txt)
[converter.txt](https://github.com/opencv/dldt/files/3675631/converter.txt)
[densenet-calib.txt](https://github.com/opencv/dldt/files/3675654/densenet-calib.txt)

Dataset i'm using

[int8 issue.zip](https://github.com/opencv/dldt/files/3675665/int8.issue.zip)

**Comment by shubha-ramani** [comment] 2019-10-01 20:43
Dear @aanubhav 

Thanks for attaching your files ! Will look into it shortly.

Shubha

**Comment by shubha-ramani** [comment] 2019-10-02 20:49
Dear @aanubhav 

I noticed that you are using an extremely old version of OpenVino openvino_2019.1.144. We just released 2019R3 today.  Can you kindly retry on R3 ? If the problem persists let me know.

Thanks,

Shubha

**Comment by aanubhav** [comment] 2019-10-03 07:07
Hi @shubha-ramani 

With this version i am able to quantize the tensorflow's object detection api models, but not this one.I think i am passing something wrong in the "densenet-calib.yml" file, this is where i need help because i'm not able to see any examples with multi-accuracy as a metric.

Also i tried DL workbench in 2019_R2 version, but the int8 quantization button (after following the steps in the documentation) is still greyed out, Until i'm using a FP32 model it shouldn't happen right ?

**Comment by shubha-ramani** [comment] 2019-10-03 20:28
Dear @aanubhav 
I guess I don't understand your problem - why can't you retry with R3 ? The issue is, let me explain, OpenVino software has changed vastly from R1.1 to R3. You really cannot reproduce an issue on R1.1 and draw parallels to what exists in the software today.

Let me try and understand you better though. Why is it that you cannot reproduce this issue on R3 ?

Thanks,

Shubha

**Comment by aanubhav** [comment] 2019-10-04 06:09
Sure @shubha-ramani  ,

Initially, i was thinking i am not passing the "densenet-calib.yml" with correct parameters.
Anyways, I will give R3 a try today and let you know.

Thanks 
Anubhav

**Comment by shubha-ramani** [comment] 2019-10-04 16:16
Dear @aanubhav 
I sincerely appreciate your willingness to try OpenVino R3.  Let us know what happens,

Thanks,

Shubha

**Comment by ivan-slobozhan** [comment] 2019-12-11 12:53
Dear @aanubhav 

I faced the same issue while working on a similar problem.

The problem here is that in your config file, you are using a classification adapter. Classification adapter (adapters/classification.py) is using ClassificationPrediction or ArgMaxClassificationPrediction representations in `process` function. Now, if you look closer into metrics/multilabel_recognition.py file, where multi_accuracy is defined, you can observe that it recognizes only MultiLabelRecognitionPrediction 
`prediction_types = (MultiLabelRecognitionPrediction, )`
So, what you need is to include the ClassificationPrediction and ArgMaxClassificationPrediction representations into allowed `prediction_types`. This should fix the issue.

Hope it helps,

Ivan

**Comment by AnastasiaKazantaeva** [comment] 2020-07-13 20:35
It seems that the issue is not actual anymore. Closing it. Feel free to reopen or better create a new issue.

**Closed by AnastasiaKazantaeva** 2020-07-13 20:35 UTC
