### ISSUE TITLE
dispatcherEventReceive() Read failed -1 or -4 on 2019-R1.1

### ISSUE THREAD

**Issue by UrsusVoid** [openvinotoolkit/openvino#230] opened 2019-08-20 05:06 UTC
I'm trying to use multiple NCS2 devices to run multiple execution networks simultaneously,
but my test app always crashes eventually (sometimes after tens of seconds sometimes after several hours) with the following errors:
```
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Failed to read output from FIFO: NC_ERROR
/usr/src/debug/openvino-ie/2019-R1.1/dldt-2019_R1.1/inference-engine/src/vpu/myriad_plugin/myriad_executor.cpp:343
/usr/include/openvino-ie/details/ie_exception_conversion.hpp:71
E: [xLink] [     12754] dispatcherEventReceive:347	dispatcherEventReceive() Read failed -4 | event 0x7f6760a80e90 XLINK_WRITE_REQ
E: [xLink] [     12754] eventReader:233	eventReader stopped
I: [xLink] [     12754] dispatcherReset:480	Resetting...
I: [xLink] [     12754] dispatcherReset:501	Pending event is XLINK_READ_REL_REQ, size is 4, Mark it served
I: [xLink] [     12754] closeDeviceFdAndResetScheduler:450	Dispatcher Cleaning...
E: [ncAPI] [     12754] ncFifoReadElem:3353	Packet reading is failed.
```
or
```
terminate called recursively
E: [xLink] [    935407] dispatcherEventReceive:347	dispatcherEventReceive() Read failed -1 | event 0x7fb6313bfe90 XLINK_READ_REL_REQ
E: [xLink] [    935407] eventReader:233	eventReader stopped
E: [xLink] [    935407] dispatcherEventSend:924	Write failed header -1 | event XLINK_READ_REL_RESP
E: [xLink] [    935407] eventSchedulerRun:584	Event sending failed
I: [xLink] [    935407] dispatcherReset:480	Resetting...
I: [xLink] [    935407] closeDeviceFdAndResetScheduler:450	Dispatcher Cleaning...
I: [xLink] [    935407] closeDeviceFdAndResetScheduler:465	Cleaning Successfully
I: [xLink] [    935407] eventSchedulerRun:616	Scheduler thread stopped
E: [xLink] [    935407] XLinkReadDataWithTimeOut:1343	Event data is invalid
E: [ncAPI] [    935407] ncFifoReadElem:3353	Packet reading is failed.
E: [xLink] [    935407] XLinkReadDataWithTimeOut:1343	Event data is invalid
E: [ncAPI] [    935407] checkGraphMonitorResponse:1673	XLink error, rc: X_LINK_ERROR
E: [ncAPI] [    935407] ncGraphQueueInference:3822	Can't get trigger response
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Failed to read output from FIFO: NC_ERROR
/usr/src/debug/openvino-ie/2019-R1.1/dldt-2019_R1.1/inference-engine/src/vpu/myriad_plugin/myriad_executor.cpp:343
/usr/include/openvino-ie/details/ie_exception_conversion.hpp:71
```

I'm currently using 2019-R1.1 cross-compiled on my yocto linux, five NCS2 devices, and a realsense camera.
My test app is pretty simple, it just creates 10 execution networks with `person-detection-retail-0013` model, creates a thread per each execution network, and performs `Infer()` on the latest frame from the camera repeatedly.

What can I do to further dig into this issue?

**Comment by LushSplendor** [comment] 2019-08-20 11:07
Hm.. this error might be caused by the RealSense depth camera.
Now I'm trying to reproduce the same issue without the camera.

**Comment by shubha-ramani** [comment] 2019-08-20 17:19
Dear @LushSplendor 
Please keep us updated.  By the way, don't hesitate to inquire also on  [the intel real sense forum](https://forums.intel.com/s/topic/0TO0P00000018NTWAY/intel-realsense-technology) if you've root caused it to be Intel Real Sense Camera related.

Thanks !

Shubha

**Comment by LushSplendor** [comment] 2019-08-21 05:24
Without the RealSense camera, after roughly 3.5 hours of execution, I got this error:
```
terminate called recursively
terminate called after throwing an instance of 'E: [xLink] [    556829] dispatcherEventSend:934	Write failed event -4

E: [xLink] [    556829] dispatcherEventReceive:347	dispatcherEventReceive() Read failed -4 | event 0x7f84de5e9e90 XLINK_READ_REL_RESP

E: [xLink] [    556829] eventReader:233	eventReader stopped
I: [xLink] [    556829] dispatcherReset:480	Resetting...
I: [xLink] [    556829] dispatcherReset:501	Pending event is XLINK_WRITE_REQ, size is 522240, Mark it served

I: [xLink] [    556829] closeDeviceFdAndResetScheduler:450	Dispatcher Cleaning...
E: [ncAPI] [    556829] ncGraphQueueInference:3816	Can't send trigger request
I: [xLink] [    556830] closeDeviceFdAndResetScheduler:465	Cleaning Successfully

I: [xLink] [    556830] eventSchedulerRun:616	Scheduler thread stopped
InferenceEngine::details::InferenceEngineException'
  what():  Failed to queue inference: NC_ERROR
/usr/src/debug/openvino-ie/2019-R1.1/dldt-2019_R1.1/inference-engine/src/vpu/myriad_plugin/myriad_executor.cpp:330
/usr/include/openvino-ie/details/ie_exception_conversion.hpp:71
```

**Comment by shubha-ramani** [comment] 2019-08-21 18:41
Dear @LushSplendor 
You mentioned that you are on 2019-R1.1. OpenVino recently released R2. I know it's a bit inconvenient but can you retry on R2 ? The reason I ask is because it's very common for problems to miraculously be fixed when people move to the latest updated release.

I know that we fixed some multi-threading/Inference Engine issues in R2.

Let me know how I can help.
 
Shubha

**Comment by LushSplendor** [comment] 2019-08-23 02:07
Dear @shubha-ramani 
Sadly, I can't test R2 as I have another issue on R2 (#226).
Is there any way to see more logs, possibly from the NCS stick itself, in addition to the ncAPI & XLink logs?

**Comment by sahira-rizvi** [comment] 2022-03-23 01:25
Closing, feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira

**Closed by sahira-rizvi** 2022-03-23 01:25 UTC
