### ISSUE TITLE
[Bug] E: BSO found 0 ioexpander device

### ISSUE THREAD

**Issue by Tylersuard** [openvinotoolkit/openvino#4324] opened 2021-02-14 01:26 UTC
##### System information (version)
<!-- Example
- OpenVINO => 2021
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

I followed the tutorial here: https://software.intel.com/content/www/us/en/develop/articles/human-pose-estimation-demo-microsoft-windows.html

Getting the above error.  Running console in admin mode.  

Running this command: human_pose_estimation_demo.exe –h
causes the error.

**Comment by avitial** [comment] 2021-02-16 16:36
@Tylersuard assume your issue is related to HDDL card usage with OpenVINO, but can't help without details about your issue. Please provide more details of the issue you are facing and environment information (OS, Hardware specs, OpenVINO version, etc.). 

Anything that could help identify the issue and troubleshoot would be great, or if its a specific problem or bug report please provide steps you followed so it can reproduce.


~Luis

**Comment by avitial** [comment] 2021-03-17 16:24
Closing this as it cannot be reproduced due to missing information. Feel free to reopen and provide additional information related to this topic if issue persists.

**Closed by avitial** 2021-03-17 16:24 UTC
Labels: incomplete, support_request
