### ISSUE TITLE
[Bug] Crash during app exit when using OpenVino GPU plugin

### ISSUE THREAD

**Issue by venki-thiyag** [openvinotoolkit/openvino#13729] opened 2022-10-30 15:56 UTC
##### System information (version)

- OpenVINO=> 2022.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification => Model inference, crash during app exit

##### Detailed description
Crash is not observed all the time, but sometimes observed when app is closed and call stack is pointing to openvino_intel_gpu_plugin.dll
Attached crash dump.

[small.zip](https://github.com/openvinotoolkit/openvino/files/9896236/small.zip)

![image](https://user-images.githubusercontent.com/8221785/198888457-f7c65902-cee8-4773-b230-aa104b13cbaa.png)

**Comment by andrei-kochin** [comment] 2022-10-30 21:31
Hello @venki-thiyag,

Thanks for reaching OpenVINO! we'll look into it

@vladimir-paramuzov could you please take a look?

**Comment by brmarkus** [comment] 2022-10-31 17:48
Can you provide any details about your application?
Do you use a Release-build or a Debug-build, can you see the crash with both types?

Is your application using multiple threads to interact with OpenVINO?

Can you share (pseudo-)code for how you initialize OpenVINO and how you de-initialize it? Do you allocate any OpenVINO resources on the heap (e.g. with the `new()` operator?

Do you see a chance to try a different neural network (maybe it has a side-effect)?

Do you use a persistent or temporary OpenVINO model-cache?

**Comment by venki-thiyag** [comment] 2022-11-01 03:51
@brmarkus 

Crash was in release mode.

Application is multi threaded, but OpenVINO object is constructed and used in single threaded manner, but there is a chance that destructor might be called from different thread.

**Memory:** Yes, OpenVINO is allocated new operator.

**Usage:**
With respect to structure, in header file following objects are declared:

```
        ov::InferRequest infer_request_;
        ov::Tensor input_tensor_;
        ov::Tensor output_tensor_;

``` 

in loadModel API:
input and output tensor are created and also infer_request is also initialised.

in runModel API:

infer request object is initialised with input and output tensor
infer() API is called

in clearModel API is called as follows:

```
void OpenVinoProcessing::clearModel()
{
    infer_request_.cancel();
    infer_request_.wait_for(std::chrono::milliseconds(500));
}

```

Not sure if any other cleanup API needs to be called.

Haven't yet tried with other models, not sure if this needs to be done.

With respect to caching, we haven't set any specific details, we are creating with default values.

**Comment by venki-thiyag** [comment] 2022-11-02 11:36
Another point, where can we find debug symbols for released binaries, so that we can try to troubleshoot crash issues ourselves.

**Comment by avitial** [comment] 2022-11-21 21:17
@venki-thiyag would it be possible to share a minimal sample reproducer? Does the error occur with other models (i.e. any model from OMZ)? 

@vladimir-paramuzov @andrei-kochin could you please take a look?

**Comment by avitial** [comment] 2022-12-29 20:30
Closing this as it can't be reproduced due to missing details. Feel free to reopen and provide requested additional information if issue persists.

**Closed by avitial** 2022-12-29 20:30 UTC
Labels: category: GPU, support_request

**Comment by venki-thiyag** [comment] 2023-03-09 14:33
After upgrading to 2022.3 issue is not observed, so we can close this.
