### ISSUE TITLE
GENERAL_ERROR axis must be in the range of [0, 5) , actually -1

### ISSUE THREAD

**Issue by ynjiun** [openvinotoolkit/openvino#12373] opened 2022-07-31 22:22 UTC
Hi 
I have converted my model.onnx successfully to IR (model.xml and model.bin, model.mapping) using mo command as below:

`mo --input_model ./model.onnx --input left_img,right_img --input_shape [1,3,320,1152],[1,3,320,1152] --data_type=FP16 `

But when I tried to compile IR to MYRIAD blob, I encountered the following error:
```
[ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/frontend/frontend.cpp:592 Failed to compile layer "4830": [ GENERAL_ERROR ] 
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu20/b/repos/openvino/src/plugins/intel_myriad/graph_transformer/src/stages/gather_elements.cpp:160 axis must be in the range of [0, 5) , actually -1
```
Attached please find my model.onnx in model.zip
[model.zip](https://github.com/openvinotoolkit/openvino/files/9229817/model.zip)

The compile command I used is:
```
/opt/intel/openvino_2022/tools/compile_tool/compile_tool \
    -m ./model.xml \
    -d MYRIAD \
    -ip FP16 \
    -VPU_NUMBER_OF_SHAVES 8 \
    -VPU_NUMBER_OF_CMX_SLICES 8 \
    -op FP16 
```

What am I missing? Please help. Thanks.

**Comment by jgespino** [comment] 2022-08-01 20:46
Hi @ynjiun 

It looks like the issue is with the GatherElements op in your model with the axis attribute specified as `-1`. Although the MYRIAD plugin should support the GatherElemenets Op, it's expecting a positive value for the axis. I'll have to confirm with the development team if MYRIAD supports negative values for this op or if this is by design.

https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_myriad/graph_transformer/src/stages/gather_elements.cpp#L160

Regards,
Jesus

Ref. 88690

**Comment by ZeicBeniamin** [comment] 2022-12-02 10:13
Hello!
I have the same problem with the GatherElements operator. Is there any quick fix on this issue (like manually modifying the code and rebuilding the sources)?

**Comment by avitial** [comment] 2023-01-10 02:20
@ynjiun @ZeicBeniamin the '_GatherElements_' operator does not support negative axis for Myriad plugin, so the error you see is the expected behavior. 

The following PR https://github.com/openvinotoolkit/openvino/pull/13995 will update the documentation to capture this information.

**Comment by avitial** [comment] 2023-02-16 23:48
PR has been merged, closing this issue.

**Closed by avitial** 2023-02-16 23:48 UTC
Labels: bug, category: VPU, PSE
