### ISSUE TITLE
[VPU] Unsupported precision I32

### ISSUE THREAD

**Issue by laggui** [openvinotoolkit/openvino#250] opened 2019-09-16 17:38 UTC
Hi all,

I successfully converted my SSDLite models (without any post-processing) from ONNX to OpenVINO IR to use with the Inference Engine. I have one FP32 model that I managed to benchmark on my Intel CPU, and another model in half precision (FP16) to evaluate the performance on the NCS2.

The model optimizer successfully generates the IR model for my FP16 model, but when I try to infer an input image I get the following error:

```sh
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  [VPU] Unsupported precision I32for data 7648_const
Aborted (core dumped)
```

This constant is associated to a reshape operation on the outputs, and I'm not sure why the Model Optimizer successfully generated the IR for the specified data type (FP16) without converting that integer constant to a supported type for the VPU.

I haven't been able to find much on this, any help is appreciated!

Thanks :)

**Comment by shubha-ramani** [comment] 2019-09-16 17:43
Dear @laggui 
Please attach your *.IR and your inference script as a *.zip so that we can reproduce it. Also are your SSDLite models public or did you custom build them ? Having access to the SSDLite original models as well as the mo command you used to generate IR would also be helpful.

Thanks,

Shubha

**Comment by laggui** [comment] 2019-09-16 18:30
@shubha-ramani the models are based on our PyTorch implementation, but the models I am trying to benchmark with have dummy weights so I don't mind releasing the ONNX models exported from PyTorch. You can download the necessary files [here](https://drive.google.com/file/d/1Dzx3nb4T8P88R8dCKi8haGFzz0aZkItf/view?usp=sharing).

**Model Optimizer command**
```sh
$ python mo.py -m SSDLite_fp16.onnx -n ssdlite_fp16 --output_dir ssdlite_fp16 -i [1,3,300,300] --data_type FP16
```

**Inference script reference**
I included the C++ project file as well as the CMake file to build the example. From within the `bin/intel64/Release` dir, run the following command to execute the sample on your NCS2:

```sh
$ ./openvino_inference_example <ssdlite_fp16.xml_path> <input_image> MYRIAD -pc
```

If you want to test the FP32 model on your CPU, you can use the following command:

```sh
$ ./openvino_inference_example <ssdlite.xml_path> <input_image> CPU -pc
```

Let me know if you need anything else!

**Comment by shubha-ramani** [comment] 2019-09-17 17:14
Dear @laggui ,
I downloaded your tar.gz. And thanks for the additional information above. I will definitely debug this and take a look !

Shubha

**Comment by shubha-ramani** [comment] 2019-09-18 20:56
Dearest @laggui 
Thanks for all your debugging materials ! You'll be happy to know that this is surely a bug and I have filed it on your behalf. I can't thank you enough for your cooperation and patience. I will let you know once we have a root cause and fix.

Thanks again !

Shubha

**Comment by laggui** [comment] 2019-09-18 21:19
@shubha-ramani you're welcome :)

Thanks for the help, I'll be following this closely.

**Comment by avitial** [comment] 2020-08-12 22:06
@laggui this bug should have been already addressed, please checkout the latest version of OpenVINO available.

Closing this, feel free to reopen and ask additional questions related to this topic.

Ref. 22525

**Closed by avitial** 2020-08-12 22:06 UTC
