### ISSUE TITLE
[Bug] ngraph and opencv setting is not correct in bin/setupvars.sh when build from source code

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/openvino#4125] opened 2021-02-02 00:59 UTC
OpenVINO => commit 4795391b73381660b69b4cd3986c7a0bf902e868 (HEAD -> tag20212, tag: 2021.2)
Operating System / Platform => 18.04.5 LTS (GNU/Linux 4.15.0-117-generic x86_64)
Compiler => gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

python 3.7 with virtualenv
```
virtualenv -p python3.7 ~/pyenv/ov20212
source ~/pyenv/ov20212/bin/activate
```

##### Detailed description
ngraph and opencv setting is not correct in setupvars.sh when build from source code

##### Steps to reproduce
```
cmake -DCMAKE_INSTALL_PREFIX=~/openvino_work/install \
        -DENABLE_MKL_DNN=ON \
        -DENABLE_GNA=OFF \
        -DENABLE_CLDNN=OFF \
        -DENABLE_MYRIAD=OFF \
        -DENABLE_VPU=OFF \
        -DENABLE_OPENCV=OFF \
        -DCMAKE_BUILD_TYPE=Debug \
        -DNGRAPH_ONNX_IMPORT_ENABLE=OFF \
         ../openvino

make 

make install
```

the below is needed to set correct path for ngraph in setupvars.sh
```
export LD_LIBRARY_PATH=$INSTALLDIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export ngraph_DIR=$INSTALLDIR/cmake
```

I use the following hard code in setupvars.sh to really enable opencv, otherwise, benchmark_app will not be built with deployment_tools/inference_engine/samples/cpp/build_samples.sh.
 ```
export export LD_LIBRARY_PATH="/root/openvino_work/openvino/inference-engine/temp/opencv_4.5.0_ubuntu18/opencv/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export OpenCV_DIR=/root/openvino_work/openvino/inference-engine/temp/opencv_4.5.0_ubuntu18/opencv/cmake/
```

**Comment by ilya-lavrenov** [comment] 2021-02-02 12:04
@slyubimt have you tried to use setupvars.sh on install tree?

**Comment by slyubimt** [comment] 2021-02-02 13:16
The problem is that OpenCV is not part of OpenVINO repository and it is required to clone and build it separately. 
OpenCV directory layout from GitHub repository does not match content provided by Intel® Distribution of OpenVINO™ package and setupvars script paths.  That's why it is developer responsibility to define OpenCV_DIR and LD_LIBRARY_PATH to OpenCV libs to have ability to run samples for OpenVINO built from sources.

You can find more here:
https://github.com/openvinotoolkit/openvino/wiki/BuildingCode#installing
https://github.com/openvinotoolkit/openvino/wiki/BuildingCode#use-custom-opencv-builds-for-inference-engine
https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend

@mshabunin 
Is any idea on how we can improve it?

**Comment by slyubimt** [comment] 2021-02-02 13:25
`2021.2` branch does not have correct directory layout for OpenVINO and nGraph in particular. Fix will be available in 2021.3.
Please use latest from master branch.

**Comment by guoyejun** [comment] 2021-02-02 14:53
> @slyubimt have you tried to use setupvars.sh on install tree?

sure, all my changes are based on setupvars.sh on install tree.

**Comment by guoyejun** [comment] 2021-02-02 14:57
> `2021.2` branch does not have correct directory layout for OpenVINO and nGraph in particular. Fix will be available in 2021.3.
> Please use latest from master branch.

just tried the master branch at 79fa676e351a1e48bea290159229db94df775e7b, the ngraph setting is fixed, but I still need to set  opencv with:
# export export LD_LIBRARY_PATH="/root/openvino_work/openvino/inference-engine/temp/opencv_4.5.1_ubuntu18/opencv/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
# export OpenCV_DIR=/root/openvino_work/openvino/inference-engine/temp/opencv_4.5.1_ubuntu18/opencv/cmake/

**Comment by guoyejun** [comment] 2021-02-02 15:16
> The problem is that OpenCV is not part of OpenVINO repository and it is required to clone and build it separately.
> OpenCV directory layout from GitHub repository does not match content provided by Intel® Distribution of OpenVINO™ package and setupvars script paths. That's why it is developer responsibility to define OpenCV_DIR and LD_LIBRARY_PATH to OpenCV libs to have ability to run samples for OpenVINO built from sources.
> 
> You can find more here:
> https://github.com/openvinotoolkit/openvino/wiki/BuildingCode#installing
> https://github.com/openvinotoolkit/openvino/wiki/BuildingCode#use-custom-opencv-builds-for-inference-engine
> https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend
> 
> @mshabunin
> Is any idea on how we can improve it?

my simple idea is that, the behavior of setupvars.sh should be same no matter it is installed from pre-built package or built/installed from source code. There's nothing for developer to do when it is installed.

**Comment by jgespino** [comment] 2022-03-14 22:13
Closing, please re-open if additional assistance is needed.

**Closed by jgespino** 2022-03-14 22:13 UTC
Labels: bug, support_request
