### ISSUE TITLE
cl_cache mechanism failed

### ISSUE THREAD

**Issue by ly5234** [openvinotoolkit/openvino#9329] opened 2021-12-21 03:34 UTC
##### System information (version)
- OpenVINO=> 2021.4.752  & 2021.3.394
- Operating System / Platform => win 64
- Compiler => Visual Studio 2017
- Problem classification => IR model load

##### Detailed description
My application using the openvino framework will run on two machines, here referred to as PC A and PC B.

PC A: i7-8700, UHD Graphics 630
PC B: i7-1185G7, Iris(R) Xe Graphics 

In order to speed up the model loading on the GPU, I used the cl_cache folder according to the official recommendation, but something strange happened.
In order to verify whether the mechanism is effective, I run a demo 100 times on machines A and B respectively.
The demo running on the two machines is exactly the same.

PC A consumes a long time the first time,  about 200s, but the follow-up is very fast (6s), which is in line with expectations.
However, PC B regenerates the cache occasionally, which makes subsequent loading still very slow, and the number of cache will increase uncontrollably.

I have also tried different versions, but the problem is not solved, how should I solve this problem?

**Comment by jgespino** [comment] 2021-12-21 19:43
Hi @ly5234 

Could you share how are you running the tests and provide additional information about your PC B (i7-1185G7, Iris(R) Xe Graphics)?

- Graphics Driver Version
- Are you using your own code or our sample application?
- Are you using C, C++ or Python?
- What model are you using? Are you converting to IR first?

I ran a test on a system I have similar to yours (i7-1165G7) using Graphics Driver version 30.0.101.1191 and I was unable to reproduce the behavior you are seeing.

I used the benchmark_app to run 100 times using ssd-resnet34-1200-onnx in IR format. Creating the cl_cache directory decreased the loading time and the cache was only generated the first time the application ran. 

Regards,
Jesus

**Comment by ly5234** [comment] 2021-12-22 00:59
> Hi @ly5234
> 
> Could you share how are you running the tests and provide additional information about your PC B (i7-1185G7, Iris(R) Xe Graphics)?
> 
> * Graphics Driver Version
> * Are you using your own code or our sample application?
> * Are you using C, C++ or Python?
> * What model are you using? Are you converting to IR first?
> 
> I ran a test on a system I have similar to yours (i7-1165G7) using Graphics Driver version 30.0.101.1191 and I was unable to reproduce the behavior you are seeing.
> 
> I used the benchmark_app to run 100 times using ssd-resnet34-1200-onnx in IR format. Creating the cl_cache directory decreased the loading time and the cache was only generated the first time the application ran.
> 
> Regards, Jesus


Hi  Jesus @jgespino ,

Thank you for your reply. 
I use an C++-based integrated applications (.exe) now. 
The model is a segmentation network structure designed by myself, I have used the official PYTHON demo to convert ONNX model into IR model (.xml & .bin). In the application, I directly read the IR model and run the inference process.
By the way, the IR model was generated on another PC (i7-7700), using the same OPENVINO version, I think it will not affect the usage, right?

`python mo.py --data_type FP16 --input_model xxx.onnx --output_dir xxxxx`

Give me some time, I will make an extremely simplified demo to test, and provide you with my C++ code and results. 
Thanks again for your help.

**Comment by ly5234** [comment] 2021-12-22 01:22
PC B:  Graphics Driver version 27.20.100.9415

**Comment by ly5234** [comment] 2021-12-22 06:10
Hi @jgespino. I am back .  As I said above, I ran an extremely simple demo.
`
#include <iostream>
#include <string> 
#include <vector>
#include <fstream>
#include <opencv2/core/core.hpp>
#include <ie_core.hpp>
#include <inference_engine.hpp> 

using namespace InferenceEngine;
using namespace std;

const string DEVICE = "GPU";

bool fileExist(const std::string& path)
{
	ifstream f(path.c_str());
	return f.good();
}

void initModel(string xml, string bin)
{
	auto tStart = std::chrono::high_resolution_clock::now();
	// --------------------------- 1. Load inference engine instance -------------------------------------
	Core ie;
	// -----------------------------------------------------------------------------------------------------

	std::map<std::string, Version> versionMap = ie.GetVersions(DEVICE);
	std::map<std::string, Version>::iterator it = versionMap.begin();

	for (it = versionMap.begin(); it != versionMap.end(); ++it)
	{
		std::cout << "BuildNumber: " << it->second.buildNumber << std::endl;
		std::cout << "Description: " << it->second.description << std::endl;
	}

	if (!fileExist(xml) || !fileExist(bin))
	{
		std::cerr << ".xml or .bin not exist." << std::endl;
		return;
	}

	// --------------------------- 2. Read IR Generated by ModelOptimizer (.xml and .bin files) ------------
	CNNNetwork network = ie.ReadNetwork(xml);
	network.setBatchSize(1);
	// -----------------------------------------------------------------------------------------------------

	// --------------------------- 3. Configure input & output ---------------------------------------------
	std::cout << "Configure input & output" << std::endl;
	const InputsDataMap inputInfoMap(network.getInputsInfo());
	std::string input_name = inputInfoMap.begin()->first;
	InputInfo::Ptr input_info = inputInfoMap.begin()->second;
	auto descriptor = input_info->getTensorDesc();

	if (descriptor.getPrecision() != Precision::U8)
		input_info->setPrecision(Precision::U8);
	OutputsDataMap outputInfoMap(network.getOutputsInfo());

	std::string output_name_1 = "top_id";
	DataPtr output_info_1 = outputInfoMap[output_name_1];
	std::string output_name_2 = "top_val";
	DataPtr output_info_2 = outputInfoMap[output_name_2];

	if (output_info_1->getTensorDesc().getPrecision() != Precision::FP32)
		output_info_1->setPrecision(Precision::FP32);
	if (output_info_2->getTensorDesc().getPrecision() != Precision::FP32)
		output_info_2->setPrecision(Precision::FP32);
	// -----------------------------------------------------------------------------------------------------

	// --------------------------- 4. Loading model to the device ------------------------------------------
	std::cout << "Loading model to the device" << std::endl;
	ExecutableNetwork executable_network = ie.LoadNetwork(network, DEVICE);
	std::cout << "Load model finish." << std::endl;
	// -----------------------------------------------------------------------------------------------------

	// --------------------------- 5. Create infer request -------------------------------------------------
	InferRequest infer_request = executable_network.CreateInferRequest();
	// -----------------------------------------------------------------------------------------------------
	auto tEnd = std::chrono::high_resolution_clock::now();
	float tTotal = std::chrono::duration<float, std::milli>(tEnd - tStart).count();
	std::cout << "Cost time: " << tTotal  << " ms" << std::endl;
	//...........infer 


}

`

And the following is the result of running the above program on 'PC B',

![PCB](https://user-images.githubusercontent.com/4337484/147042842-a5c308a9-83d1-4e22-8cbb-d5a6da2b5e37.png)

As you can see, in the 4th run, it took unusually more time. I tracked the cl_cache folder, and this part of the extra time was used to generate the cache.
In order to speed up the debug process, I chose a small resnet50 network instead of my segmentation CNN network. If you need, I'd like to to provide my IR model.

**Comment by jgespino** [comment] 2021-12-22 17:58
Hi @ly5234 

Thank you for providing your sample code, I was able to reproduce using resnet50-tf model when downgrading my driver version to `27.20.100.9466` (closest available to yours). However, the issue is not reproduced when updating to the latest driver version `30.0.101.1191`. 

Could you try to update the graphics driver and let me know if the issue is also resolved on your side?

Regards,
Jesus

**Comment by ly5234** [comment] 2021-12-23 01:47
Hi @jgespino 

I have tried to update the driver version to 30.0.101.1191, and the problem is not reproduced. That is great news .

What I am curious about is that, in fact, the driver version I use on PC A (i7-8700, UHD Graphics 630) is also 27.20.100.8681 (similar to the PC B, i7-1185G7, Iris(R) Xe Graphics, 27.20.100.9415), but it always works very well on PC A. 
So, could you share me the list of the minimum driver requirements for different CPUs / Integrated graphics (if any), or furthermore, the essential reason for the problem is the CPU version or the graphics driver version ?

Anyway, thank you for help me solve this problem. I also hope to help other developers who are plagued by the same problem.

**Comment by avitial** [comment] 2021-12-27 20:00
@ly5234 I believe the issue with this driver was specific to TGL system running GPU based workloads (PC B in your case), so in the case of PC A (8th Gen/Coffee Lake) the GPU workload wasn't affected by this driver version. 

I am not aware of any minimum driver requirements for specific CPUs, based on the operating system simply follow the configuration steps for Intel® Processor Graphics (GPU):
- [Windows](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_windows.html#optional-steps-for-intel-processor-graphics-gpu)
- [Linux ](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_linux.html#optional-steps-for-intel-processor-graphics-gpu)


Closing this, feel free to reopen to ask any questions related to this topic.

BR,
Luis

**Closed by avitial** 2021-12-27 20:00 UTC
Labels: category: GPU, support_request, PSE
