### ISSUE TITLE
Inference engine refuses to run simple TF model on MYRIAD

### ISSUE THREAD

**Issue by ongun-kanat** [openvinotoolkit/openvino#481] opened 2020-05-04 10:56 UTC
Hi I am trying to execute the simple TF 1.x model below that calculates a matrix multiplication operation `y = A*x` on Intel neural compute stick 2:

```python3
import tensorflow as tf
import pathlib
import sys

def main():
    graph = tf.Graph()

    with graph.as_default():
        x = tf.placeholder(dtype=tf.float16, shape=(None, 1), name="x")
        A = tf.placeholder(dtype=tf.float16, shape=(None, None), name="A")
        y = tf.matmul(A, x, name="y")

    graph_def = graph.as_graph_def(add_shapes=True)

    models_dir = pathlib.Path(__file__).resolve().parent / "models"

    try:
        if not models_dir.exists():
            models_dir.mkdir()

        graph_file = models_dir / "model_tf1.pb"

        with tf.gfile.GFile(str(graph_file), "wb") as out:
            # Even though it says string the output is binary
            out.write(graph_def.SerializeToString())

    except Exception as err:
        print(err, file=sys.stderr)
        exit(1)



if __name__ == "__main__":
    main()
```

Then I generate IR model using model optimizer with this command:

```bat
"%INTEL_OPENVINO_DIR%\deployment_tools\model_optimizer\mo_tf.py" --data_type=FP16 --input_model models\model_tf1.pb --output_dir models --input "x[100 1],A[100 100]" --output y
```
Then I use this script to execute model and get the average run time:

```python3
import sys
import argparse
import pathlib
import time

import numpy as np

import openvino.inference_engine as ie


def create_argparser():
    parser = argparse.ArgumentParser()

    parser.add_argument("-d", "--device",
                        help="The device to run model on",
                        choices=["CPU", "MYRIAD"],
                        default="MYRIAD",
                        type=str,
                        required=False)

    parser.add_argument("model_directory",
                        help="The directory that contains the model .bin and .xml files")

    parser.add_argument("-m", "--model-name",
                        help="The name of the model .bin and .xml files in model directory",
                        type=str,
                        default="model_tf1")

    parser.add_argument("-N", "--forward-pass-count",
                        help="Number of forward passes. The execution time will be averaged",
                        type=int,
                        default=100)

    return parser


def main():
    parser = create_argparser()
    args = parser.parse_args()

    ie_cor = ie.IECore()

    if args.device not in ie_cor.available_devices:
        print("ERROR: No {} device is present."
              "Check if USB stick is connected.".format(args.device),
              file=sys.stderr)

    model_dir = pathlib.Path(args.model_directory)
    model_xml = str(model_dir / (args.model_name + ".xml"))
    model_bin = str(model_dir / (args.model_name + ".bin"))

    network = ie_cor.read_network(model=model_xml, weights=model_bin)
    exec_net = ie_cor.load_network(network=network, device_name=args.device)

    run_times_total = 0.0
    for i_test in range(args.forward_pass_count):
        x_shape = network.inputs["x"].shape
        A_shape = network.inputs["A"].shape

        x_in = np.random.uniform(low=-10, high=10, size=x_shape)
        A_in = np.random.uniform(low=-20, high=20, size=A_shape)

        start = time.monotonic()
        exec_net.infer(inputs={"x": x_in, "A": A_in})
        end = time.monotonic()

        run_times_total += end - start

    avg_run_time = run_times_total / args.forward_pass_count

    print("average_run_time=", avg_run_time, "seconds")


if __name__ == '__main__':
    main()
```

The command I use to execute the inference script is:

```
python benchmark_model_tf1.py .\models
```
This command fails with the error below:

```
Traceback (most recent call last):
  File "benchmark_model_tf1.py", line 75, in <module>
    main()
  File "benchmark_model_tf1.py", line 53, in main
    exec_net = ie_cor.load_network(network=network, device_name=args.device)
  File "ie_api.pyx", line 178, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 187, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Failed to reshape Network: Check 'arg0_shape[axis_index_arg0].compatible(arg1_shape[axis_index_arg1])' failed at ..\ngraph\src\ngraph\op\dot.cpp:130:
While validating node 'v0::Dot Dot_360(Parameter_358[0]:f16{1,100}, Parameter_359[0]:f16{1,1}) -> (dynamic?)':
Paired axes (axis 1 from arg0, axis 0 from arg1) do not have same length (arg0 shape: {1,100}, arg1 shape: {1,1}, reduction axes count: 1).
```

However when I use CPU as my device it runs perfectly:

Command:

```
python benchmark_model_tf1.py -d CPU .\models
```

The output:
```
[E:] [BSL] found 0 ioexpander device
average_run_time= 0.00047000000020489094 seconds
```

So it seems like there is a bug in MYRIAD plugin. 

I tried giving the input shapes with `--input_shape [100,1],[100,100]` but it also produces the exact same error with MYRIAD device.

My system info:
OS: Windows 10 1803 build 17134.1425 x86_64
OpenVINO ver 2020.2 (openvino_2020.2.117)
Python: 3.6.10
Python Packages:
```
Package              Version
-------------------- -------------------
absl-py              0.9.0
asn1crypto           1.3.0
astor                0.8.0
certifi              2020.4.5.1
cffi                 1.14.0
chardet              3.0.4
cryptography         2.8
decorator            4.4.2
defusedxml           0.6.0
gast                 0.3.3
grpcio               1.27.2
h5py                 2.10.0
idna                 2.6
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
Markdown             3.1.1
mkl-fft              1.0.6
mkl-random           1.0.1
mxnet                1.2.1
networkx             2.4
numpy                1.15.0
onnx                 1.6.0
pip                  20.0.2
protobuf             3.6.1
pycparser            2.20
pyOpenSSL            19.1.0
pyreadline           2.1
PySocks              1.7.1
requests             2.18.4
scipy                1.1.0
setuptools           46.1.3.post20200330
six                  1.14.0
TBB                  0.1
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
typing-extensions    3.7.4
urllib3              1.22
Werkzeug             1.0.1
wheel                0.34.2
win-inet-pton        1.1.0
wincertstore         0.2
wrapt                1.12.1
```

**Comment by leavim** [comment] 2020-05-20 20:55
Hi @ongun-kanat, I am able to see this issue as reported, currently investigating. Just curious if you have a more complex model and this primitive is causing troubles there.

Could you try giving  `--input "x[100 1],A[1 100]"` to your MO command and check if that makes any difference? 

Regards,
Luis

**Comment by ongun-kanat** [comment] 2020-05-25 16:10
> Hi @ongun-kanat, I am able to see this issue as reported, currently investigating. Just curious if you have a more complex model and this primitive is causing troubles there.

No I created model as an warm-up example for myself. I also want to compare the performance of the USB module vs CPU. I am creating a tool for converting in-company models to various other representations so I wanted to try a basic model first.


> Could you try giving `--input "x[100 1],A[1 100]"` to your MO command and check if that makes any difference?

In this case the model works on MYRIAD without an error:

```
[E:] [BSL] found 0 ioexpander device
average_run_time= 0.0015700000000106228 seconds
```

**Comment by ongun-kanat** [comment] 2020-06-08 12:09
Any updates on this or do you have any workarounds for matrix ops?

**Comment by avitial** [comment] 2020-06-30 17:39
@ongun-kanat apologies for the delay in my response. The reason this doesn't work on Myriad is because the first dimension is supposed to be a batch by design, in your given case this is not valid for Myriad as Myriad only supports batch=1.

**Comment by ongun-kanat** [comment] 2020-06-30 18:06
@avitial That's weird. Because I **can** run other single-input (without `A`) feed-forward neural networks only giving an input `x[1024 2]` (where 1024 is the batch size and 2 is the 2 different dimensions of input) and it works on USB (I don't have access to my work computer but I can share such a network tomorrow). 

As we verified it also works when the **second** dimension is 1 , **not the batch dimension**. So it indicates something is wrong with the input size inference in Inference Engine.

**Comment by jgespino** [comment] 2022-03-01 22:08
Closing, please re-open if additional assistance is needed.

**Closed by jgespino** 2022-03-01 22:08 UTC
