### ISSUE TITLE
Cannot download model and dataset files using git lfs pull

### ISSUE THREAD

**Issue by kopxiong** [openvinotoolkit/openvino#209] opened 2019-07-23 11:18 UTC
Hi,
I followed the Accuracy Checker tutorial page [Accuracy Checker Sample Example](https://docs.openvinotoolkit.org/latest/_tools_accuracy_checker_sample_README.html), then I encountered the issue
$ git lfs pull

[397864ca9e1a384c4d106f42a84a156534db0311670bef4d20e55d3c5c1513b0] Object does not exist on the server: [404] Object does not exist on the server
[3ca191620ab3c5fcabe0818a13ac24f0ddd5abc564dd5958070b2e589f577ec8] Object does not exist on the server: [404] Object does not exist on the server
[d5edc50c8c4e8ec4e15ff2a03d771665f61fc58d633a14071a1844eaeb70ab4f] Object does not exist on the server: [404] Object does not exist on the server
[46cea661615846a41baeb7ba2fb989a6a6b3169b8d0391e3e5de718fb5ec28a8] Object does not exist on the server: [404] Object does not exist on the server
[78014a0ca4f53d7ca28915b431cd0e270660b0c9725944baa71bfe0f7c0bb269] Object does not exist on the server: [404] Object does not exist on the server
[e853d694cc939576722a5cb99f69991989176900b7ab3abaf4d2c47ef6e5ac5d] Object does not exist on the server: [404] Object does not exist on the server
[48b255355c47a0db5ab84e299cb45d49289f644fcaa61f22fe3a4ea309e4d74a] Object does not exist on the server: [404] Object does not exist on the server
[7525267b41a1a0a8c4d45423bc1c3a762db1721b64afb88645ec56e25ea3f0ee] Object does not exist on the server: [404] Object does not exist on the server
[5d5f93c42477b56c1ccd08e14e0b094349a855d4eece93474cb2cbc0abf11fcb] Object does not exist on the server: [404] Object does not exist on the server
[df37a9b4ed4b3895f894cfa60e9743990ade7242d45e46886109c54131e65ac8] Object does not exist on the server: [404] Object does not exist on the server
[89b878ee363b8e11db53056dd9bf9fad633fa10c190a3f4a99b0938b337add35] Object does not exist on the server: [404] Object does not exist on the server
[6587b2478d617711574befa48ac0c1bd4de7c0f55403786e2ea7b20ef26d6d4e] Object does not exist on the server: [404] Object does not exist on the server
[326761f4f5dacca72fcdbac770bda98d7b3c4df0ba6e3a827a6a25673a0d1b8c] Object does not exist on the server: [404] Object does not exist on the server
[626d3b700edca72134d6e46c5f36a33ffa7c6abb9147af5e1a40da2e79b07f2a] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.com/opencv/dldt.git/info/lfs'

I am using Windows 10 and have already cloned the dldt repo from [dldt repo](https://github.com/opencv/dldt). Have I missed something configs?

**Comment by shubha-ramani** [comment] 2019-07-23 16:14
Dear @kopxiong 
My I ask - why are you using glt lfs (Large File System) ? Can you kindly try plain old git without lfs ?

Thanks,

Shubha

**Comment by kopxiong** [comment] 2019-07-24 02:16
Dear @shubha-ramani 
I would like to go through the **Accuracy Checker Sample** example by evaluating **SampLeNet** topology, but I can't find the **sample_dataset** and **configuration files** from the downloaded repo. Do you have any suggestions? Thanks!

Best,
Andy

**Comment by shubha-ramani** [comment] 2019-07-24 15:59
Dear @kopxiong  I'm not finding anything about SampLeNet on the Internet. Can you kindly provide a link ?

Thanks,

Shubha

**Comment by eaidova** [comment] 2019-07-26 14:53
Dear @kopxiong, 

with the latest release Accuracy Checker migrates to Open Model Zoo [repository](https://github.com/opencv/open_model_zoo).
SampleNet model uploaded without git LFS can be founded [here](https://github.com/opencv/open_model_zoo/tree/master/tools/accuracy_checker/data/test_models)
Please try to follow updated sample [readme](https://github.com/opencv/open_model_zoo/blob/master/tools/accuracy_checker/sample/README.md) to launch Accuracy Checker sample

Thanks,
Katya

**Comment by lazarevevgeny** [comment] 2020-05-25 12:26
The issue is resolved. Closing.

**Closed by lazarevevgeny** 2020-05-25 12:26 UTC
