### ISSUE TITLE
Trying to build on Arch linux

### ISSUE THREAD

**Issue by aaronchantrill** [openvinotoolkit/openvino#392] opened 2020-02-20 09:17 UTC
I'm trying to build this on Arch linux, but keep getting this error:

```
-- DL_SDK_TEMP envionment not set
-- Downloading from https://download.01.org/opencv/2020/openvinotoolkit/2020.1/inference_engine/opencv_4.2.0-082_.txz to ~/Projects/NCS2/dldt/inference-engine/temp/download/opencv_4.2.0-082_.txz ...
-- /usr/bin/aria2c ,*.*.*.* -d ~/Projects/NCS2/dldt/inference-engine/temp/download https://download.01.org/opencv/2020/openvinotoolkit/2020.1/inference_engine/opencv_4.2.0-082_.txz

02/20 21:59:34 [NOTICE] Downloading 1 item(s)

02/20 21:59:35 [ERROR] CUID#7 - Download aborted. URI=https://download.01.org/opencv/2020/openvinotoolkit/2020.1/inference_engine/opencv_4.2.0-082_.txz
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://download.01.org/opencv/2020/openvinotoolkit/2020.1/inference_engine/opencv_4.2.0-082_.txz
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

02/20 21:59:35 [NOTICE] Download GID#f364d288f0c24d2b not complete: 

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
f364d2|ERR |       0B/s|https://download.01.org/opencv/2020/openvinotoolkit/2020.1/inference_engine/opencv_4.2.0-082_.txz

Status Legend:
(ERR):error occurred.
```

The actual file on download.01.org is opencv_4.2.0-082.txz. It looks like the filename is being built from a template like "opencv_{version}_{distro}.txz, but since distro is coming back blank, I end up with a dangling underscore at the end of the filename. Unfortunately, I haven't been able to figure out where this is coming from. Does anyone know?

Thanks,
Aaron

**Comment by dkurt** [comment] 2020-02-20 17:38
try to disable OpenCV by `-DENABLE_OPENCV=OFF` or build it from source and specify `OpenCV_DIR`

**Comment by qiyuangong** [comment] 2020-03-02 07:52
This error is caused by https://github.com/opencv/dldt/blob/2020/inference-engine/cmake/dependencies.cmake#L150 . It didn't find supported OS string, so it ends up with empty string, which broken the final URL.

I think you can disable OpenCV, or change `dependencies.cmake` according to https://github.com/opencv/dldt/issues/400 .

**Comment by AnastasiaKazantaeva** [comment] 2020-07-17 16:09
It seems that the issues is not actual anymore. Closing it. Feel free to reopen it or create a new one,

**Closed by AnastasiaKazantaeva** 2020-07-17 16:09 UTC
Labels: bug, category: build, effort: few hours, good first issue, help wanted
