### ISSUE TITLE
Problems when downloading the topologies, and the folders structure

### ISSUE THREAD

**Issue by Bahramudin** [openvinotoolkit/openvino#154] opened 2019-05-20 04:04 UTC
I am trying to download all the topologies, but it fails to download all of them but some. Before I also mentioned this error, that if it is possible to compress all the topologies in one package and then it can be download very easily. because the topologies list is very long, so in most cases using script downloading those files, it will fail, and also if run the script for the second and third time, then it will start downloading all the topologies which already exist, there is no check for existing files. 

The best way is to download the topologies all by one not by script. 

The second problem is the structure in the `C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\intel_models` with the structure in the download topologies folder are not the same, which makes it very hard to find the correspondings topologies, please make these structure the same.

E.g: when I look for the **person-vehicle-bike-detection-crossroad-0078** topology in the downloaded topologies folder, it is hard to find, because there is not the same directory structure.

I was waiting for the new version which the error may be fixed, but when I downloaded the error still remains.

**NOTE:**  The previous version (2018) was nice, which all the topologies came with the download package, and the directory structure was all fine and human-readable, and easy to find and use.

**Please** avoid using script download topologies. 

Here are some errors:
```
========= Downloading D:\topologies\classification\vgg\19\caffe\vgg19.caffemodel
... 49%, 275064 KB, 40 KB/s, 6782 seconds passed
Error Connecting: HTTPConnectionPool(host='www.robots.ox.ac.uk', port=80): Read timed out.
```

`Error Connecting: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0B7ubpZO7HnlCV3pud2oyR3lNMWs (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000211EFA7FEF0>: Failed to establish a new connection: [WinError 10060]`

**Comment by shubha-ramani** [comment] 2019-05-20 14:08
Dear @Bahramudin 
In the latest 2019 R1, there is no intel_models directory so I suspect that you are using a very old version of OpenVino.  Today the intel models are stored at the below link
[https://download.01.org/opencv/2019/open_model_zoo/R1/](https://download.01.org/opencv/2019/open_model_zoo/R1/)

If you use the latest 2019 R1, cd into C:\Program Files (x86)\IntelSWTools\openvino_2019.1.144\deployment_tools\tools\model_downloader and do a **python downloader.py --all**
model downloader should work fine for you. 

Let me know if this helps,

Thanks,

Shubha

**Comment by Bahramudin** [comment] 2019-05-20 16:04
@shubha-ramani  Thanks for the reply and giving the link for downloading topologies. But I am using the latest version of the OpenVino, it is the directory structure:
![Annotation 2019-05-20 234531](https://user-images.githubusercontent.com/13574895/58034690-bd50b680-7b59-11e9-80bb-e35da1bb2185.jpg)

So it is what I see, I think I am not wrong. 

By the way, I know how to download the topologies, I just run `python downloader.py --all`. BUT I said before that there are some problems with this script

**It is what I get when I run:**
> ========= Downloading D:\topologies\object_detection\common\mobilenet-ssd\caffe\mobilenet-ssd.caffemodel
> Error Connecting: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=0B3gersZ2cHIxRm5PMWRoTkdHdHc (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000023D6B8C32B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

So unable to use the script for downloading the topologies. I have tried a lot, but no result.
Because of that, I said if it is possible to bundle all the topologies in a single package and put for download, but you give the link, now it is something possible to download the files, but one-by-one.

Anyway, now it is better than before, thanks again!

**Comment by shubha-ramani** [comment] 2019-05-20 17:06
@Bahramudin 
I'm so sorry. intel_models is indeed where you said it is. My mistake. 
When you run the downloader.py script though you pass in an --output_dir and the models which get downloaded are different from the intel trained models. Instead what you get are a variety of supported models which are not made by Intel. They are downloaded and separated into categories classification, face_recognition, object_detection, optical_character_recognition etc.
It sounds like you are having connection problems, reading your error above. Are you possibly behind a proxy ? If you are behind a proxy you must set the environment variables http_proxy and https_proxy. I have found that if there is a good network connection, I don't have issues with downloader.py .

**Comment by Bahramudin** [comment] 2019-05-21 01:43
@shubha-ramani OK you are welcome! _Yes, I used --output_dir flag_ 

The problem with the download script is because it accesses some links which in some countries because of policy, access to some links are not allowed especially the google related links. 

So the best way is besides downloading by scripts, it will be good tat OpenVino also provide some other ways to download the topologies, I have used VPN and proxy for that and tried many ways but I was unable to download all of them, but only some.

And one another problem with the script is that when running for the second, third, ..., time, then it will start to download already downloaded files again, which is very waste of time, and there is no checking if the file already exists then skip downloading and go for the next one.

So the user does not have full control on downloading files (to avoid duplicated downloads and so on)

You mentioned that they are different from the  **Intel trained models**,  so which one prefers to use? 
What is the benefits with the downloading topologies by scripts?

Thanks!

**Comment by Bahramudin** [comment] 2019-05-21 09:34
@shubha-ramani I got this error when forwarding the net:

> No symbol file loaded for cpu_extension_avx2.dll
> C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\deployment_tools\inference_engine\bin\intel64\Release\cpu_extension_avx2.dll

It is why?

Exactly this line throws the error:
`cv::Mat detection = net.forward();`

**Note that**, this was working well with the previous version (2018 R5)

**Comment by shubha-ramani** [comment] 2019-05-21 22:58
Dear @Bahramudin 
Your feedback about downloader.py is very welcome. I understand your frustrations ! Development engineers and managers are reading this forum so believe me, they're taking it in.

As for that memory violation error you're getting above, well...very difficult to say why you are getting it without debugging your code.

Why not build a debug version of IE, using this [README](https://github.com/opencv/dldt/blob/2019/inference-engine/README.md) and step through the code ?

Also, I encourage you to download R2019R1.1 - which just got released this week.

Hope it helps. Thanks for using OpenVino !

Shubha

**Comment by Bahramudin** [comment] 2019-05-22 01:14
@shubha-ramani Thanks! That will be good if Development engineers and managers take care of that problem (download topologies).

The second, I have already using the latest version **2019 R1.1**, and yes, I run the code in debug mode, when I installed the OpenVino, it already has the Release and Debug versions, and I already have added these two in my system path, if not, the program will not start. 

This was not happening while I was using **2018 R5**, I think I have everything correctly when I run the Demos 
```
demo_squeezenet_download_convert_run.bat
demo_security_barrier_camera.bat
```
It runs just fine, so it means that everything installed correctly.

And when I googled, I got this one, I think it somehow related to this error.
[Intel Inference Engine: cpu_extension_avx2.dll #11689](https://github.com/opencv/opencv/pull/11689/files)

What is your opinion? 
Thanks and waiting for your reply.

**Comment by Bahramudin** [comment] 2019-05-22 02:30
@shubha-ramani I solved the problem of **memory violation error** it was caused by adding both release and debug lib to the system path at the same time.  Now the download problem persists, I hope in the next releases it can be solved.

Thanks!!

**Comment by shubha-ramani** [comment] 2019-05-22 20:38
Dear @Bahramudin,
Happy to hear that you solved your Access Violation errors. Yes mixing up Debug and Release libs could definitely cause that.

Thanks for reporting back about the root cause !

As for the download.py problems i will write a Feature Request ticket detailing your commentary.

Thanks for using OpenVino !

Shubha

**Comment by sahira-rizvi** [comment] 2022-03-23 01:24
Closing, feel free to re-open or create a new issue if additional assistance is needed.

Sincerely,
Sahira

**Closed by sahira-rizvi** 2022-03-23 01:24 UTC
