### ISSUE TITLE
Openvino input blob preparation: OpenCV(4.5.2-openvino) Error: Assertion failed ((unsigned)i < (unsigned)cn) in cv::Vec<unsigned char,3>

### ISSUE THREAD

**Issue by Choyon10** [openvinotoolkit/openvino#15310] opened 2023-01-26 08:30 UTC
##### System information (version)
 - OpenVINO => 2022.3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: Model Conversion
- Framework: TensorFlow
- Model name: VGGFace

##### Detailed description
I am using VGGFace model for face recognition, successfully made the IR representation. from the network architechture I have seen that the required layout for this model architechure is **(NHWC)** as the input shape for this model are**(1,224,224,3)** and the output layout as **(HW)** as the output shape are **(1,2622).**
So according to the input and output information the input_output configuration..

```
input_info = network.getInputsInfo();
for (auto& item : input_info) {
    auto inputName = item.first;
    cout << inputName<<endl;
    auto input_data = item.second;
    input_data->setPrecision(InferenceEngine::Precision::U8);
    input_data->setLayout(InferenceEngine::Layout::NHWC);
    input_data->getPreProcess().setResizeAlgorithm(InferenceEngine::RESIZE_BILINEAR);
    input_data->getPreProcess().setColorFormat(InferenceEngine::ColorFormat::BGR);
    }
output_info = network.getOutputsInfo();
for (auto& item : output_info) {
    auto outputName = item.first;
    cout << outputName << endl;
    auto output_data = item.second;
    output_data->setPrecision(InferenceEngine::Precision::FP32);
    output_data->setLayout(InferenceEngine::Layout::HW);
}
```

For creating cv to input blob I have write script as..

```
  string input_name;
  input_name = input_info.begin()->first;
  Mat image = imread("D:\\pic\\1.jpg");
  resize(image, image, Size(224, 224));
  Blob::Ptr input_blob = infer_request.GetBlob(input_name);
  matU8ToBlob<uint8_t>(image, input_blob, 0);
```

In that case I got an error in the matU8ToBlob conversion : `OpenCV(4.5.2-openvino) Error: Assertion failed ((unsigned)i < (unsigned)cn)`

can anyone please help to resolve this.

NB: For creating the blob I had already tried with (wrapMat2Blob) function but as this method create blob with NCHW layout by default. so in the inference time it's not working and got this exception.

```
Unhandled exception at 0x00007FF9486406BC in Project1.exe: Microsoft C++ exception: InferenceEngine::details::InferenceEngineException at memory 
```

**Comment by Wovchena** [comment] 2023-01-30 15:18
How do you know the error is produced by `matU8ToBlob()`? Can you point to the exact line that produces the error?

You should write and share a reproducer: a simple program which depends on OpenCV only and which generates the error you are facing.

**Comment by Choyon10** [comment] 2023-01-31 08:06
Here is the inference script and in the matU8ToBlob<uint8_t>(image, input_blob) code this code gives an exception. Could you please give some suggestion...
```
InferenceEngine::CNNNetwork network;
InferenceEngine::InferRequest infer_request;

InferenceEngine::InputsDataMap input_info;
InferenceEngine::OutputsDataMap output_info;


string device = "CPU";
string model_path = "Model\\Face_Recognition\\VGG-Face.xml";
  string weight_path = "Model\\Face_Recognition\\VGG-Face.bin";
network = core.ReadNetwork(model_path,weight_path);

    input_info = network.getInputsInfo();
    for (auto& item : input_info) {
        auto inputName = item.first;
        cout << inputName<<endl;
        auto input_data = item.second;
        input_data->setPrecision(InferenceEngine::Precision::U8);
        input_data->setLayout(InferenceEngine::Layout::NHWC);
        input_data->getPreProcess().setResizeAlgorithm(InferenceEngine::RESIZE_BILINEAR);
        input_data->getPreProcess().setColorFormat(InferenceEngine::ColorFormat::BGR);
    }
    output_info = network.getOutputsInfo();
    for (auto& item : output_info) {
        auto outputName = item.first;
        cout << outputName << endl;
        auto output_data = item.second;
        output_data->setPrecision(InferenceEngine::Precision::FP32);
        output_data->setLayout(InferenceEngine::Layout::HW);
    }

    executable_network = core.LoadNetwork(network, device);
    infer_request = executable_network.CreateInferRequest();

    string input_name;
    input_name = input_info.begin()->first;
    
    Mat image = imread("D:\\pic\\1.jpg");

    resize(image, image, Size(224, 224));
    Blob::Ptr input_blob = wrapMat2Blob(image);
    infer_request.SetBlob(input_name, input_blob);

    Blob::Ptr input_blob = infer_request.GetBlob(input_name);
    matU8ToBlob<uint8_t>(image, input_blob); /// In here this code give an exception.
    infer_request.Infer();
```

**Comment by Wovchena** [comment] 2023-01-31 10:30
1. The problem is that `matU8ToBlob<uint8_t>(image, input_blob);` assumes that the layout is `NCHW`, but you reset to `NHWC` with `input_data->setLayout(InferenceEngine::Layout::NHWC);`

2. > I had already tried with (wrapMat2Blob) function but as this method create blob with NCHW layout by default.

Why do you claim `wrapMat2Blob()` creates `NCHW` blob? I can see it sets `NHWC`: https://github.com/openvinotoolkit/openvino/blob/f342e5d208745d00932b2290b8ff02e9c0f9f12f/samples/cpp/common/utils/include/samples/ocv_common.hpp#L75

3. You have both `Blob::Ptr input_blob = wrapMat2Blob(image);` and `matU8ToBlob<uint8_t>(image, input_blob);` in your  implementation. But you need only one. You have two options:
    a. Keep `Blob::Ptr input_blob = wrapMat2Blob(image);` only. And remove
    ```
    Blob::Ptr input_blob = wrapMat2Blob(image);
    infer_request.SetBlob(input_name, input_blob);
    ```
    b. Or remove `input_data->setLayout(InferenceEngine::Layout::NHWC);` and `Blob::Ptr input_blob = wrapMat2Blob(image);`.

**Comment by Choyon10** [comment] 2023-02-01 06:01
Basically I have tried both of them separately for creating input blob but not the same time. when using the `wrapMat2Blob(image)` , At that moment I didn't use `matU8ToBlob<uint8_t>(image, input_blob);`. 

**As it's gives error this is why I have just include both of them in here.**

But when use `wrapMat2Blob(image)` It's not making any error but in the inference time it's given an exception. which I mention in the first question.
```
Unhandled exception at 0x00007FF9486406BC in Project1.exe: Microsoft C++ exception: InferenceEngine::details::InferenceEngineException at memory 
```

At that moment I have found that `wrapMat2Blob` by default create input blob in the NCHW layout format and on the other hand our model input layout is NHWC. So I thought the issue is in the creation of input blob.

 I have found there have another option for creating input blob  is 'matU8ToBlob'. But after following this one It couldn't able to generate the input blob.

**Comment by Wovchena** [comment] 2023-02-01 11:37
Can you share the full code so I could compile it. And also the model and the image you use?

**Comment by andrei-kochin** [comment] 2023-02-02 11:29
@Choyon10 could you please address query from @Wovchena  so we can proceed further?

**Comment by Wovchena** [comment] 2023-02-08 11:19
@Choyon10, can the issue be closed?

**Comment by andrei-kochin** [comment] 2023-02-10 18:40
Closing since no reply and full code snippet was not provided.

@Choyon10 feel free to re-open if the issues is still actual

**Closed by andrei-kochin** 2023-02-10 18:40 UTC
Labels: support_request, category: CPP API
