### ISSUE TITLE
i meet a  Segmentation fault (core dumped) when i load several models

### ISSUE THREAD

**Issue by jlygit** [openvinotoolkit/openvino#114] opened 2019-04-02 12:08 UTC
hello,
i meet a  Segmentation fault (core dumped) when i load four models one times.

it crashs in this code:
executable_network = plugin.LoadNetwork(network, {{PluginConfigParams::KEY_CPU_BIND_THREAD, PluginConfigParams::YES},{PluginConfigParams::KEY_EXCLUSIVE_ASYNC_REQUESTS, PluginConfigParams::YES}});

and i gdb it shows:

![image](https://user-images.githubusercontent.com/10195989/55401126-60397b00-5582-11e9-8039-38ece2c9b60d.png)

it like a MKLDNNMemory::Create fail. and it crashs --Segmentation fault (core dumped)

why it do not return a fail and i can catch it.

**Comment by shubha-ramani** [comment] 2019-04-02 16:47
Dear @jlygit,
core dumps are never good !  Can you attach your model and Inference Engine code as a zip to to this ticket ? Also please let me know the mo command you used to generate IR.

As always, thanks for using OpenVino. Once I can reproduce this core dump, I will file a bug on your behalf.

Sincerely,

Shubha

**Comment by ilyachur** [comment] 2019-04-03 03:44
Hi @jlygit,

The issue with memory allocation for the CPU plugin which looks like your problem, was fixed in the 2019 R1 release.
Could you download the latest OpenVino 2019 R1 which was just released today and try to reproduce your issue on the 2019 R1 release?

**Comment by ilyachur** [comment] 2020-05-27 10:05
@jlygit Did the new version of OpeVINO solve your problem?

@dmitry-gorokhov FYI

**Comment by AnastasiaKazantaeva** [comment] 2020-07-20 12:56
It seems that the issues is not actual anymore as no response. Closing it. Feel free to reopen it or create a new one.

**Closed by AnastasiaKazantaeva** 2020-07-20 12:56 UTC
Labels: bug, category: CPU

**Comment by VijayaKumarKamma** [comment] 2020-10-23 16:30
i am getting the same issue if i am using the latest engine with 2021.1  and model comes with 2019.r1 that is face-person detection. Please healp.
