### ISSUE TITLE
The text gets cluterred while hovering the Deployment Carousel

### ISSUE THREAD

**Issue by 456535688765** [openvinotoolkit/openvino#16222] opened 2023-03-10 15:23 UTC
Before 
![Screenshot (226)](https://user-images.githubusercontent.com/92295764/224354688-eb3032b9-21be-4b45-af49-eb5d3b3d64d0.png)
After
![Screenshot (227)](https://user-images.githubusercontent.com/92295764/224354891-704c4ac5-8926-43a0-8119-d3c891283b4d.png)

**Comment by hbalasu1** [comment] 2023-03-15 06:26
Hi @456535688765 

When I hover my mouse cursor over all three boxes (MODEL, OPTIMIZATION, AND DEPLOYMENT), all the boxes will turn white with bold font when the cursor points to the blue box. 

If you see the same, this seems like expected to make the box clickable and link to respective pages. 

Thank you

**Comment by kblaszczak-intel** [comment] 2023-03-15 07:44
Hey @456535688765
Thanks for sharing the concern :) The behavior is intentional to indicate that any of the three categories can be clicked. But I can see in  your screenshots that there is a slight issue foth the font itself. Especially the letter "f" in "run inference locally." We use vector svg here so there's always some displacement when scaling the image, but this should not happen. I'll have a look at the image itself and try to fix it.

**Comment by sgolebiewski-intel** [comment] 2023-03-15 07:44
Hello, @456535688765

the screenshots you provided suggest expected behavior of the 'carousel'. The background of the boxes that @hbalasu1 mentioned turns white on hover. 
You mention that the text 'gets cluttered'. Could you be more specific,?  (Please, provide more details regarding the configuration you are using. You can try disabling the extensions in the browser and see if the problem persists)

**Comment by hbalasu1** [comment] 2023-03-22 06:45
Hi @456535688765 
Since this issue is fixed, can we close this case?

**Comment by avitial** [comment] 2023-04-28 19:30
Closing this as issue seems to have been addressed. Feel free to reopen to ask any questions related to this topic.

**Closed by avitial** 2023-04-28 19:30 UTC
Labels: category: docs
