### ISSUE TITLE
[Bug]C++ Runtime cannnot read network(optimized model),but python can do it.

### ISSUE THREAD

**Issue by BeCoolMaker** [openvinotoolkit/openvino#14686] opened 2022-12-16 02:10 UTC
**After I convert YOLOV5n.pt to ONNX and then to IR model, I can use python to reason normally, but I can use C++to report an error.**
##### System information (c++)
- OpenVINO => openvino_2022.1.0.643
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

- Model name: Yolov5n
##### System information (python 3.9.13)
- onnx => 1.11.0
- opencv-python => 4.6.0.66
- openvino => 2022.2.0
- openvino-dev => 2022.2.0
- openvino-telemetry => 2022.1.1
- Framework: Pytorch

Code : C++ Inference
```
#include <ie/inference_engine.hpp>
using namespace InferenceEngine;

Core ie;
auto cnnNetwork = ie.ReadNetwork(_xml_path);
```
Output 
```
C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\inference\src\ie_network_reader.cpp:518 [ NETWORK_NOT_READ ] Unable to read the model: D:\project\yolov5-7.0\openvino\optimized_model.bin Please check that model format: bin is supported and the model is correct. Available frontends: ir onnx
```
Code : Python Inference
```
from openvino.runtime import Core

ie = Core()
model = ie.read_model(model=r"openvino\optimized_model.xml")
compiled_model = ie.compile_model(model=model, device_name="CPU")
input_layer_ir = compiled_model.input(0)

print(model)
```
Output 
```
<Model: 'torch-jit-export'
inputs[
<ConstOutput: names[images] shape{1,3,640,640} type: f32>
]
outputs[
<ConstOutput: names[output0] shape{1,25200,7} type: f32> 
]>
```

Code : Python Optimized
```
#python optime 
from openvino.tools.pot import IEEngine
from openvino.tools.pot import load_model, save_model
from openvino.tools.pot import compress_model_weights
from openvino.tools.pot import create_pipeline
from openvino.tools.pot import DataLoader

import os
import numpy as np
import cv2 as cv
import argparse


class ImageLoader(DataLoader):
    """ Loads images from a folder """
    def __init__(self, dataset_path,shape):
        # Use OpenCV to gather image files
        # Collect names of image files
        self._files = []
        all_files_in_dir = os.listdir(dataset_path)
        for name in all_files_in_dir:
            file = os.path.join(dataset_path, name)
            if cv.haveImageReader(file):
                self._files.append(file)

        # Define shape of the model (1280,1280)
        self._shape = shape

    def __len__(self):
        """ Returns the length of the dataset """
        return len(self._files)

    def __getitem__(self, index):
        """ Returns image data by index in the NCHW layout
        Note: model-specific preprocessing is omitted, consider adding it here
        """
        if index >= len(self):
            raise IndexError("Index out of dataset size")

        image = cv.imread(self._files[index]) # read image with OpenCV
        image = cv.resize(image, self._shape) # resize to a target input size
        image = np.expand_dims(image, 0)  # add batch dimension
        image = image.transpose(0, 3, 1, 2)  # convert to NCHW layout
        return image, None   # annotation is set to None


def main(opt):
    # Model config specifies the model name and paths to model .xml and .bin file
    model_config = {
        "model_name": "model",
        "model": opt.model_dir,
        "weights": opt.weights,
    }

    # Engine config
    # engine_config = {"device": "CPU"}
    engine_config = {"device": opt.device}

    algorithms = [
        {
            "name": "DefaultQuantization",
            "params": {
                "target_device": "ANY",
                "stat_subset_size": opt.stat_subset_size
            },
        }
    ]

    print("[Info]: Implement and create user's data loader")   
    data_loader = ImageLoader(opt.image_dir,opt.img_size)

    print("[Info]: Load model")
    model = load_model(model_config=model_config)
    
    print("[Info]: Initialize the engine for metric calculation and statistics collection.")
    engine = IEEngine(config=engine_config, data_loader=data_loader)
  
    print("[Info]: Create a pipeline of compression algorithms and run it.")    
    pipeline = create_pipeline(algorithms, engine)
    compressed_model = pipeline.run(model=model)

    print("[Info]: (Optional): Compress model weights to quantized precision to reduce the size of the final .bin file.")
    compress_model_weights(compressed_model)

    print("[Info]: Save the compressed model to the desired path.")
    _ = save_model(
        model=compressed_model,
        save_path=opt.save_path,
        model_name=opt.save_model_name,
    )


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--model_dir', type=str, default=r'.\openvino\best.xml', help='Xml path')
    parser.add_argument('--weights', type=str, default=r'.\openvino\best.bin', help='Bin path')
    parser.add_argument('--image_dir', type=str, default=r'dataset\train\images', help='Image dir')
    parser.add_argument('--img_size', nargs='+', type=int, default=[640, 640], help='Image shape ,like [h,w]')
    parser.add_argument('--device', type=str, default="CPU", help='device CPU,GPUs that do not support Nvidia')
    parser.add_argument('--stat_subset_size', type=int, default=300, help='Calibration image files size')
    parser.add_argument('--save_path', type=str, default='openvino', help='')
    parser.add_argument('--save_model_name', type=str, default='optimized_model', help='Save model name')
    opt = parser.parse_args()

    main(opt)
```

**Comment by brmarkus** [comment] 2022-12-16 05:45
Can you double-check to not have different versions of OpenVINO installed (globally installed as pre-built binary delivery; installed via `pip`; installed via `pip` in a virtual-environment; OpenVINO built from source)?
Can you print the version of OpenVINO in the C++ and in the python program?
The VisualStudio project might use mixed header- and library-search-paths, maybe based on `setvards.bat` called before starting VisualStudio?

**Comment by BeCoolMaker** [comment] 2022-12-16 06:03
I do have two python versions of OpenVINO, but I have tested that both versions work normally.I don't understand how to print the version of openvino in C++ and python,but I checked it with pip.

C++ Runtime is based on OpenVINO 2022.1.0.643.The virtual environment of python also exists in this version.This version can run normally in C++without quantifying the IR model.

**Comment by brmarkus** [comment] 2022-12-16 06:20
> I do have two python versions of OpenVINO, but I have tested that both versions work normally.I don't understand how to print the version of openvino in C++ and python,but I checked it with pip.

For C++, you might check this sample: https://github.com/openvinotoolkit/openvino/blob/master/samples/cpp/benchmark_app/main.cpp#L301

For Python, it's similar: https://github.com/openvinotoolkit/openvino/blob/master/tools/benchmark_tool/openvino/tools/benchmark/benchmark.py#L42

Retrieving the version at runtime will reveal which underlying installation ultimately is used, especially if there are multiple versions installed in parallel (like pre-built installed version of OpenVINO contain Python bindings already, but depending on search paths and environment settings a separately installed PIP package might get used.)

> C++ Runtime is based on OpenVINO 2022.1.0.643.The virtual environment of python also exists in this version.This version can run normally in C++without quantifying the IR model.

**Comment by BeCoolMaker** [comment] 2022-12-16 06:32
C++:
![image](https://user-images.githubusercontent.com/27920539/208036840-d5158538-93a0-42fe-a532-1045cf0ae1b8.png)

Python:
![image](https://user-images.githubusercontent.com/27920539/208036741-f7e0154a-2599-45d8-941f-35a3cb41effc.png)

**Comment by brmarkus** [comment] 2022-12-16 06:50
Uh, wait.
Have you swapped the filenames of BIN and of XML? Can you double-check the C++ code if you really provide the path and filename of the XML-file? It looks like you provided the path and filename of the BIN file.

`Unable to read the model: D:\project\yolov5-7.0\openvino\optimized_model.bin`, this is supposed to be the XML-file.

**Comment by BeCoolMaker** [comment] 2022-12-16 07:08
Thanks for your reply. I have tried bin and xml,but it had no effect. Here is my path
```
std::string model_dir = R"(D:\project\yolov5-7.0\openvino\optimized_model.xml)";
```

**Comment by brmarkus** [comment] 2022-12-16 07:17
Is the file `optimized_model.bin` in the same directory as the `optimized_model.xml`?

In your Python code snippet you use relative paths - are you sure it's the same path and file system location?
(just for consistency, the XML- and BIN-files are the same, in the same location for C++ and Python)

**Comment by BeCoolMaker** [comment] 2022-12-16 07:47
I just tried to use absolute path in Python, which has no effect.

They are all in the same path and have only one IR model, so they all access the same model file. And they are generated by the "openvino. tools. pot. save_model()" method, so the names of xml and bin are consistent.

**Comment by brmarkus** [comment] 2022-12-16 08:31
Please have a look at OpenVINO read-network implementation of your installed version here: https://github.com/openvinotoolkit/openvino/blob/releases/2022/2/src/inference/src/ie_network_reader.cpp#L518

The exception's message says is constructed as `"Unable to read the model: " << modelPath`.
The model-path is supposed to be the path and filename of the XML-file.

But in your case, the log-message indicates the BIN file...:
`Unable to read the model: D:\project\yolov5-7.0\openvino\optimized_model.bin`

In your original post you showed the code-line `auto cnnNetwork = ie.ReadNetwork(_xml_path);`, where now you mention `std::string model_dir = R"(D:\project\yolov5-7.0\openvino\optimized_model.xml)"`.

**Comment by BeCoolMaker** [comment] 2022-12-16 08:54
I have tried both xml and bin files.I'll try to debug the code.

```
bool Detector::init(string xml_path,string label_path,int img_size,double cof_threshold,double nms_area_threshold) {
    _xml_path = xml_path;
    _cof_threshold = cof_threshold;
    _nms_area_threshold = nms_area_threshold;
    _img_size = img_size;
    try {
        labels = DetYolov7::parse_label(label_path);
        Core ie;
        auto cnnNetwork = ie.ReadNetwork(_xml_path);
        InputsDataMap inputInfo(cnnNetwork.getInputsInfo());
        InputInfo::Ptr& input = inputInfo.begin()->second;
        this->_input_name = inputInfo.begin()->first;
        input->setPrecision(Precision::FP32);
        input->getInputData()->setLayout(Layout::NCHW);
        ICNNNetwork::InputShapes inputShapes = cnnNetwork.getInputShapes();
        SizeVector& inSizeVector = inputShapes.begin()->second;
        cnnNetwork.reshape(inputShapes);
        _outputinfo = OutputsDataMap(cnnNetwork.getOutputsInfo());
        for (auto& output : _outputinfo) {
            output.second->setPrecision(Precision::FP32);
        }
        _network = ie.LoadNetwork(cnnNetwork,"CPU");
        return true;
    } catch (const std::exception& e) {
        cout << e.what() << endl;
        return false;
    }
}

int main() {
  std::string model_dir = R"(D:\project\yolov5-7.0\openvino\optimized_model.xml)";
  std::string label_txt =R"(D:\project\yolov5-7.0\openvino\label.txt)"; 
  double cof_threshold = 0.25;
  double nms_area_threshold = 0.45;
  Mat im = imread(R"(D:\project\yolov5-7.0\openvino\im.bmp)");

  cout << ov::get_openvino_version();
  Detector det5;
  bool isInit = det5.init(model_dir,label_txt,1280,cof_threshold,nms_area_threshold);
  if (!isInit) {
      return 0;
  }
}
```

**Comment by andrei-kochin** [comment] 2022-12-16 19:54
@BeCoolMaker  just to exclude the directory parsing issue could you please try moving optimized_model.xml and optimized_model.bin to the same dir you running your app? So you'll have:
`std::string model_dir = "optimized_model.xml";`

**Comment by BeCoolMaker** [comment] 2022-12-19 05:16
@andrei-kochin No effect,thanks

**Comment by andrei-kochin** [comment] 2022-12-19 06:01
Hello @BeCoolMaker,

Just to make sure that your XMLs are correct could you please try with simple one-layer model attached?
[test.zip](https://github.com/openvinotoolkit/openvino/files/10256309/test.zip)

**Comment by avitial** [comment] 2023-01-31 03:29
Closing this, I hope previous responses were sufficient to help you proceed. 

Feel free to reopen and provide additional information about the issue (minimal app reproducer, model files, etc.) or ask any questions related to this topic.

**Closed by avitial** 2023-01-31 03:29 UTC
Labels: support_request, category: CPP API
